### ISSUE TITLE
3d printer renders last printed object when there is no object in the output slot

### ISSUE THREAD

**Issue by MFernflower** [MightyPirates/OpenComputers#1002]
![sfubv](https://cloud.githubusercontent.com/assets/3164942/6957155/69cc0ea4-d8c6-11e4-9d6b-97a84c51ee6c.png)

**Comment by fnuecke** [comment]
Yes, that's because it's still configured for that block. You could just call `printer.commit([n])` again, to print another `n` copies of that block. Or extend `print3d` to do something like `print3d 2` to just print 2 of the already configured one.

So it's one of those rare cases where it truly _is_ a feature, not a bug ;-)
