### ISSUE TITLE
Adapter as upgrades for robots and drones

### ISSUE THREAD

**Issue by MisterErwin** [MightyPirates/OpenComputers#1004]
Well, my suggestion is, that adapters are valid upgrades for robots&drones. (Like the geolyzer)

So robots/drones can retrieve more informations from their surrounding.

Or maybe add this only to robots and add a (not solid) block that acts like an adapter block when the drone is in the same block space.

Please leave your opinion ;)

**Comment by Vexatos** [comment]
I think this is quite..... powerful. Too powerful... Far too powerful. There is a reason why robots and drones are currently unable to interact with components. They are not meant to do this.

**Comment by fnuecke** [comment]
I'm pretty much with Vexatos on this one.

**Comment by Kubuxu** [comment]
@fnuecke IIRC you on your own suggested allowing robots to deploy into "stationary" platform to interact with components.

**Comment by Vexatos** [comment]
I still don't like it, it makes robots far too powerful.

**Comment by fnuecke** [comment]
@Kubuxu I may have mentioned that as a possibility, that doesn't automatically mean it's a good one, or that I still have to agree with it ;-) And that only fits the last part of this (the drone "adapter station" thing), having robots act as moving adapters is overkill, I think.

One of the _technical_ reasons against this is, that it'll need re-evaluation of _every_ component, when used in a robot, because now the fact that outside components do not play any role at all, is a given. Changing this can have many unexpected consequences, e.g. due to there suddenly being more than one keyboard/screen and so on.

**Comment by MisterErwin** [comment]
While this idea is (at least for me) more realistic, but it would break some other things in terms of not useful anymore...

Not sure if I should close this, so...

**Comment by fnuecke** [comment]
Yeah, I don't think I like this going into 'vanilla' OC.
It should be possible to do this in an addon mod, though, just saying ;-)
