### ISSUE TITLE
Conflict on recipes with SecurityCraft

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#1013]
Hello! 
Have a conflict with SecurityCraft in recipes. 
oc:numPad has same recipe as SecurityCraft's keyPad. 
I'm not sure on which side this should be fixed. 
This does not result in crash, just leads to non-availability of numPad part for crafting.

**Comment by fnuecke** [comment]
Hrm... since OC's recipes are based on config files I don't really want to hardcode a switch to an alternative recipe based on mod detection.

@Geforce132 How about we make the items oredict compatible? Then I can use the oredict name in my recipe configs and disable the OC keypad recipe if SecurityCraft is present (and the oredict entry is already present). So basically give yours priority, since the OC one is a pure crafting material.
For what it's worth, OC's numpad already has an oredict entry, `oc:materialNumPad`. We could either come up with an alternative one used by both, or you could register your keypad with the oredict using that (if it doesn't have one already, of course)? I could do that on my end, too, I guess, but I'd like to avoid registering other mods' items in the oredict without their devs' consent.

**Comment by Geforce132** [comment]
@fnuecke No, don't worry, you can keep your recipe how it is, I've changed my keypad's recipe in the upcoming version of SecurityCraft. Thanks for letting me know though. :)

Followed you on Twitter, by the way.

**Comment by fnuecke** [comment]
Awesome, thanks! And yep, just saw :-)

Will be closing this then.
