### ISSUE TITLE
Allow turning off RAID-ness of RAIDs

### ISSUE THREAD

**Issue by dgelessus** [MightyPirates/OpenComputers#1016]
Basically have a GUI button (perhaps also controllable via computer) to switch between RAID mode, where all disks are combined into a single filesystem, and normal disk drive mode, where each disk is a separate filesystem, as if it were installed directly in the computer. Having three separate disks instead of a single RAID can be more useful in various cases, e. g. setting up identical boot drives for multiple robots/tablets, or simply to store large amounts of data while keeping the disks independent and not **losing all data when removing one of them**. Also, software RAIDs.

If this would be computer-controllable, there would probably need to be a new `raid` component, with at least two methods to get/set the RAID-ness, and perhaps also a utility method to get the addresses of all of the disks (or of the single RAID filesystem).

**Comment by Vexatos** [comment]
Wouldn't that just be extra file storage in a component, without any risks (wiping the filesystems) involved? Sounds quite cheaty to me...

**Comment by dgelessus** [comment]
That depends on whether the disk wiping is _meant_ to be a limitation for the player, or if it was just the most reasonable way to solve corner cases when the RAID changes. I always imagined the latter, because merging disks when they are added to the RAID would be problematic when there are naming conflicts (and it would realistically make no sense whatsoever), and shrinking the RAID on disk removal wouldn't always work either.

**Comment by Vexatos** [comment]
It would completely eliminate the limitation of Hard Drives that are in the different Case tiers with being plain additional slots for hard drives; I don't see anything good with that, you'd have almost no memory limitations anymore. At all.

**Comment by dgelessus** [comment]
Isn't that more of a problem with RAIDs in general? They already accept any tier of HDD in their current form. True, it would be slightly easier to upgrade the HDDs when in "separate drive" mode, but tbh I would be surprised if somebody used a RAID with anything other than T3 disks.

**Comment by fnuecke** [comment]
I've been mulling over this for the past few days, but I think that doesn't work well with the existing features (e.g. tiered slots in cases would become completely pointless). Or the rack would have to become a lot more expensive. Or there'd have to be tiered Raids, which I don't like.

While the fact that Raids get wiped when a disk is removed is indeed partially due to it being the simplest, most understandable way to handling special cases, it also gives Raids a certain limitation in use, avoiding the choice of Raid vs. built-in disk becoming a no-brainer.

As for software raids, you can do that in Lua. If you throw in a networked filesystem you could even combine multiple servers, acting as file servers, into a huge raid system.
