### ISSUE TITLE
Reading description instead of NBT data

### ISSUE THREAD

**Issue by LordTy** [MightyPirates/OpenComputers#1019]
I have seen a few request for the reading of NBT data, which are understandably denied.

However, I think a way to allow us to still sort items based on NBT data that is visible to the player (eg safari nets, seeds, bees) would be to expose the description string of the item. 

Then it is up to the programmer to correctly parse this string and it allows the mod-makers to decide which data is visible.

**Comment by Vexatos** [comment]
... Database upgrades exist...

**Comment by Kubuxu** [comment]
And many ad suggested items already have special converters.

**Comment by gjgfuj** [comment]
I agree with this, however, the description string is client side and as
such cannot be read by computers.

**Comment by fnuecke** [comment]
Well, all of the arguments against this I immediately thought of were already mentioned. Just wanna expand on those points a bit more:
- You can sort items, including based on NBT data, using the database upgrade, by getting the hash of an item in the database (`database.computeHash()`).
- If there is anything specific, a converter is the sane way to go - text parsing on the Lua side is unnecessarily error prone, for one simply because it's string parsing, for two because it involves localization on the server, which is nothing one should rely on, ever (yes, usually it boils down to resulting in the English strings, but still).
  There are converters for safari nets and bees already, for example (though the one for the bees only works while the bee is in the analyzer or a bee house/apiary/alveary... if I don't forget _again_ I'll make that work for plain item stacks, too...)

**Comment by LordTy** [comment]
I understand the error proneness of the string parsing, but this was the best I could think of. The converters I haven't seen before, is there somewhere I can find more information on them?

The problem I had with using a database to sort the items was that a database can only compare to known items, which severely limits the uses when trying to automate breeding processes.

**Comment by Kubuxu** [comment]
https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/integration/mfr/ConverterSafariNet.scala <- example

**Comment by fnuecke** [comment]
[Example using Java](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/integration/ic2/ConverterElectricItem.java) in case you're unfamiliar with Scala. As you see, it's quite simple to make one.

**Comment by gjgfuj** [comment]
I think what they were referring to is how to access the converters lua
side.

**Comment by Vexatos** [comment]
> trying to automate breeding processes

@LordTy I hope you know that there is a special converter for Bees so automating bee breeding already is easily possible.

**Comment by fnuecke** [comment]
> I think what they were referring to is how to access the converters lua side.

Ah, well that's automatic - given some callback returns the converted type. Such as the `getStackInSlot` method of the inventory controller.
