### ISSUE TITLE
Print light emitting materials

### ISSUE THREAD

**Issue by L00Cyph3r** [MightyPirates/OpenComputers#1024]
#### Feature-request

I've not done the most research, but AFAIK, it's currently not possible.

So I would like to know if it's possible to make the 3d-printer print light-emitting materials.
It would be so epic to print your own lamps.

**Comment by fnuecke** [comment]
Heh, it is possible in the dev builds :-) (as of a few hours ago)

Default max light level is limited to 8, though (can be changed in config), because chamelium is crafted without glowstone, just redstone. So redstone torch-ish light level seemed appropriate.

Guess you saved me from creating a ticket to remember adding it to the changelog myself :P
