### ISSUE TITLE
Beacon Material For Prints

### ISSUE THREAD

**Issue by natedogith1** [MightyPirates/OpenComputers#1027]
Is there a reason that you have to use vanilla beacon base blocks to make a print a beacon base?

**Comment by Vexatos** [comment]
Because there is always a cost involved in making beacon bases, even if it's just iron. You shouldn't be able to make a beacon base out of pure plastic.

**Comment by fnuecke** [comment]
What he said.

Unless you mean "why can't mod blocks that serve as beacon base be used"? Never thought of that, to be honest. It could be possible to check via the block... perhaps... but the dynamic check is context sensitive (aka unreliable because I'd have to pass a dummy world/position), and it'd make registering the recipes a pain. So that's how it is and how it'll stay for now.

**Comment by natedogith1** [comment]
That is indeed what I meant, and that explains that, hadn't looked too much into it myself so I wasn't sure.
