### ISSUE TITLE
[request] things to reduce or "increase" complexity in drones

### ISSUE THREAD

**Issue by Tcll** [MightyPirates/OpenComputers#1030]
This issue REALLY frustrated me when I found out I couldn't use my upgrades I wanted because of topped complexity:
- magnet<br>
- solar<br>
- inventory<br>
  <br>
- maxed internals<br>
- no cards

I ended up having to scrap the inventory upgrade after finding out I needed a wifi card before my drone would even boot.

so my recommendation is to change the recipe for the drone case to include a chest (base inventory) and a wifi card (no more bootup issues)

or make it possible to add alot more items with less complexity usage (T3 drone)
(why do T3 parts build a T2 case?)

OT: may I mention I don't like the rubber-band motion whenever a drone moves...
I was expecting a solid movement... heh

---

also, could you make it possible for a drone to track you
(I want my drones to follow me)

**Comment by Vexatos** [comment]
You can very well boot a drone without a wireless network card, you'll just have to program the EEPROM in advance.

The low complexity cap is very much intended, it makes you unable to have a single drone for everything. If you, for example, want an inventory in your drone, you could get rid of the wireless netowork card and instead use a pre-programmed EEPROM.

The T2 drone uses T3 items simply because it is such a highly advanced device, and it is only intended to be used for quite specific tasks, a little like Microcontrollers, which is another reason why they have such a low complexity cap.

For tracking drones, just install a Computronics Radar Upgrade.

**Comment by Tcll** [comment]
yea but there's more than 5 upgrades for the drone and only 3 upgrade slots in a T2 case...
you already can't do everything... heh

I'd think the complexity should be just enough to fill up what's provided, and I do stress it should at the very least have a base inventory...

I can accept the wifi card not being used to build the case as long as it doesn't rob other things from the complexity...
I think there's 3 cards that can go into a drone, but as of the T2 case of course it can only use 2...

I'd think my T3 case request could use 2 (maybe 3) cards and 4 upgrades, and of course T2 RAM :P

I'm talking about this for multiplayer servers where too many instances is a bad thing...

**Comment by Vexatos** [comment]
The complexity is there so you are NOT able to use max RAM, max CPU et cetera. It limits you in those ways as well (also, why would you ever need more than a Tier 1.5 RAM in a drone?).

Also, no base inventory, just like robots. there is no reason for that. Many drone setups do not need any inventory.

Again, the limited amount of slots and complexity is very, very much intended for people to make multiple drones for specific purposes rather than one drone for all purposes. If you don't like that, just get a Creative Drone Case.

By the way, drones ar pretty server friendly, having one or two shouldn't make much of a difference.

**Comment by Tcll** [comment]
> also, why would you ever need more than a Tier 1.5 RAM in a drone?

Artificial Intelligence

**Comment by Vexatos** [comment]
> Artificial Intelligence

Use a robot for that. Or use a wireless network card and send your data over in memory-friendly chunks.

There is a workaround for every problem you are having. Every single one. The purpose of this mod is to make you find and (ab)use those workarounds.

**Comment by gjgfuj** [comment]
Yeah, exactly.

**Comment by Tcll** [comment]
> Use a robot for that

:srs:

> Or use a wireless network card and send your data over in memory-friendly chunks.

that's more like it.

I'd like to abuse the workarounds if I wasn't so limited
that's why I was requesting a T3 case

otherwize I could perhaps have the server admins grant me a creative case

**Comment by Vexatos** [comment]
> if I wasn't so limited

It is limited because it makes you actually think about what to add to your drone instead of maxing out everything. A Tier 1 CPU is, for instance, all you will ever need in 99% of your (drone) cases.

**Comment by fnuecke** [comment]
I think there's nothing I can add that hasn't been said. If you want creative mode, get a creative drone somehow. Otherwise play the mod as it's meant to be played and work around the limitations - which is a pretty big gameplay element of a _lot_ of tech mods, I might add.

**Comment by Tcll** [comment]
IK this is old, but can I still request a T3 case which would have an extra card slot, upgrade slot, and increased complexitity??
(using a creative case to solve what you'd expect out of what's available is stupid)

I still feel you should be able to use every slot in your drone, and things should be a bit more user-friendly.
(I havn't even used a robot yet as I havn't thought of a use for the slow, flightless, clunky thing)

drones are cooler, but they're too limited
