### ISSUE TITLE
Feature Request:  debug.getVersion()

### ISSUE THREAD

**Issue by MyNameIsKodos** [MightyPirates/OpenComputers#1048]
I've been in the OC IRC for a bit over a year now, and I've helped quite a few people, but one common question I seem to find myself asking is 'What version of OC are you using?'.  More often than not, I get something along the lines of 'latest' or '1.5'.  Which, frankly, isn't very helpful.  

I'd love a function that would be able to either grab the file name's listed version, or the internal version number.  This way, I can just have them run the function in creative mode (Assuming they have access).  

Alternatively, this could be a function in the computer component rather than debug, so that those on survival servers without access to creative mode or the debug card can also check this.

Edited for formatting.

**Comment by Vexatos** [comment]
It should not be available in the computer as it's not a feature related to gameplay.

**Comment by MyNameIsKodos** [comment]
True, but it wouldn't be a gameplay advantage, nor would it directly affect anything. It would be a purely useless function outside of the scope of helping someone figure out an exact version of the mod they're using.

**Comment by Kubuxu** [comment]
You ca just look on jar or FML's mod list.

**Comment by Vexatos** [comment]
Yet another function in the computer there to confuse people because they will think "What does this do?".

@Kodos-Atoz If you want to get the version a player uses, you can just make them look into their mod list in the Minecraft main menu, it's shown there. That's probably much easier than having an almost useless function.

**Comment by MyNameIsKodos** [comment]
Don't think I haven't tried to get them to look in the mods folder.  It's seriously a chore to get them to comply to simple requests and common sense knowledge is seemingly rare.  This would be a quality of life feature for those of us in IRC who are asked about things that were fixed versions ago due to people not updating. This would simply be a quicker way of finding out the version.

**Comment by Vexatos** [comment]
Then it will also be a chore to get them to print a certain function in OC, especially with things like "I cannot even get my computer to turn on". Good luck.

The mod list will still be easier, no matter how many problems you have with getting people to use it.

**Comment by MyNameIsKodos** [comment]
Maybe, maybe not.  Either way, I'd still like to get Sangar's input on this before I close this (Or he does)

**Comment by fnuecke** [comment]
Well, on the one hand it seems a bit... superfluous, because, as pointed out, it's in the FML mod list, and there's even a mod that allows to you view that in-game (i.e. not just from the main menu). And it would require people to get a working computer _first_, which I feel invalidates a lot of the "it's for easier support" argument?

_But_ I don't agree that it's completely out of place, either, since it could simply be interpreted as the "hardware version" of the computers, because that's what it basically is.

Another, IMHO more sensible option, would be to display it somewhere in the manual.

**Comment by MyNameIsKodos** [comment]
I'd be okay with it being in the manual, just so long as it's accessible /somewhere/ in game.

**Comment by Vexatos** [comment]
As long as it's not in component.computer...

**Comment by skyem123** [comment]
I like the idea of it being a 'hardware version'

**Comment by MyNameIsKodos** [comment]
My friend says we should add a (And I'm going to quote him from here on out) program called ocdiag that will list the 'hardware version', all components in the computer, etc  (End quote)

I'm not sure how good of an idea this is, but I wanted to put it here in the event it may inspire another idea in someone.

**Comment by rashdanml** [comment]
The main index.md file should be a perfect place for it, since it's titled "OpenComputers Manual", change to: "OpenComputers (ver) Manual".
