### ISSUE TITLE
Storage media wiping should be consistent

### ISSUE THREAD

**Issue by dgelessus** [MightyPirates/OpenComputers#1052]
At the moment floppies can be wiped by crafting, HDDs ~~using RAIDs~~ by sneak-right-clicking, and EEPROMs cannot be wiped "manually" at all. The advantages of wiping by crafting have been discussed before, so I'd suggest that all storage media should be wipable that way, including EEPROMs. Whether that should be possible for read-only EEPROMs is a different question.

Floppies currently also lose their color when wiped, I'm not sure if that's intentional. Dunno about you, but my floppy disks don't turn black when I pass over them with a magnet. ;)

**Comment by Vexatos** [comment]
I second this :+1:

**Comment by fnuecke** [comment]
Yeah, for HDDs it's already in, that was an oversight. For EEPROMs... I guess why not, yeah. Also not sure about the readonly ones, though. But the main reason is to "protect" the data that's already on it, so wiping it shouldn't matter, so I guess why not. And it was possibly via shift-rclick before, so there's that.

As for the color... that's because the entire NBT-tag is nuked... suppose I could add a whitelist for stuff to be carried over, like the color.
