### ISSUE TITLE
Mipmaps not working - 1.7.10

### ISSUE THREAD

**Issue by Methes** [MightyPirates/OpenComputers#1061]
Using only:
OpenComputers-MC1.7.10-1.5.6.13
Forge 10.13.2.1291 OR
Forge 10.13.2.1343-1.7.10
Using fresh generated configs.

Mipmap setting (in video settings) has no effect. Remove OpenComputers and they work.

Any more info you need?

**Comment by fnuecke** [comment]
Comparison screenshot of what you'd expect to see vs. what you see would be helpful. Also, does this happen just by the mod being present, or only when certain blocks are placed in the world. If the latter, which blocks? Only while looking at those blocks, or even when facing away? And anything else you can think of that might be helpful to narrowing it down.

**Comment by Methes** [comment]
It happens just by the mod being present, no blocks are needed.
Sadly the logs don't say anything special about mipmaps.
This is a fresh new world:
![withoutoc](https://cloud.githubusercontent.com/assets/8257735/7130887/a5c96a68-e277-11e4-8f74-96042d1645e0.png)
![withoc](https://cloud.githubusercontent.com/assets/8257735/7130888/a5cc4f80-e277-11e4-96a4-483961f11162.png)

I recommend downloading the pictures and switching between them to see the differences better.

I'm using latest drivers for my GTX580.

**Comment by Methes** [comment]
Here are the logs, just to be sure (I'm a noob).
In part two I tried turning Mipmaps levels to 0 and then back up to 4 to see any errors in logs, but there were none.
Part one - http://pastebin.com/fMWVmVxm
Part two - http://pastebin.com/H2Lzg0s5

**Comment by fnuecke** [comment]
Well, this certainly was one of the weirder issues to track down. I never noticed this before, because I usually play with anisotropic filtering enabled, and in that case it seems the mipmap setting is ignored anyway. In other words, out of four possible combinations (AF on/of, mipmaps on/off) it only happens in that one specific constellation. So I started disabling rendering related stuff, to no avail. Then I disabled all the blocks. And it was gone. So testing finally devolved into disabling individual blocks, and, well.

Lesson learned: don't register textures for your blocks that aren't the size of a power of two! Because MC sure as hell won't just throw it into a next-larger bin in the texture atlas, oh no. It'll make the atlas have a size for which it is impossible to generate mipmaps... in hindsight it's somewhat obvious, but I still think MC could/should automatically handle this, or at least give out a warning. [/rant]

Anyway, it's fixed now! Thanks for making me aware of this.
