### ISSUE TITLE
Add memory CPU speed modifier.

### ISSUE THREAD

**Issue by sulljason** [MightyPirates/OpenComputers#1067]
Since in actual computers a CPUs speed is also dictated by memory latency and bandwidth. I think it would add more depth if the RAM DIMMs had a modifier like effect on the CPU execution speed for example: .5x 1x etc...

**Comment by fnuecke** [comment]
I'm not too sure I like the idea of the RAM having an influence over general execution speed. Sure, for certain operations it could make sense, but it feels a lot less intuitive than the CPUs influence on general performance. In addition, the RAM already has a very important functionality, that being providing working memory... mixing the two feels a little... messy.

The only reason I'm not closing this right away is because it could be used to add an incentive towards using better RAM when using the LuaJ fallback.

I'll think about it.

**Comment by sulljason** [comment]
Understood, thanks for considering it. I just like having design/engineering challenges to overcome in hardware (why I'm majoring in computer engineering.). Also throwing hardware at problems is kinda fun in an irresponsible instant gratification kind of way lol.

**Comment by fnuecke** [comment]
I'll look into taking the tier of memory into account of call budget computation in the CPUs when that is implemented, and made a note in that issue, so I'll be closing this.

**Comment by sulljason** [comment]
This is a really late reply, but thanks for seriously considering the idea.
