### ISSUE TITLE
Add HDD seek time and throughput limitation.

### ISSUE THREAD

**Issue by sulljason** [MightyPirates/OpenComputers#1069]
To make memory more useful (especially the large tier 3 capacities) hard drives could have realistic limitations such as random seek time and throughput. I think it would make having large pools of memory more useful because of caching to avoid I/O penalties; especially for things like a data base server.

**Comment by Vexatos** [comment]
T3 Memory already is quite useful if you operate with things like databases to store massive amounts of data.

**Comment by sulljason** [comment]
But since there isn't a penalty afaik for reading from the disk you could just store it all on disk and recall it as fast as if it were in memory.

Wiki:
"Hard disk drives (HDDs) come in three tiers, with increasing storage capacity (each tier's capacity is configurable). They can store more data than a simple floppy, but are also more expensive to craft. They can also only be installed in computer cases and servers. They can only be installed in robots during the assembly phase. (Prior to 1.3: They can not be installed in robots.) "

No kind of I/O penalty is mentioned.

**Comment by fnuecke** [comment]
Well, there is no penalty based on tier, nor hard drive specific. All filesystems in OC have the same "speed". But it is _far_ **far** _**far**_ from memory speed. It's one of the reasons you actually see OpenOS booting, and not just being there in an instant. That's not a "fake" slowdown on the Lua side, that's the actual speed of file system slowing it down. Adding different speeds by type (e.g. floppy slower than hdd, hdds differently fast by tier) is something I do consider adding in the future, but it'll probably have to be in a major update, since that would require potentially breaking API changes.
