### ISSUE TITLE
More unicode points

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#1076]
The unifont.hex that OpenComputers uses, while being the default build, excludes all of the code points above 0xFFFF. The other .hex.gz files in the release also contain the upper points beyond 0xFFFF, providing 8021 more characters (though some of these are just placeholders). From what I understand they are also under the same license so that shouldn't be an issue.

Only two files needed (can probably just be combined into one):
unifont-7.0.06.hex
unifont_upper-7.0.06.hex

~~(also because I want the mathematical alphanumeric symbols)~~

**Comment by fnuecke** [comment]
No. Java's `char` can only represent up to 0xFFFF, so this would require a lot of internal changes (lookup by char array instead of char, etc). Which isn't quite worth it.

**Comment by Kubuxu** [comment]
It is good to know that OC allows only code points up to 2 bytes.

**Comment by gamax92** [comment]
I don't understand but may I ask why you'd have to go to character arrays instead of something like an int? Unicode only goes up to 21bits so a 31bit number (Java's signed ints) should work fine for that.

**Comment by dgelessus** [comment]
@fnuecke Would it be possible to use [surrogate pairs](http://en.wikipedia.org/wiki/UTF-16#U.2B10000_to_U.2B10FFFF)? That's how characters outside the BMP are encoded in UTF-16, which is 16-bit-based as well. I'm not sure what exactly you were thinking of with `char` arrays.
@gamax92 Technically that would be possible, but extremely annoying to use. Think "why not use byte-arrays instead of ints to store numbers > 255?"

**Comment by gamax92** [comment]
Yes, I would think looking up via an array is more annoying than using a number, it's the same idea as if you were using UTF-32

**Comment by fnuecke** [comment]
Textbuffers are currently set up as arrays of chars. Changing that to arrays of ints might work somewhat-ish, but would complicate a few things. It'd also double the bandwidth use of screen updates for something maybe 1% of all people playing OC would use :P

**Comment by fnuecke** [comment]
Oh, and I was referring to `Character.toChars` in the above.

**Comment by dgelessus** [comment]
Dang, I keep forgetting that in the end screens don't use strings in any way and are really just 2D `char` arrays. This now makes much more sense. -.-

**Comment by gamax92** [comment]
Ahh, right. That whole mess, carry on. Also now that I actually look at whats in the upper set, seems useless to use it. A lot of it is just unmapped/non existence, placeholder symbols, obscure languages, duplicates of other symbols. Would only be useful for more text-GUI elements or a couple of other font sets. Not like there are already ~2000 place holder symbols in the current set :cake: 
![](http://i.imgur.com/ngSW7DB.png)

(Also just wondering, wouldn't it be more bandwidth friendly to send things as UTF-8 strings instead of character arrays, since the majority of the text on screen is likely to be ASCII which is one byte.)

**Comment by dgelessus** [comment]
ASCII only requires 1 byte in UTF-8, but code points 0x0100 - 0xFFFF require 3 bytes. Depending on how Minecraft's network protocol works it might be even more wasteful - UTF-8 characters would need to be `String`s, which are based on 16-bit `char`s. If that isn't optimized in any way, you'd be sending 8-bit data in 16-bit blocks, taking up twice as much space as really necessary. Of course you could store the UTF-8 bytes in a `byte[]` instead of a `String`, but that would require even more intermediate conversion. (Disclaimer: I have no idea how Minecraft's network protocol actually works, I'm just looking at byte length.)

**Comment by gamax92** [comment]
I believe you can tell Java how to store its strings, but it will by default use UTF-16 or something like that.

**Comment by fnuecke** [comment]
Actually, never mind that part. I forgot how I actually do things... the buffers are converted to strings and stored that way, then split up into char arrays again when loading. So the bandwidth would only change based on the chars actually used!

But yeah, since that additional range doesn't seem particularly useful anyway, I don't think it warrants the work involved.
