### ISSUE TITLE
__gc metamethods causing out of memory errors...

### ISSUE THREAD

**Issue by mpmxyz** [MightyPirates/OpenComputers#1079]
Here's a tricky one for you:
I've been chasing an out of memory bug for a while. And #991 was only part of it.
It probably has to do with __gc metamethods allocating memory. That is fine if the garbage collection happened because enough time passed since the last one. But it's calling for trouble if it has been triggered by a low amount of free memory.
Try this code:
`
for i=1,1000 do a=setmetatable({},{__gc=function() end}) end
`
If it runs fine, you might have to run it again - at the end lua.lua and the whole computer crashes with an "out of memory" error.

But it was an empty function. How did that happen?
I haven't analyzed it completely yet but at least part of it lies within the file machine.lua.
To be more exact: the function sgc. It is the function that - behind the scenes - is actually used as the __gc metamethod. To execute the user supplied __gc metamethod it creates a new coroutine with the given function and executes it once. And this coroutine creation obviously needs memory - at a time, at which there is almost no free memory available.

**Comment by MyNameIsKodos** [comment]
This may or may not be related, I'm not entirely sure.  But the other day, I was idling on the server I play on, my computer on and in the Lua interpreter, doing nothing, and it randomly beeped twice and shut off.  I analyzed it to find that it crashed with an Out of Memory error as well.

**Comment by fnuecke** [comment]
While this can't be completely prevented, because there has to be some form of time limit enforcement in the user defined `__gc` callbacks, this change should make the wrapper a lot less memory hungry. It's essentially re-using the same coroutine now, unless some `__gc` actually times out, in which case it has to be recreated.

The example code above, for example, instead of crashing the test computer immediately, could now be run once without issue, and twice in close succession, merely bouncing me back to the shell, after which I could re-start the interpreter and do it again.
