### ISSUE TITLE
Error found with FilteredEnvironment

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#1094]
I have made a FilteredEnvironment for a Driver that removes a certain Callback function depending on a config option which can be changed in the in-game config GUI. If the config option is turned off and you load the world, place an adapter next to the block the environment is made for and open the Lua interpreter, `=component.theBlock.theMethod` properly returns "nil" as the method doesn't exist (It does have documentation so it would print something otherwise). When you now close the world (but not the game!), change the config option in the ingame config GUI and re-load the world, `=component.theBlock.theMethod` prints an error, something about "key not found" pointing to kernel, and crashes the Lua interpreter (i.e. makes you return to the shell). This will continue to happen until you break and replace the adapter block adjacent to the block the driver is on because then it re-loads the callback list properly. After the Adapter has been replaced, `=component.theBlock.theMethod` properly returns the component documentation.

**Comment by fnuecke** [comment]
ce552ff99de94b84e93da84007c0aad2e36bcbd1 should fix the error. The method will still be nil, though, because the Lua side caches the proxies (for very much noticeable performance), and there's no easy way to invalidate proxies, so a reboot of the ingame computer will still be required.
You could work around this by disconnecting the component, recreate and reconnecting it, if you really have to.
