### ISSUE TITLE
Possible memory leak when place(render) hologram

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#1105]
http://pastebin.com/8SWD7rwF

**Comment by fnuecke** [comment]
I doubt it's a memory _leak_, because that code only runs once, to initialize some global data structures re-used for rendering all holograms.

Try bumping up your max memory (`-Xmx2G` or so). If that doesn't work it might be the GPU not having enough memory, in which case I can try to catch that and simply not render holograms or something...

**Comment by Kubuxu** [comment]
When there is a memory leak it can happen anywhere. The place where the OOM Exception shown usually is not cause of memory leak.

**Comment by ghost** [comment]
1.5.3 was without this issue, players report me this issue when upgraded to 1.5.6

**Comment by fnuecke** [comment]
It's quite possible that addition of textures/blocks/other data in either OC or another mod brought this over the limit. This is "direct" memory that cannot be allocated, after all. Have you tried increasing the max heap space? I'm pretty sure I read somewhere that that should also increase the available max direct memory. Alternatively you can try bumping that directly via `-XX:MaxDirectMemorySize=256m` for example (the default value and whether it's enforced or grows dynamically seems to be left to the implementation of the JVM, apparently, one mentioned default I found was 64m).
