### ISSUE TITLE
[Feature] debug.getinfo()

### ISSUE THREAD

**Issue by Kubuxu** [MightyPirates/OpenComputers#1110]
To make strict mode for Lua work intuitively I have to to use debug.getinfo to detect main chunks. This can be done by matching tracebacks but it is slow and also not compatible in case of native functions.

**Comment by mpmxyz** [comment]
You have to be careful though, because it would allow access to the original pcall function using "f" within the "what" string. (User side pcall has been wrapped to avoid someone using it to circumvent timeout errors.)
Here are some links to the documentation:
http://www.lua.org/manual/5.2/manual.html#lua_getinfo
http://www.lua.org/manual/5.2/manual.html#pdf-debug.getinfo

**Comment by Kubuxu** [comment]
The functions `f` and `L` could be even disabled. What I really need is to check using option `S` and `what` element which can be `main`, `C` or function name. I have to filter those three results.

**Comment by fnuecke** [comment]
Hrm, so long as the returned information is limited to the basics / string values it looks like it should be safe to expose a wrapper for that. I'll have a look at `getinfo`'s actual implementation, first, though, to make sure it doesn't have any possibly undocumented side effects.
