### ISSUE TITLE
robot.forward()/robot.back()/robot.up() returns 'impossible move' even if there is empty space and chuck loaded

### ISSUE THREAD

**Issue by ivan114** [MightyPirates/OpenComputers#1113]
I created a tree chopping program for chopping 2*2 spruce wood
The robot will chop the tree layer by layer from the bottom
However when it reached the 2nd last layer and go up to the last layer
robot.up() returns 'impossible move' and particle effect come out
![2015-04-30_18 01 26](https://cloud.githubusercontent.com/assets/3946919/7410624/33e0ae54-ef63-11e4-91e4-f03834f06a5c.png)
![2015-04-30_18 01 17](https://cloud.githubusercontent.com/assets/3946919/7410710/06f334b0-ef64-11e4-9613-01d18a8b310b.png)
I have tried using robot.forward()/robot.back() but still the same problem
It should able to up the last layer as it emptied the space before going up
This problem only occur between the last wood layer and 2nd last wood layer, but I don't know why.
Here is the code I used, the tree chopping part is in stage==2:

``` lua
local component = require("component")
local sides = require("sides")
local robot = require("robot")
local stage = 0
local level = 0
local wCounter = 0
while true do
  if stage == 0 then
    level = 0
    if not robot.detect() then
      stage = 5
    else
      robot.select(1)
      robot.swingDown()
      stage = 1
    end
  elseif stage == 1 then
if not robot.compare() then
      print("Waiting..."..wCounter)
      wCounter = wCounter + 1
      os.sleep(10)
    else
      print("Start cutting")
      robot.swingDown()
      robot.placeDown()
      robot.swing()
      robot.forward()
      stage = 2
    end
  elseif stage == 2 then
    local s,m
    robot.swing()
    robot.forward()
    robot.turnLeft()
    robot.swing()
    robot.turnRight()
    robot.back()
    robot.turnLeft()
    robot.swing()
    robot.turnRight()
    robot.swingUp()
    s,m = robot.up()
    while not s do
      robot.swingUp()
      print("error msg: "..m)
      s,m = robot.up()
    end
    level = level + 1
    s = true
    if not robot.detect() then stage = 3 end
  elseif stage == 3 then
    if level > 0 then
      robot.swingDown()
      robot.down()
      level = level - 1
    else
      stage = 4
    end
  elseif stage == 4 then
    obot.back()
    robot.turnLeft()
    while robot.count()~=0 do
      robot.drop()
      robot.select(robot.select() + 1)
    end
    robot.turnRight()
    stage = 0
  elseif stage == 5 then
    robot.turnLeft()
    robot.suck(4)
    robot.turnRight()
    robot.forward()
    robot.forward()
    robot.turnLeft()
    robot.place()
    robot.turnLeft()
    robot.forward()
    robot.turnRight()
    robot.place()
    robot.turnRight()
    robot.place()
    robot.turnRight()
    robot.turnRight()
    robot.forward()
    robot.turnRight()
    robot.turnRight()
    robot.place()
    stage = 0
    print('Round Finished')
  end
end
```

**Comment by fnuecke** [comment]
Robots have a flight-height limitation. The general movement rules for robots go like this:
- 1. Robots may only move if the start or target position is valid (e.g. to allow building bridges).
- 2. The position below a robot is always valid (can always move down).
- 3. Positions up to `flightHeight` above a solid block are valid (limited flight capabilities, default is 8).
- 4. Any position that has an adjacent block with a solid face towards the position is valid (robots can "climb").

Here's an image visualizing that (minus the second rule, because that'd just clutter it).
![Imgur](http://i.imgur.com/LXhH3tc.png)

As of 1.5.9 (you can grab a dev build if from [Jenkins](http://ci.cil.li) if you like) you'll be able to install hover upgrades to increase (tier 1) and pretty much circumvent (tier 2) this limitation. Or you can disable this in the config, by setting `limitFlightHeight` to 256 or so.
