### ISSUE TITLE
Increase number of components for each CPU tier?

### ISSUE THREAD

**Issue by Mordenkainen** [MightyPirates/OpenComputers#113]
While I like the mechanic, I feel the current component limits may be a bit low and/or not working properly.

As an example, I built a computer with:
tier 1 chassis
tier 1 cpu
tier 1 hdd
tier 1 display adapter
redstone card
tier 1 screen
keyboard
1 adapter block (interfacing with 1 carriage controller)
1 power converter block

This system had too many components to boot. It almost feels like that this is just about the "minimal" useful system, with the exception of perhaps the adapter and/or redstone card. While removing one of these components allowed the computer to boot, I don't believe the minimal system + two points of contact with the outside world should be beyond a tier 1 system.

Also:

```
for address, name in components.list() do print(name..": "..address) end
```

only lists 8 components, so I am not quite sure how this system exceeds the limit of 8 components for a tier 1 CPU.

Perhaps the limit could be changed, or made into a config entry?

**Comment by fnuecke** [comment]
Is this using the second prerelease? Because file systems no longer count towards the component limit starting with that one, so that will... "relax" the limit, relatively speaking. I'll also make the computer itself not count as a component, so that's one more other component that can be used.

As for the message that there are too many components, with that build, that's odd either way. It may be due to a missing list update... I'll force refreshing the list of components when trying to start a computer, that should fix it.

**Comment by Mordenkainen** [comment]
Please ignore my comment about the count possibly being wrong. I just realized that I had removed the HDD from that computer, bringing the count down to 8. It was indeed 9 with the HDD installed.

This was with the first prerelease, I will update to the latest and give it a try, thanks!
