### ISSUE TITLE
Database shift click bug

### ISSUE THREAD

**Issue by Keridos** [MightyPirates/OpenComputers#1139]
When shift clicking stacks of items into the database upgrade, at least with redone conduits from enderio, instead of only putting in in once, it fills the entire database slots which are empty with that item. using dev build 621 from your jenkins.

**Comment by fnuecke** [comment]
Not really a bug, more (subjectively) unexpected behavior. Shift-clicking inserts a stack, distributing it across slots. Since the slots have size zero, it inserts into all empty slots, but also tries all slots, because no items are "consumed". I'll have to check if adding a special case to avoid that is reasonably simple to add.
