### ISSUE TITLE
Remove "global" loot.properties, make it be in dirs and configure the dir as a loot

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#1140]
Change this:

```
loots
| - loot.properties
| - ADir
| - AnotherDir
```

into this:

```
loots
| - ADir
|   | - loot.properties
| - Another Dir
|   | - loot.properties
```

**Comment by Vexatos** [comment]
Why? That does not make any sense at all.

**Comment by SoniEx2** [comment]
@Vexatos What do you mean? you can `ls` in java.

Each subdir loot.properties would have things like LootName=<name>, Weight=<weight>, etc, instead of having a "global" DirName=LootName:Weight:Etc.

**Comment by Vexatos** [comment]
Yea, but why would you need it? It would just slow down parsing a lot.

**Comment by Kubuxu** [comment]
And editing.

**Comment by fnuecke** [comment]
I don't see the point in this, it just adds another, unnecessary level of nesting, IMHO. Because I'm assuming you'd have another subdirectory for the actual loot disk contents, or you'd prevent the use of the file `loot.properties` in the ingame file system. Last but not least, this would break existing setups.

Give me a _reasonable_ use-case where this makes sense, and I may reopen it.

**Comment by SoniEx2** [comment]
It's easier to git diff it and you don't have to use git blame.

**Comment by SoniEx2** [comment]
Oh and it'd allow ":" in names.

**Comment by LizzyTrickster** [comment]
how would it be easier to git diff? surely all changes going to one file are easier to track then multiple little files?

**Comment by SoniEx2** [comment]
Mostly the committer/author part. Makes it easier to know who made what.

**Comment by natedogith1** [comment]
Having some form of non-global file could allow for extra loot disks to be added more easily by users/servers. Actually, is there a way for users/servers to add loot disks without modifying the jar?

**Comment by fnuecke** [comment]
> Makes it easier to know who made what.

Uhh, why would you look at the `loot.properties` instead of _the actual files_ for that? Sorry, but that argument makes no sense to me.

> Oh and it'd allow ":" in names.

No one has brought this up in, what, over a year? So demand doesn't seem to be high enough to validate a breaking change. If anything, allowing to escape colons in the name could be a solution to hat (i.e. `dir=name\:with_colon:1:dyeMagenta`).

> Actually, is there a way for users/servers to add loot disks without modifying the jar?

Yes, throw them in `<world save>/opencomputers/loot/<loot disk>/<content>`. Have a `<world save>/opencomputers/loot/loot.properties` with the same format as the one in the JAR (i.e. `<loot disk>=Label:weight:color`).
Keep in mind that those are only re-checked on world load, so if you add some you'll have to reboot the server.

**Comment by SoniEx2** [comment]
Can other mods add loot disks without modifying the jar?

**Comment by fnuecke** [comment]
No, but I'm planning to add a way for that (both loot disks and custom EEPROMs).

**Comment by SoniEx2** [comment]
Can you make it so it only requires putting files in a dir, and OC autodiscovers it?

**Comment by fnuecke** [comment]
It'll probably be something along the lines of "provide path to directory containing a loot.properties file and directories for the actual loot disk contents". Well, class name + path, to make it search in the mod's JAR.

**Comment by SoniEx2** [comment]
;_;

**Comment by SoniEx2** [comment]
;_; You know I'm only doing this because ~~I'm curious about how to do it in~~ I wanna copy it into my mod, right?

**Comment by LizzyTrickster** [comment]
So you want others to do your work for you?

**Comment by fnuecke** [comment]
Not sure if that was just a bad choice of words, because yeah, that's what it sounds like.
Either way, locking this because this is getting way off topic.
