### ISSUE TITLE
 Unsupported platform, persistance (armv7)

### ISSUE THREAD

**Issue by fagci** [MightyPirates/OpenComputers#1142]
Hello.
I have

```
java version "1.7.0_60",
OpenComputers-MC1.8-1.5.9.23-universal.jar,
Forge Mod Loader version 8.0.76.1402 for Minecraft 1.8,
Linux host 3.0.36+ #2 SMP PREEMPT Sun Dec 8 13:01:00 PDT 2013 armv7l armv7l armv7l GNU/Linux
```

I have already installed Eris from sources by make linux && make install.
Library successfully loads by

```
ldd -v native.32.arm.so
        libc.so.6 => /lib/arm-linux-gnueabi/libc.so.6 (0x40189000)
        /lib/ld-linux.so.3 (0x400f8000)

        Version information:
        ./native.32.arm.so:
                libc.so.6 (GLIBC_2.7) => /lib/arm-linux-gnueabi/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib/arm-linux-gnueabi/libc.so.6
        /lib/arm-linux-gnueabi/libc.so.6:
                ld-linux.so.3 (GLIBC_2.4) => /lib/ld-linux.so.3
                ld-linux.so.3 (GLIBC_PRIVATE) => /lib/ld-linux.so.3
```

But when I run server, at OC Api init process file OpenComputersMod-1.5.9.23-native.32.arm.so disappears and log says:

```
Could not load native library 'OpenComputersMod-1.5.9.23-native.32.arm.so'.
java.lang.UnsatisfiedLinkError: /home/fagci/mcserver/OpenComputersMod-1.5.9.23-native.32.arm.so: /home/fagci/mcserver/OpenComputersMod-1.5.9.23-native.32.arm.so: cannot open shared object file: No such file or directory
...
```

Why it occures?

**Comment by fnuecke** [comment]
OC doesn't look for the libraries on the system, it only uses the ones it ships itself (in the JAR), because those additionally contain the required glue library to make things usable from Java.

Could you please:
- Clone [the OC-Natives repo](https://github.com/MightyPirates/OC-Natives) (with `--recursive`!) and try to build that (see readme in repository)? You may have to adjust some paths in the `build.gradle`.
- If that works, you'll find the libraries in `binaries/nativeSharedLibrary/*`.
- Rename them to fit the other libs in OC (`native.32.arm7.so` for example) and add them to the OC JAR (at `assets/opencomputers/lib`).
- Finally, in the config, set `forceNativeLibWithName` to the lib you want to test, so e.g. `forceNativeLibWithName=native.32.arm7.so`.

What kind of system/hardware are you running on, by the way?

**Comment by fagci** [comment]
Ok will try =)
My HW is mk908 v5 TV stick =)

**Comment by fagci** [comment]
Thank you!
It works after compilation of library with 
`gradlew armDebugNativesSharedLibrary` and `arm-linux-gnueabihf-gcc` in build.gradle

**Comment by fnuecke** [comment]
Great, thanks for sharing that info!
I'll be sure to direct anyone else using this rather rare (I think?) setup to this issue in the future :)
