### ISSUE TITLE
Allow custom Geolyzer scan area

### ISSUE THREAD

**Issue by fagci** [MightyPirates/OpenComputers#1149]
We need some options for scanning: `miny, maxy` for speedup scanning process. =)
I already made some small scanning program, output via GPU, but too slow..

**Comment by fnuecke** [comment]
What do you mean exactly, and how do you imagine it would speed things up?

**Comment by fagci** [comment]
Geolyzer scans whole column by Y axis, but I need only two blocks (32, 33), as example. As I analyzed, scanning process is bottleneck of fast density determining.
And I already have an upgraded tablet (diamond parts) and optimized code (local vars, less calculations in loop), but scanning speed too slow...
May be make an init function, ex.: geolyzer.setYRange(min,max)

**Comment by fnuecke** [comment]
That won't make it faster, though. It'll just give you less data. The limiting factor here is that the look-up has to be synchronized to the server thread (since it accesses world information), so a single scan will always take (at least) one world tick.

The only way to speed it up would be to increase the amount of data retrieved in one scan, but I don't really like that idea, because, since this has to run in the server thread, it can then start lagging the server.

Allowing a custom scan "area" to be defined (instead of the pillar, say, a bounding box) with a maximum volume (equal or similar to that of the current pillar) might be an option, but it'd have to wait for OC 1.6, because it'll need breaking changes to the API (since the scanning is implemented via an event that's also available via the API).

**Comment by fagci** [comment]
I understood=)
So, bounds will be nice way to improve scanning process!
Will checkout changes frequently=)

**Comment by TheRealOrangus** [comment]
A method like this:

``` lua
geolyzer.scan(x1: number, y1: number, z1: number, x2: number, y2: number, z2: number): table
```

would be so much awesome!
