### ISSUE TITLE
[Suggestion] Integrated Graphics

### ISSUE THREAD

**Issue by GitBranch** [MightyPirates/OpenComputers#1154]
Starting from Tier 2, there will be an additional kind of CPU called "CPU (With Integrated Graphics)", which has a GPU a tier below them, i.e. A Tier 2 CPU will get Tier 1 Graphics. A Tier 3 CPU will get Tier 2 Graphics.

Now I know if I want simplicity I should go to computercraft but whatever.

**Comment by rashdanml** [comment]
A possible way to balance it: the recipe to craft said a Tier 2 CPU with iGPU: a regular Tier 2 CPU and a Tier 1 GPU. That way, you have to craft a GPU either way, but combining the two lets you have more expansion slots available for other things. 

And since a Tier 3 CPU with iGPU would only have a Tier 2 GPU, the Tier 3 GPU would have to be placed into an expansion slot with a Tier 3 CPU to get the maximum possible features from both. So, no Tier 4 CPU.

**Comment by GitBranch** [comment]
^ great idea... anyways. I was too spoiled by creative... so... didn't think about crafting

**Comment by skyem123** [comment]
Well... While this does kinda go against the normal OC style, it does seem useful.

**Comment by fnuecke** [comment]
I actually don't dislike this idea, and the way @rashdanml suggested is what I had in mind when I read the suggestion, too. Maybe a few additional "glue" components (some of the dreaded iron nuggets, a t1/t2 chip and some redstone or so).

I'll look into it, if I'm not mistaken this should be relatively simple to implement.
