### ISSUE TITLE
Add support for tables and functions in signals

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#1157]
This can be done by writing the signal system in Lua and having an internal pollSignal function (consumes and returns any Java-side signal, or returns nil if no signals are available), which would only be called by the BIOS every time a pullSignal reaches it.

Alternatively it's possible to use a bunch of IdentityHashMaps and WeakHashMaps and the Lua registry to allow tables and functions to support round trips when going into Java land, altho this is a hack.

This would let me push tables into signals so I can get very lazy UUIDs (no 2 tables are ever equal as you get an out of memory error when that happens).

**Comment by Vexatos** [comment]
Tables: `serialization.(un)serialize`. Done.
Functions: No.
Do not pass table or function objects in signals. That's just wrong. You can't pass objects over a network in real life either, only string messages.

**Comment by SoniEx2** [comment]
@Vexatos 

``` lua
local t = {}
local t2 = serialization.unserialize(serialization.serialize(t))
print(t == t2) -- prints "false", any fix? I *need* their _guaranteed uniqueness_ property for this.
```

**Comment by SoniEx2** [comment]
Hmm I guess I could use os.clock() instead...

**Comment by Vexatos** [comment]
@SoniEx2 firstly, it needs to be `serialization.unserialize(serialization.serialize(t))`; secondly, it will still return false because it will create a new table for obvious reasons. You _can not and should not_ be able to send entire objects through a network, it just does not make any sense at all.

**Comment by SoniEx2** [comment]
> You can not and should not be able to send entire objects **through a network**

Wat. I'm talking about OS signals/events. AKA syscalls.

You CAN send pointers thru Linux syscalls, so why can't you send them thru OC signals?

**Comment by Vexatos** [comment]
OS signals? Do those even exist in OC?

**Comment by SoniEx2** [comment]
http://ocdoc.cil.li/api:computer

http://ocdoc.cil.li/api:event

You didn't know?

**Comment by Vexatos** [comment]
Ah that's what you mean, that's what I mean as well... Might just have been a misunderstanding.

**Comment by SoniEx2** [comment]
Ok so why not?

**Comment by fnuecke** [comment]
The reason the queuing system is implemented on the host side (and therefore more limited, because it has to be serialized "manually" and can't automagically use Eris) was originally that the memory made available to Lua was much more limited, so that tended to cause out of memory issues. Now it's mostly to avoid each architecture having to re-implement their own queuing mechanic.

You can still very easily implement what you want on top of the existing system, however. Wrap push and pull signal, use randomly generated ids for the events and store the data in a local table. I'd be happy to merge a good implementation of that into OpenOS.

**Comment by gjgfuj** [comment]
Indeed the signal api is already wrapped, in the event api.

**Comment by SoniEx2** [comment]
> use randomly generated ids

Not guaranteed to be unique.

**Comment by fnuecke** [comment]
Well there are no hard guarantees anyway, since a component could theoretically interfere. But I suppose you could just use sequential ids - in fact, just `#pending` (with pending being the table of queued signals) should work.

**Comment by SoniEx2** [comment]
So... use a global?

Because, you know, this program could be loaded multiple times. (or am I mistaking OC for CC? didn't OC have a multi-program thing?)

**Comment by Vexatos** [comment]
@SoniEx2 _G is the exact same thing for every program in OC. So if you do it in _G, it will be safe across all programs.

**Comment by natedogith1** [comment]
Since you're trying to use tables to implement uuids, couldn't you just tostring the table and use that as the id?

**Comment by fnuecke** [comment]
> So... use a global?

No, a local.

> Because, you know, this program could be loaded multiple times

No, it'd be an init script. And even if you ran it multiple times (which would be dumb) you'd just wrap around the already wrapped methods again, which would have no visible effect, it'd just increase memory use because of the additional layers.

> tostring the table

inb4 Soni cries "not guaranteed to be unique across loads" (which, to be fair, is correct, but such a collision is really unlikely I'd wager).

**Comment by payonel** [comment]
I think we have seen in numerous user projects that the limitation of the signal system can easily be worked around using remote procedure calls and clever metatables. I think it best to leave the signal system as it is.
