### ISSUE TITLE
Computers no longer accept power from Electrical Age cables

### ISSUE THREAD

**Issue by cinder1992** [MightyPirates/OpenComputers#1177]
Upon first loading OpenComputers without a power mod of some sort installed, the warning text claims that Electrical Age is a compatible power source for computers:
![ocbug1](https://cloud.githubusercontent.com/assets/2326377/7810105/3d067a3e-0397-11e5-8a48-d810bb0ce23b.png)

 However, with the current OC version and EA version, it appears this is not the case:
![ocbug2](https://cloud.githubusercontent.com/assets/2326377/7810153/8955b904-0397-11e5-9973-14def426e79f.png)

The power warning text goes away when Electrical Age is installed, however it appears that compatibility is broken.

The power setup shown is a constant-voltage source of 200v, I have tried it with all other cables and voltages.

Tested with the following mod versions:
forge-1.7.10-10.13.3.1478
OpenComputers-MC1.7.10-1.5.11.25
ElectricalAge-BETA-1.9_r46

**Comment by fnuecke** [comment]
The conversion logic is implemented on ELN's side. IIRC there should be an extra converter block. Since OC's API hasn't changed in that area in a long time, I'd assume that still works. That's that part (i.e. cables probably won't connect directly).

There was also an issue on the OC side where it failed to recognize ELN as a power providing mod, that's what I fixed just now (i.e. it would still have worked if some other power providing mod was also present).

**Comment by cinder1992** [comment]
OC did NOT fail to recognize ELN as a power providing mod, I was just unaware that there was a converter block required.

**Comment by fnuecke** [comment]
Oh, I didn't see the text over the first screenshot. Huh, it's kind of weird that it did recognize it then, though... maybe it's shipping some other power mods' API as well? Strange. Anyway, glad to hear it works!
