### ISSUE TITLE
Float positions for 3D Printing

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1179]
Well, yeah, allow floats like 14.5, not just 14 and 15, please? :D

**Comment by fnuecke** [comment]
I'm honestly not a big fan of that idea, the full "pixel" thing was very deliberate choice. I kind of dislike things deviating from MC's inherent "units" (based on the 16x16 textures, that is).

Technically speaking, though, it'd be quite possible, but I'd still restrict it to 0.1 steps, because I need/want to keep storing the values as bytes, and 1/16th increments would be very awkward to work with.

**Comment by Inari-Whitebear** [comment]
It would be particularly nice to print text onto a background, or have a way to make even vent-covers..

**Comment by payonel** [comment]
Trying to resolve old tickets -- and because sangar wasn't "a big fan" of this I think it best to close it (As opposed to labeling this open for adoption)
