### ISSUE TITLE
Remote terminal in block format

### ISSUE THREAD

**Issue by Zyles** [MightyPirates/OpenComputers#118]
Please add ability to use a normal computer as a remote terminal into a server rack wirelessly.

I don't want to put down 400 cables with chunkloading.

This computer should also have lower requirements since it acts as a "thin client" basically and you already have most on the server. But it needs computer screen support too of course.

Also maybe the ability to repeat wireless over longer distance?

Thanks!

**Comment by fnuecke** [comment]
There was an interesting idea on the IRC about this: allowing a remote terminal to be placed onto a screen (like a keyboard, basically). When opening the screens' GUI, what would actually open would be the bound server's GUI. The bigger problem would be the direct rendering on the screen, this isn't supported by the current code architecture at all right now, so that may turn out to be a good bit of work. Anyway, I'll look into it when I have the time.

As for wireless repeaters/routers, this has been requested before, and I'm planning to add something like this. I'll create an extra ticket for that.

**Comment by fnuecke** [comment]
Linked cards in 1.3 + software should do the trick.
