### ISSUE TITLE
3D Prints don't count as solid blocks?

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1181]
So yeah, seems even if i print a full block of a solid material, redstone pretends it isn't a solid block... is this intended?
![2015-05-27_19-30-50_exfro7](https://cloud.githubusercontent.com/assets/1077971/7842982/fe95a0de-04a6-11e5-91aa-70c0f069c006.png)

**Comment by fnuecke** [comment]
Since the only difference to, say, the Redstone I/O block seems to be the `isOpaqueCube` override, I'll have to assume that's what's causing it (which would make sense, because it's also behaving that way for glass, which is a full block). However, that method is not context sensitive, so it has to return the same value for all prints, so it has to be what it is. So, sorry, but can't fix, #BlameMinecraft.
