### ISSUE TITLE
Lua 5.3 Missing Functions

### ISSUE THREAD

**Issue by natedogith1** [MightyPirates/OpenComputers#1184]
The Lua 5.3 architecture seems to be missing some functions. It's missing a lot of the utf8 functions (and I think a few of the current implementations might not match the specifications). It's also missing the new math functions/constants.

**Comment by dgelessus** [comment]
Looking at 206f432 it seems that the `utf8` lib is not available at all. OC's `unicode` lib is different and was already available before Lua 5.3, although it does provide a few functions that are similar to some of the `utf8` functions.

**Comment by fnuecke** [comment]
Yeah, I'll need to have a look at the new `utf8` lib, should probably be safe to expose all of it. Will need adjustments to JNLua though, which entails recompiling the libs, so I'll want to wait to see if other issue pop up to save myself the time recompiling more often than necessary (because that's quite time consuming with several VMs and real machines I have to work with for that :P).

**Comment by fnuecke** [comment]
Done via a1be4941342d558b28e61e49b186ade7fdd57dbc.
