### ISSUE TITLE
Wireless Redstone: SlimeVoid Edition is on MC1.8, but OC doesn't detect it

### ISSUE THREAD

**Issue by Techokami** [MightyPirates/OpenComputers#1226]
Quite simply, the non-ChickenBones incarnation of Wireless Redstone is out for MC1.8, but OC on 1.8 needs to be updated to support it.

**Comment by fnuecke** [comment]
Had a look, and they changed something so that the old way doesn't work anymore. And the API is confusing as ever (I never really found a proper entry point to begin with, hence the reflection hackery). Honestly don't have the motivation nor time to dig into this. If someone wants to take a look, please be my guest.

**Comment by payonel** [comment]
the never went beyond 1.8 and we don't support 1.8 anymore
