### ISSUE TITLE
Better utf8 library?

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#1230]
The utf8 library over here is much more feature complete, works in both lua 5.2 and 5.3, and uses the Lua license
https://github.com/starwing/luautf8

Is it possible this one could be added instead, It's compatible with the original lua 5.3 utf8 api, doesn't remove existing features such as those from the Scala unicode api, and adds even more creating a more complete "utf-8 aware version of string api"

It is a bit of an increase of course, about 50KiB for me when I compiled it in lua5.3

Some of the tables can be removed, such as the width tables, since they don't correspond to unifont

It also properly handles upper unicode points, the Scala unicode api has several issues with that:
- char cannot generate them
- lower/upper/sub/reverse/wtrunc all mangle them

**Comment by dgelessus** [comment]
Sounds to me like that should go into the `unicode` library, not `utf8`. Lua's built-in `utf8` lib is minimalistic on purpose and only handles encoding and decoding of UTF-8 strings, I don't think that should be changed. Maybe `unicode` should include all attributes of `utf8` though, that way existing programs need less rewriting and less `require`s are required. (badum disch)

Speaking of `utf8` in Lua 5.2, [this](https://github.com/dgelessus/oc-stuff/blob/master/utf8.lua) might be of use.

**Comment by gamax92** [comment]
Well, you can always just simply copy the lutf8lib.c file from lua 5.3 and tweak it a tiny bit, if you wanted utf8 in Lua 5.2. But yeah, the idea is that it would go into the unicode library, since the existing stuff (lower/upper/sub/reverse/len/char) is in that. Then you wouldn't get two utf8 separate handling libraries when 5.3 is up and running

**Comment by fnuecke** [comment]
I'll have to actually go through what each of them do. OC's `unicode` lib is kind of a mess at this point, because of all the quick-quick additions that were done to better support the Unifont rendering.

Depending on how much would be added over 5.3's `utf8` lib I might still want to keep them separate (I kind of don't want to change the standard lib stuff; in retrospect I'm quite unhappy with `os.sleep`, should really be `computer.sleep` or something, but too late for that now). Either way I'm not too keen on recompiling the native libs >_> Will see what can be re-used from Java to add such functionality. Also, IIRC from glancing over the linked lib, it had pattern matching? That will most likely not make it, considering even the normal one is currently tightly wrapped to avoid it running for a long time for evil inputs.

**Comment by gamax92** [comment]
Ahh right, I forgot all of the pattern stuff was reimplemented in machine.lua, so that gets rid of find/gmatch/gsub/match. byte is covered by utf8.codepoint. char/len/lower/reverse/sub/upper are all covered by scala currently. charpos seems to be covered by utf8.offset. width/widthindex are not useful. title and upper only differ by 12 characters. fold and lower only differ by 14 characters.

Now that I look at it, the custom library is not worth it. Probably just not add it.

**Comment by SoniEx2** [comment]
@fnuecke Add computer.sleep and deprecate os.sleep (but keep it as an alias to computer.sleep for a few versions, maybe until Lua 5.4)
