### ISSUE TITLE
Connected textures with printer

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1250]
Maybe I'm missing something, but I can't seem to figure out how to make connected textures work with it. I'd assume there'd be a special texture name for the connected version of a texture, but the texture thingy doesn't wanna tell me it.
So this is either a feature request for that, or a bug report for the analyzer :D

**Comment by fnuecke** [comment]
Connected textures are probably implemented differently in each mod that does them, so I'm not sure a "catch-all" solution is even possible. If you can find someone with experience in adding compatibility with them (e.g. in facades supporting chisel textures) to give me a few pointers (or even have a go at adding compat to OC themselves), that'd be quite helpful, otherwise no promises as to when I'd look into this ;)
