### ISSUE TITLE
Robot drops items while digging (MCPC+)

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#127]
Using mcpc-plus-1.6.4-R2.1-forge965-B231 and OpenComputers-MC1.6.4-1.2.0

**Comment by fnuecke** [comment]
Can't reproduce (though I did try with B243, not B231), a little more context? What tool? If you're talking something like TC Hammers then that's expected and intended behavior (it only picks up the 'main' broken block).

**Comment by ghost** [comment]
It doesn't depend on the tool.

Tried B245, no changes.
Mods installed:
1.6.2_Jammy_Furniture_Mod_V4.5.zip
AdvancedMachines_exp_1.6.4.zip
buildcraft-A-1.6.4-4.2.2.jar
buildcraft-Z-additional-buildcraft-objects-1.0.7.558.jar
chargepads-1.6.2-universal-3.0.0.94-experimental.jar
CodeChickenCore 0.9.0.7.jar
CompactWindmills MC.1.6.4 v.1.0.2.3.jar
forestry-A-2.3.1.1.jar
IC2NuclearControl-1.6.2e-ic2-experimental.zip
industrialcraft-2_2.0.384-experimental.jar
mod_AdvancedSolarPanels_3_4_6_IC_EXP.zip
mod_zGraviSuite_1_9_8_MC_1_6_4_IC_EXP.zip
OpenComponents-MC1.6.4-dev27.jar
OpenComputers-MC1.6.4-1.2.0.jar
ProjectRedBase-1.6.4-4.2.2.19.jar
ProjectRedIntegration-1.6.4-4.2.2.19.jar
ProjectRedLighting-1.6.4-4.2.2.19.jar
ProjectRedWorld-1.6.4-4.2.2.19.jar
Railcraft_1.6.4-8.3.2.0.jar
Transducers-1.1.0.zip
TrussMod-beta-1.6.4-32.jar
Universal-Electricity-3.0.1.45-core.jar
WR-CBE 1.4.0.6.jar

**Comment by fnuecke** [comment]
Hmm, odd. Just to make sure it wasn't "accidentally fixed", could you try with the [latest dev build](http://ci.cil.li/job/OpenComputers/)? If that doesn't work either I'll try to reproduce it with your mod list.

Edit: oh, also could you check your log for any related errors / stacktraces?

**Comment by ghost** [comment]
No errors in log, only one line related to the mod: "[INFO] [FakePlayer] Initializing fake player for li/cil/oc/server/component/robot/Player: [Playername.robot]"

I found the problem, it's AuthMe bukkit plugin. If it's disabled, robot works correctly. I think that adding fake player to "unrestricted names" may be a solution, but fakeplayers' names are different for each player.

**Comment by fnuecke** [comment]
There's a config option `robot.nameFormat` you can use to make all robots use the same name, could you give it a try and see if you can solve the issue that way?

**Comment by ghost** [comment]
I changed this to 'OpenComputers', now all robots have this name, but fakeplayers still use default format.

**Comment by fnuecke** [comment]
Thanks. That's interesting. I'll see if I can find what might be causing this.

**Comment by fnuecke** [comment]
Can't reproduce that, when I adjust that setting the fake players properly use that name:

```
2014-02-22 19:43:08 [INFO] [FakePlayer] Initializing fake player for li/cil/oc/server/component/robot/Player: [OpenComputers]
```

Or what did you mean by 'use the default format'?

**Comment by ghost** [comment]
Are you using latest dev build?
I described problem wrong. There's the situation: i make robot and place it first time, when robot.nameFormat is "%playername%.robot". Robot's and fake player's names are right. Then i change robot.nameFormat to "OpenComputers", restart the server, and place robot second time. It's name is "OpenComputers", but name of fake player is "%playername%.robot".

**Comment by fnuecke** [comment]
Yes, that was with the latest dev build (though nothing changed in the robot name logic since... forever). The robot name (from Analyzer) and fake player name (server log) always match up for me. Maybe this also has to do with the plugin? Could you try without so I know in which direction to investigate? Thanks!

**Comment by ghost** [comment]
All plugins disabled, but fake player name for any robot is always "Playername.robot", even robot is placed by another player, not "Playername".

**Comment by fnuecke** [comment]
Could you please post your config? (Upload it to pastebin or so)

**Comment by ghost** [comment]
Config: http://pastebin.com/XZGR8DwC

**Comment by fnuecke** [comment]
All right, to summarize:
- I set up a clean install of MCPC+ (B245) with the latest OC dev build (157) and your config.
- Robot and fake player were named as expected (`OpenComputers`).
- I edited the config to include `$player$`.
- Fake player is named after the first robot that gets loaded / placed.

So the issue here seems to be that MCPC+ initializes the fake player only once - for the first instance that is created for the custom player class. I assume this is done for performance, but I don't know how to work around this. The actual instances of the fake player instances are named correctly. I guess this would be a non-issue if MCPC+ would track its FakePlayer singletons based on the actual fake player's name instead of the class name. As it stands I don't think there's much I can do about this, except to declare variables the `nameFormat` as unsupported on MCPC+.
