### ISSUE TITLE
[Feature Request] Add 3D Printed Drone Cases and/or Robot 

### ISSUE THREAD

**Issue by rhjobe** [MightyPirates/OpenComputers#1281]
Add 3D printed drone cases to allow for more customization of Robots/Drones using the 3D Printer

**Comment by samwalls** [comment]
There could be issues if you think that is is necessary that the drones are the size they are, if you could make them so small that someone could barely hit it (if it was an attack drone for instance) it might be considered unbalanced; but then again, no one really used drones for weponisation. And for robots it obviously doesnt matter, since they take up a block anyway.

This would also mean that you could potentially make drones with a glass texture or something, and they are then invisible.or make robots equal to the size of a block, and then give them a random block's texture like camouflage (that would be funny). A way around this would possibly be to have it so that drone cases require the positions for the 4 hover-thingers to be defined somewhere in the block space.

**Comment by dgelessus** [comment]
I'm quite sure that the drone hitbox doesn't depend on the 3D model. Would be news to me if Minecraft mobs had pixel-perfect hitboxes. But you could still do annoying things with models that are only 1_1_1 pixel big and hard to see, so this feature should probably at least have a config option to turn it off.

**Comment by dstensnes** [comment]
I was just about to suggest this too, when i found this issue. This is exactly the thing i wanted to suggest. How nice it would be to have a drone avatar for the computer AI controlling your base :)
