### ISSUE TITLE
Other ways for robots to gain XP

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#129]
It might be interesting to have other ways to level up robots besides having them labor away all day. Some ideas that have come up so far:
- Allow 'supercharging' robots, i.e. pay a (very, very) large amount of energy to increase the XP of robots a bit.
- Allow 'recycling' old computer parts to increase a robot's XP. This might be done in a similar fashion to #128, except instead of RAM you'd use microchips or so.
- Add an upgrade that increases the speed with which robots gain experience.

If you have more ideas, please share them. Keep in mind that this is purely brainstorming right now, none of the above will necessarily be implemented.

**Comment by Mr-Turing** [comment]
problem with recycling is that with enough materials its trivial to just make infinite microchips and etc, same with energy.

On the other hand, having the robots more modular, with say an expanded battery, more efficient generator, faster engine etc would be cool, have you ever played with Steves Carts? Something kinda like that, you have a limit to how complex your robot can be.

All in all I think levels don't make much sense, if anything performace should degrade over time. Maybe operation speed could be dependant on power level.

**Comment by FredMSloniker** [comment]
The reason players collect experience is to spend it (enchanting and anvils in vanilla, more in other mods). Instead of experience enhancing a robot's abilities directly, it should be able to use it to do these things (with the right addons, at least).

Alternately, perhaps the robot should have the ability to vend collected experience, so you can send your robot out mining, then have it give you the orbs as well as the ores. (Perhaps robots could even be able to drain XP from 'willing' subjects to share with another in multiplayer?)
