### ISSUE TITLE
TCP events

### ISSUE THREAD

**Issue by tuxmark5** [MightyPirates/OpenComputers#1297]
Current buffer implementation when combined with internet (TCP) stream just keeps running an "eternal" loop until it receives enough data and then returns, which is horribly inefficient as it wastes CPU cycles.

Also right now there is no way to create internet applications that have a more advanced GUI as OC doesn't support waiting for TCP and keyboard/mouse events at the same time. The closest you can get to that is to use a timer and to poll socket every several milliseconds but that too is not only inefficient, but also adds a slight delay on all received TCP messages.

I propose to add a new signal that indicates when data is received through a TCP socket. This would make internet component way more useful, efficient and enable creation of more flexible applications.

**Comment by fnuecke** [comment]
Let me point you towards [the IRC program](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/loot/OpenIRC/irc.lua#L377) and rest my case :P

But seriously: you can set a timeout on the buffer, or alternatively you can simply not use the buffer at all and directly read on the socket, which is a non-blocking operation, to implement an event driven way of communicating. There's no good place to hook that into OpenOS itself, IMHO.

**Comment by tuxmark5** [comment]
Using a timeout is an awful way to do things. 
The current buffer's implementation is horrible as it keeps the thread running a loop at full capacity. 
There are already events such as "modem_message" related to communication. It's just as logical to have a similar analogy for TCP messages.

This could be implemented as a separate thread that monitors all TCP sockets and posts events to different computers when there is data available on a socket. I could implement it myself, but i'm not really a Scala person.

**Comment by fnuecke** [comment]
Nope, it does not. Reading from the socket is not a direct operation, so the actual read will make the computer yield. And as I said, you don't have to use the buffer at all, you can just read from the raw socket, which is non-blocking.

Equating OC's network messages with TCP sockets is kinda pointless, really, due to how immensely different they are in concept and implementation.

There are no threads in Lua. There are coroutines, yes, but they can't easily be used to do you what you seem to imagine, at the very least not in OpenOS, which is what I meant above. So.

And this has _nothing_ to do with the "host" side, so it has nothing to do with Scala, either :P

**Comment by tuxmark5** [comment]
The issue with raw & non-blocking sockets is that you have to read them repeatedly to know if there is a new data in them. I want events so you wouldn't have to. That's why things like select(2) exist in Linux/Unix.

As for threads, I was referring to a Scala/JVM thread that could use a Selector on SocketChannels:
https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/component/InternetCard.scala

**Comment by tuxmark5** [comment]
I guess I was not specific enough in my request. What I meant is for TCP read events to be available through computer.pullSignal(), which could have a new signal type, say, tcp_read that could indicate the socket that can be read and perhaps some user specified tag.

If this is for some reason impossible to implement, I would like to know why as not to waste anybodies time anymore.

**Comment by fnuecke** [comment]
I got that part, but I really don't want any more native threads running around than there have to be; due to the read yielding I'm not quite convinced the polling is bad enough to have yet another layer of threading that needs synchronizing and all that entails.

I'll leave it open for now, to get some more opinions on this.

**Comment by tuxmark5** [comment]
I guess I could provide a use case: I would like to create a "remote" app that controls all the robots via TCP commands (actually, any form of IPC would work for me, as the controlling app runs on the same machine as minecraft's server). That would mean that every robot in the game would non-stop keep polling open sockets to receive new commands. Imagine at least 100 bots doing it at the same time.

You would really only need just 1 native thread for this to work (a thread per bot would be obviously a waste). That thread could be too created lazily. So in most cases when average users don't use this functionality, the thread wouldn't be even created and thus, no performance lost. Hell, you could add a config option for this if that extra thread is so "dangerous".

I don't know much about Minecraft's (or Forge's) internals, but there might be slight possibility to reuse an existing thread for this (Minecraft's server must have a selector hidden somewhere as to handle multiple clients at once).

**Comment by jeffreykog** [comment]
It looks like this is the correct moment to let the TCP api make use of netty behind the scenes. Netty handles async IO really nice and prevents you from either making a thread per socket or make you want to pull your hair out over java NIO.

**Comment by jeffreykog** [comment]
With this, you can create some function similar to C's `select()` function to block in 1 location for multiple fd's

**Comment by fnuecke** [comment]
Hmm, I guess. Ideally this would be possibly by adding a direct callback to the internet card that is that `select` call. That way no additional threads would be needed.

**Comment by makkarpov** [comment]
I think that you should reuse existing Netty thread pool that is used by Minecraft to handle network. This way IO can become fully asynchronous without using any additional threads.

**EDIT**: Single player game can run without networking IO, so only in this case you should create your own thread pool.

**Comment by Kubuxu** [comment]
As it is only pushing an event a one selector thread should be enough there should no need for workers threads.

They are useful if you have some blocking operations to do on a buffer content. Pushing an event isn't one of them (AFAIK).

**Comment by fnuecke** [comment]
Giving this some more thought, I'm really not convinced the event path is a good one. How would a hypothetical worker thread know when to push another signal / when the current buffer has been read? If it were to just keep pushing, how would the Lua side know the event is still valid?

Exposing a `select` equivalent to be called from the machine seems much more reliable to me.

**Comment by makkarpov** [comment]
`select` is a good way when you need to handle multiple TCP sockets at same time. But in usual case, you need to handle a TCP socket + something else that uses events. In this case `select` (if I understood it's operation correctly) has no benefit over blocking `recv`.

**Comment by fnuecke** [comment]
Yeah, it'd basically have to be a select with timeout of zero (i.e. return immediately) because yielding from native callbacks is not supported (because those coroutines could not be persisted). The only advantage of querying the raw sockets manually would be that it could 1) be a direct call, i.e. return immediately and not in the next tick like read, 2) check for multiple sockets at once.

**Comment by tuxmark5** [comment]
@fnuecke Workers don't really need to know when the current buffer has been read. The only information that the signal would provide is a message saying "you can read from this socket, because there is some data in it now". The rest is handler by user/OpenOS. If OpenOS/user ignores these messages then the whole internet card model should work as it is unchanged.

Exposing raw select or something similar to it is not good enough as there needs to be a way to listen for both TCP "select" events and regular signals. And since there exists event system already in a form of signals, there is no need to invent a new event system exclusively for tcp events.

**Comment by natedogith1** [comment]
Could you have the OC computer call a method (when it reads the buffer) that tells the java/scala code that it can queue another event?

**Comment by fnuecke** [comment]
> The rest is handler by user/OpenOS.

Uhh, still. How would the worker know when to send the _next_ signal?

What @natedogith1 suggests could work, I suppose, i.e. setting a flag that a signal should be emitted if something is available.

**Comment by makkarpov** [comment]
> How would the worker know when to send the next signal?

When another packet arrives. Or maybe I misunderstood the question? 
A flag that prevents sending events will be also useful.

**Comment by fnuecke** [comment]
Here's the issue I'm seeing:
- Worker thread runs, sees data available, pushes "tcp_data".
- Runs again, sees data, pushes "tcp_data".
- Lua runs, pulls event, sees "tcp_data", reads _all the data_.
- Lua runs, pulls event, sees "tcp_data", tries to read but there's no data anymore.

**Comment by Kubuxu** [comment]
It could push an event with data in it. Not just that there is data waiting.

**Comment by fnuecke** [comment]
That's what the inet card did (for http requested data) in the olden days, and it was a nightmare to work with, so I'd rather avoid that :P

**Comment by makkarpov** [comment]
FIFO queue at event handler? Basic idea is to bundle data with event (maybe with some size-limiting and throttling), and implement some stream abstraction at lua side (maybe an replaying decoder one :D)

**Comment by fnuecke** [comment]
See my previous comment ;) I really don't like the concept of bundling the data with the actual events. Had it before, and it was terrible. And hacking low-level support for a specific signal type into the event handler doesn't sound like a very nice design, either :-/

**Comment by makkarpov** [comment]
But you not explained why it's terrible. I thought that it terrible because you need to process raw chunked data without any buffering.

**Comment by fnuecke** [comment]
It's terrible because if you `os.sleep()` or `event.pull(somefilter)` you potentially lose packets without knowing it.

**Comment by makkarpov** [comment]
Don't do `os.sleep()` then. It applies to all events, not for TCP ones. You can lose keystrokes or modem messages in exactly same way. Filtered `event.pull` isn't a TCP issue, it's issue of event library. Also, you can attach buffering implementation as `event.listen`

**Comment by makkarpov** [comment]
The main idea of implementing TCP events is not because they are error-proof, but because they create possibility to handle multiple event-bound things at same time. If you know that there will be TCP events - just do not filter it out. I think that only possible issue is if server sends data too fast and event queue overflows.

P.S. To mitigate this issue you either should look at Netty built-in traffic shaper or implement some `queue full` flag that will throttle connection

**Comment by fnuecke** [comment]
I'll ignore that first part, because "it's broken anyway" isn't really a good argument to convert a working and more robust system to it. ;) A listener can work, yeah, but it's generally more of a hassle to work with, because it's not automatically removed when a program terminates.

And while I realize what the desire here is, I don't want to break the existing system (again), which this would, pretty much. Or it'd be completely redundant, which would be really ugly and confusing.

At this point I think something along the lines of `requestDataNotification()` (quite probably under another name ofc) setting a flag, so that the inet card can send a signal when data is available sounds like the most backwards compatible way to also satisfy the request for easier "background" handling of TCP data. It'd also allow implementing a full "data via events" system on the Lua side (via a listener that's registered during startup, which is what they were originally meant for anyway).

**Comment by makkarpov** [comment]
Yeah, I do not think that "it's broken anyway" is a good argument, but I think that you _know_ that you write TCP program, and you _know_ that event is fired only once, and you _should_ avoid event filters just because if you use them, your program will not work properly. You may document this broken thing if you want to :P

To keep function of current programs, you may introduce some 'card state' variable - full sync / select() driven / full async.

**Comment by tuxmark5** [comment]
I guess the obvious solution to receiving several events in succession would be to opt-in for these events in the first place. 

Basically:

``` lua
local socket = internet.open("...")
while true do
  socket.requestData() -- tells to send exactly one signal when there is new data available from now on
  local signal = computer.pullSignal()
  if signal == "tcp_event" then
    socket.read()
  end
end
```

**Comment by fnuecke** [comment]
So to recap, current two suggested possibilities:
- Have a flag on the card/socket whether to emit signals or require `read()` to be called.
  - These modes would be fully exclusive.
  - Only has to be set up once.
  - On card this would not work in OSes with multi-tasking very well (e.g. plan9k).
  - On socket this introduces the problem of having to figure out for which socket it was.
  - Potential loss of packets when the computer's signal queue overflows.
    - With no way of detecting that.
- Have a flag on the socket that can be set to emit one signal if data is available.
  - Will be disabled when the signal was fired.
  - Has to be called after each received event.
  - Also potential loss, but much less likely, since we'd not be spamming the queue ourselves.

**Comment by Kubuxu** [comment]
Plan9k can work around it by something along: `hasData`.

**Comment by fnuecke** [comment]
Hmm? What I mean is: if there are two programs running in plan9k and one wants to use the current mode, and one the event mode, that wouldn't work if it's a flag on the card itself.

**Comment by makkarpov** [comment]
I think that second choice would be preferred. Function that sets event flag should emit signal immediately if some data is available when it fired. This behaviour is needed to avoid race condition when data is received after `read`, but before `setEventFlag`. 

Also you will have to read some Netty documentation on how to implement back-pressure when buffer is full. Currently I googled some Netty provided class - `GlobalTrafficShapingHandler` that also limits traffic flow, maybe it will help you with implementation details.

**Comment by Kubuxu** [comment]
In Plan9k you in general are not using event listeners. You `pull` everything and system makes it work.

**Comment by fnuecke** [comment]
Hmhm. One issue I forgot to list with the second one above is that you'll _have_ to use a timeout when pulling, because otherwise you can lock up if the signal is dropped due to a full signal queue.

plan9k: well, regardless of the implementation, it's still two incompatible modes, no? One would try to call a method, be that by pulling or whatever else means, one would try to wait for a signal, again, via what means ever. Enlighten me :P

**Comment by Kubuxu** [comment]
If you pull in plan9k, the process yields to tasker saying that it waits for signal. If system has not other task to do imminently it pulls from Java. This way signals can be lost on filter/sleep.

IMHO even saying that some socket might have data in it would be enough in most cases. You can't loose data this way but it would require for tcp sockets to have some unique identifier so you know which one it is. This would allow for `select` implementation in Lua.

**Comment by natedogith1** [comment]
For the first implementation suggestion, figuring out which socket has data ready seems easy to me, just include the handle id with the event.

As for the race condition makkarpov mentioned, instead of having that extra signal, you could just call `setEventFlag` before you call `read` instead of after.

**Comment by brisingraerowing** [comment]
While reading the above posts, I thought of something.

How it would work:
1. Data arrives on a socket with no data.
2. Event poller sees data, signals event, and adds the socket's fd to an internal list.
3. No one reads data before next poll
4. Event poller sees data in the socket, but since the fd is in the list, does nothing.
5. Someone reads some data, which internally removes the fd from the list
6. Event poller sees data, and since the fd was removed from the list when the data was read, signals an event.
7. Repeat as needed.

@fnuecke How would a workflow like that work? It would be completely internal changes.

**Comment by fnuecke** [comment]
422592d84e83c5c293bd0eb5e5f103ab590fa076
