### ISSUE TITLE
video transfer

### ISSUE THREAD

**Issue by nailfor** [MightyPirates/OpenComputers#1298]
I have an idea for modifying OpenComp :
block camera and capture cards . Also in the drone can be integrated camera module .
The output image on the screen or on the Google glasses

**Comment by Techokami** [comment]
Already done, see [Computronics](http://wiki.vex.tty.sh/wiki:computronics).

**Comment by nailfor** [comment]
no, the Computronics give me text data like this

local camera = peripheral.wrap("right")
local array = " .,-=+xX#"
local monitor = peripheral.wrap("monitor_0")
local yp = 1
monitor.clear()
monitor.setTextScale(0.5)
monitor.setCursorPos(1,1)

for j = -0.35,0.25,0.025 do
  for i = -1,1,0.036 do
    local d = camera.distance(i, 0-j)
    local a = 1
    if d > 0 then a = 2 + (8 - math.min(8, (d/1.2))) end
    monitor.write(string.sub(array, a, a))
  end
  yp=yp+1
  monitor.setCursorPos(1,yp)
end

My idea of ​​a real image as it sees players

**Comment by feldim2425** [comment]
I don't think that this would be possible, because a camera require that the Server can render the Picture. But all renderers are Client-side only.

**Comment by makkarpov** [comment]
> But all renderers are Client-side only.

And in many cases server does not have a GPU to render it `as player sees`.

The only way that it can be implemented is a ray tracing, and it is already done by Computronics.

**Comment by Techokami** [comment]
Actual graphics? Now _that_ goes into the realm of insane bandwith usage. That and the server doesn't do rendering, as people have pointed out.
Instead, find a way to interpret the raytracing in a fancy way!

**Comment by nailfor** [comment]
CCTV mod can do this, but his no more supported.

**Comment by MyNameIsKodos** [comment]
This would be a good place to point out the LookingGlass API.  It does all the heavy lifting of providing a remote area's render, and simply outputs it as a texture for use with various things.  Though this particular suggestion has already been implemented in a mod called SecurityCraft

**Comment by fnuecke** [comment]
Sure, for client rendering Looking Glass would be an option (though I wouldn't want to use it for a "core" feature in OC because I don't want to have any hard dependencies), but that wouldn't solve the request for accessing such data on the server (i.e. in a Lua script).

I'm pretty sure this topic has come up before, and no good good way of implementing it has ever come up, so yeah. Unless someone has a spark of genius, this is impossible, exactly because - as mentioned above - there's simply no information about the rendering on the server (heck, it doesn't even have textures - and even if it had, which it doesn't, it could use a different resource pack than the clients!)

The Computronics camera is the closest you'll get to this - a raytraced representation of the blocky world around you.
