### ISSUE TITLE
Add sneaky and duration parameters to robot.swing

### ISSUE THREAD

**Issue by Symmetryc** [MightyPirates/OpenComputers#13]
Hey, I was just wondering if it there is a possibility of you adding the extra sneaky and duration functionality of robot.use to robot.swing. If you can, I love you :P. Anyways, amazing mod!

**Comment by fnuecke** [comment]
I just might, can you give me a example where it's needed (not primarily as a reason but as a test case)?

**Comment by Symmetryc** [comment]
Using specialized tools like such as TConstruct weapons and enchanted items to mine and attack with.

**Comment by fnuecke** [comment]
Which tools are you referring to, specifically? I don't see any mention of weapons that use duration when used to attack on the TC wiki nor when trying them out ingame. The only thing in that regard is their short bow, which also works using right clicks (ergo robot.use). That just doesn't work right now because they manually interact with the low-level player inventory directly instead of its interface, so it doesn't find the arrows in the robot's inventory - I might open a ticket on their repo and ask if there's a reason for that.

**Comment by Symmetryc** [comment]
Sorry I meant tools as well, such as pickaxes where you have to hold down left click to mine a block.

**Comment by fnuecke** [comment]
Ah, OK. In that case the delay is handled automatically - yes, the block breaks instantly (if it can be broken with the current tool), but the pause after the operation takes as long as it would take a player to break a block with that tool. See `robot.delays.harvestRatio` and `robot.xp.harvestSpeedBoostPerLevel` in the config.

Is there any case where sneaky for left clicks is actually required?

**Comment by Symmetryc** [comment]
OK, thanks! Sneaky left clicks are required by Dartcraft (IIRC) when you break a block, but you don't want your abilities to affect it or something along those lines.

**Comment by fnuecke** [comment]
All right, I'll add the sneaky parameter to swing, too.

**Comment by Symmetryc** [comment]
Cool, I will definitely use your mod more often now, happy holidays!
