### ISSUE TITLE
Screen bug

### ISSUE THREAD

**Issue by Nex4rius** [MightyPirates/OpenComputers#1306]
The screen does not turn off when you turn off the computer with the button in the GUI.

If you break and replace the cable connecting the screen to the computer the screen doesn't delete the old text properly.
This shows it better -> https://www.youtube.com/watch?v=SdwSAnWW0_k&feature=youtu.be

I'm using OpenComputers-MC1.7.10-1.5.14.30-universal

**Comment by makkarpov** [comment]
It can be intented behaviour when you, for example, use network switches to handle multiple monitors. But, when you break the cable, screen should shut down when it runs out of power.

**Comment by fnuecke** [comment]
Since I can't reproduce here's what I'm pretty sure is happening: since it powers off so quickly, it looks like there's very little power in the network. So when reconnecting the computer tries to clear it, but that probably fails because it'd consume too much energy. Try sticking a capacitor on there, charge it, and see if that still happens.

**Comment by Nex4rius** [comment]
Its also happening with a fully charged capacitor.

**Comment by fnuecke** [comment]
Hrm, then I'm afraid I have no idea what's going on there; tho it's _probably_ just OpenOS derping, so I'm admittedly not too bothered :X Are you running any tweak mods like OptiFine or Fastcraft that might influence update logic? Cauldron?
