### ISSUE TITLE
Robot cannot use angel blocks

### ISSUE THREAD

**Issue by Belgabor** [MightyPirates/OpenComputers#132]
Since the angel block from extra utilities can be placed by a player into empty space a robot should be able to do the same =)
(I'm aware of the config option, but being able to use the angel block in default mode seems more fun)

**Comment by fnuecke** [comment]
Well, they _can_ be placed using `robot.use`. `robot.place` won't work here, since that would mean place == use, which is not the case by design (otherwise tools could be used from the inventory, too, for example). The placing position is somewhat wonky, but I don't think such a corner-case warrants its own special case in the already overloaded place logic, sorry ;-)
