### ISSUE TITLE
(Suggestion) Storage box for floppy disks

### ISSUE THREAD

**Issue by flarn2006** [MightyPirates/OpenComputers#1321]
Remember those boxes you used to store floppy disks in back when they were still used? Seeing as floppy disks are still useful in OpenComputers, I think it would be nice if you could craft one of those. You'd place it like a chest, only it would be smaller (and look like a disk box) and it can hold maybe a dozen or two disks. And of course you'd be able to see the disks in it like you would with a real one.

**Comment by Vexatos** [comment]
Disk Cartridges with some fancy model and the disks actually rendered in it? Yes please.

**Comment by makkarpov** [comment]
Maybe these blocks can also show actual discs indexed by name, not as discs shown in chests, so when you open it you can see disc names without hovering on discs itself and quickly pick up disc that you need.

**Comment by Techokami** [comment]
Install BiblioCraft, use a disc rack.

**Comment by makkarpov** [comment]
Install BiblioCraft and get dupes for free. No, thanks.

**Comment by Techokami** [comment]
Wait, dupes? O_o
Please elaborate.

**Comment by makkarpov** [comment]
I can easily explain why BiblioCraft == backdoor. Steps to reproduce:
1. Grab latest 1.7.10 vanilla server
2. Install latest forge ontop.
3. Grab latest BiblioCraft JAR (currently 1.10.4) and place it into server mods directory
4. Accept eula and start server

Now, at client:
1. Install same forge version on client side
2. Install same BiblioCraft version to be able to login
3. Grab [this JAR](please don't link hack/cheat mods, thanks) and place it into mods folder.
4. Login to server. No op, no creative, just player like anyone else.
5. Press H (or look for key bindings to change this key)
6. You will see GUI like this (I added translation from Russian): ![image](https://cloud.githubusercontent.com/assets/1329592/8857008/430c4748-3177-11e5-8189-394ca6992601.png)
7. Enjoy!

I tested it on MC 1.7.10, Forge 10.13.4.1481, BiblioCraft 1.10.4 and it works just fine:
![image](https://cloud.githubusercontent.com/assets/1329592/8857052/9db00cde-3177-11e5-8fbe-cbef26d0f162.png)

**P.S.** This vulnerability was published on Russian websites at 9 Jun 2015. So many servers maybe already were exploited just because they installed BiblioCraft.

**Comment by fnuecke** [comment]
You mean [one of those](http://qualitasdistribution.com/OsCommerce/images/boi82dis.JPG)? Hrm, why not. Giving it a nice GUI to make managing them by name easier sounds like pita but would give it an actual use besides looking pretty.

**Comment by Vexatos** [comment]
@makkarpov Has it been [reported yet](https://github.com/Nuchaz/BiblioCraft/issues)?

@fnuecke I like the idea a lot. It would mostly be there because it's pretty, though.

**Comment by makkarpov** [comment]
Vexatos, it was reported [a month ago](https://github.com/Nuchaz/BiblioCraft/issues/294) by a developer who found this nice feature, but still not resolved.

**Comment by Techokami** [comment]
oh so it's a hack :neutral_face: 
Well at least Nuchaz said he's going to squash it now that he's done remodeling his website

**Comment by jadenPete** [comment]
I like it :) Sangar if u can add a cool bibliocraft-style 3d look to it, I think u should add this.

**Comment by payonel** [comment]
punting this to computronics if vex wants to add something like this :)
