### ISSUE TITLE
Server extensibility seems a bit limited

### ISSUE THREAD

**Issue by Belgabor** [MightyPirates/OpenComputers#133]
I've played with servers on creative a bit yesterday. For a build I'm envisioning the extensibility seems a bit low though. If I didn't make a mistake even a remote console needs a gfx card in the server to work. With a tier 3 server that leaves only one extension slot free so you couldn't even implement a wireless router as a server which seems somewhat counter-intuitive.
The options I propose to remedy:
1. Have more extension slots
2. Do not require a gfx card for remote consoles
3. Have an internal network card

What I would propose is a mixture of 2 and 3. Maybe have an internal tier 0 "gpu" that only allows the term API (maybe even limited) via remote console if no gfx card is present. An internal network card seems like something obvious to have in a server =)
Much of this proposal comes from the gut feeling that a wireless router is something that should be implementable with even a tier 1 server.

**Comment by fnuecke** [comment]
Thanks for the feedback! Card slots in servers definitely warrant further discussion.

I've been thinking of making a basic GPU 'internal' a couple of times, but I somehow really don't like the idea of 'hardwiring' parts. I'm already pretty uncomfortable with the built-in keyboard+screen for the remote terminal. So right now I'd tend to making more slots available in the higher tier servers, and may bumping the slot tiers a bit.

**Comment by fnuecke** [comment]
After further thinking, though, what exactly do you mean by 'wireless router'? Nothing is stopping you from adding a WLAN card and GPU to a basic server at the same time. Maybe this is the piece of information you're missing: WLAN cards can still send normal network messages, too. They're normal network card _plus_ wireless.

**Comment by Belgabor** [comment]
Yes, indeed I didn't know that, was probably assuming too much realism there =)

**Comment by SpiritedDusty** [comment]
I think that servers should have an internal network card because it would make sense that servers would be able to do networking by default. Its rare to see a server in real life that doesn't communicate over the network. Maybe you could have servers be crafted with the network card so it doesn't consume a slot in the rack.

**Comment by Vexatos** [comment]
@SpiritedDusty I second this.

**Comment by fnuecke** [comment]
Crafted with the network card as in craft a finished server with a card to become a network server or just add the card to normal server's recipe? While I agree that it could make sense to have it 'included' in the server (and that it's - nowadays - to be expected that network cards are onboard) it does take away from the modularity, so I'm still a little hesitant. Also, normal or wireless? Because if normal then you'll have two cards when adding a wireless one, which would be unnecessarily confusing, and if wireless that seems a little too high-tier to be built-in, IMHO.

If we really go for onboard, I think I'd prefer a built-in GPU (tier two to support the remote terminals full capabilities) that can _only_ work with the remote terminal (i.e. that cannot be bound to external screens).

**Comment by SpiritedDusty** [comment]
I'd say it should be crafted with an already finished server, wireless and regular network cards. This would take up one less slot in the server, but it will still allow users to put the network card into the server component slot regularly if they choose to do so.

**Comment by pingbird** [comment]
i was thinking that we could have a block that has a bunch of card ports and it will register them on the network as a normal component, that way you can have as many as you want :D

**Comment by SpiritedDusty** [comment]
That seems a overpowered IMO. Since if you have one of those "card extenders" thing, there would be no point of making multiple components such as internet cards or network cards because all you're computers could just share one.

**Comment by fnuecke** [comment]
External RAM won't really be a thing, I feel that is too unrealistic and powerful at the same time. As @SpiritedDusty said, this could be very hard to balance. For servers in particular I'm leaning more and more towards the built-in-but-only-for-remote-terminals-GPU route, the more I think about the more reasonable it seems. All three components (GPU, Screen and Keyboard) would only be actually connected to the server once it's bound to a terminal for the first time. After that they'd stay connected - there's no reliable way to handle an 'unbinding', since the server may not be loaded when the terminal is rebound, and even worse, there's no truly safe way knowing if a terminal gets destroyed / disposed of.
Additionally, higher tier servers might get one or possibly even two more card slots.

Side-tracking a little, a possible solution to handle the 'you need multiple GPUs for multiple screens' thing might be a new block that could be placed next to screens and act like a (lower performance) external GPU, perhaps?

But an external disk bay might be interesting - possibly even as a RAID to give it some added value? So it transparently combines multiple disks into one file system? Someone want to have a go at that? :D

**Comment by pingbird** [comment]
with a computer / server you can use networking to "host" your components, its just expensive
i think the block should probably have a server in its recipe to balance it

**Comment by fnuecke** [comment]
Coming back to this after a while, I'm not sure anymore if multiple server tiers were already a thing back then. Because right now the obvious approach seems to be to have tier 2 and 3 servers simply have more card slots. I'd probably reduce the tier of supported cards in tier 1 cases, though. This is actually something of an oversight right now... since they're more powerful than T3 cases in that respect, but don't need diamonds. I'm thinking something like this:

| Server Tier | Card Slots | Card Tiers | CPU/RAM/HDD Slots | CPU/RAM/HDD Tier |
| --- | --- | --- | --- | --- |
| 1 | 2 | 2, 2 | 2 | 2 |
| 2 | 3 | 3, 2, 2 | 3 | 3 |
| 3 | 4 | 3, 3, 2, 2 | 4 | 3 |

Opinions?
