### ISSUE TITLE
[Bug|Minor]: File/dir names with numbers are a  bit... off..

### ISSUE THREAD

**Issue by Shuudoushi** [MightyPirates/OpenComputers#1330]
A picture is worth a thousand words right? http://puu.sh/jbGwW/cf9e4af4c5.png

**Comment by dgelessus** [comment]
Do you mean we should do it like most "explorer"-type programs and pretend that every sequence of digits is a decimal number? Somehow I prefer the way `ls` does it in cases like this:

```
000c82756fd54e40cb236199f2b479629d0aca2f
0027d4edd626883a618bc464df2ce54855bf650d
0045afb6a30c4beb3793b116a025111a411a14c9
00562baef8bd1db4c43990f6b1027361e7f620c4
00b38fae5d28d99514a3e73a913af16359b12b7a
00c71b8f15ddfaf958c0c31da003031b8789b3a6
00e06362a31ad7094e452c5bcea837b061825cb0
```

instead of

![dumb sorting](https://cloud.githubusercontent.com/assets/6641959/8886788/9f28eb86-3270-11e5-8c1a-d3552af66b65.png)

(I mean, what the heck is 000c even doing between 00c7 and 00e0? How does that make any sense at all?)

If you want your numbers to be sorted properly, add leading zeroes as necessary. You know, like is done in [`/boot`](https://github.com/MightyPirates/OpenComputers/tree/master-MC1.7.10/src/main/resources/assets/opencomputers/loot/OpenOS/boot) by default.

**Comment by Kubuxu** [comment]
Its normal. Files are sorted lexical not numerically. IMHO it wouldn't make sense to look for number in front as then what if I have hex numbers in front?

**Comment by fnuecke** [comment]
As mentioned above, not a bug, that's just how string sorting works ;-)
If it bothers you a lot, make a PR for a parameter that makes it use [natural sorting](https://en.wikipedia.org/wiki/Natural_sort_order).
