### ISSUE TITLE
Tank upgrade for robots

### ISSUE THREAD

**Issue by Iworb** [MightyPirates/OpenComputers#135]
Please, add to the robots way to spill of liquids from cells.
(That's right way to open issue?)

**Comment by fnuecke** [comment]
That's better, thanks :-)

Cells as in the ones added by IC2? As far as I'm aware player's can't empty them into the world (like buckets), so I don't really agree robots should be able to. There's also no 'generic' way to handle this, since not all cells would have a fluid/block form.
If you mean into containers, note that they can already do that using `robot.use()` (into BC tanks, for example).

**Comment by Iworb** [comment]
Yes, players can't do this, but in the MiscPeripherals (addon to ComputerCraft) was turtle with inner liquid container and she can spill liquids. Spilling of liquids will cost some energy - I think, this is good price for using this ability. And one more reason: buckets can stack only by 1, but cells has full (64) stack. This ability will be good for building spleef fields.

**Comment by fnuecke** [comment]
Well if anything I guess this could be something similar, i.e. a 'tank upgrade' or so. I don't think I'll find the time to implement it anytime soon, so if someone else wants to... *whistle*

**Comment by TorakWolf** [comment]
You can equip it with one wrench and bucket ( need inventory controller upgrade ( 1.3.0 + ) ), and one portable tank...

**Comment by fnuecke** [comment]
Yeah, with the inventory controller I think this is relatively redundant. Anyone feel free to add it as an addon, but I don't think I'll be implementing a tank upgrade.
