### ISSUE TITLE
Preemptive yielding

### ISSUE THREAD

**Issue by makkarpov** [MightyPirates/OpenComputers#1359]
Not actually an issue, but some sort of question: why preemptive yielding is not implemented at least in native library? Are `os.sleep` or `event.pull` functions special that only can be yielded from?

**Comment by Kubuxu** [comment]
It is not totally possible because the only way to do that would be with `debug.hook` unfortunately it is not possible to save computer if it was yielded from a hook.

This is why hooks are used for to error out thigh loops and then computers.

OC is using cooperative multitasking with a small twist of a kill switch.

**Comment by makkarpov** [comment]
But @fnuecke has full access to modification of native library - without this access it's impossible to implement even persistence. That's why I asking.

**Comment by fnuecke** [comment]
Well, yeah, but writing out the state and restoring it is a different caliber of intrusiveness than actually changing the internal workings of the Lua VM, which is something I really don't feel comfortable with doing. Aside from that, the timeouts would still be required for the LuaJ fallback, and I'd like to keep the difference in behavior there as small as possible. Also this would lead to behaviors deviating from actual vanilla Lua, which I also don't really like.

As for `event.pull`/`os.sleep`, no, you can also just `coroutine.yield` on the top level (i.e. in your BIOS / `init.lua`).
