### ISSUE TITLE
Setting the wireless frequency resets the output to false

### ISSUE THREAD

**Issue by denstark** [MightyPirates/OpenComputers#1363]
Using a redstone card tier 2, and working with ChickenBones Wireless Redstone, when you set the wireless frequency using `redstone.setWirelessFrequency(freq)`, the output will turn off if it was on before.

You can confirm by doing the following in the lua prompt:

```
r = component.redstone
r.setWirelessFrequency(802)
=r.getWirelessOutput()
-- The freq is off
r.setWirelessOutput(true)
-- The freq is on
r.setWirelessFrequency(802)
=r.getWirelessOutput()
-- The freq is off
```

**Comment by fnuecke** [comment]
Technically what happens is that when you change frequencies the signal for the old one is disabled (because the card may only send on one frequency) and it won't automatically enable the one you switched to (which IIRC was because that didn't work so well). I suppose I could add a check to just ignore the call if the frequency doesn't change, though.

**Comment by MyNameIsKodos** [comment]
Would a T3 Redstone card be doable, in that it would be able to broadcast on multiple frequencies? Say, max 16?

**Comment by fnuecke** [comment]
Theoretically, possibly, though I can't remember the APIs of the WR mods well enough to be sure they even support multiple frequencies from one endpoint. But I feel that deviates too much from how they operate usually, that being one frequency per endpoint. Now if there were some WR mod that has sort-of "bundled wireless redstone", maybe. I'm not aware of one, though :P

**Comment by MyNameIsKodos** [comment]
Ah well. I'll just use a proper redstone control program once we get server rack extension boards :3
