### ISSUE TITLE
make filesystems and drives more similar

### ISSUE THREAD

**Issue by etnpce** [MightyPirates/OpenComputers#1365]
I don't know how I want to order and word this, so I'm just going to throw out Ideas.
The only change to drives I want is for each platter to have their own data, and for there to be two new drive methods to write/read one sector from each platter simultaneously.
I feel like file systems should act as if they were wrapping drives, rather than being totally separate, space usage should be changed to use sectors, rather than bytes, and a file should use its size, divided by the sector size, rounded up, as the number of sectors, while a directory would use either just one sector, or a number of sectors based on how many files it contains
Also, to make drives and filesystems equal, the maximum amount of data that can be written or read to a file in one call in a filesystem would be the number of platters times the sector size
My idea for the size a directory would require is to have the total number of characters in all names of the direct descendants of the directory plus 2 bytes per platter each(sector addresses on each platter), one byte for name length each,and four bytes (file size) per non-directory. That size would then be divided by sector size and rounded up to get the number of sectors used

Wow, I wish I could figure out how to write that better.

**Comment by SaphireLattice** [comment]
Sorry, but do you know how the real filesystems work? Also, you're basically asking to remove "filesystem" component and replace it with raw filesystem that uses "drive" component, and that's possible completely on Lua side.

**Comment by etnpce** [comment]
No, I am saying that the limits of managed and unmanaged drives should be the same, so that someone could theoretically perfectly emulate filesystem components with a drive component, all this would change would be to add the two drive methods, and tweak filesystem speed and file size

**Comment by gamax92** [comment]
This is a terrible idea. You're forcing crappy dated filesystem concepts onto OC, and emulating a filesystem component with a drive component is already perfectly possible.

**Comment by etnpce** [comment]
crappy dated filesystem concepts? Also, the main reason I created this issue is that emulating a filesystem would be 4 times slower than normal filesystems, because of the limitations of drives.  this suggestion would make filesystems and drives the same speed, and make the three tiers of hard drive have different access speeds, while also making most files require less space

**Comment by SaphireLattice** [comment]
Could you please explain what do you want from filesystem/drive components? And not as single big blob of text. From what i see you want to enforce filesystem component use blocks as measurement unit and (somehow) make folders allocate some size. Which doesn't makes sense or is impossible without making filesystem component use raw data instead of being a wrapper for real OS's filesystem (which it's currently is, a wrapper i mean). And where did you got that "4 times slower"?

**Comment by fnuecke** [comment]
> emulating a filesystem would be 4 times slower than normal filesystems

How'd you get to those numbers?

> and (somehow) make folders allocate some size

FWIW, folders already use up 512 bytes, which is to prevent people from spamming them, since they get written to the actual file system sooner or later.

**Comment by etnpce** [comment]
At most, you can read one sector (512 bytes) at once from a drive, with a filesystem, you can read 2048 bytes at once, and write an infinite number of bytes.  I think you all all misunderstanding what I am asking for.  All this suggestion really comes down to is adding two drive methods, making files use the next multiple of 512 bytes instead of 512 plus their size, possibly making directories take more space when they contain many files, and limiting read/write speeds in filesystems to what they would be if they did use drives.  I am not saying to make filesytems actually wrap drives, I am saying that drives and filesystems should equally powerful

**Comment by fnuecke** [comment]
The "at once" is pretty meaningless in the context of this discussion, though, because those are direct calls. In fact, reading multiple sectors (in particular when they "overlap", i.e. are at the same head position on different platters) is already _faster_ than the normal filesystem component: with a T1 file system (floppy, e.g.) you get [one tenth](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/component/FileSystem.scala#L370) of the read calls per tick you could do [with a drive](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/component/Drive.scala#L255). So from my understanding, just do those multiple reads from Lua, and your request is fulfilled. No need for changes.

**Comment by etnpce** [comment]
Sorry, I didn't know about the different numbers of read calls, that does make this entire request almost meaningless.
