### ISSUE TITLE
comparing wheat and sugar cane

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#1372]
When comparing full grown wheat, with wheat from inventory of the robot it returns false.
Its the same with sugar canes, Kodos on IRC told me the block is different from the item.

This is in this version, OpenComputers-MC1.8-1.5.15.33-universal, i tried with the dev, but it does the same.

**Comment by MyNameIsKodos** [comment]
No, I didn't say the IDs were wrong, I said that the crop block is different from item.

**Comment by ghost** [comment]
sry my mistake, text corrected.

**Comment by fnuecke** [comment]
As mentioned this is a general issue with things where the item and blocks are actually two completely separate things. With wheat vs. seeds it's somewhat intuitive, but this is the case for quite a few items/blocks in Minecraft (IIRC comparators and cauldrons also do not actually use an ItemBlock so you'll have issues there as well).

Since this can also happen for other mods' items I honestly think this would be a tad too susceptible to code rot, and particularly plants with growing stages would be... meh. So I'd suggest just having a table in Lua that maps block info (name+meta) to item info (name+damage or such) and using that for comparisons.
