### ISSUE TITLE
Retroactive achievement unlocking

### ISSUE THREAD

**Issue by Aleszp** [MightyPirates/OpenComputers#1375]
There are three little topics I'd like to mention:
1. Achievement _Signals_ requires _Now we're talking_. The first one requires crafting wireless NIC (network interface card), the second one wired NIC. However crafting (easy recepies mode) wireless NIC doesn't require previous crafting of wired one, what makes achievement _Signals_ unobtainable without previous crafting of wired NIC. I'd recommend making achievement _Now we're talking_ obtainable by crafting both types of NIC (like in vanilla _Time to mine_ may be obtained by crafting any type of pickaxe).
2. Similarly achievement _Wonderful_ (for crafting assembler) requires achievement _Batteries included_, yet doesn't require making capacitor (easy recepies mode). I'd recommend making _Wonderful_ depend not on _Batteries included_, but on previous _All the Small Things_ (for crafting microchip).
3. Don't you think that 512kB (default size) is a little bit weird size of a floppy? Wouldn't 720kB (3.5" Double Side Double Density) or 360kB (3.5" Single Side Double Density or 5.25" Double Density) be more familiar?
Personally I'd suggest 720kB (which I set in my config) as it wouldn't break any existing setup (unless someone made program that requires exact capacity).

What do you think? 

**EDIT:** Replaced HTML with Markdown.

**Comment by fnuecke** [comment]
1. and 2.: this is a problem with crafting based achievements in general and even if the recipes weren't fully configurable from the get-go (which they obviously are), given mods such as MineTweaker exist I honestly think it's an exercise in futility to try and make them properly "ordered". In pretty much _every_ game of Minecraft I've played until now I've sooner or later _always_ had the issue of missing achievements, mods' as well as vanilla achievements, and have come to accept that as just being the way it is. Sure, it'd be an option to retroactively unlock all prerequisite achievements when an achievement is unlocked, but I'm not sure I like it, since that's not how MC achievements behave in general. If enough people think that'd be a good idea I might be convinced to change that, though ;-)
2. I like powers of two, and that was just the logical size when taking into account HDD sizes (in particular since in the earlier versions of OC all FSes were equally fast). In hindsight, if anything I might have made them only 256KiB large, but I honestly don't really want to change that default value now.

> What do you think? 

I think you should use Markdown instead of HTML to format your posts; the HTML is a mess to read in the eMail notifications. ;-)

But yeah, tl;dr I need some votes on whether achievements should automatically also unlock prerequisites.

**Comment by Aleszp** [comment]
1. and 2. I understand, that's why I mentioned it.
2. I thought that it was origin of this kind, yet as I daily use floppies (I'm playing with Win98 and DOS 6.22 on real, not virtual machine XD, using both 360k 5.25" and 1.44M 3.5") mod sizes were just weird for me XD.

Ups, sorry, I'm new to commenting anything on github, first what I tried was html and as it worked I sticked to it, I'll upgrade my previous comment.

**Comment by fnuecke** [comment]
No worries, just wanted to mention it ;-)
(I personally also think it's much easier to write Markdown, but tastes differ, ofc.)

**Comment by MyNameIsKodos** [comment]
Achievements unlocking prerequisites?  No, I don't think so.  No other mod does this, and vanilla doesn't even unlock the achievement UNTIL the prereqs are met, which makes sense as it's basically a line of progression.

**Comment by dgelessus** [comment]
@fnuecke

> I like powers of two

I know, especially when it comes to RAM chips. `;)`

**Comment by fnuecke** [comment]
WAM is superspecial anyway, due to the .5 tiering :P

**Comment by fnuecke** [comment]
Sticking with how achievements work in all the rest of MC, so it'll stay like it is.
