### ISSUE TITLE
Background color not cleared on error nor boot

### ISSUE THREAD

**Issue by LemADEC** [MightyPirates/OpenComputers#1377]
When resetting the LUA OpenOS, screen background color remains as it was before the boot.
If it was red or white, console becomes unreadable. Since OS rebooted, I would expect it be set to black.

Similarly, when a LUA script crashes while current background color is red, the errors are unreadable (red foreground and background).

**Comment by LemADEC** [comment]
The clear command also fails to reset the background color.

**Comment by dgelessus** [comment]
The background color is part of the GPU state. Most commands don't mess with colors at all, or restore the original colors that they started with once they're done, so a "custom" color will stay unless you manually change it. A full shutdown and reboot of the computer should reset the colors though, the Lua BIOS always sets foreground to white and background to black early on in the boot process.

**Comment by ExDomino** [comment]
The default Lua BIOS doesn't change the foreground nor the background color:
http://pastebin.com/8kd5AxKA

**Comment by fnuecke** [comment]
No, but OpenOS's [`init.lua`](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/loot/OpenOS/init.lua#L45-L46) does. So I'd have to guess you changed something in there? If you didn't and rebooting doesn't reset it, I'll have to have a look. Other than that, things are as expected - it is very much intentional that clearing the screen doesn't reset the colors.

Also:

> pastebin

Why not just link to the [`bios.lua`](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/lua/bios.lua) in the repo? >_>

**Comment by ExDomino** [comment]
Because I didn't know there is a bios.lua in the repo. xD

**Comment by LemADEC** [comment]
I didn't change anything in the default Lua BIOS nor OpenOS.
Issue is reproduced with Screen of Tier 1, 2 & 3 and Graphic card Tier 3.
Issue is reproduced with Screen of Tier 1 and Graphic card Tier 1.

If we assume Clear shouldn't change the colors, then I would expect the prompt to adapt with the current background color, so it remains readable.

**Comment by ExDomino** [comment]
Personally I don't really like the fact that screens are a kind of chalkboard. I'd prefer that screens are cleared when the graphic card binded to them is shutted down and all color modifications are reset when the screen is turned on again (white on black), without any need of coding for that (either in the os "init.lua" or in the bios "eeprom").

**Comment by fnuecke** [comment]
Works perfectly fine for me (i.e. it's reset to white on black when rebooting), so I have to assume it's something with your setup. Are you on the latest version? Can you reproduce this on a computer created via `/oc_spawnComputer`?

And no, I don't agree the prompt should go ahead and change the colors; I dislike such automatisms since they usually go wrong in a couple of cases. If you change the color, make sure you do it right / reset it when done (there's always `pcall` if you want to play it safe).

**Comment by ExDomino** [comment]
A new command that reset screen colors to default, for example clean(), would be nice. ^^
clean() would reset the foreground and the background before calling clear()

**Comment by LemADEC** [comment]
I've been using OpenComputers-MC1.7.10-1.5.15.31-universal on Forge10.13.4.1492-1.7.10 with a bunch of other mods.
By resetting computer, I mean pressing Ctrl-C while in console.

I can reproduce it with just OpenComputers and Forge then:
- create a Single player, creative world
- type /oc_spawnComputer
- right click the screen
- type lua
- type component.gpu.setBackground(0xFFFFFF)
- Ctrl-c => back to console
- Ctrl-c => reset to white screen

**Comment by fnuecke** [comment]
That's not resetting it, that's just exiting and relaunching the shell. Run `reboot` to actually reboot it.

As for an alternative clear method... something like `term.reset()` perhaps? (clean is too close to clear and could lead to confusion IMHO.) I suppose that'd be easy enough to add, so why not.

**Comment by ExDomino** [comment]
At this moment, closing the computer with the shutdown button in the case clear the monitor as well. I'm not sure if it's intented, but I LOVE this behavior. If it is a bug, could you create a new config option to preserve this behavior please? ^^

**Comment by fnuecke** [comment]
Intended and pretty much always (at least very long) been like that (or at least supposed to be :P), the code that does that hasn't been touched since May 2014 (yay Git). The case where it doesn't clear is when the connection is cut (e.g. by a cable being destroyed).

**Comment by ExDomino** [comment]
Could you make that the screen is cleared if the connection is cut as well? ^^

**Comment by fnuecke** [comment]
No.

**Comment by ExDomino** [comment]
Why not?

**Comment by fnuecke** [comment]
Because on that level it's indistinguishable from a chunk unload, so you might come back to an empty screen without having cleared it.

**Comment by ExDomino** [comment]
Ok, I got it.
