### ISSUE TITLE
Suggestion: diamond nugget

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#1379]
Diamond nugget, or something equivalent, in order to replace the diamond into some tier 3 recipes (not all of them, for example for microchip), because diamond is a really expensive ressource and when a crafting needs 4 diamonds, you really hesitate before crafting it, especialy when tier 1 and 2 only need nuggets.

**Comment by makkarpov** [comment]
Diamond isn't a metal, so I think that there should be something other than nuggets.

**Comment by ExDomino** [comment]
Something that you could divise a diamond by 9 in order to prevent microchip tier 3 to have a really big cost, it's a bit against the other microchip (tier 1 and 2) recipes.

**Comment by Vexatos** [comment]
I think the Tier 3 Microchip recipe is fine as it is right now considering it is only used for the very end of the OC tier stuff. Also, what @makkarpov said.

**Comment by gjgfuj** [comment]
I agree here, the tier 3 microchip is quite expensive compared to the rest.
But: the tier 3 stuff is actually quite powerful comparatively.

**Comment by BeansGalaxy** [comment]
maby have it so you get 8 diamond shards from 1 diamond and you need 9 diamond shards to make one diamond so you shatter the diamond and loose some of it while breaking it so to make a full one you need a little bit more.

**Comment by Vexatos** [comment]
As @makkarpov said: Diamonds are _not_ metals, they are crystalline. You can't just "break and re-fuse" them. and smashing a diamond would require a considerable amount of force, the shards produced being pretty much useless for computer parts due to them being random. I think the recipes are fine the way they are. Tier 3 stuff is expensive, but also very powerful, remember it's the "top-tier" items so they should be expensive.

**Comment by Kubuxu** [comment]
Small digression:
Diamonds in MC:
- are not random, all are the same
- already can be joined into one
- also diamonds are very easy to break. They are hard but brittle.

**Comment by Vexatos** [comment]
I know diamonds are brittle, I still think adding smaller diamond... thingers is a bad idea.

**Comment by fnuecke** [comment]
"Realism" (as in they can't be merged together) isn't really a valid argument here, I'd say; as mentioned this rule is already invalidated by vanilla MC via diamond blocks. Or fitting nuggets together into an ingot _without any tools_.

_However_: while I'd be fine with adding diamond... shards (?) to allow people to tweak their recipes to a finer degree, I don't really think they'd find a lot of use in the default recipes, because I'd tend to agree they're relatively fine as they are - and particularly changing the chips will have a _massive_ impact due them being used everywhere. Not a change I'd want to make lightly.

**Comment by scj643** [comment]
I think as a config option it would work. Also making a tool that has to be used to break the diamonds or a powered block.

**Comment by gjgfuj** [comment]
Well, OC has capability to only register items if used in the recipe sets.
so just as an option for the recipe sets would be fine, and then maybe
adding another recipe set that replaces it with diamond shards?

**Comment by Vexatos** [comment]
@gjgfuj The item will still be registered even if not used in any recipe, it will just be hidden from Creative Tabs and NEI.

**Comment by gjgfuj** [comment]
Oh does it? I was unaware, but the point of having another recipe set where
it is used instead is still valid.

**Comment by fnuecke** [comment]
Yeah, they are, to avoid IDs changing and all that entails.

An alternative recipe set, sure, I don't mind having more of those. Doesn't need a new config IMHO, just slap the include in the `user.recipes`.

**Comment by fnuecke** [comment]
Waddayaknow, there was an issue for this :X This is in 1.6, added a few commits back.
