### ISSUE TITLE
Weird Console Rendering Errors

### ISSUE THREAD

**Issue by KFAFSP** [MightyPirates/OpenComputers#138]
Hello again. I am the one who opened the ticket #137. I am using the recommended dev-build to get around the fallback LuaJ Problem. This is what happens:

![Screenshot](https://f.cloud.github.com/assets/4153280/2257861/196b62c0-9e20-11e3-810a-65887861bb1e.jpg)

Well, I'd say that the Fallback works now, but there seems to be another problem. There are no logged errors for me to show. It works in singleplayer, so it is supposedly linked to the native libs not being available.

In addition to that I'd like to ask: Why exactly are the natives not available for 2003 RC2? I made a mistake last post, the RC2 is not WinXP Codebase, but instead Win Vista Codebase and therefore within the system requirements.

**Comment by KFAFSP** [comment]
Update:

I swear, I didn't do anything but restart the server again. Now it has changed. It still isn't working but I get an error from the console:
![Screenshot](https://f.cloud.github.com/assets/4153280/2260485/5c6da28c-9e42-11e3-8c6d-9b4af3549e71.jpeg)

**Comment by KFAFSP** [comment]
Hello again. I did some research myself in order to try and help fix this problem. The error clearly refers to the line :

match = value:match("^([^']+)%b''", init)

But from what I know about LuaJ (fallback is active, as we know), this error often occurs when there is a stack overflow. However, that must have occured inside the match function, which would only occur if the string is invalid. There are no other recursive calls in any other part of the shell to neither evaluate() nor execute(). I think this is an environmental problem. However, I don't really have much experience with the new 5.2 Env system, so diagnosis is still up to you.

I will try to remove the shell execution from init.lua and see what happens when directly running a lua prompt. That should allow me to test the function myself and maybe do a little debugging.

**Comment by fnuecke** [comment]
Regarding the first screen shot, it's a sort of known issue, which has been there since the start, but I still don't know what causes it (seems MC loads the font texture as completely white). Restarting the client/reloading the texture pack (just click on the loaded one again) usually makes it go away.

As for the AIOOBE... that's... interesting. It worked for me after all, and LuaJ _should_ behave the same on all systems, since it is Java, after all... I'll investigate some more.

The reason why there is no native support on Server 2k3: in the WinXP code based one the JVM crashes when trying to load the libraries (as it does on WinXP), due to the statically linked MSVC runtime being incompatible with that version of Windows (and I'm not using and older version of those because I can't figure out how to compile for 64 bit then). So I'm checking for that using `org.apache.commons.lang3.SystemUtils`, and don't even try, to avoid the crash. If you can tell me how to differentiate the versions of Server2k3 in code I'll add such a check, otherwise I might add a config option that allows people to force trying to load the library. So you could try that then.

**Comment by fnuecke** [comment]
OK, so apparently the last time I checked that pattern match wasn't in there after all. Also, it appears to be a bug in LuaJ. Which I think I've fixed. At least the computers boot again. Sorry about that!
