### ISSUE TITLE
Add rotation to Hologram projector

### ISSUE THREAD

**Issue by Sukasa** [MightyPirates/OpenComputers#1401]
Would be nice to see two additional functions added to the Hologram component,

getRotation() returns pitch / roll / yaw

setRotation(pitch, roll, yaw) sets them, in either radians or degrees.  This would allow for some interesting applications of the hologram projector, such as rotating holographic signs

**Comment by fnuecke** [comment]
Hrm, I seem to recall I said no to this once before, but I suppose it might be a nice little feature for the T2 hologram projector... question just being, if we're talking specifically about animated rotation, should it be setting specific rotations, or should it rather be setting rotation speeds? Because the former would make for very, _very_ jerky animations (since each change would manually have to be triggered by a machine (and those only run on the server), and then sent to the client).

**Comment by dgelessus** [comment]
How about `getRotation` and `setRotation` for changing the direction, and `getRotationSpeed` and `setRotationSpeed` to change the "smooth rotation" speed? Of course they would work together - `setRotation` doesn't stop smooth rotation, and `setRotationSpeed` starts the rotation at the current direction. Smooth rotation should also drain a small bit more power.

**Comment by jadenPete** [comment]
I like this idea.

**Comment by TheRealOrangus** [comment]
Better would be `setRotation`, `getRotation`, **`setRotationTime`** and **`getRotationTime`**, where the paremeter for rotation time is a floating number of seconds, which means the time while the rotation changes to the new state, like the jerkest on the 0, smoother on 1 and very very slow rotation on 10(?)..
Also would be nice, if this would be not pitch/roll/yaw, but rotation around axes X/Y/Z.

**Comment by dgelessus** [comment]
The rotation time could then simply be an optional fourth argument to the existing methods. But that would mean that if you want to rotate the long way around (e. g. you want 270° ccw instead of 90° cw) you'd need to use multiple steps, which seems a little unnecessary. For a continuous rotation that never ends you'd also need a loop that simply does halfway rotations over and over again.
