### ISSUE TITLE
Diamond, Gold, Iron, etc Robots, and Dyed Robots

### ISSUE THREAD

**Issue by jadenPete** [MightyPirates/OpenComputers#1410]
The title says it all, I think you should be able to place robots in a crafting table, surround them with dies, diamonds, gold ingots, etc. Robots that are diamond are more durable.

**Comment by Vexatos** [comment]
"durable"? There is no such thing as "durable"... Unless you mean explosion resistance, in which case diamonds would not be more resistant at all.

**Comment by jadenPete** [comment]
You know what I mean :|

**Comment by SaphireLattice** [comment]
No. We don't. Robots DON'T have durability. Unless you're saying that it
should be implemented.

**Comment by Techokami** [comment]
Robots change color based on experience earned with the appropriate upgrade. That's why you can't dye them.

Sent from my Windows Phone

**Comment by jadenPete** [comment]
By durable I mean stronger to attacks and explosions. And if tier 1, they will look normal. Tier 2 = Gold. Tier 3 = diamond.

**Comment by Vexatos** [comment]
"stronger to attacks"? Robots cannot be attacked. "Stronger to explosions"? Already answered that.

**Comment by jadenPete** [comment]
Thanks for the heads up, but please stop correcting me.

**Comment by TheRealOrangus** [comment]
I think it's a bit off-topic, though, I think it would be just awesome(but useless) if robots could dye themselfs progamatically, and color which represents the tier would be just for the glass?

**Comment by fnuecke** [comment]
Since the only thing that can "damage" robots are explosions, and they're quite durable in that area already... I don't think this is worth implementing, time-wise. As for dyes, as mentioned above, colors on robots are already... monopolized by upgrades (AFAIK only the XP upgrade, but theoretically any upgrade could change the robot's tint). So manual dying won't happen, sorry. And you can change the color of the power indicator programmatically (the - by default red - lights running in circles).

**Comment by dgelessus** [comment]
Color Upgrade, I say!

**Comment by fnuecke** [comment]
Ask @Vexatos to make some using colorful lamps or something :P

**Comment by Vexatos** [comment]
Good idea, but I need to make it incompatible with the XP upgrade somehow.

**Comment by fnuecke** [comment]
You can probably just use the priority of the [event listener](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/common/event/ExperienceUpgradeHandler.scala#L68) to always go first or last, depending on what you prefer (last probably makes more sense, IMHO, i.e. have it override the XP upgrade's color, since an explicit fixed color feels like it should have a higher priority than a dynamic one to me).

**Comment by Vexatos** [comment]
There you go, I just added the Colorful Upgrade to Computronics. [Does this look about right?](http://gfycat.com/PowerfulFreshDikkops)

**Comment by fnuecke** [comment]
Assuming it only changes the actual value every now and then (i.e. doesn't call synchronizeSlot super frequently), which is what the screen output on the robot seems to indicate, and the blending is done automatically: awesome! :-)

**Comment by jadenPete** [comment]
Thanks 4 ur effort, but Computronics isn't for 1.8 :(

**Comment by Vexatos** [comment]
@fnuecke It's definitely not meant to be called this often, this is just an example. It's about as expensive as `robot.setLightColor` which also sends a packet everytime it's called. The Colorful Upgrade only sends at most one packet per tick, however (it does so in the `update` method), so it shouldn't be too bad.

**Comment by fnuecke** [comment]
Yeah, that should be fine (note that setLightColor is somewhat more lightweight, because it only sends the color, whereas syncSlot sends the stack, but eh, unlikely to be more problematic than anything else :P)
