### ISSUE TITLE
OpenComputers-MC1.8-1.5.**.* ShadersMod-v2.4.12mc1.8 Incompatibility

### ISSUE THREAD

**Issue by ImmersiveGaming** [MightyPirates/OpenComputers#1418]
Crash in item search screen for "tor" or opening OpenComputer tab in creative inventory. Is there any fix for this? 
Mods: 
BiomesOPlenty-1.8.3.0.0.1389universal
OpenCOmputers-MC1.8-1.5.17.36
Optifine_1.8.0_HD_U_D5
ShadersMod-v2.4.12mc1.8

Reproducible with shaders mod installed. Works fine without it. Crash report: http://pastebin.com/a2VNYYs3

**Comment by sylphio** [comment]
Try to put the chunk loading mode in the video setting to default. Already got similar problem and they were all caused by optifine.

**Comment by fnuecke** [comment]
Since 1.8 is _really_ picky about it's GL state, I'm relatively sure there's nothing completely "wrong" on OC's side, or it'd break anyways. If you can reproduce this without Optifine and get the ShadersMod author to give a hint what to look at, lemme know and I'll reopen this, otherwise nothing I can do.
