### ISSUE TITLE
A new computer case block model

### ISSUE THREAD

**Issue by samwalls** [MightyPirates/OpenComputers#1494]
I would like to suggest a new computer case model which you can see inside, much like how you get windows on the side panels of computer cases today. When you add components, they are visualised inside the case in 3D (again, similarly to how components are lain out on a modern motherboard).
Apart from adding swag visuals to the mod it makes it more satisfying to have made a computer component and see it inside the case; it might also be useful if you have random computers all over the place that you can identify them by how they look inside (to a degree).

**Comment by scj643** [comment]
Seems like it might cause lag for lower end computers that play Minecraft

**Comment by Kubuxu** [comment]
It shouldn't be a problem as most parts could be rendered as ISBRH and there are not that many computers placed.

**Comment by skyem123** [comment]
And maybe if graphics are in "fast" mode, there won't be any fancy rendering?

**Comment by samwalls** [comment]
@scj643 well, the block could still be static right? A set of static models that are turning off/on as needed..? idk, i've never made a mod, but in the grand scheme of things it wouldn't be that bad I think.

**Comment by fnuecke** [comment]
Not something I'll sink time into, but if someone wants to PR a fancy block renderer for the cases... (and do the 1.8 port :P)

**Comment by samwalls** [comment]
@fnuecke well, I might like to try, I have a lot of experience with java but never done a minecraft mod (or looked at scala for that matter :P) -  what would adding this involve? I assume there will have to be some logic for when components are added / removed so that the models are shown / hidden respectively. Do I just fork the mod, and if I get it working suggest a merge or something?

**Comment by fnuecke** [comment]
The inventory of the case needs manual syncing to the clients, since MC only keeps inventory info on clients as soon as a player actually opens that inventory, for example. For some things OC already does this, e.g. the robot to render equipped items and upgrades, as well as in OC 1.6 the server racks.

Once that info is there, and gets synced on inventory changes (probably just sending that in markDirty or what it's called should do) you'll need a custom block renderer (example: [rack renderer](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/client/renderer/block/ServerRack.scala)). I'm not sure how much hackery would be involved to use the textures of the items in the rack (e.g. cards) in the block renderer. IIRC in MC 1.7 items and blocks have a separate texture atlas, in MC 1.8 items and blocks share the same texture atlas, so that part might actually be easier there.
