### ISSUE TITLE
SSD and SwapFS

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#1513]
An SSD should be 3x as fast as an HDD when reading, and 1.5x when writing. A given SSD should be more expensive than an HDD of equivalent size.

The Lua engine should also support Swap files and Swap drives. Objects would be swapped out to SSD/HDD and the slower the medium the longer it'd take and thus the slower your programs would run.

**Comment by Vexatos** [comment]
swap can be implemented purely in Lua. It ill be insanely slow and that's why noone would ever do it.
Regarding SSDs: No. Also #1383.

**Comment by SoniEx2** [comment]
But SSDs solve the "insanely slow" problem!

**Comment by MyNameIsKodos** [comment]
To quote Sangar,

 I'm pretty strongly opposed to adding larger storage than the T3 HDDs to OC, in particular none that are faster than what exists already. For one because, well, there are tapes, and for two, I haven't heard of a single sensible usecase where you'd actually need more space (or speed) than you can get with HDDs/a RAID. So, unless you can give me one that isn't "because it'd be cool", I'll be closing this :P

**Comment by SoniEx2** [comment]
I wish OC supported [DownloadMoreRAM.com](http://downloadmoreram.com/index.php) :(

**Comment by skyem123** [comment]
There _is_ a wget utility...

**Comment by magik6k** [comment]
If you want faster drives just use unmanaged mode, and clever coding. I'm working on an app which is meant to be able to handle few tens mb of data in reasonable time. I don't feel any need for faster storage, current T3 unmanaged drives are really fast if you only can use them properly. For swap you can use pure lua, I have experimented with that in plan9k and it turned out to be useless. Again, just code apps in a way that don't require that much RAM.
