### ISSUE TITLE
nanomachines do not have a properly populated index of inputs

### ISSUE THREAD

**Issue by Rosethorns** [MightyPirates/OpenComputers#1515]
At this time nanomachines seem to have a hard limit on the amount of different available inputs there are. 19

the white listed potion effects alone come to about 15 of those. yet only 3 seem to be available within that 19 index list. (speed, damage boost, and absorb) the other 16 indexes are either particle effects or nothing what so ever.

**Comment by Vexatos** [comment]
You are not supposed to have every effect on every configuration anyway. There is a limited number of inputs depending on the number of available effects in your mod pack. One input can cause multiple behaviors ("effects"), also one behavior may have multiple inputs connected to it. If your current configuration is useless to you, reconfigure yourself by ingesting another set of nanomachines. Or just drink grog to get rid of them.

**Comment by gjgfuj** [comment]
Or you can call "reconfigure" on the nanomachine.

**Comment by Rosethorns** [comment]
so the 19 options available are randomized per person when they first drink nanomachines? please consider rewording that part of the manual as it wasn't clear until you put it that way.

And no one is going to use nanomachines if its random and you have to drink new ones everytime you are displeased with your dice roll. yeesh.

**Comment by Vexatos** [comment]
@Rosethorns no, they are randomized per set of nanomachines eaten. Also, #1462 may be something worth reading.

Nanomachines are very powerful. The randomization is one of its greatest balance points since some of the effects may be bad and you want to keep the chance of getting a bad effect.

Them "not doing anything at all" isn't possible. Every input has at least some behavior, but not all behaviors are shown. Some are hidden, usually the very good or the very bad ones.

**Comment by Rosethorns** [comment]
I actually agree with the poster in #1462

"Its the greatest balance point for nanomachines" yeah okay, But you also spend more time in a crafting table rolling dice that might never hit snake eyes. Than you do coding. Which to me seems to fly in the face of the entire point of OC.

Right now it encompasses everything that is wrong with Forestry bees or any other RNGEESUS mechanic. It isn't fun, its frustrating.

you also said in that issue that people could just pastbin the uber nonmachines program yeah thats true.

But people do that anyway. trying to fight OPness in OC is the most hypocritical thing. OC is by its nature is capable of working around basicly any mods chosen restriction with ease if you know a little lua. Having powered potion effects is not that much of a stretch. There is already a bajillion config options for people to tweak what THEY deem too powerful, they can make them draw more energy, they can lower safe input count, yada yada.

All I am saying is please for the love of god rethink the balance mechanic, rolling dice in a crafting table over and over for the miracle chance of something good is hell on earth. especially when the nano machines are going to eat you when you have more than 2 active at a time anyway. Especially when each effect is at best power 1 of that effect.

**Comment by Vexatos** [comment]
> OC is by its nature is capable of working around basicly any mods chosen restriction with ease if you know a little lua

I surely hope it is not. Most of the integration added by OC and its addons is very much considering the mods' balance points and tries not to break them. I, for instance, always ask a mod author for permission before I add integration for their mod. It certainly is powerful, but it should never unbalance any mod too much.

Regarding the balance mechanic: The problem is that it has to make some sort of sense. It's nanomachines. Inside your body. You ingest them and they do whatever they want inside of you (explaining the randomness). You just tell certain parts of them to be on or off. You can't tell them where exactly to go in your body without @fnuecke having to create a virtual image of every possible connection in your body (which is a really bad idea), its effects, its coordinates, and the ways the machines will have to travel through your blood stream to reach those connection points (I hope you get what I mean). The randomness also allows having _negative_ effects without people being able to do much about those. That's the main balance point: Nanomachines have bad effects, some of them are not even displayed and only appear when something goes wrong. Having the system non-random would allow creating nanomachines without any negative effect on purpose, first-try etc. And a system that gives cheap buffs like 3x3-digging, item magnet or speed/resistance for almost no cost really is quite cheaty. And don't forget one input may connect to multiple behaviors, so you may have that one input that gives you both speed and weakness potion effects, making you be a lot more careful with your active effects.

**Comment by Theyoungster** [comment]
Don't forget, sometimes you need to trigger two inputs for an effect.
For example, in my world, inputs 13 and 16, when both on, activate Fire Resistance.

Check EVERY INPUT COMBINATION, not just every one on its own..

**Comment by Rosethorns** [comment]
wait wait wait. SO there is actually 361 indexs?! dayum. can we put that in the manual please that "Some effects are triggered by multiple active inputs."

**Comment by Theyoungster** [comment]
I think you switched your numbers around, it's 136. I can gist a program I used to find all the inputs if you want.

**Comment by fnuecke** [comment]
I've added a debug command so you can verify the current configuration if you're OP, `oc_nanomachines`, which'll dump the configuration to the chat (format is `behavior <- (inputs)`).

The manual is part of the repository and in simple Markdown format, so please feel free to make a PR improving the wording!
