### ISSUE TITLE
Crash with bluepower

### ISSUE THREAD

**Issue by wormzjl** [MightyPirates/OpenComputers#1587]
http://pastebin.com/XBwPP9Cb

**Comment by fnuecke** [comment]
Since the massive stack expansion is happening in BP code, my guess would be that that's for BP to fix.

@amadornes, what's your feedback on this? If there's anything I can do to prevent this in [my implementation of the API](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/integration/bluepower/BundledRedstoneDevice.scala), let me know!

**Comment by amadornes** [comment]
This is probably something on my end, yes. I'm rewriting pretty much everything, so I don't know when a patch for this will be available. I'll try to reproduce it when it's ready to be used :)

**Comment by wormzjl** [comment]
ok gonna close this one
