### ISSUE TITLE
Computer fans

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#159]
3 tiers:
Basic: Included in every case by default
Gold: Reduces noise by 50%
Diamond: Reduces noise by 100% (or 90 or 95, whatever)

**Comment by fnuecke** [comment]
100% probably, 5% volume would just uselessly waste system resources.

Also note to self: consider heat as a factor when adding this.

**Comment by Forecaster** [comment]
Heat mechanics! Woo! \o/

**Comment by LordFokas** [comment]
Then i suggest measuring the CPU's idle time. The less idle time, the more power the CPU uses and the more heat it produces. As heat rises, fans will use more and more power to try and keep it cool.

And then you have a cool heat mechanic (pun intended), which is also realistic.
Plus, the more load you put on the computer the more power it uses, so it balances it out.

Then we can make computers cheaper (but not CC dirt cheap), and balance them out with power usage instead of a one time resource fee.

What do you guys think?

**Comment by Vexatos** [comment]
@LordFokas How exactly do you want the power to increase? How to define "Idle time" in Minecraft?

**Comment by fnuecke** [comment]
The CPU time is possible (it is already being tracked and `os.clock()` in Lua already returns that, even), but it's not terribly reliable, because the machine threads run with really really low priority, so how long they take to finish something isn't strongly correlated to the actual work they do.

I think it would make more sense to directly bind this to the amount of energy consumed instead. It's how it works in real life, after all - more power in, more heat out.

As for changing the costs in reaction to this, that will depend on how the actual cooling would work I think. Passive heat sinks? Fans that just work? Or fans that require a tiny bit of energy themselves? Water cooling? Will cooling parts lose durability over time (nuclear reactor heat sink like)?

**Comment by Vexatos** [comment]
Cooling parts should not use durability, After setting up, a Computer should not require any maintenance at all (except power, of course). In my opinion, there should be fans which reduce sound and heat as their tier increases, but they would also require more power (Only a little, though, compared to the rest). For water cooling, for this there would need to be another block added, the Cooler, attach it directly to the Computer case's side, it will require a little energy, and it will continuously consume water; it will use the power to cool the water down and will also need to have one side attached to air, so it can get rid of possible water vapour. This Cooler block should be fairly expensive since it is powerful, water cooling should be as powerful as the highest tier fan, _but_ it will have a downside compared to the fan: It will _not_ reduce the noise the Computer makes, just keep it cooled. So, your best bet will still be the best fan possible (Which will also require less power, the water cooling should cost a decent amount of energy)

**Comment by LordFokas** [comment]
@Vexatos in that case, it should be inverted. The fan uses less power, but the water cooling is more silent, so the player has to make a choice. I really don't believe in absolute best win-win-win solutions.

**Comment by pingbird** [comment]
hmm,  i was thinking they could have a durability of the temperature similar to the way IC2 reactor components worked, if they get too hot they break

**Comment by Vexatos** [comment]
@infinikiller64 Again, I would not do this...

> Cooling parts should not use durability, After setting up, a Computer should not require any maintenance at all (except power, of course).

**Comment by LordFokas** [comment]
I agree... cooling parts should be that resilient... IRL you switch PC components long before you need to switch cooling hardware.

But accumulating dust, which would make the heating process faster might be cool :p

**Comment by pingbird** [comment]
Vexatos, thats not exactly what i meant
the parts will regain durability when they cool down
and perhaps instead of breaking the computer yields longer / shuts off
more of a hardmode feature though

**Comment by Xanadu16** [comment]
The problem with fans is that there's plenty of different kinds of computer fans in real life. What do you put emphasis on? Performance or Quietness are the two main categories that all fans try to strive for in real life.

For example, Noctua's brand of real life fans puts a HEAVY emphasis on gritty tough performance capability, while be quiet!'s fans put a heavy emphasis on getting the most performance per decibel and taking absolutely NO compromises when adding noise to the fans.

I think there should be three types of fans per tier, Performance, Balanced, Quiet. Performance cools and removes heat a lot better, at the cost of a little noise. 

For example, Diamond fans:
Performance: 90% noise, MOST heat being pumped out
Balanced: 95% noise, fairly a lot of heat being pumped out
Quiet: 100% noise, still blows some heat out, as quiet as it can be

This is the perfect anti to a no always win-win situation. You have to put emphasis on what you want from your PC.

Also, in the case of having a PC in a desert, it should raise the temperature from the heat alone. You'd be looking into performance fans, not quiet fans.

**Comment by Wuerfel21** [comment]
"Also, in the case of having a PC in a desert, it should raise the temperature from the heat alone."
Might get derpy with BoP, or even better TwilightForest...

**Comment by twothe** [comment]
While I think it might be fun once if a computer overheats, you need to take into account how this affects gameplay long-term. Effectively heat-mechanics will force players to play in (close to) optimum environments just to get their PCs running smoothly.

In addition noise is **the** most annoying thing in a game and you should not force this on players, it will just backfire.

**Comment by Vexatos** [comment]
@twothe Good luck getting a silent Computer in real life without having good cooling. By the way, this mod is about realistic (as realistic as possible in minecraft) computer assembly.

**Comment by Techokami** [comment]
@Vexatos I believe it is known as liquid cooling :wink:

**Comment by twothe** [comment]
@Vexatos it is standing next to me. Components from BeQuiet are just that: quiet.

The point is that this is still a game, and many things that are realistic are also annoying. For example your character does not have to use the toilet every 1-2 hours, because that would mean you spent a significant part of your game time doing something which is maybe fun the first time, but seriously annoying after a while. Computers which are noisy for no other reason but to force you to spend even more diamonds are about the same.

**Comment by Forecaster** [comment]
I'd rather not have noise be a factor at all. Rather it should have an effect on the functionality of the computer.

For example being able to get a small increase in performance by properly cooling the computer.

Creating a mechanic centered around an annoyance with no gameplay effects is a waste of a mechanic.

**Comment by twothe** [comment]
"Creating a mechanic centered around an annoyance with no gameplay effects is a waste of a mechanic."
Agreed. Also each mechanic needs to be a fair deal for the player. Having a decision between cheap and fast computers is a fair deal. Having a decision between being annoyed by a mechanic or pay to avoid it is not. And I neither see a fair deal with the current proposal for noise nor for the heat mechanic.

**Comment by fnuecke** [comment]
If this ever makes it in, noise won't be part of that mechanic. It's way too unreliable (e.g. RotaryCraft + sound mufflers glitch for me on a regular basis). Also, it'd be pointless when people play with sound muted. For now there are enough other things to keep busy with, though, anyway.

**Comment by Vexatos** [comment]
@fnuecke Config option for the sounds, maybe? :P

**Comment by fnuecke** [comment]
Maybe, but I expect it'd not be worth the effort, really ;-)

**Comment by fnuecke** [comment]
Having thought about this a bit more, I don't think I'll be looking into adding this after all. Too much effort for a "feature" that will mostly just be annoying and potentially unreliable. Considering it is very possible for addons to add their own computers someone could very well make a "supercomputer" addon that adds computers that need cooling, too (with which I mean to say it's not something that absolutely _has_ to be in OC itself).
