### ISSUE TITLE
[1.8.9] Placing screen crashes game as well as places other mod's blocks

### ISSUE THREAD

**Issue by greeeeeenbean** [MightyPirates/OpenComputers#1600]
Placing screens places Tinkers Construct slime blocks and RFTools crafter, among other things. See here: https://gfycat.com/VerifiableConcreteApe then getting this crash: http://pastebin.com/RpkJYLPp here's another better one: http://pastebin.com/zzfEWeYh (This one had charset removed at the request of gamax92)

Also In my minecraft chat I'm getting "There were errors running the class transformer." so here's my
[fml-client-latest.log](https://github.com/MightyPirates/OpenComputers/files/78035/crash-2016-01-04_21.21.30-client.txt)

Here's my mod list:

buildcraft-7.2.0pre4.jar
Charset-0.0.6-648417f355d2630285a51740.ja
chiselsandbits-mc1.8.9-v1.8-beta1.jar
ezstorage-1.8.8-1.2.1.jar
InventoryTweaks-1.60-dev-26.jar
jei_1.8.9-2.13.7.64.jar
journeymap-1.8.8-5.1.3-unlimited.jar
Mantle-1.8.8-0.6.jar
mcjtylib-1.8.9-1.8.1beta2.jar
OpenComputers-MC1.8.9-1.5.21.1.jar
RebornCore-1.8.9-1.3.0.6-universal.jar
rftools-1.8.9-4.20beta2.jar
TConstruct-1.8.8-2.0.1.jar
TechReborn-1.8.9-0.7.6.26-universal (1).j

**Comment by gamax92** [comment]
The issue with the class transformer seems to be with BuildCraft, with only OC and BuildCraft I get the message.

The blocks however, seem to only happen with the screens, random various other blocks from the mods don't seem to break, but all three screens do.

Narrowed it down to this though:

```
buildcraft-7.2.0-pre6.jar
ezstorage-1.8.8-1.2.1.jar
jei_1.8.9-2.13.7.64.jar
Mantle-1.8.8-0.6.jar
mcjtylib-1.8.9-1.8.1beta2.jar
OpenComputers-MC1.8.9-1.5.21.1.jar
RebornCore-1.8.9-1.3.0.6-universal.jar
rftools-1.8.9-4.20beta2.jar
TConstruct-1.8.8-2.0.1.jar
TechReborn-1.8.9-0.7.6.26-universal.jar
```

Also don't test in the same world, the bug seems to either stay or not stay regardless of installed mod changes. Even with just OpenComputers, if the world had the bug in it screens will sometimes place and sometimes place nothing and light the area up.

**Comment by fnuecke** [comment]
I'm not even marginally sure this is causing it, but a couple of those mods have 1.8.8 in the name, so if those have a 1.8.9 version, maybe try that...

I know the differences between 1.8.8 and 1.8.9 are nearly non-existent, but still.

**Comment by RuinTD** [comment]
Can confirm. Also happens with Thaumcraft, in which screens become loot crates upon placing.

**Comment by fnuecke** [comment]
Looks like I screwed up meta in rotatables in the 1.8 -> 1.8.8 port, whoops.
