### ISSUE TITLE
Misc. Ideas.

### ISSUE THREAD

**Issue by skarlitz** [MightyPirates/OpenComputers#161]
Here is a list of features I'd like to see (Or have envisioned being) in this mod.
+Satellites (Essentially an uber-expensive relay that is a one-time thing; It's shot up into the air and you could have some sort of code to connect to it. Essentially a relay across vast distances (So no need for connecting to the actual internet and relaying messages through that OR making huge amounts of relays everywhere.)

+Allow better interoperability between servers in a server rack. True, you could use wireless networking, but in a real world sense it'd be easier to just hook multiple servers up with an ethernet cable. Doing so in OC would require extending a cable from one side from the other. There should be a built in networking for servers in a server rack.

+Fix CC Events. Some events for CC peripherals DO work (Not sure if this is because they were meant to be by their mod authors or not), but the adapter does NOT pick up on events from blocks like the PIM (Player Inventory Manager) for OpenPeripherals.

+In-game manual for certain little hints (Like a book that can be crafted. It could give hints like how to do startup scripts to new users of the mod)

Also
What you see in CC: http://imgur.com/qPCNLvT
What you see in OC: http://imgur.com/ZV1LhM6

Keep up the good work. ;P

**Comment by fnuecke** [comment]
Thanks a lot for the feedback!

I have been thinking about something like satellites, actually. I've been playing with the idea of making this possible via some interaction with Galacticraft, if present (e.g. something on a space station or so). There'd have to be some fall-back variant in case it's not present, though. Still needs some more thinking through.

A normal network card will do, as long as the servers are connected to _any_ side - racks also act as switches. If the side is set to 'none' it's by design that they do not connect to _anything_. What will probably change is the number / tiering of slots / what is built-in into servers (see #133).

Events from peripherals are generated using the normal 'queue event' logic, so there's nothing to fix there. I'm guessing that the events that you are missing try to push userdata (i.e. Java objects - OpenPeripherals uses that here and there, as far as I'm aware), and that's not possible in OC to keep persistence seamless / working.

There's the basic pseudo-manpage-ish ingame help system, but a 'getting started' book / floppy / thing might be a nice addition. Someone would have to write that, though. Adding it in will be the least effort :-P

I'm leaving this open for discussion on satellites / long range relays and better ingame help.

Thanks again.

**Comment by MaHuJa** [comment]
Braindumping: External wireless blocks with directional antennas; they have a very long range (particularly when communicating with another of the same type) but only in a certain direction, perhaps a 30 degrees "field of view" (15 to either side) for the antenna. 

As for documentation, here's a question: What's the minimal reading list to have a basic familiarity with the most important concepts, assuming you're already familiar with lua or even CC? Does it even exist for the libraries you have to require() to use? (man certainly doesn't have anything to say)

**Comment by Vexatos** [comment]
Galacticraft Space Station with a "GPS Station": Makes the computer able to get its own x/y/z location

**Comment by skarlitz** [comment]
Also, a random question: What made you choose bitmasks for hologram column patterns rather than something like holo.set(x,y,z,true/false)? Bitmasks get a little annoying to work with. :P 

As for the servers, I meant for servers within a server rack to communicate with one another. Thataway they can all collectively work towards a task.

**Comment by fnuecke** [comment]
Bitmasks: because that's the internal representation and I was lazy. Might add a more comfortable callback. May not. There's the bit32 lib, after all. Someone want to write a hologram lib? :-P

Servers: as was I. Unless they're set to 'none', servers in the same rack can communicate via the wired network (given a network card). I don't want to have them built-in network cards, mostly because I want to keep them modular. As I said, they might get more slots / built-in GPU which would basically also mean one more slot in most scenarios ;-)

**Comment by skarlitz** [comment]
I'm working on a hologram lib at the moment, with some of the binary knowledge I've managed to scrape together. xD I'll hastebin it when I get it done.

Also, as for the event system, I think OC only supports string event args (Right? I mean you're the creator so I would think you would know that :P). OpenCCSensors was using a stupid system where you had to use its API to wrap a sensor peripheral. Basically, when you called a method from a sensor, it returned an event ID instead of the actual fucking information you would expect the call to return. From there, you had to listen to events thrown by the sensor peripheral and find the one with the same ID as the one returned by the call to the sensor. It really is an annoyingly complicated system and perhaps if you could make some sort of adapter for the sensors, that would be great. Or maybe make your own sensors if you are rebellious? :P I don't know, but I think OCS is a bit of a necessity for some people. I was actually planning to make a holomap.

**Comment by skarlitz** [comment]
Also, how do you use the b32 library? I am stumped. I need to bitwise negate a value buuuuuuuut I can't figure out how to call 'bnot' from the b32 library to save my life.

**Comment by fnuecke** [comment]
Signals/events in OC support basic types (strings, numbers, booleans) but _no_ tables or functions as parameters. As for the sensors, I'm afraid I just don't have the time to write wrappers for everything out there, but writing a module/library for that should be doable, in particular if you already know how it works underneath anyway, no? ;-)

As for the bit32 lib, I can only point you to [the reference manual](http://www.lua.org/manual/5.2/manual.html#6.7), that should contain everything you need to know.
