### ISSUE TITLE
Incompatability with MrCrayfish Furniture in 1.8.9

### ISSUE THREAD

**Issue by dnastajus** [MightyPirates/OpenComputers#1629]

**Comment by Techokami** [comment]
...explain? What does it do wrong? Does it crash? If so, can we see the crash log?

**Comment by dnastajus** [comment]
I think its id conflict but at same time i dont think its id confilct... There is no mcr mod tab and when i place block from opencomputers it mommentaly turns to block from mrcrayfish furniture

**Comment by LizzyTrickster** [comment]
does it happen with just furnature mod and opencomputers?

Mod versions?

On 24 January 2016 at 21:56, DeividasLTU notifications@github.com wrote:

> I think its id conflict but at same time i dont think its id confilct...
> There is no mcr mod tab and when i place block from opencomputers it
> mommentaly turns to block from mrcrayfish furniture
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MightyPirates/OpenComputers/issues/1629#issuecomment-174345067
> .

## 

Regards,
Josh Green

**Comment by Techokami** [comment]
Why would there be an ID conflict to begin with? That problem was effectively put to bed with MC1.7

**Comment by dnastajus** [comment]
to put bed with MC1.7 what that means?

**Comment by Landrash** [comment]
Since 1.7 there are no more ID conflicts since items don't use ID numbers anymore.

**Comment by Techokami** [comment]
> to put bed with MC1.7 what that means?

Sorry, I forget that some sayings in certain regions of the world are unknown in others.
In 1.7, IDs were effectively eliminated, instead using namespaces and a dynamic per-world ID assignment system. So ID conflicts should not be happening, because the furniture mod uses its own unique namespace while OpenComputers uses its own unique namespace. They're not going to intersect and create a conflict.

HOWEVER, I think some investigation needs to be done with how MrCrayfish is rendering his custom models. The renderer might be affecting OpenComputers?

**Comment by fnuecke** [comment]
This is probably already fixed in 1.5.22, please give that a try (find it on [Jenkins](http://ci.cil.li)).

**Comment by fnuecke** [comment]
Now also on Github (Releases tab) and Curse.
