### ISSUE TITLE
Long range directional antenna

### ISSUE THREAD

**Issue by MaHuJa** [MightyPirates/OpenComputers#165]
I'm splitting this out from the "kitchen sink discussion thread" #161 turned into. It also has potential to simplify (or at least change) the requirements on #119 

The idea is to have a block with a (rotating) directional antenna (e.g. parabola), which only receives/sends messages in the direction it's pointing - e.g. if it's pointing within 15 degrees of the other side - but having a far higher range than a wl-card built-in omni antenna, including on the receiving side.

I'm thinking sending and receiving range gets a multiplier of at least 5, and having one at each end (communicating with each other) then gives a 5*5 times "normal" (omni) range. This would go a long way to reduce the number of relays required for a given connection, and with a lot of long-range point-to-point connections it would be far easier to manage a network.

I propose three tiers of blocks;
_Tier1_ requires you to go set its direction manually in a gui
_Tier2_ includes motors in the recipe, and allows a program to point it in any direction (presumably not disallowing the manual method from tier1)
_Tier3_ could be a phased array antenna which would have a wider field of view, up to 60 degrees off-bore, but maybe a slightly lower range performance(4.5 to normal 5?).

**Decisions to be made**

Vertical direction: Do we include or ignore it? (I see enforcing the vertical direction without allowing it to be set to be the worst answer)

Rather than a signal being on-off if it's in the cone or not, should its range multiplier fall off as it approaches the edges? See also real world antenna lobes: as you approach the edge the signal strength approaches 0. 

Blocking terrain:
If there's terrain in the way, do we lessen the signal strength? This would encourage moving these blocks up to high places where they belong.
- Option 1: Only when said terrain is loaded. This would produce some potentially confusing behavior, like being able to communicate only when there's noone at site B.
- Option 2: Cache from when it was last loaded. Which is far more coding work.
- Option 3: Ignore this entirely, allowing people to bury their antennas deep underground.
  Omni-directionals could perhaps be excluded from this entirely.

**Comment by fnuecke** [comment]
Nice write-up. I agree that the main issues are verticality and blocking terrain.

For verticality I actually think ignoring it wouldn't be so bad. In fact, these are meant for long distances, where the vertical angle would become negligible anyway - so maybe just have a minimum distance (somewhere around the max normal wireless range)?

Blocking terrain over extreme ranges is a much more interesting problem. For things further away (5*400 = 125 chunks!) decreasing the granularity of the sampling would make sense, I guess, so instead of picking blocks on the line between sender and receiver (as done for current wireless communication), one would pick chunks. Their 'opacity' could be computed from the delta of the average of their heightmap (which could be recomputed in a separate thread when they are loaded and then stored for re-use) to the sender/targets heights. Or something like that.

I see the use in this, but there are other things higher up my priority list, so I can't say when/if I will add this. Do note that the wireless network can be interacted with using the API, though, so it would be perfectly possible to implement this as an addon mod, if someone wants to test how viable this is :-)

**Comment by fnuecke** [comment]
The Linked Card coming in 1.3 will more or less address the issue of long-distance point-to-point communication, so at least I won't be looking into implementing this.
