### ISSUE TITLE
[Feature Request] Sided Block driver

### ISSUE THREAD

**Issue by boq** [MightyPirates/OpenComputers#1650]
Would is be possible to get Block driver that is aware of adapter orientation?

 Few pros:
- Adapter orientation seems to be natural choice for default value when one is needed for sided interfaces (`ISidedInventory`, `IFluidHandler`, etc), especially since `ForgeDirection.UNKNOWN` is no longer an option.
- It would allow to write more "realistic" adapters, i.e. ones that don't allow querying properties available only on side that's not attached to adapter.
- It would simplify porting from/to ComputerCraft.

**Comment by Vexatos** [comment]
I'd rather have `worksWith` and `createEnvironment` take the side of the block to create a driver for that the adapter is next to as a parameter instead of the Adapter's side. This would also be more consistent with CC.

**Comment by Vexatos** [comment]
And, since it would break every addon ever (quite literally), I'd probably have it be a separate interface... I guess...

**Comment by boq** [comment]
So that's why I suggest separate interface. Something like: 

``` java
interface SidedBlock {
 boolean worksWith(World world, int x, int y, int z, EnumFacing side);
 ManagedEnvironment createEnvironment(World world, int x, int y, int z, EnumFacing side);
}
```

(or maybe `BlockPos` too)

**Comment by gjgfuj** [comment]
Blockpos, yes, always blockpos.

**Comment by fnuecke** [comment]
Yeah, good idea. Blame it not having that in the first place on my inexperience way back when :P I took the incentive to take the trip down down the change log memory lane, and this part hasn't really changed since pretty much the start of OC, so... roughly 2.5 years ago \o/

Due to backwards compat an extra interface it'll be I guess, yeah. @boq's proposed one looks good as it is to me. I'll look into adding it when my cold is properly gone and my head works again somewhat. And after I try finishing porting 1.6 to 1.8.9.

**Comment by fnuecke** [comment]
It's in. Note that I did not extensively test this yet, if something's not working, let me know, thanks!

**Comment by boq** [comment]
Thank you!

Though it seems little bit weird: I can't find any references to new functionality in Adapter - it seems to still call undirectional `driverFor`, so SidedBlock drivers will always get `UNKNOWN`.

**Comment by fnuecke** [comment]
Oops, you're right of course. Will fix momentarily.

**Comment by fnuecke** [comment]
Done!

**Comment by Landrash** [comment]
@fnuecke Since there seems to be some breaking changes being requested like Sided block drivers, rearranging slots and so on, why not have there be some breaking changes in the eventual 1.9 version.

It's probably way off but these changes might be able to live in a separate branch until then if folks wants to work on them and it would give the addon makers etc a headsup.

**Comment by gjgfuj** [comment]
that would be a good idea, yes.
