### ISSUE TITLE
Suggestion: rearrange inventory slots in cases etc...

### ISSUE THREAD

**Issue by MalkContent** [MightyPirates/OpenComputers#1658]
... in such a way that the lower tiered component slots have a lower id.
This way shift-clicking in low tier components land in the lowest available slot the fit. Would also be helpful for automatic filling of cases/assemblers through hoppers or other simple item moving systems.

**Comment by jhagrid77** [comment]
Yes I do agree, as I'm use to the creative stuff, so when I pulled out a Tier 3, I just shift clicked everything in.

**Comment by fnuecke** [comment]
While I agree this would be nice, to avoid breaking everything the actual inventory slots would have to remain the same, meaning mapping slots around in the GUI (because insertion order anywhere else is up to the caller), which will be messy and hard to read and maintain, and lead to different behavior between insertion order in the GUI vs via machines / piping items in. So unless someone has a genius idea how to solve this, I'm afraid this won't happen.

**Comment by jhagrid77** [comment]
Shift click everything from highest to lowest xD.

**Comment by MalkContent** [comment]
Could you rearrange the slots in such a way that already present slots would be of the same type, just not the same tier?
Going out on a limb here and guess the code checking for the presence of cards/harddrives does not care for correctness of tier.
Existing computers would keep working and hopefully the rest of "everything" wouldn't break either.

**Comment by payonel** [comment]
I think this could be done by adding a custom `  protected def tryTransferStackInSlot(from: Slot, intoPlayerInventory: Boolean)` for the assembler, and prefer the slot with the lower tier
