### ISSUE TITLE
hoppers can add and remove components to/from computers with set user(s)

### ISSUE THREAD

**Issue by MalkContent** [MightyPirates/OpenComputers#1659]

**Comment by jhagrid77** [comment]
Feature request, or it just can?

**Comment by MalkContent** [comment]
It can already. man useradd says that other people can't use the computer and can't change components when the user list isn't empty and can't be broken. So the ability to manipulate the computer's inventory with hoppers (and i assume any other indirect way) seems to be unintended behaviour.

**Comment by jhagrid77** [comment]
Maybe in multiplayer, but in single player you can access everything. I don't exactly think this is a bug, to be honest.

**Comment by MalkContent** [comment]
What are you on about. There is no singleplayer unless oc actually decided to handle the internal server differently for some weird reason. And no it's not a bug, it's what I assume to be unintended behaviour.

**Comment by jhagrid77** [comment]
Did you find this out in single-player or multi-player? In single-player the player (you) has access to all computers and are pretty much the whole network administrator. Therefore you can access everything in it. While in multi-player (not too sure how it works) you must create your own "account" and the one who placed it and everything first, has access to it all. Therefore in single-player I don't think this is a bug, as you are the only one who can actually interact with it, so OC wouldn't have to block anything in single-player.

**Comment by MalkContent** [comment]
Found out in singleplayer, verified in multiplayer. SP would have to have explicitly different behaviour and that would be very odd.

**Comment by fnuecke** [comment]
The user / case protection functionality was never designed to be a cure-all. More as a thing to work in tandem with other protection mods. So yeah, piping stuff out of computers isn't blocked. Mostly because then user-interaction of permitted users with the inventory would need a bunch more special handling, which I'm not too keen on. It _might_ be possible to work around this by temporarily unlocking it while any user has the GUI open... I'll need to investigate that.

(Also there _is_ explicit differentiation between SP and MP, so that players can't lock themselves out in SP.)

**Comment by MalkContent** [comment]
(o. i thought that was implicit due to you only being able to register online users :| )

**Comment by payonel** [comment]
we're going to keep the user permissions simple, thanks for the requeset
