### ISSUE TITLE
unittest floppy

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#1660]
We should get a unittest floppy.

**Comment by fnuecke** [comment]
Yeah, they should totally make one. /s

In all seriousness though, I'm assuming you mean for OpenOS library functionality checks? If so, from what I understand @payonel has a bunch of tests set up from his OpenOS rework. I'm not sure this would make sense to put on a loot disk though, since 99.9999999% of all users would never ever need it. But a new repo with the tests so that the can easily be cloned into a savegame might make sense.

**Comment by SoniEx2** [comment]
And for the sandbox.

**Comment by payonel** [comment]
Nearly all of the unit tests I did I tracked via my OpenPrograms project: https://github.com/OpenPrograms/payonel-Programs/tree/master/payo-tests/var/payo-tests

The code however is quite messy, inconsistent, and weird. The joy of writing unit tests I guess - less form and fewer cares :)

If anyone wants to take some ideas from it, of course I don't mind :) Good luck to the poor sap that does though for reasons listed above.

**Comment by Landrash** [comment]
This seems like a disk that could be useful in a handful of cases but having to need it cloned into a saved game might be problematic for some users.
Wouldn't a fairly simple crafting recipe be better? Something along the lines of `Enchanted book  + disk`

**Comment by payonel** [comment]
unit testing or unit test api would be best suited for oppm, not core mod addition
