### ISSUE TITLE
Robots lose everything on crash

### ISSUE THREAD

**Issue by cfamiglietti** [MightyPirates/OpenComputers#167]
Every now and then a random crash (misc, unrelated, memory, etc) will occur and about 1/3 of the times ANY robots out will lose everything:
XP/Level
Tool
Upgrades
Disk
Inventory

There are no error logs related and I'm fairly sure it's NOT OpenComputers/Robots causing the crashes however, many times robots don't recover and lose everything. (after crash server sees robot as just the plain "block" without seeing the state/metadata pre-crash?)

**Comment by fnuecke** [comment]
Hmm, sounds like a deadlock. I've seen this effect in other mods before (like, way back before I even started on OC) so I'm leaning to pin this on Minecraft, but let's see... what would help is:
- The FML log before the crash. Even if there's no actual crash log/stacktrace, there might be some hints nonetheless.
- The region file containing the robot (and the coordinates of the robot), after the crash but before trying to load the world again.
- The FML log of loading the world after the crash.

The region file would be the most interesting one, to see if the actual NBT data of the robot's tile entity is intact after the crash, or if it's just gone (which is what this sounds like). If it's just gone then I'm afraid there's really nothing I can do about this.

Also, you might want to try attaching VisualVM to Minecraft - if this really _is_ a deadlock, it'll be able to tell, meaning you'll be able to figure out which mod actually causes it.

**Comment by cfamiglietti** [comment]
I just noticed that when the server crashes in a particular way (no warning, crash log etc), the client reads that the server is still up, running and I'm still logged in. I'm forced to SSH in and kill it (usually there's a single Java MC thread/subthread running high CPU when this happens) . Is this what you mean by "deadlock"? This is the particular crash that always seems to reset robots. There's been other typical crashes (OOM) that seem to just have a chance at resetting the robot. Maybe 1/4 or 1/5 times do robots reset on OOM.

I'm still looking into my other mods as well. Like I said, I'm positive it's not OC considering I've experienced these crashes before my son and I had advanced enough to even build a computer on our SMP server. I'll look into determining the region file(s) for the areas we're working in and thanks for the tip on VisualVM. I'll see what I can get you on all of the above.

FML Logs: I looked through them before but there seemed to be nothing out of the ordinary, loading mods, mapping, loading spawn, etc. No conflicts, no warnings, only a couple "Mod missing version info". On the stopping end, typical "Not Enough Memory" message or (worse) nothing. I'll be sure to save the next set of logs and post them in case I'm missing something.

I'm not sure if it's worth noting but our computer's state seems to always persist through crashes. Granted, it's not usually executing anything but if left on, in editor, particular directory etc, it's where we left it.

In your development build currently, I've noticed some comments re save states for robots/components/computers. In the case of "deadlock", would upcoming changes have any affect on my issue? It may not be OC causing the crash, just looking to keep spendy and leveled robots intact (even if rebooted/powered off) even if someone else made a mistake.

EDIT: Found the link to a commit in source that seems relevant: https://github.com/MightyPirates/OpenComputers/commit/f9c4306692bbc6333dcacb3e9063647047b25656

I'll wait until next release to put too much into it (soon?) :D

Thanks a ton for the time into the mod, active development and info. :)

**Comment by fnuecke** [comment]
Yeah, I'm 99% sure that's a deadlock. Those are the typical symptoms. This basically means a mods' thread is waiting for the main Minecraft thread to 'release' something, while the Minecraft thread waits for said thread to release something else. So they wait for all eternity.

Too bad about the logs, but somewhat expected.

You can figure out which region file your robot is saved in using [this tool](http://dinnerbone.com/minecraft/tools/coordinates/). If you want to speed things up (i.e. not have to wait until I have the time :-P) you can open up the region file with the robot _after_ a crash, but _before_ loading it again with a tool like [NBTExplorer](https://github.com/jaquadro/NBTExplorer/releases) and look for the chunk with the robot, then tell me what's in there (screenshot of the expanded NBT tree e.g.), otherwise just upload the region file somewhere.

As for the save system, that's probably not related in this case - how many robots do you have? The effect I'm working around will only occur when you have a _lot_ of robots in a single chunk (not sure about an actual number, but I'd estimate a few dozen would still be OK).

Note that you can get the latest build [here](http://ci.cil.li/job/OpenComputers/lastSuccessfulBuild/artifact/build/libs/OpenComputers-MC1.6.4-1.2.3.285-universal.jar) and see if that changes anything. I wouldn't expect it to, however. The only thing that's 'externalized' is a part of the NBT tag (the dump of the computer's internal Lua state), the basic info is still stored the same way as before.

**Comment by fnuecke** [comment]
If there's any new info on this, let me know and I'll reopen the issue.
