### ISSUE TITLE
Unable to boot plan9k [1.6.0 Beta 1]

### ISSUE THREAD

**Issue by Techokami** [MightyPirates/OpenComputers#1696]
I know this was mentioned in the past, but it looks like it was solved? However it either wasn't fixed at all or got regressed:
![2016-03-14_19 18 03](https://cloud.githubusercontent.com/assets/1530728/13763130/53de9e98-ea1a-11e5-88f6-f12601816879.png)

**Comment by RobertCochran** [comment]
https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/loot/Plan9k/lib/modules/base/06_cowfs.lua#L169

Because Plan9k is using the return value from `fs.open()` as an integer file descriptor, rather than the userdata is it now.

The breaking change was committed in c762129

**Comment by magik6k** [comment]
No it wasn's solved, being too busy. As workaround you may try removing the module.

**Comment by Techokami** [comment]
The workaround works, but is very very messy for new users.

**Comment by magik6k** [comment]
It is, I just have to manage to get some time to fix that..

**Comment by fnuecke** [comment]
@magik6k feel free to merge that change back into your codebase, or come up with something better when you have the time, this is just the quickest thing that came to mind :P
