### ISSUE TITLE
Robot uses items designed to not work with FakePlayers

### ISSUE THREAD

**Issue by WayofTime** [MightyPirates/OpenComputers#170]
There are a few items in my mod that I have coded to check for FakePlayer as a method to determine if the player using this is indeed an actual player. The Robot, as a consequence, appears to be able to use the Dagger of Sacrifice from Blood Magic.

The best way to fix this issue would be to have the part of the robot that uses items extend FakePlayer. This should fix other items that work similarly.

**Comment by WayofTime** [comment]
Might be an issue on my end. If you already extend FakePlayer, thank you for your time!

**Comment by fnuecke** [comment]
Crap, closed the window. Once again. Yes, I extend EntityPlayer directly, because when Forge changed the FakePlayer to extend EntityPlayerMP instead, things broke horribly on my end. And I didn't have the time / put the priority on it to look into it again since then. AFAIK real players are always EntityPlayerMP, which is more specific than EntityPlayer, so that might serve as a filter in the meantime?

I'll be looking into this again in the hopefully not too far future.

**Comment by fnuecke** [comment]
For reference, Cauldron is also stupid and blindly casts stuff around, [so this happens](https://gist.github.com/rymate1234/44efa39dce65da5110ba). Meaning I'll have to have another look at this rather sooner than later.

**Comment by fnuecke** [comment]
Should be fixed, extends `FakePlayer` now.
