### ISSUE TITLE
Palette Issues in OpenOS 1.6 Terminal library

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#1727]
There are various spots in the new terminal library where palette colors are not properly and result in black/dark blue.

If the current color was set explicitly via a palette index, the terminal library will try to restore the color like usual, but fails to mark the index as an index, and instead sets the background/foreground to black/dark blue

Dark blue because a palette index of 15 gets misinterpreted as #00000F

Poking @payonel

**Comment by payonel** [comment]
oh this was resolved in PR https://github.com/MightyPirates/OpenComputers/pull/1734 
I  think we can close this. @gamax92  has a PR https://github.com/OpenPrograms/gamax92-Programs/pull/3 for the wocchat side fixes that need to be merged first - maybe we wait for @gamax92 to confirm the issue is resolved.

**Comment by gamax92** [comment]
Should be fixed, It's working for me and can't see any other place for possible error.
