### ISSUE TITLE
ANSI escape sequences

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#1738]
Can the term API be modified to process ANSI escape sequences? I'd think a lot of real-world Lua scripts use them so it'd make sense to support them.

**Comment by fnuecke** [comment]
My main concern with this would be it slowing down term rendering by a fair amount; and also requiring a good bit of memory.

If this can be done in a modular fashion (i.e. if it can be disabled [by default / based on memory?]), I'd not be opposed though.

Your thoughts on this @payonel?

**Comment by SoniEx2** [comment]
``` lua
if not string.find(str, "\x1b", 1, true) then -- do a plain search in C, this is pretty fast
  -- do plain rendering
else
  -- do slow rendering
end
```

Also split the string in 500-char chunks while doing slow rendering. That makes it use C strlib which makes it much faster.

**Comment by Kubuxu** [comment]
Plan9k implements vt100 codes (vt100 was first terminal to implement ANSI). It isn't that slow but it isn't simple either.

**Comment by payonel** [comment]
I want to keep term as simple as possible. The term rework was fueled entirely because it had grown too complex. The term library in OpenOS 1.6 is an entirely new rewrite, with only a few of the old API still around (the API existing projects were even using - i didn't want to break stuff)

That said, I have found a few cases (in helping users write smart scripts) where it would have been nice to be able to inject smart "hooks" into the processing of term reads and writes (there is very limited support for this with term.read filters and masks but nothing for term.write). I have the desire to allow scripts to provide smarter callbacks/handlers into term.read and term.write which would allow fine tuning term behavior without having to change term code for it.

My idea has been to have a version of term lib to support advanced callback injection. Someone (why not @SoniEx2 ?! :) ) could write an OpenPrograms package that would inject the escape sequence handler at boot.

My ETA on this? I don't know. But I've thought of the injection support already.

**Comment by SoniEx2** [comment]
Oh, cool! Yeah, sure, that's ok. Should I close this then?

**Comment by payonel** [comment]
Sure [go ahead and close this] :) I'll probably remember to ping you some day when term is upgraded for something like this
