### ISSUE TITLE
[Suggestion-Modification] RAID Controller Expansion Card + RAID Configurator (built-in BIOS) vs. RAID Block (RAID0)

### ISSUE THREAD

**Issue by setsunafseiei** [MightyPirates/OpenComputers#1740]
### RAID Controller Expansion Card vs RAID Block

> ADVANTAGE OF RAID Controller Expansion Card
> 1. Realistic
> 2. Configurable - using different types of RAID setup RAID0, RAID1, RAID10, and other RAID#
> 3. Using Hard Disk Drive inside a computer case, OR using slot built-in with the RAID Controller Card and appears to be connected directly to the RAID controller card

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

> ADVANTAGE OF RAID Block
> 1. Space for other expansion block is not being used

**Comment by gamax92** [comment]
You realize that any raid level besides 0 makes no sense, right? There is no possible chance of data corruption or drive failure in OC, and if you do happen to get corrupted data, it's either a bug or your irl pc  is dying.

And a RAID Card is no less realistic than a RAID Block, there are such things as external RAID machines that are designed to have tons of drives shoved into them.

**Comment by fnuecke** [comment]
As gamax92 said, anything but 0 doesn't really make sense in the context of OC. As for the card idea, I'm assuming that should work with the disks built into a case? I'm afraid that won't work, since the disks would still be accessible normally, too (components can't "disable" other components). And if you mean be the card itself be the data storage, then sorry, but no. So your best bet is to use unmanaged disks and write a (RAID) file-system in Lua.
