### ISSUE TITLE
[BUG] OpenComputers 1.6 Beta 1 (for 1.7.10 and 1.8.9)

### ISSUE THREAD

**Issue by setsunafseiei** [MightyPirates/OpenComputers#1754]
After the loading screen of the open computers. It jump to the directory to home but there is no home director found on both HDD and OpenOS... 

![](http://i.hizliresim.com/y5pPlk.png)

In which this isn't notice by some of the users..

**Comment by payonel** [comment]
You are in the home directory. Your prompt is showing you your current directory.
/home/# 
^ that is your current directory
The OpenOS shell is inspired by real life linux shell. Might I recommend a tutorial on the linux shell http://linuxcommand.org/lc3_learning_the_shell.php

**Comment by setsunafseiei** [comment]
Automatically goes at /home/# but when applying a pastebin, it goes error

**Comment by payonel** [comment]
The error is not an issue with OpenOS, but with whatever it is your "pc" script is trying to do.

**Comment by setsunafseiei** [comment]
Maybe the pastebin isn't yet implemented AND is home a directory? it isn't found in the hard disk if you search for the list  of all directories in the HDD. So it isn't a directory yet.

**Comment by payonel** [comment]
What? You are IN the home directory in that screenshot. I can see the error occurs when you RUN that pc script you downloaded.

pwd prints the path you are currently in
the default prompt also displays what directory you are in
use ls / to see a list of directories from root, which includes a /home dir

Again, the error you see has NOTHING to do with a missing /home dir. The download says it saved a pc script at /home/pc. When you type pc, you are executing that script because you are IN that path.

Again, this is not an OpenOS bug, but an issue with the script you are (mis?)using.

**Comment by setsunafseiei** [comment]
Ok then fine... what i mean is, can you run pastebin in /home/# directory? 
because i have proven that.. and that isn't mine

**Comment by payonel** [comment]
pastebin appears to have downloaded the file, which you named pc, When you ran the script, it failed. That's an issue with the file you downloaded, not pastebin

**Comment by setsunafseiei** [comment]
I did that and while i run cd .. which escapes from /home/# to /#... the pastebin worked

**Comment by setsunafseiei** [comment]
I will run it again for proof

**Comment by payonel** [comment]
@setsunafseiei this is a problem with your script, not OpenOS

**Comment by setsunafseiei** [comment]
ok sorry... wrong, yeah it is the problem of the MineOS

**Comment by setsunafseiei** [comment]
but i still have bug

**Comment by GalaxyWar** [comment]
А как тогда исправить?????

**Comment by payonel** [comment]
google translate says "А как тогда исправить" means "And as if to fix"
Let's keep the conversation in english only please
And no, there is no bug with openos with this bug report.
