### ISSUE TITLE
There were errors running the class transformer.

### ISSUE THREAD

**Issue by IchigoGames** [MightyPirates/OpenComputers#1761]
[fml-server-latest.txt](https://github.com/MightyPirates/OpenComputers/files/210653/fml-server-latest.txt) i get this when i log into my server so im just doing what it told me to.

**Comment by fnuecke** [comment]
Thanks for reporting! I've updated / properly re-enabled IC2 integration, which was half of this.

The other half is `simplefluidtanks` shipping a broken version of the CoFH API:

> [10:41:16] [Server thread/DEBUG] [FML/]: Found API cofh.api.item (owned by CoFHAPI providing CoFHAPI|item) embedded in simplefluidtanks

I say broken, because the one it shipped apparently declares the `IToolHammer` interface with signatures still using integer coordinates (x, y, z) instead of the new `BlockPos`, which [the official port of the CoFH API does](https://github.com/CoFH/CoFHLib/blob/1.8/src/main/java/cofh/api/item/IToolHammer.java) (as does OC).

> [10:41:41] [Server thread/WARN] [OpenComputers/OpenComputers]: Missing implementations for interface cofh.api.item.IToolHammer, skipping injection.
> [10:41:41] [Server thread/WARN] [OpenComputers/OpenComputers]: Missing implementation of isUsable(Lnet/minecraft/item/ItemStack;Lnet/minecraft/entity/EntityLivingBase;III)Z
> [10:41:41] [Server thread/WARN] [OpenComputers/OpenComputers]: Missing implementation of toolUsed(Lnet/minecraft/item/ItemStack;Lnet/minecraft/entity/EntityLivingBase;III)V

So it'd be best if you'd report that to them, thanks.

**Comment by Zarathul** [comment]
> The other half is simplefluidtanks shipping a broken version of the CoFH API:
> 
> > [10:41:16] [Server thread/DEBUG] [FML/]: Found API cofh.api.item (owned by CoFHAPI providing CoFHAPI|item) embedded in simplefluidtanks
> 
> I say broken, because the one it shipped apparently declares the IToolHammer interface with signatures still using integer coordinates (x, y, z) instead of the new BlockPos, which the official port of the CoFH API does (as does OC).

That's not the case. [I never have shipped any version but the one with BlockPos.](https://github.com/Zarathul/simplefluidtanks/blob/1.8/src/main/java/cofh/api/item/IToolHammer.java)

**Comment by fnuecke** [comment]
Hmm, then I suppose some other mod ships it without including the `API` annotation. Great.

@IchigoGames Mind looking through your mod JARs to see which mod other than simplefluidtanks includes the CoFH item API?

**Comment by brisingraerowing** [comment]
@fnuecke Don't you hate it when things like this happen?

**Comment by brisingraerowing** [comment]
Since I have IC2, and there are no builds that I could find with this fix, I compiled my own from the OC1.6-MC1.8.9 branch.

And man, is Gradle easy to use. I know next to nothing about Java, but building with Gradle is a snap.

And thanks for making an AWESOME mod!

**Comment by fnuecke** [comment]
Eh, it could be worse, the game could crash ;-) In this particular case it's also not _that_ surprising since it took a long time until there was an official version of the CoFH API.

As for builds, [the build server](http://ci.cil.li) is linked in the readme (i.e. front page of this repo), you can always grab the compiled latest version there! But good to hear the build still works on a "fresh" machine.

**Comment by brisingraerowing** [comment]
Derp. I see that now.

I had to remove IC2 due to a crash in the method that draws its tooltips in the inventory, making the IC2 tabs and the Search Items tab unusable. Oh well. I couldn't figure out how to get to the IC2 bug tracker, although I would guess the issue affects other people as well. I haven't looked at if there is a new version yet, though.
