### ISSUE TITLE
generator component eats burnable fluid containers

### ISSUE THREAD

**Issue by xarses** [MightyPirates/OpenComputers#1779]
if you call generator.insert() on a slot that contains a burnable fluid, in a reusable container, the fluid is added, and the container is destroyed. This is of specific note with buckets, or IC2 fluid cells

**Comment by Vexatos** [comment]
Isn't that what the Vanilla furnace does? Pretty sure it is.

**Comment by xarses** [comment]
a bucket is returned in a vanilla furnace, ic2 'lava cell' is not returned and a universal cell isn't supported

![2016-04-25_07 52 20](https://cloud.githubusercontent.com/assets/2107834/14788046/0d715e02-0abb-11e6-9fac-3ccef8f4f621.png)

**Comment by fnuecke** [comment]
Are you sure about that? In particular, have you tried calling `generator.remove()` to try and get the bucket back out? Because that's how it should behave, and in general at that (it [gets the container item of the burnable item](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/component/UpgradeGenerator.scala#L100-L101)).

**Comment by xarses** [comment]
This works as long as generator.count() ~= 0, it appears to reach 0 if the bucket is left in the generator and the fuel is consumed. 

As you noted it is returned during this period. If we reach the full life of the fuel though it appears to disappear. I need to double check this

**Comment by fnuecke** [comment]
Ah, in which case it probably consumes the bucket as fuel, that seems likely, yes :P Will look into it.
