### ISSUE TITLE
Better Command Block / Creative protections

### ISSUE THREAD

**Issue by ZeekDaGeek** [MightyPirates/OpenComputers#1783]
It would be nice to have some better protections for Command Blocks as peripherals. When turning on the `enableCommandBlockDriver` option it might be nice to have an alternative that forces you to have a `* (Creative)` in order to run wrap the component. Whenever you run the `component.command_block.executeCommand()` or similar methods check that the one of the following applies before running:
- Is within a Computer Case (Creative)
- Is within a Microcontroller Case (Creative)
- Is within a Server (Creative)
- Has a Creative APU

You also seem to have protections for right clicking on a case, however, you can for the most part just attach a keyboard to highjack it. Maybe only allow Keyboard (Creative) as a peripheral for Creative case things.

Edit: You also protect cases from being opened, however, you can pull Server (Creative) out of a rack and open it up without any issues.

**Comment by Vexatos** [comment]
Well, isn't that kind of what the debug card solves? It was added to deprecate command block drivers and provide a safe way to do command stuff since, if I recall correctly, it can only be put in creative cases and those can only be opened by ops or in creative mode (if not, this should be a thing). You can execute commands with it and much more.

**Comment by gjgfuj** [comment]
I think it can (and should) be in any case, but only ops can open them.

**Comment by jhagrid77** [comment]
Never really understood much about the debug card.

**Comment by fnuecke** [comment]
Yeah, the creative case "protections" weren't designed as catch-alls, more as going hand-in-hand with actual protection mods/plugins (that would prevent block placement e.g.)

As for the command block driver being unchecked, there's no way for drivers/environments to check if the system they're being called from is creative. I suppose one way to make this possible might be to make use of the userlist of a computer. As in, expose the list to callbacks, and if there's only users in there that are ops, allow it, otherwise don't or something like that?

**Comment by gjgfuj** [comment]
The command block driver is (at least it should be) disabled by default and
the debug card should probably be used instead.

**Comment by payonel** [comment]
yeah, for OC the debug card should be the tool of choice :)
