### ISSUE TITLE
[RFC] Exposing system environment info

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#1785]
In light of the new devfs system and someone requesting something along those lines in the past (but it never making it into an issue from what I can tell), it might make sense to provide an API for querying system information such as CPU tier and speeds, RAM tier, GPU tier and speeds, device "manufacturer" (in the form of the mod adding the item/block e.g.) and whatever else we can think of. More generally, a list of _all_ components, even those not adding an API (this would partially also resolve #1778), and providing some meta information on the components.

The most generic approach would probably be a new method a la `computer.getHardware()` returning a table of all the things. I'm afraid even if this may result in a pretty large table (memory concerns) there's no real way around it, since some of the components listed might not have an address (such as RAM modules for example). That table might look something like this:

```
{ { device = "cpu",
    tier = 1,
    speed = 0.5,
    brand = "OpenComputers" },
  { device = "keyboard",
    brand = "OpenComputers" },
  { device = "tape_drive",
    brand = "Computronics },
  ...
}
```

A lot of basic data could be collected automatically, via OCs existing APIs, but there might be a need for a new API to provide more fine-grained control.

I don't know how more low-level architectures might best implement this; if there's an alternative approach that would make that easier let me know (poking @iamgreaser and @ds84182).

Feedback appreciated.

**Comment by skyem123** [comment]
This seems useful! I wonder if it would be reasonable for it to give the call budgets of the component, or would that be exposing too much internal detail?

**Comment by fnuecke** [comment]
The call budget is indeed what I meant by speeds, so yes, I'd be in favor of exposing that. While something like a clockrate would be less... odd, I don't see much point in obfuscating these values.

**Comment by Vexatos** [comment]
"Manufacturer" should not be the mod name or ID. I think it should be an optional thing an addon may register, something like `EnvironmentProvider` that returns a string for a given environment... Or maybe an interface on the environment itself? Something to customize it. If no such thing is given, it would default to `nil` or a generic "unknown".

**Comment by fnuecke** [comment]
Why not default to the mod name? I find that to be quite the logical default.

**Comment by Vexatos** [comment]
"breaks immersion"? I simply don't think it would be a good default as mod names aren't anything you are supposed to care about.

**Comment by fnuecke** [comment]
Ehh, I can't say I agree with mod names breaking immersion. Also, I'm pretty sure OC's name is mentioned in several places (at the very least in the manual :P), so there's precedent ;-)

There would definitely be an API to allow overriding it though.

**Comment by Vexatos** [comment]
Still, I do think it should be "unknown" rather than the mod ID. It just doesn't seem like something that should be defaulted to in this case. There should be no default brand, and if there was, it should be mod-independent like everything else in OC.

**Comment by ds84182** [comment]
I'm thinking that the system info should have some sort of representation on the Java side, and arches should figure out their own way to convert the Java representation to whatever they want.

**Comment by iamgreaser** [comment]
Modern PCs have a similar system for this (DMI/SMBIOS) but the actual storage format is quite different (think less "JSON" and more "ACPI"... and then think of JSON again purely to flush the horror out of your mind).

> I'm afraid even if this may result in a pretty large table

As long as you don't add any of ██████'s mods the table won't be too large, and even then you'd hit a component limit before the table had an opportunity to get so large.

Of course, if you _are_ concerned about the table of dicts getting rather clunky, you could adopt some sort of physical addressing scheme, and a 0-terminated list of numbers would give you a route through relays and stuff... but that would be better off handled as a different RFC. (To be honest, it'd make things easier even for soft-arches.)

**Comment by fnuecke** [comment]
Splitting device from power from message networking (i.e. split what's one thing into three) is something that's been on my mind for quite some time (with device networking having "channels" which is already implicitly the case via the component limits, but would make that more... intuitive). But yeah, different topic.

For now I suppose a flat list that can also be queried via the API somehow (probably the Machine?) will do.

(Curiosity, is one of those blocks an `@`? :P)

**Comment by xarses** [comment]
knowing the mod is important, because what happens when two mods provide the "same" module, but it has a different interface. Also this is something that we get with real tools like `lspci` `lshw` `ohai` and others. Sometimes it matters, other times it does not.

This would resolve #1777 more than it does #1778

**Comment by SolraBizna** [comment]
OC-ARM exposes critical information about the CPU and memory with an extremely architecture-specific method. That information is all that very low-level startup code (i.e. code running before component IO is comfortable) needs. Having access to complete system information in an architecture-independent way would be a good thing.

I'd recommend not including a version that dumps the whole list at once. If there's a real risk of an out of memory condition as a result of the call, that prevents it from being used in limited environments, i.e. precisely where it's needed the most.

In OC-ARM, when listing attached components, the program first "latches" the component list. The (hardware) list is only allowed to change at the moment it is "latched". Subsequently, the program can read one component at a time, safe in the knowledge that the _list_ won't update in the middle of it, whether or not components are _actually_ attached/detached. Having a slightly outdated list if the user changes things around is a much less serious problem than having the list change in the middle of iterating through index-by-index, which would result in duplicate or missing components at best.

I'd recommend taking a similar approach here. Something like `computer.latchHardwareList` followed by calls to `computer.readHardwareList` with increasing indices until you get a nil return. For Lua, you could then build a friendly iterator-based `computer.getHardware` interface with a small bit of OS code. Writing code that cares about one specific value then becomes easy. For instance:

```
function getCPUTier()
  for info in computer.getHardware() do
    if info.device == "cpu" then
      return info.tier
    end
  end
  error("We don't have a CPU? What are we running on?")
end
```

For low-level stuff, using the existing component infrastructure as much as possible is a Good Thing. Every low-level architecture already has to provide at least one means of doing "generic component stuff" to be useful. It's frequently clumsy, but using it to access non-critical system information is far less clumsy than, say, using it to do disk or screen IO. OC-ARM---and therefore my still-difficult-to-find "universal" interchange format---already has support for "dicts" even though they aren't currently used anywhere that I know of. Perhaps most importantly, any new component API which is documented for Lua is automatically documented for every other architecture.

One might say that having a self-describing format---even a binary one---for something like this on low-level architectures is "cheating". I would consider Open Firmware to be a compelling counter-argument to that. In fact, what we've seen so far---generic-but-clumsy architecture independent methods, paired with architecture-specific high performance paths added for a few key devices---is extremely reminiscent of real Open Firmware platforms.

Ahem. Anyway...

As for branding, I'm putting myself in the "default unknown" camp. I only have the weak argument that the mod author should have explicit control over their branding; my mod ID might be "SolraAwesomeOCMod" even though I would want my "brand" to be "SolrOC" or something like that. As soon as a brand other than "unknown" gets attached, backwards compatibility becomes an issue if it were to be subsequently changed. (In practice, most OC code would simply break if the interface changes, and otherwise not care.)

**Comment by payonel** [comment]
I don't have firmware development experience. I point that out because if my ideas are offensively incongruent to established norms, I do apologize.

In no particular order, I have 3 things I wanted to talk about in this comment.
1: Mod Name
2: Query Interface (The API for the emulated OS)
3: List of minimum/autopopulated fields

### Mod Name

I think it would be nice to have the mod name somewhere. People are arguing for and against using the "Brand" or "ID" for the mod name, but I'd like it _somwhere_. Even if we had a "Vendor", or "mod name", or "namespace" field. And mod authors could override it if they please.

### API

I have concerns about an iterator solution - it might be saving memory on the emulated side, but there would have to be state held on the jvm side. Would this be a vulnerability to memory abuse? Is it possible to return a list of thin proxies in an array, and the proxy would have to be resolved before using it?

```
function getCPUTier()
  for index,proxy_ref in ipairs(computer.getHardware()) do
    local proxy = proxy_ref:derefence()
    if proxy and proxy.device == "cpu" then
      return proxy.tier
    end
  end
  error("We don't have a CPU? What are we running on?")
end
```

### Definition

I think we should discuss the expected fields any device should publish/return. I expect many hardware domain experts could argue endlessly about what are common publishable "fields" of a "device" - but perhaps we should try to keep this realistic for the domain we have with OC. Nonetheless, I feel my short list is not only lacking, but probably wrong. Again, this isn't my area expertise, but I think this should be discussed.
Each proxy shall provide the following table entries

"methods" => table -- table of callable methods on the proxy: default component proxy or empty table
"device" => string -- block name: default what WAILA would say
"vendor => string -- mod authoring info/full class namespace

Some other fields for consideration (just brain storming)
"PhySlot" => string -- where the device is plugged in, nil if not in the case/chassis
"tier" => string -- oc tier or nil

**Comment by SolraBizna** [comment]
> I have concerns about an iterator solution - it might be saving memory on the emulated side, but there would have to be state held on the jvm side.

A list of interesting devices has to be stored coherently _somewhere_ for this to work, no matter what. With my suggestion (and a little bit of care when serializing/deserializing) it could be as simple as an array of WeakReference<Node>. None of the overhead of a Lua table, or proxies. 

Unless you're referring to the state of the iterator function itself, in which case, that simply isn't so. One reason I like that solution is that a friendly, iterator-driven `getHardware` would (and should!) be written simply in pure Lua.

**Comment by Vexatos** [comment]
> but I'd like it _somwhere_

I'd like it _nowhere_, that is the thing. Unless the mod in question specifically allows displaying the mod name there, it should not be showed. I... I really don't think it should be there. I wouldn't want the name "Computronics" to show up anywhere outside the manual; yes, I could (and would) just override it with whatever API is going to be added, but I think the mod name exposure should stay opt-in (and maybe in the API doc declare something like `This method should return the "brand" or "vendor" of any specific component, for example the mod name."`

**Comment by payonel** [comment]
@SolraBizna an array of weakrefs would be compatible with what I'm saying. What I'm saying that I believe is different from your proposal is that I feel the Lua side should be responsible for the cached list (you don't like that i said proxies, apparently that is overhead? call them whatever you want to call them - weakrefs/proxies/table wrappers/serialized identifers/etc). As for the iterator in "pure Lua" -- what I'm trying to say is: On the Lua side the lowest level call back over the jvm boundary should not be an iterator, but something that returns a list of (e.g.) weakrefs. Perhaps we are saying the same thing here.

@Vexatos Why not? I get see that my (real life) components are nvidia, or intel, or Realtek. Why not see that it is Computronics? How is this wrong?

**Comment by Vexatos** [comment]
It's not a brand name, it's a mod name. I don't think it should appear by default. It should be on the mod dev to choose to display it. You never know is that dev may or may not want to display their mod name in-game.

**Comment by payonel** [comment]
"it's not a brand name, it's a mod name" fine, then we can call the field "mod_name", or "ModName", etc. The ultimate name of the field is of little importance. In fact, I originally said, << Even if we had a "Vendor", or "mod name", or "namespace" field >>

At the end of the day, I don't really care. I'm glad in real life devices post codes that tell us what company made them. Though I suppose they all opted into that standard :)

**Comment by SolraBizna** [comment]
> On the Lua side the lowest level call back over the jvm boundary should not be an iterator, but something that returns a list of (e.g.) weakrefs.

I'm still confused as to what you mean. Is it because of the yielding rules? Because those were significantly relaxed in 5.2.

Passing a WeakReference as a userdata value to the Lua side creates a serialization nightmare. (How to hook it back up when loading?) Passing a strong reference has that problem plus it lets Lua code maliciously hold onto the reference. Passing a UUID is a problem because some devices (like memory modules) don't currently have one.

Here's a latch-free alternative that may satisfy both of us:
- modify OpenComputers API so that every device of interest must have a UUID
- `computer.listHardware`, which uses multiple returns to return the UUIDs*
- `computer.listHardware` supports filters, similarly to `component.list` (saving a program that just wants the CPU tier from having to incur the memory cost of listing the 700 RAM modules some mod allowed them to insert)
- (optional) `computer.getHardwareInSlot` which allows, for instance, to get the UUID of "the module in the second RAM slot"
- `computer.readHardwareInfo` which takes a UUID and returns the data block for that device

OC-ARM already detects and automatically "packs" UUIDs returned from components, so this is only a little more overhead there than using integers. UUIDs (like WeakReferences) don't force the component to stay in memory after it is "destroyed", but (unlike WeakReferences) don't create weird serialization issues. This also gives the responsibility for the list lifecycle to the Lua side, while also providing ways to mitigate the memory impact.

\* Returning multiple values allows architectures like OC-ARM that have simple value-based reply truncation to set an upper limit on the number of modules they care about. It would also allow code like `my_cpu = computer.listHardware("cpu")`. Lua code that wants it as a table can simply do `my_table = {computer.listHardware()}`.

> I'm glad in real life devices post codes that tell us what company made them.

I think everybody in this thread wants a "company name" kind of field. The sources of disagreement seem to be whether the name of the mod should be used automatically in cases where the mod author has not (yet) provided a brand, and whether there should also be a separate "specifically and only for the mod name" field.

**Comment by Vexatos** [comment]
I would certainly opt out of showing the mod name in Computronics. The issue is that I think it should be opt-in instead.

**Comment by fnuecke** [comment]
I get the the "muh immurusun" argument, but frankly, in this case I don't think it has much ground? People know the names of the mods they use anyway, and almost everyone will see them in the tooltips all the time. I'd actually argue components having a default vendor name (which for obvious reasons would be their providing mod) **adds** to the immersion.

**Comment by iamgreaser** [comment]
I get the feeling that if components were refered to by slot rather than by UUID then this might be easier to implement as then you can work out a logical order to probe the slots. But that's another issue.

**Comment by MaHuJa** [comment]
Slots would only really apply to things mounted inside the computer case. I'm assuming this would apply to everything.

> I'm glad in real life devices post codes that tell us what company made them. 

Some of them give fake returns to be compatible with software made for what they're pretending to be. Some give fake returns because they're 'made in china'. (That non-literal meaning of "made in china".)

**Brand/Vendor:**
If the vendor/brand field is to have any value, it needs to be used by a majority. Majorities are gained by defaults. (As a rule, an american president has around 30% support from eligible voters. 30% is not a majority. It's just more than the competitor.) If you're not setting a sensible default, don't add it in the first place. None of `"unknown", "", nil` are sensible defaults.

I don't see how one can link "default to mod name" to "immersion breaking", unless I can assume flaws in the reasoning. For example, is it because, being so used to seeing "computronics" outside of the game, that seeing it breaks _your_ immersion, and you're projecting that onto everyone else?
That would make sense, but would also be a reason to discard it. 

I'm curious about what computronics will be putting there to avoid being _more_ immersion breaking. AFAICT computronics is not themed "two or more competing suppliers". (Not that there's much flavor text space to build that theme.) Is it then going to use the field for jokes like they do in ksp?

**Fields:**

> and whatever else we can think of

I would also like a component_cost field, and conversely a field for how many components this part supports (cpus and bus extenders). Right now, you can know if a computer supports more components by adding them (crashing the computer and potentially exploding whatever it was controlling) or by counting the item tiers in the chassis, and then tracing ALL the cables. Even the buried ones.

**API:**

I would probably go with "everything gets a UUID", is visible as components, and add this as `component.getinfo(addr)` or similar. Less infrastructure to add. Code interacting with `component.*` is either dealing with a specific component, already filters components, or is using the api so little they should work with these. The downside is that the component library is going to hold a few more strings, and `components.lua`, unless changed to filter for API size, is going to show some useless lines.

**Comment by Vexatos** [comment]
It'd pretty much be arbitrary brand names, yes. There'd be one company responsible for all things music, for instance.

**Comment by SolraBizna** [comment]
> I would probably go with "everything gets a UUID", is visible as components, and add this as component.getinfo(addr) or similar. Less infrastructure to add.

A downside of doing it that way is that each architecture would have to add its own equivalent to `component.getinfo`. An upside is that each architecture already has a fitting means of iterating through a list of components in a coherent way. That way also adds some confusion in terms of "what components count as a component toward the component limit", but then restores some clarity (and brings in a lot of utility) by means of the suggested `component_cost` field. I think I like this.

A slightly simpler variation would be to have (from Lua's perspective) a `readComponentInfo` callback that all components are required to implement, rather than something like `component.getinfo`. This breaks API compatibility, but that was already about to happen, wasn't it? Components that simply implement this new callback would still be compatible with versions that don't require it, but would be ready for the next version.

Perhaps `component.list` could also be modified to return only components that implement APIs other than `readComponentInfo`, unless the all-inclusive filter `""` is given. I'm not actually sure whether this bit would be helpful or not.
