### ISSUE TITLE
[Feature Request] Option to hide/show the GUI screen

### ISSUE THREAD

**Issue by Creuilcreuil** [MightyPirates/OpenComputers#1788]
Hello, like said in the title, i think it would be nice if there is an option to hide the GUI screen so we can use the in-game one instead.

**Comment by MyNameIsKodos** [comment]
Just put your screen in touch mode, and make your program have an onscreen keyboard.

**Comment by Creuilcreuil** [comment]
Oh I had not thought !!! And you know why ? Because that sucks (a lot).

**Comment by LizzyTrickster** [comment]
Is taking the keyboard off too much work?

**Comment by jhagrid77** [comment]
Well, this is late, but I agree with @MyNameIsKodos . I would also like to say, (no I am not a moderator or anything) that we are a kind community, not one who insults another for giving a simple suggestion ( @Creuilcreuil ).

**Comment by xarses** [comment]
@Creuilcreuil There isn't enough information here to understand what you are attempting to do, and why a touch only screen might not work [well]. I for one don't even understand What you want to do besides removing the keyboard component which is the prescribed way to disable the UI

If you don't want the UI to open as easily, you probably want to invert the touch mode. see `setTouchModeInverted(true)` on the [screen component ](http://ocdoc.cil.li/component:screen)

**Comment by fnuecke** [comment]
There's two options, have mouse only non-GUI as Kodos suggested, or GUI with keyboard and mouse. I feel adding a keyboard only non-GUI variant would be a bit... unclear (basically you'd be in a GUI without the GUI showing, which is kinda meh). And keyboard only because to catch clicks in that mode I'd have to somehow raycast the GUI clicks into the world and onto the screen manually, which is more work than I feel it justifies. If someone wants to PR this and it's not a hacky mess, cool, but I probably won't look into this, sorry.

**Comment by payonel** [comment]
it'd be a hacky mess to do this
