### ISSUE TITLE
[Suggestion] Chunk loader ticks based on player

### ISSUE THREAD

**Issue by Polyana-Fontes** [MightyPirates/OpenComputers#1817]
The chunk loader module loads chunks [using mod tickets](https://github.com/MightyPirates/OpenComputers/blob/399e0f44e6e6088a8b95f011011d817cbec45177/src/main/scala/li/cil/oc/server/component/UpgradeChunkloader.scala#L51) so there's no way to limit the amount of chunk loaders per player. The limitation per players is good for servers because it would stop players from abusing the module to load too many chunks, without a player-based limitation we have to limit the entire mod, this is bad because the limitation will not be distributed equally for all players, meaning that one player will get more chunks loaded than an other and meaning that a player that attempts to load a single chunk may not get his chunk loaded because an other player is loading like 250.

[Drones](https://github.com/MightyPirates/OpenComputers/blob/399e0f44e6e6088a8b95f011011d817cbec45177/src/main/scala/li/cil/oc/common/item/Drone.scala#L43) and [robots](https://github.com/MightyPirates/OpenComputers/blob/399e0f44e6e6088a8b95f011011d817cbec45177/src/main/scala/li/cil/oc/common/block/RobotProxy.scala#L236) know who placed them in the world, I think it would not be hard to make a computer case, microcontroller and server rack to know who placed them. It's also simple to [request player ticks](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/common/ForgeChunkManager.java#L671)

**Comment by skyem123** [comment]
If computers remember who placed them, then we would need a way to change the "owner"

**Comment by gjgfuj** [comment]
I would suggest maybe a right click to bind a chunk loader module to a
player. The ticket then belongs to said player. You can then just block the
mod from chunk loading and only allow chunk loading when bound to a player.

**Comment by skyem123** [comment]
Actually... yeah. That's a good idea.

**Comment by fnuecke** [comment]
Binding chunk loaders to players sounds like a reasonable solution, yeah. Just need to be made perfectly clear that it needs to be bound to work.

**Comment by skyem123** [comment]
well... if unbound it could use the per mod limit?

**Comment by skyem123** [comment]
or... even better: config option!

**Comment by gjgfuj** [comment]
It could also possibly bind automatically to the player who crafted it if
one did.. that's just a possibility though.

**Comment by fnuecke** [comment]
Hmhm, it could autobind on craft as a convenience, or probably better yet, when first picked up (think autocrafting).

And if / when this gets implemented, I'd rather it not work when unbound at all, would allow players to circumvent their chunk loader limit.

**Comment by payonel** [comment]
the problem is how to bind existing chunk loaders, when migrating to newer builds. I'll leave this open for adoption because it's not a bad suggestion to limit chunk loaders, but i don't see the right solution for OC given where we are now

**Comment by kmecpp** [comment]
Hi, I run a somewhat large server with OpenComputers and I've been forced me to completely disable chunk loading for the mod because certain things in OC are loaded 24/7. This behavior is completely unsustainable for any multiplayer server because it is possible to eventually be utilizing 100% of the servers resources even without there being any players online. Currently however, disabling chunk loading breaks a number of things in the mod. For example my players have reported drones getting bricked if they're unloaded as well as a number of other issues.

To address your issue @payonel why not just add a config option to enable this suggestion of player based chunk loading but have it disabled by default? This way, server operators at least have the option of enabling it if they chose. Any method of binding _existing_ chunk loaders to players at that point is helpful but not even necessary. Personally I don't care _existing_ chunk loaders don't function at all. IMO if players have to just re-place the block for them to work that's a very minor issue.
