### ISSUE TITLE
[OC 1.6.0.20 - dev] Interrupt doesn't work

### ISSUE THREAD

**Issue by feldim2425** [MightyPirates/OpenComputers#1845]
Ctrl + C seems to work but Ctrl + Alt + C also just throws a interrupt event and doesn't force the program to stop.

OC 1.6.0.20-dev
MC 1.9.4

**Comment by LizzyTrickster** [comment]
What program / code are you running?

**Comment by feldim2425** [comment]
It tested it in the "edit" and the "lua"-program also without any program (just the OpenOS Shell).

I know Ctrl + Alt + C is not needed in this programs. But it should throw an error and stop the code.

**Comment by payonel** [comment]
^C (control+C) pushes an event to the event queue called "interrupt" - a program is free to ignore or handle this signal. Unlike termination signals, omition to handle these does NOT cause your program to terminate:

That is, we do the opposite of http://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html
"The (obvious) default action for all of these signals is to cause the process to terminate. "

I've considered reversing this behavior to be gnu-like. For now, we continue to operate as we always have, i.e. we do not terminate a process that does not handle this event.

^alt+c does not push an "interrupt" event to the queue, but rather, aborts the process with an error message "interrupted". This cannot be handled by user scripts.

**Comment by feldim2425** [comment]
If you want it gnu like it should terminate if there is no handler and call the handler if there is one. It would be bad if you can't terminate a programm that has no handled exit

And the ^Alt+C  was / is more like a SIGKILL

**Comment by payonel** [comment]
I understand the gnu-like behavior...which is why I linked the docs. My issue is I'm not convinced we want gnu-like behavior is this area (right now). Maybe we do. We are well aware we are not gnu-like in this case (yet?)

My point is, this issue is (at least, currently) "As Designed" -- or at best "Feature Requested".

_EDIT_
Maybe I take issue with your title, "doesn't work"
It does work, as currently designed.
Perhaps you disagree with that design. That is fine. It's not broken, but perhaps not the right design. A new feature to support gnu-like termination for unhandled signals is a very reasonable request. I've considered it myself.

**Comment by feldim2425** [comment]
I just know that the code is still in /lib/event.lua for the Interrupt and it was there before. So if it got removed this will be useless (i think): 
https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/loot/openos/lib/event.lua#L199-L202
( and the event.shouldInterrupt() method )

EDIT: I just thought the "Kill Interrupt" is still there because the keybinding is still handled in event.lua

**Comment by payonel** [comment]
Yes, that is the abort, SIGKILL-like, interrupted error. This is NOT the ^C event added to the queue.

**Comment by feldim2425** [comment]
~~Yeah so the Ctrl+Alt+C combination should still work. I also see no reason why shouldInterrupt() return false if the keys are pressed.~~

EDIT: I think I found the issue in the term.lua
https://github.com/MightyPirates/OpenComputers/blob/master-MC1.9.4/src/main/resources/assets/opencomputers/loot/openos/lib/term.lua#L86

There is a pcall that catches the error and "convert" it into a event with the same name (in this case "interrupted").  And yes edit.lua uses the term.pull() method.

**Comment by payonel** [comment]
First of all -- thank you for your patience! I have been misunderstanding your point this whole time and have been reading extra meaning into your explanations because of that.

I believe I now see part of what you are saying.

hard interrupt should be unhandled and abort, and yes, term.pull is catching it. I have good reason to catch it in term, but this (term.pull) is the wrong place to catch it. I will adjust this and correct the use case. The correct title for this bug should be "term.pull is catching hard interrupt"

Thanks much, I'll get this fixed.
