### ISSUE TITLE
Robot using Analyzer?

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1868]
Not sure if I'm just doing it wrong, but it seems the robot can't use the analyzer I put into its hand :<

For sneaky use it just returns
true, "item_placed"

Or is there some other way to get the analyzer info?

**Comment by xarses** [comment]
afaiu there is no way to get back the data that is posted to the client chat window from any tool. This would be awesome to have

**Comment by Inari-Whitebear** [comment]
So, is this a feature that would be accepted? :p

**Comment by payonel** [comment]
open-for-adoption added.
open-for-adoption: "not something I plan to do in the near future, but would accept a PR to this effect"

**Comment by payonel** [comment]
Inari: were you serious in requesting this feature? It is something I have considered but today as I research how to support this I find it isn't going to be straightforward

I have stubbed out getting the code ready to support this: https://github.com/payonel/OpenComputers/commit/0c8a7d83f8019818b7c0842f3a4c505fd04116e4

We are lacking any kind of design for this sort of thing
We can't just returns all the strings the analyzer would normally print as a return value of the robot.use() call -- these areas of the code are quite separated, it's not an option

Thus we need some other mechanism for getting the analyze produces. The simplest way is to provide another signal that the analyzer produces.

another solution would be to allow the robot to use the analyzer as a coponent - which isn't a simple solution as that would still require some user experience design; how would we want to "return" the data

Given the need for feedback and time since this ticket was created, I'm removing the 1.7.3 milestone from this ticket but leaving it open for discussion. It might be something I'll reconsider for the release following 1.7.3

**Comment by skyem123** [comment]
I don't want it to be yet another component, I feel just a signal with the details would be fine (maybe you could expose an API for items to send signals to computers on use?)
