### ISSUE TITLE
maximum multi-screen 8x6, not 8x8

### ISSUE THREAD

**Issue by payonel** [MightyPirates/OpenComputers#1888]
Should the game join 8x8 screens into a single multi-block?

I don't know if this is a bug, sorry if it is by-design.

I thought part of the advantage (besides licensing) of the new font was that it could scale evenly - so I was surprised when the maximum screen multi-block ( OpenComputers-MC1.7.10-1.6.0.929-dev-universal.jar ) was 8-wide and 6-tall, rather than 8x8, or a 1x1 ratio.

**Comment by fnuecke** [comment]
This is due to the maximum resolutions having that (or a similar) aspect ratio. From back in the day when the actual max res wasn't area based (but per axis). So in principle I'm open to changing the default config values, but would like to hear what others are thinking first.

**Comment by J0SLAN** [comment]
I like the config option. Being able to either force people to have tiny screens or allowing huge screens sounds pretty good to me.

**Comment by NickNackGus** [comment]
As long as someone is replying to this, my opinion is the same; a server-side config option. On the other hand, I assume that determining which screens fit together needs to be handled client-side to some extent? What's a sane upper limit for multi-block screens? 32 blocks by 32 blocks ought to be enough for anyone, right? In all seriousness, I can imagine someone wanting a 16 block wide screen, and don't see any reason not to allow square aspect ratios, since the resolution of screens can be changed to any aspect ratio that fits in their maximum resolution.

**Comment by payonel** [comment]
i actually think it makes sense to leave it as 8x6 to follow the res of the screens

**Comment by J0SLAN** [comment]
Yes, it _makes sense_, but it can also make sense to give a config option for larger screens; for example when a server wants to have a giant screen for a public board, but is forced to use multiple monitors set up next to each other with the ugly borders. Is it such a bad suggestion that it can't even be considered low-priority?

**Comment by skyem123** [comment]
Having a config option sounds like a good idea...

**Comment by uehlbran** [comment]
Would be nice to allow any size multi-screen. Like a config option.
