### ISSUE TITLE
[1.9.4] Errors in the class transformer message

### ISSUE THREAD

**Issue by kwpugh** [MightyPirates/OpenComputers#1889]
Forge: 1964
Mod: OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar

latest.log:   https://gist.githubusercontent.com/kwpugh/53b65222495b13050b39d79c472ace90/raw/91f1882336142eaa8dc4c381f9384e27f772b57c/opencomputer

**Comment by fnuecke** [comment]
> [11:01:32] [Client thread/WARN]: Missing implementation of isUsable(Lnet/minecraft/item/ItemStack;Lnet/minecraft/entity/EntityLivingBase;III)Z
> [11:01:32] [Client thread/WARN]: Missing implementation of toolUsed(Lnet/minecraft/item/ItemStack;Lnet/minecraft/entity/EntityLivingBase;III)V

So the actual issue is someone is still shipping an invalid CoFH API (for reference, [this is the official one](https://github.com/CoFH/CoFHLib/blob/1.9/src/main/java/cofh/api/item/IToolHammer.java), note the lack `isUsable(..., int x, int y, int z)`). The positive thing is, I was missing the entity targeting methods from the official API anyway, so I added those _and_ the methods for the unofficial API, because it doesn't hurt.
