### ISSUE TITLE
Feature Request: CraftOS Compatability Mode?

### ISSUE THREAD

**Issue by Techokami** [MightyPirates/OpenComputers#189]
So, the big thing preventing my group of friends from adopting OpenComputers over ComputerCraft is the lack of available programs. Of course, this is a newer mod and thus has yet to build up the community and program library. So how about in the interim... a sort of compatability mode or layer for CraftOS programs? Like WINE, but for Lua-based computer mods for Minecraft. That way, people can use OpenComputers in place of ComputerCraft to run CraftOS programs, instead of having two redundant mods.

Also, a porting guide for bringing CraftOS programs to OpenComputers would be very helpful as well.

**Comment by SpiritedDusty** [comment]
The main complication with porting things over is that CC uses Lua 5.1 and OC uses Lua 5.2. There are some Lua 5.1 specific things such as `setfenv()` and `getfenv()` that are just very hard to port over to Lua 5.2.

**Comment by Techokami** [comment]
Either there's a typo in your previous message, or Lua 5.2 does not like itself.

Maybe instead, it could be used as a tutorial for implementing new architectures? The Lua 5.3 thread in the forums talks about doing it, and having a guide would help other people implement new architectures on their own. Who knows, someone might put together a lightweight 6502 based architecture like RedPower2 used to have...

**Comment by fnuecke** [comment]
As mentioned, full compatibility is impossible, not only due to the different language version, but also because there is no concept of 'side' when it comes to components in OC (e.g. `peripheral.wrap('top')` simply could not be automatically translated to OC, because you'd have to provide the address instead).

There has been some work in wrapping what can be wrapped [over here](https://github.com/BigRenegade/OC-Compatibility-Libraries/tree/master/lib), you may consider contributing / see how far this gets you.

As for custom architectures, if someone has a real interest in this, please contact me (forums, irc, whichever way you prefer) and I'll be happy to help. I just don't feel the time it'd take to write a tutorial/guide on this would be time well spent (since I'm not sure anyone would actually read it :P).

**Comment by Techokami** [comment]
Well, thank you very much for the information. I'll have to look into the wrapping project and see how far that can allow me to utilize existing programs, and chip in to fill any gaps.
As for custom architectures, I'd love to try and implement one, but my Java skills are incredibly rusty (haven't worked in the language for YEARS) and I have no idea where to begin looking for code implementing eloraam's custom 6502 CPU from RedPower2... may that mod rest in peace.
