### ISSUE TITLE
a pre-flashed eeprom that acts like a cmos [feature/ suggestion]

### ISSUE THREAD

**Issue by n00b7** [MightyPirates/OpenComputers#1904]
i originally wanted a cmos & a cmos battert but these two comments changed my mind:
Diklabyte: @n00b7 You can use the eeprom.getData():string and eeprom.setData(data:string) functions instead.
This can be used as a CMOS ;)

 Techokami:
The BIOS and its "settings" are stored on an EEPROM. This is an Electronically Erasable Read-Only Memory device, and is the precursor to Flash ROM (you can erase and rewrite the ROM in-circuit). CMOS is a fabrication process for creating low-power integrated circuits, and is what was used to create the SRAM (Static RAM) chip used to store BIOS settings. SRAM needs a constant power signal to retain its data, which is why a battery is present. But, EEPROMs retain their data without requiring power, so they do not need a battery.

so i would like a eeprom pre-flashed that's like a cmos but we would still have a lua bios eeprom
and maby even add a bios logo?

**Comment by LizzyTrickster** [comment]
Apart from being irritating and useless, what purpose would adding this
fulfil?

**Comment by n00b7** [comment]
making it feel like a true dos machine

**Comment by payonel** [comment]
@n00b7 while OC likes to be realistic, it is also preferable to having functional benefit to each complexity asked of the user. Was there a functional benefit to your suggestion? If it is "immersion" only, it isn't worth the "cost".

**Comment by n00b7** [comment]
ok

**Comment by Diklabyte** [comment]
@n00b7 You can use the `eeprom.getData():string` and `eeprom.setData(data:string)` functions instead.
This can be used as a CMOS ;)

**Comment by Techokami** [comment]
The BIOS and its "settings" are stored on an EEPROM. This is an Electronically Erasable Read-Only Memory device, and is the precursor to Flash ROM (you can erase and rewrite the ROM in-circuit). CMOS is a fabrication process for creating low-power integrated circuits, and is what was used to create the SRAM (Static RAM) chip used to store BIOS settings. SRAM needs a constant power signal to retain its data, which is why a battery is present. But, EEPROMs retain their data without requiring power, so they do not need a battery.

Therefore, this request is pointless, since it isn't realistic for the technology currently in use.

Sent from my Windows Phone

**Comment by n00b7** [comment]
i guess that there could be a pre-flashed bios that works like a cmos

**Comment by xarses** [comment]
Please no, we have reliable, durable and cheap EEPROM materials in OC/IRL. Why would we reproduce inferior and irritating system that comprises CMOS?

What I think you want is a tradional BIOS with the menu's and all the fixings, which has no care as to which system stores its settings

**Comment by xarses** [comment]
> making it feel like a true dos machine

We follow *NIX (UNIX/Linux // POSIX) not DOS (at least as far as openos is concerned)

**Comment by fnuecke** [comment]
No.
