### ISSUE TITLE
Sometimes Materials are really out of whack

### ISSUE THREAD

**Issue by xarses** [MightyPirates/OpenComputers#1913]
With the default crafting config, the materials list seems to randomly get out of hand. This seems to be specific to upgrades, so maybe it has something to do with them getting a uuid? other things seem to behave when not in the upgrade container slot

![2016-06-23_20 54 02](https://cloud.githubusercontent.com/assets/2107834/16352429/0c3cb9f4-3a23-11e6-80d1-5a3ead43740a.png)

PS. I'm not sure why we hide the tool tip but not the materials list (which is quite often longer)

MC 1.7.10
Forge 1566
OpenComputers-MC1.7.10-1.5.22.42-universal

**Comment by fnuecke** [comment]
Yeaaah... the cost computation never really got along well with modded recipes, in particular if they involve tools (the hammer and file and cutter are probably the cause here, i.e. each _use_ actually gets counted as a consumed tool).

It's something I attempted to give a more elaborate and stable go in CraftingCosts, but kinda failed. Repeatedly. Until I gave up. I might just remove this from OC, but as in some cases it can still be useful, I probably won't. But I also don't feel like putting more work into it. If someone else wants to, by all means.

**Comment by xarses** [comment]
Upon further investigation, the only items impacted are:
- T1-3 Case
- T1-3 Battery Upgrade
- Tank Upgrade
- Nano Machines
- Chamelium
- Block of Chamelium

And for some reason the Access Point is impacted in a wierd other way, it's materials are 'Access Point'

Looking at it, any OC recipe that uses Chamelium or Iron Bars is impacted.

@Vexatos would be informed that some of the computronix items also have this issue 
- Coloful Upgrade (contains Chamelium)
- Camera Upgrade
- Chat Upgrade
- Radar Upgrade

All the random parts come from GT5u. For OC the default recipes are used, for Computronix, the GT recipes load

**Comment by xarses** [comment]
Not a problem in 1.6.x
