### ISSUE TITLE
feature request: Project: REd

### ISSUE THREAD

**Issue by Leftorius** [MightyPirates/OpenComputers#2]
It would be awesome if OpenComputers would support the project red wires

**Comment by fnuecke** [comment]
I'm currently looking into it. Normal red alloy wire already seems to work (presumably because it interfaces through the vanilla MC redstone functions), bundled signals may or may not turn out to be a little more tricky. In the "worst case" I'll just have to start reading up on Forge Multipart sooner than planned.

**Comment by pantheis** [comment]
Just came here to request this after just finding out about your mod, and look, it's already done! Awesome! :)

**Comment by evg-zhabotinsky** [comment]
Oops it was mentioned accidentally.

**Comment by Column01** [comment]
Accidental reference ^^ sorry!
