### ISSUE TITLE
Font drawing issue

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#20]
I was playing the game when I noticed that /C/ had a normal looking /C but the second / was curved and distorted.
My in-game resolution is 1600x1200,
Screenshot: http://puu.sh/5Wevp.png
This was done on a superior screen with proper electrical flow.

**Comment by fnuecke** [comment]
That's due to the downscaling. You could set it to a lower resolution to reduce the effect. Maybe I could do something like only scaling the GUI to certain steps (multiples of two, 0.1 steps) which might make it a little better.

**Comment by fnuecke** [comment]
Aaaand I just remembered that there was a setting that could alleviate this all along... try `client.textLinearFiltering`, if you can stomach the slight blur it can bring with it. Otherwise I can only recommend setting your ingame screens' resolution to something that doesn't require that much scaling. I'll close this for now.
