### ISSUE TITLE
Adapter no longer connects to IC2 reactor chamber

### ISSUE THREAD

**Issue by WazWaz** [MightyPirates/OpenComputers#2038]
Still works for the Reactor itself, but this isn't accessible when all sides of the Reactor are covered by Reactor Chambers. This used to work fine some time in the past (the "reactor" component would show for either Reactor or a connected Reactor Chamber).

IC2 industrialcraft-2-2.6.37-ex110
OC OpenComputers-MC1.10.2-1.6.0.3-rc.1

**Comment by xarses** [comment]
IIRC, it connects to the reactor access port, and none of the other casings

**Comment by Vexatos** [comment]
It actually connects to the Redstone Port. The Access port is for inventory access (using transposers or inventory controllers).

**Comment by WazWaz** [comment]
I mean for EU-mode reactors, which is a Reactor with up to 6 Reactor Chambers around the outside - the problem being that if there are 6 Reactor Chambers, then there cannot be an Adapter. The Adapter is used both to access the Inventory to observe the fuel rods etc (though this too is broken in a different way now - see #2039), and to access the "reactor" Component for EU output information. A separate Redstone connection, to the Reactor or Reactor Chamber can turn the reactor on/off.

**Comment by xarses** [comment]
you should be able to work around the problem by using a reactor port, the reactor will stay in EU mode with an incomplete housing.

My guess is we need to convert some of https://github.com/MightyPirates/OpenComputers/tree/master-MC1.7.10/src/main/scala/li/cil/oc/integration/ic2 to https://github.com/MightyPirates/OpenComputers/tree/master-MC1.10/src/main/scala/li/cil/oc/integration/ic2 since ReactorChamber is missing, I'm guessing that's the cause.

**Comment by WazWaz** [comment]
As far as I can tell from trying combinations in-game, no, the reactor_redstone_port cannot find any reactor when it is merely touching an EU-mode reactor.

I think this is because it looks for FluidReactorLookup.class (then gets the IReactor from that if it finds one), whereas reactor looks for IReactor.class. At least from my poor understanding of reading the code.
