### ISSUE TITLE
Spamming AssertionError caused by Plugin's Block.getState() on Robot

### ISSUE THREAD

**Issue by tachigami** [MightyPirates/OpenComputers#2040]
When you handle BlockBreakEvent this way

```
    @EventHandler
    public void onBreak(BlockBreakEvent event) {
        Player player = event.getPlayer();
        Block block = event.getBlock(); //the block robot is digging
        Block above = event.getBlock().getRelative(0, 1, 0); //robot itself

        above.getState(); //causes AssertionError (see stacktrace below)
    }
```

http://pastebin.com/ynWLKnAQ

But all is fine if you do PlayerInteractEvent `event.getClickedBlock().getState()` on robot.

I have changed one line of code [here ](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/machine/Machine.scala#L768) from `assert(!isExecuting)` to `if (isExecuting) return` and it seems to work fine. If this change is acceptable please fix it in your code.

And one more thing. When robot is digged ONE block, then BlockBreakEvent will throw TWISE. Why this happens?

**Comment by fnuecke** [comment]
Simply returning is not something I'd like to do there, as in that scenario the computer cannot output a valid save state (because it is currently running the code that lead back to the save call). And removing it would make it really hard to debug such cases in the future. Given that I don't really see a nice solution for this; I'm open for ideas...

It's called once when starting to break the block, and a second time when _actually_ breaking the block, after the time elapsed it takes to actually break the block with the currently equipped tool.

**Comment by tachigami** [comment]
This issue should not be considered as something rare and useless. For example WorldGuard plugin with its chest-protection feature enabled causes bunch of exceptions when the robot tries to dig protected region. The example above is just a simplified example of the problem.
