### ISSUE TITLE
Feature Request: Graphics modes?

### ISSUE THREAD

**Issue by Techokami** [MightyPirates/OpenComputers#207]
Here's something I've really wanted to see in mods like this: a mode where you can create actual graphics. Doesn't need to be something insane and 3D, maybe a simpler sprite-based mode, like on the MSX. Depending on the graphics card, you can go from having 1bpp black-and-white sprites like the MSX with a screen size of 160 pixels by 144 pixels, to having 4bpp (16-color) sprites on a 320 pixels by 240 pixels screen, up to having the full 8bpp (256-color) range on a 640 pixels by 480 pixels screen. Or, if sprite-based rendering is too tough to pull off, it could simply be a framebuffer-like system (as seen in Love2D).

Graphics can be stored on a small amount of RAM provided by the tier of graphic card used, which can be expanded by using available RAM in the computer. There should be hard limits on how many sprites can be in use at a time for lower tier cards. And this mode should obviously require _more_ energy to function, because it is a more complex rendering mode.

So what would this be useful for? Well for starters, people can make software that have ACTUAL GUIs instead of text-mode faux GUIs. It also allows for creating nice-looking games (all work and no play, etc.), and for rendering actual images in the Minecraft world.

There is one mod for ComputerCraft that adds something akin to this: [CCLights2](http://www.computercraft.info/forums2/index.php?/topic/10216-mc-16x-cc156-cclights2-v041/). It uses a framebuffer-like system with limited video RAM through peripheral blocks. However, I don't think it would be possible to utilize this peripheral mod in OpenComputers without a LOT of work that would result in seemingly redundant blocks and items.

Thank you for taking your time to read this, I'm really enjoying OpenComputers a lot, and would like to see it become even better. :)

**Comment by fnuecke** [comment]
You see, the real problem here is not _rendering_ it (although that could require quite some sophisticated real-life hardware, too, if there are a bunch of screens on-screen, because you'd need a relatively large texture for each of them, eating up your real graphics card's memory), the problem is the network. Keep in mind that computer's internal logic is executed _exclusively_ on the server.

This means every change made to the buffer has to be sent to the client, over the network, which is already quite busy keeping players' and entities' positions up to date and whatever else Minecraft is sending through the ether. Sure, this can be optimized somewhat, but the 160x50 screens are already quite noticeable when spamming them with set()s. So 640x480 is utterly unrealistic I'm afraid. You're essentially asking for streaming video... using the Minecraft engine.

AFAIK CCLights2 mostly sends... 'draw calls' to the client, similar to OpenGL immediate mode? I don't know how it's implemented, but OC1.3 will (most likely) have support for 'userdata' (read: Java objects) as CC makes available using ILuaObject, so I imagine it would be possible to either port it or make something similar without jumping through too many hoops.

Either way, I don't see me implementing something like this in OC itself. This would work better (if at all, keeping technical limitations in mind) as an addon IMHO.

**Comment by Techokami** [comment]
Ah, I see. Well, it was just a suggestion. Would have been nice, but I totally forgot about network traffic.
Thank you anyway!
