### ISSUE TITLE
APU + 4 network cards in a single server

### ISSUE THREAD

**Issue by jrb0001** [MightyPirates/OpenComputers#2088]
If I build a server with an APU and 4 network cards, I can only connect 3 of them to the rack. The last one can send packets but doesn't receive any.

**Comment by payonel** [comment]
modems can always send packets, there is no confirmation of success on sending
I did confirm that you can only connect 3 components, and the 4th is reserved for gpu/apu. Even with a server blade that has no graphics (cpu only) I can only connect 3 of the 4 modems. You'll note that there is some graphical texture indicating this limitation in the GUI (in-game) when viewing the configuration of the server blades. The top most bus is thicker than the lower 3. It is the top bus that is reserved for gpu. Thus, I do believe this is by design: @fnuecke?

**Comment by Vexatos** [comment]
The top bus is the main component line, it is equivalent to an OC cable. The smaller lines are for network messages only, and the GUI only supports a limited number of them.

**Comment by jrb0001** [comment]
If it really works as designed, you should probably improve the UI if you didn't do that already (didn't play it since at least november).
