### ISSUE TITLE
World Sensor Card

### ISSUE THREAD

**Issue by Nex4rius** [MightyPirates/OpenComputers#2090]
The world sensor card doesn't show if its in a sealed area or not with

> hasBreathableAtmosphere()

[hm gifs normally work here](http://i.imgur.com/dButlXs.gif)

tested in the InfiTech2 modpack v.3.2.11
OpenComputers-MC1.7.10-1.5.22.46-universal
GalacticraftCore-1.7-3.0.12.463
Galacticraft-Planets-1.7-3.0.12.463

**Comment by MyNameIsKodos** [comment]
I'm pretty sure the world sensor checks the 'planet' (Read: Dimension) for breathable air. Overworld and some addon planets would return this as true, but moon, mars, asteroids, and a space station would not iirc.

I could be wrong, however.

**Comment by Nex4rius** [comment]
If thats true it's pretty disappointing because it means I cannot use the computers to check for sealed areas.

(I want to use it in my Stargate program to send that info through the wormhole so you are warned on the other side.)

**Comment by Timeslice42** [comment]
The world sensor card is for planetary/dimensional data, not local information.

**Comment by kpb-gh** [comment]
I'm unsure about this, but you could try redstone. The Oxygen Detector emits a signal when detecting a breathable atmosphere. Maybe this redstone signal can be used as a way to check for breathable atmosphere. 
See http://ocdoc.cil.li/component:redstone for usage of the redstone card/redstone IO

EDIT: I just made a quick program to scan for redstone at the top of the computer. If you can integrate it into your Stargate controller, it should solve your problem. Since trying to type the code is messing up, the download code is `pastebin get DHAbmmuV atmosphere`. Replace "atmosphere" with whatever you want.
You can also visit Pastebin directly and copy the raw data if it is easier than installing an Internet Card

EDIT 2: Your setup requires a Redstone Card (Tier 1 should be fine) with an Oxygen Detector (Or its redstone current) to be on top of the computer. As I am not familiar with event handling, I can't show you an integrated example.

**Comment by payonel** [comment]
by design
