### ISSUE TITLE
[FeatReq] VR

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#2095]
Can we get VR headsets?

I'm sure OC's refresh rate is enough for VR... Even if it may result in serious motion sickness (nausea effect)...

**Comment by LizzyTrickster** [comment]
OpenGlasses

**Comment by SoniEx2** [comment]
That's AR, not VR...

**Comment by Forecaster** [comment]
I'm sorry we couldn't tell that that was insufficient from all the zero use-cases you provided. : P

**Comment by SoniEx2** [comment]
Well I wanna play a fullscreen game while I play a fullscreen game... And get nausea I for 30 seconds if the framerate is too bad.

**Comment by Forecaster** [comment]
Smoosh your face up against a screen

**Comment by Inari-Whitebear** [comment]
So you want a fullscreen mode for terminals, not a VR headset

**Comment by SoniEx2** [comment]
The item would be called "VR headset" and you'd put it in the head slot. But yes, effectively fullscreen terminals.

**Comment by magik6k** [comment]
Just cover everything using OpenGlasses, it would be the same, or make yourself room from flat black blocks. Other than that, you can just write game outside minecraft as it would be effectively the same.

**Comment by SoniEx2** [comment]
Meh ever tried being nice or something :/

**Comment by asiekierka** [comment]
![](http://img.asie.pl/OsUg)

**Comment by xarses** [comment]
@SoniEx2 I'd like to give you some feedback regarding requests, It should be useful for any one collaborating with open projects.

Feature requests should contain the following information in top post:
- Describe what you want to accomplish
- Describe why existing solutions won't work for your case
- Describe some use-cases that this solution will solve (these shape the scope and when its complete)

Failure to provide enough information, or an enticing story will likely result in the project not understanding what you want and dismissing the request.

From there, expect to continue to fight for your request. You should expect back and forth on many aspects of your request such as "doesn't feature X do this already" this feeds back into updating your description and use cases to best describe why it's still needed. A good example may be #1917 

The dreaded "We aren't doing that" Every once and a while a good idea doesn't fit the project's direction. You can let it die, or refocus, in that you can re-asses what you need to make it so that you can implement an extension yourself to do what you would like to accomplish. In this case you should describe the lower level hooks you would need to have so that your higher level interface can function. In these cases it's often necessary to properly illustrate that this is enabling someone else to implement the higher level feature, not a request for the higher level feature.

**Comment by SoniEx2** [comment]
No this is perfectly fine I got an issue label dedicated to shaming me...

Hmm remind me to check github's TOS or something later...

**Comment by payonel** [comment]
I have not seen any verbal abuse or threats. Xarses gives great advice, too often I see github issue conversations that degrade into discussion forums. Let's keep these specific and on topic. Also, please respect a closed ticket (meaning, we've given it consideration and deem it "resolved", e.g. resolved "won't fix")
