### ISSUE TITLE
HTTP API should support fetching binary data

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#21]
![2013-12-23_17 55 04](https://f.cloud.github.com/assets/5545404/1803677/4943e698-6c25-11e3-85ea-9147f9034cfa.png)

I can't get any files from my dropbox using the http API because it keeps erroring Input Length = 2.

The reason why the line in Line 35 is because I changed the API a slight way so it would just simply return Result instead of having me run a function to get that (which seemed strange to me).
And yes, the domain dl.dropboxusercontent.com is whitelisted.

Reproducing the bug:
lua> x = http.request("https://dl.dropboxusercontent.com/u/76573586/OCImage/smallMiku.jpg")
lua> x()
lib/http.lua:36: Input length = 2

Or is https not supported?

**Comment by fnuecke** [comment]
No clue, I'll look into it. The reason the HTTP API is the way it is is because each line that comes back from the server is pushed as an individual signal, to avoid huge websites straight out killing a computer if it has too little memory.

**Comment by pingbird** [comment]
that image is 196 kb, it is most likely using up too much memory
yes it says 512 kb on top, but it gets copied a bit
edit: also, thats not a jpeg >_> you cryptic peice of crap
![smallmiku](https://f.cloud.github.com/assets/2466461/1804327/467f60b2-6c49-11e3-9552-c4816e3fbcd3.png)

**Comment by fnuecke** [comment]
Well the size isn't the problem, at least not at the point where it fails. The problem is that the HTTP API was only built for text data. So binary data will confuse the hell out of the stream reader which tries to interpret the data as UTF-8 text. I'll throw in a more understandable message for now, and will add a check for the content type later... though in the case of binary data it will then have to push all of the data in one go, which could make the computer run out of memory... so I'll probably push all of it either way, making the HTTP API a little dangerous to use, but for the power it offers people will just have to live with that, I guess.

I'll hijack this issue and rename it to reflect the feature this needs to work.

**Comment by ghost** [comment]
XD I switched which image it uses and it still has a problem (the new image is 48x48)
Hopefully HTTP will be able to support "Binary data" later?

**Comment by fnuecke** [comment]
It definitely will, it'll be one of the things that _should_ be relatively quick to get done (binary means everything other than plain text, i.e. stuff that'll display garbage if you open it in notepad by the way. Felt like I should explain since you "quoted" it).
