### ISSUE TITLE
io.read not waiting for input

### ISSUE THREAD

**Issue by tsilva111** [MightyPirates/OpenComputers#2106]
I am new to OpenComputers and to Lua. I'm using Minecraft 1.7.10 and i think i found a bug in the mod, since I wrote the following code and tried to run it. But the only thing that happens is that the inputs do not require the input itself nor the enter key stroke to finalize input. It allays assumes nil value.
Here's the code:

local robot = require("robot")
local event = require("event")

io.write("Front or back type '1', up or down type '2'.\n")
local mode = io.read("_n")
io.write("How many blocks? Negative numbers for back or down.\n")
local amount = io.read("_n")
amount = amount - amount%1
if mode == 1 then
    if amount > 0 then
        for i = 1,amount,1 do
            robot.forward()
        end
    elseif amount < 0 then
        for i = 1,amount,1 do
            robot.back()
        end
    end
elseif mode == 2 then
    if amount > 0 then
        for i = 1,amount,1 do
            robot.up()
        end
    elseif amount < 0 then
        for i = 1,amount,1 do
            robot.down()
        end
    end
end

**Comment by magik6k** [comment]
I guess you wanted `io.read("*n")` as it what you should use for lua5.2(and still works in 5.3). What you did is valid only for Lua 5.3, and I'm not sure if that is even implemented by io lib in OpenOS.

**Comment by Forecaster** [comment]
Use the Term API.

**Comment by payonel** [comment]
@Forecaster there no longer is any need to use the term api. term, io, and print all go through a common io table.

I didn't realize lua 5.3 allows you to drop the preceding '*' https://www.lua.org/manual/5.3/manual.html#pdf-file:read vs 5.2 https://www.lua.org/manual/5.2/manual.html#pdf-file:read

If I am understanding this change in the lua spec correctly, I consider this a bug in OpenOS -- thanks for reporting

**Comment by Forecaster** [comment]
Ah, I thought the Term API was still the preferred method

**Comment by tsilva111** [comment]
Sorry for the missing *, i just copy paste from notepad++, and it went missing in the paste.

The only problem is that term.read() doesn't accept *n to get numbers and as i said I'm new to Lua and i don't realy know how to convert a string to number.

Assume i use term.read()
and type 123 and press enter
it will drop "123\n" and I would need to convert it to number then.

**Comment by tsilva111** [comment]
possibly the missing \* is just a bad edit of mine

**Comment by payonel** [comment]
1. term.read() doesn't take the same args as io.read() -- it has its own api http://ocdoc.cil.li/api:term . @Forecaster was kind to suggest that you use term.read instead io.read because back in the day, term was better integrated. Now term and io (and print) share a common core and there is no need to give preference besides choice of api. The term api has more "terminal" interactive api than io.
2. I tested this and there seems to be something more going on here; I'm concerned there is a larger issue.
3. To convert a `string` to a `number` you can use `tonumber` [a globally available method, no requires needed], even if your string has a \n

```
local num = tonumber("123\n")
```

But this bug is still open because I'm seeing some issues using io.read("*n")

**Comment by tsilva111** [comment]
Thanks to all for the support

**Comment by payonel** [comment]
This bug is due to some old readnum code. I inherited it, and honestly, it is far too complex and not worth fixing as it is. So I redid it, and added some unit tests for it. I'll close this ticket with a ref to the commit that should resolve this.

As for your case, @tsilva111, to get these changes you'll need to reinstll openos after updating the server jar ... or patch the commit in-game manually...to be honest, we don't have a simple "update" solution. You could probably update the server jar and plop in a the openos loot disk [ http://ocdoc.cil.li/openos ] and just install on top of your existing openos installation

**Comment by payonel** [comment]
06e7149573cc310254b691b3944eeb5d99619ff8
