### ISSUE TITLE
blinking disk access light

### ISSUE THREAD

**Issue by pingbird** [MightyPirates/OpenComputers#212]
you know that light on the front of computers that blinks when the HDD is accessed, would be cool eye candy

**Comment by LordFokas** [comment]
when running programs with heavy disk access, you'd be constantly re-rendering the block... that might not be such a bright idea to lower end users... but still, very cool eye candy.

**Comment by fnuecke** [comment]
Well, at least computer cases already have a tile entity renderer anyway (which renders every draw call after all), so that wouldn't be an issue (it'd be more work for server racks, because the slot of the server that had disk activity would have to be passed along as well).

I'll keep it open for when I'm in the mood - the biggest change will, IIRC, be changing it to send a custom packet and also trigger the disk access sounds client side. Right now they're just triggered by the server and that generates the default Minecraft packet for sounds effects.

**Comment by fnuecke** [comment]
Implemented in (for now) local branch.
