### ISSUE TITLE
[Server] Double text input

### ISSUE THREAD

**Issue by its5Q** [MightyPirates/OpenComputers#2122]
I am playing on my private server with my friends, and one time we transfered server to another host and here is a bug because of it. When i press any button one time, in computer it prints this letter twice. Even paste is lagged. I cant do anything on computer because of it. Can i somehow fix it?

**Comment by its5Q** [comment]
![screenshot_216](https://cloud.githubusercontent.com/assets/12975646/20046315/ede6489e-a4f3-11e6-997e-60b083113429.png)

**Comment by payonel** [comment]
what oc version?

**Comment by magik6k** [comment]
Do you have 2 keyboards attached? Have you tried replacing them?

**Comment by payonel** [comment]
> Do you have 2 keyboards attached?

This is why I asked what version. With the latest openos multiple keyboards would not produce multiple drawn chars. It is possible on the new server you are running an outdated oc

**Comment by DemonseedElite** [comment]
I JUST started getting this as well.   OpenComputers version MC1.7.10-1.6.1.11-universal.  Part of the Unabridged 1710 r14 modpack.  

Issue began after switch to using Thermos build 58 as a server.

The OP mentioned transferring to another host and getting this issue, so I suspect his host is also running Thermos.

If this is the issue, then it really sucks, because I can't find a 1.7.10 server that core that runs things halfway decent.
Forge - Everything works, all mods, performance is horrid.
KCauldron - Performance is amazing, lot of bits of broken mods, lot of errors in the logs.
Thermos - Performance is good, most all mods seem to work, occasionally has run-away TPS - reboot often.

EDIT - Scratch that... was only happening on "my" in-game OpenComputer.  I broke it, and moved it and it works, but now, I need a power adapter.  Go figure.  Weird.
