### ISSUE TITLE
Computers are shutdown after server restart

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#2185]
When the server restarts, computers are shutted down and don't restart automaticaly. Screens show their last content but freezed, as the computer is off. Version is: 1.6.0.4.

**Comment by gamax92** [comment]
What is your MC version as well?

**Comment by ExDomino** [comment]
Version of Minecraft: 1.10.2. Modpack FTB Infinity Lite 1.3.3.

**Comment by GB-Hijacker** [comment]
I've had similar issues with FT! infinity Lite for 1.10.2. We run a creeperhost server, and during times the server idles, the comouters and screens will become out of synch. 

I have a tier 1 case and tier 1 screen. On logging in, the screen is frozen. I believe the computer is still performing its function as equipment it's controlling are still acting as I've coded them. A computer restart fixes this issue. I haven't tried chunk loading to see if the issue is related to the sever waking up from idle.

My tier 3 case with 6 block tier 3 screens also acts similarly, but I'm testing screen i/o on it and am not driving equipment with it. I can't confirm 100% it's acting identically to my tier 1 rig.

**Comment by payonel** [comment]
probably fixed, we just closed #2302

**Comment by payonel** [comment]
please retest with http://ci.cil.li/job/OpenComputers-dev-MC1.10/lastSuccessfulBuild/artifact/build/libs/OpenComputers-MC1.10.2-1.6.2.122-dev.jar

**Comment by payonel** [comment]
we are receiving reports that our latest builds are not reproducing this bug. If you see that this repro's, please open a new ticket with clear information of a repro and specify what build you are using. Make sure to test with our latest dev builds at http://ci.cil.li

**Comment by LemADEC** [comment]
Issue was only fixed for robots, computers still reproduce the issue.

**Comment by payonel** [comment]
@LemADEC please open a new ticket with repro details (don't just link back here). retest with a new world - this isn't repro'ing for me
