### ISSUE TITLE
Concurrent Modification Exception Server Crash

### ISSUE THREAD

**Issue by Renari** [MightyPirates/OpenComputers#2226]
https://gist.github.com/Renari/cbf9068ae12ffb9ca365cd419f19db8e

**Comment by payonel** [comment]
a good bug report has repro steps, please provide that
1. mod pack info
2. steps to repro/when did the crash occur, what were you doing, do it happen consistently?
3. work arounds that you've tried
4. did you try updated versions of oc?

**Comment by Renari** [comment]
1. Custom, mods are listed in the crash report.
2. No, we had two people standing near a computer on a server.
3. This only happened once.
4. It's the 1.10.2.1.6.1.6 release.

**Comment by RaeveNoir** [comment]
Do you have a computer with many components connected? Did you change and exceed the component limits in config (you can also do this with net splitters)? Have you connected bigreactors/extremereactors turbines? A lot of them?

I had the component limit raised in config so I could hook up a ton of turbines (20, and later 24) to one machine. The more turbines I had hooked up, the more likely the server would crash with these generic errors within the hour, or in the case of >40 components (all 24 turbines, 3x3 screen, fully kitted computer) just instantly.

But even getting down to stock component limit (barely got to 16, it's all autostart and touchscreen now) we still crashed after an hour or so of starting [BRGC](https://tenyx.de/brgc/).

I'm still working out if it's has to do with exceeding default component limits or a problem with the old BigReactors (now ExtremeReactors) api. Computercraft has reports of the same vague crash when using it to control several turbines.

Some logs:

Semi-intentional 'plug in all 24 reactors directly and power on' crash, with raised component limit. Crashed server almost instantly on power-on. I could run the whole set if I let the computer start and then engage two net splitters to hook up half at a time, and BRGC ran them perfectly, but it would still crash eventually.
http://pastebin.com/uqbVGB4P

Other crashes, at random with 12 or fewer reactors.
http://pastebin.com/SDQPxbBD
http://pastebin.com/e5vHnJZM

**Comment by Renari** [comment]
Sadly I did not mess with any of the default open computers settings, I did not have extreme reactors turbines hooked up and the components were basic stuff to build a computer such as a GPU, not many extras connected.

**Comment by RaeveNoir** [comment]
How long are your cable runs?

Tier 3 screens? Any programs in particular?

**Comment by Renari** [comment]
It may have been a tier 3 screen, I don't recall anymore. It might have been a tier 2 screen. There were no cables everything was touching.

**Comment by fnuecke** [comment]
The first log is something I actually not OC, the one line in there is just forwarding to what Minecraft would do there anyway, so I'd wager that it's a vanilla bug.

The other logs are completely unrelated and CME on different collections which don't have anything to do with OC, either.

**Comment by RaeveNoir** [comment]
All of the CMEs I linked were _absolutely_ related to OpenComputers. One was an _intentional_ crash by hooking up 24 ExtremeReactors turbines directly (instead of staging them through net splitters) with the component cap raised as discussed, and crashed immediately on powering up the computer. We had another CME yesterday when someone was just using OC to control redstone lamps and a billboard. Haven't had a single crash without discovering an OC box running somewhere.

**Comment by xarses** [comment]
I see in the traceback
> * RF API class 'EnergyStorage' is loaded from: jar:file:/home/renari/phuzedsekai/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/EnergyStorage.class

This seems odd that the RF API's are being provided by anyone other that COFH. As a first step I would add in COFH lib actual, and if this one is still providing the RF classes, then you should remove all of COFH from the mcjtylib jar

**Comment by RaeveNoir** [comment]
McJtyLib is for RFTools, so this might be related to #2178 then too, which is awfully similar. 

McJtyLib has an old issue with an incomplete version of COFH, but that's related to wrenches instead of power.

**Comment by Vexatos** [comment]
Are you able to reproduce the issue _without_ McJtyLib, RFTools and RFTools Dimensions?

**Comment by fnuecke** [comment]
The traces indicate access to collections OC never touches. If related to OC, this might be caused by third party components/OC integration that accesses these collections from OC callbacks, not realizing that those are called from OC's worker thread. Maybe.

**Comment by Vexatos** [comment]
Big Reactors in particular uses `ManagedPeripheral`. Aren't those synchronized to the server thread by default?

**Comment by fnuecke** [comment]
I don't think so? IIRC only `@Callback`s could be made synchronous via `direct = false`, the stuff emulating the CC API is from the executor thread, as is the case when it's called from CC. Again, IIRC.

**Comment by Vexatos** [comment]
`direct=false` is default for `@Callback`s, so I just assumed it was default for other ways too.

If it is not, then it might be a BigReactors bug. Or an RFTools Dimensions bug as mentioned in #2178.

**Comment by fnuecke** [comment]
[It's direct](https://github.com/MightyPirates/OpenComputers/blob/917befcd0e8e256bc52abb038f86bc04f236645a/src/main/scala/li/cil/oc/server/machine/PeripheralAnnotation.java#L23). 99% sure exactly because it was meant to mirror CC's behavior.
