### ISSUE TITLE
Disable automatic redrawing

### ISSUE THREAD

**Issue by malucard** [MightyPirates/OpenComputers#2227]
When you draw anything with a GPU, it redraws and shows the content. That's really bad for UI apps, since there's no way to draw to the screen without making it look like it's lagging, plus it takes a lot of time that could be used to run the program.

Something simple like `gpu.setAutoRedraw` and `gpu.redraw()` should do it.

**Comment by payonel** [comment]
sounds like you need to design a gpu pipeline, and reduce your `gpu.set` calls. this is true even in the real world.

calling `gpu.set` is going to have its cost, the more often you call `gpu.set`, the slower your interface

If you want to delay and aggregate calling `gpu.set`, you need to design your own gpu pipeline and buffer the `set` calls, then make your own `redraw` that will pack in the `set` in as few as possible invokes.

Think of the gpu object you have as the actually gpu, it shouldn't be the machines responsibility to add another layer between your gpu and the actual rendering. If you want another layer, you'll need to add it.

On the other hand, there have been many discussions about extending the capabilities of the gpu by adding video memory and double buffering with flipping api, etc: https://github.com/MightyPirates/OpenComputers/issues/779

**Comment by malucard** [comment]
Still, if a pixel changes, you need to call gpu.set. If a lot of different pixels change, there will still be many calls.

And that discussion is pretty old, you sure it'll ever get implemented?

**Comment by payonel** [comment]
in the real world when a pixel changes and it gets changed immediately there is a negative impact to performance. It isn't done that way -- instead pixels are changed en masse via a "pipeline"
For example (speaking of opencomputer api specifically), instead of changing each individual pixel, you merge pixel change calls into lines. So instead of making 50x16 set calls, you make 16. You may even have to cache previous renders to allow for full line redraws.
However, this is not possible (in opencomputers) when you have various colors. Each foreground+background variance will need its own triple-set of calls. And that's exactly where video ram and other buffering api come into play. So, if we're going to add improved gpu support, it's going to be along the lines of that old ticket.

**Comment by payonel** [comment]
I wanted to also say that you are right: a method to "disable redraw", lock the gpu, or lock the screen buffer, would allow for a means to buffer a series of `gpu.set` calls without the rendering cost. Then when buffering was done, you could unlock the gpu and all the calls would propagate, or render. But I would prefer to follow the old ticket's method of having vram to accomplish this.

**Comment by malucard** [comment]
That's what I do in my OS (except it actually runs at 320x200 using braille characters, so it's in fact cheaper to update, since eight pixels are updated at once). The rendering procedure groups as many characters with the same colors as possible, and if one has inverted colors, it inverts the colors and the braille character too. I guess that's as far as it can go, but it still lags.

Not to say I don't want vram. It would be great, and plus if it was big enough and could only hold the screen contents, it would remove the need to "compress" the framebuffer, though I doubt that'd happen for a screen as big as mine (~523KB!).

**Comment by payonel** [comment]
closing as duplicate (or at least alternative solution to) #779

**Comment by malucard** [comment]
Ohh, didn't notice that one had the feature-accepted tag
