### ISSUE TITLE
Optional arguments can't be set to nil

### ISSUE THREAD

**Issue by Fingercomp** [MightyPirates/OpenComputers#2232]
A lot of functions throw an error when `nil` is passed as one of their optional arguments.

Some of such functions are:

```lua
component.robot.compare(nil)
component.internet.connect(address, nil)
component.modem.setWakeMessage("hiworld", nil)
component.gpu.bind(address, nil)
```

And many, many others. All of them use `args.opt<Type>` that only checks if the argument is given, but doesn't check it for `nil`.

[Here](https://oc.cil.li/index.php?/topic/1195-it-was-working-before-the-last-update/) is one of the things that this bug causes. All programs that have `robot.compare()` now crash because this function is defined the following way:

```lua
function robot.compare(fuzzy)
  return component.robot.compare(sides.front, fuzzy)
end
```

If you don't give the function any argument, it calls `component.robot.compare(sides.front, nil)` and crashes the script.

**Comment by Vexatos** [comment]
The commit https://github.com/Vexatos/OpenComputers/commit/ce304ea2489359e78ed629b44b87a0d54a03fbb4 should fix it; however, it is quite a big change in the behaviour of the API. Previously, optional arguments returned their default value if the argument was not defined, e.g. if you were looking for the 4th argument but only 3 were specified. With this change, `nil` would also count as "not defined" and thus cause the methods to return their default values. While I think that this is how it should be (it also being more consistent with Lua's understanding of `nil`, i.e. `myfunc(nil)` being equal to `myfunc()`), considering there is no real point in passing `nil` to any function otherwise, it is still a big change and I am not sure whether it should be pushed into OpenComputers since I might not be aware of all the possible side effects.

**Comment by asiekierka** [comment]
If it's consistent with Lua behaviour, absolutely.

**Comment by MoonlightOwl** [comment]
I agree with @asiekierka.

**Comment by Fingercomp** [comment]
This is a bug, and it should be fixed. Why should we keep compatibility with callbacks that depend on it? Methods shouldn't make use of any bugs, and even if they do, they should be rewritten as soon as possible.

**Comment by Vexatos** [comment]
Closed via https://github.com/MightyPirates/OpenComputers/commit/ce304ea2489359e78ed629b44b87a0d54a03fbb4.

**Comment by Vexatos** [comment]
Please test the new dev build, it _should_ be fixed now.
