### ISSUE TITLE
Generic error thrown crashing server.

### ISSUE THREAD

**Issue by Renari** [MightyPirates/OpenComputers#2245]
Had this crash today, it appears there was an error deleting a file.

https://gist.github.com/Renari/44eacbabc0ef64faa748cacfb7a39001

This happened when I removed some [redstone paste](https://minecraft.curseforge.com/projects/redstone-paste) from the side of a computer, the issue wasn't reproducible by doing that though.

**Comment by fnuecke** [comment]
So much for the "quietly" part of "deleteQuietly". I'd guess you either had a file open and it was locked and for some reason that caused an error instead of an exception, or some other weird shenanigans were going on that moment with your (real world) file system.

If this pops up again, consider turning of file system buffering in the config (but only then).
