### ISSUE TITLE
Admin command to broadcast modem messages

### ISSUE THREAD

**Issue by TinkerWorX** [MightyPirates/OpenComputers#2253]
I'm in the process of creating a challenge map, and I'm using OC to display elapsed time and more. Currently I start the timer by placing a redstone block in a predetermined location. This means the quests are locked to a single map. To help alleviate this, it would be great if there was an admin command to broadcast modem messages.

The current use case is where I execute the command using Better Questing when a quest is completed. Upon completion it runs the command, which starts a timer.

**Comment by NickNackGus** [comment]
I'm assuming that there's enough computers involved that linked cards don't make sense, at least in pairs of two. However, since you are in creative, I'd like to know if something will work: try creating a pair of linked cards, then ctrl+middle clicking them. If I'm right, you could, in creative, create a large network of computers on a single linked card network. I have no idea if it would work, crash, or stop you from doing so entirely, so please share the results. ...and just in case that fails horribly, back up your world first.

**Comment by TinkerWorX** [comment]
That would definitely solve communication between machines, but what I need is to send a message directly to a machine using a command. Imagine this message coming from a Command Block or in my case from a Better Questing command reward.

**Comment by Vexatos** [comment]
Generating a modem message from thin air may lead to issues; unless it is a wireless message, sending the message at all is difficult as the sender would have to be on the network. I guess it would be doable to generate wireless messages, but you would still have to live with the range limitations that are in the config. Maybe sending to a specific linked card tunnel would be easiest (one argument of the command then being the address of the card).

**Comment by TinkerWorX** [comment]
It could also simply be a special event on the Debug Card. Maybe a "user_command" or "custom_command" event. The event would have information about the sender, which would allow you to only accept commands from certain players or players with a certain op level/gamemode. This would allow my suggestion to work, but would also open up for adding special commands that players can use themselves.

**Comment by Vexatos** [comment]
#2256 should add everything you need.
