### ISSUE TITLE
Slow down disk access?

### ISSUE THREAD

**Issue by skyem123** [MightyPirates/OpenComputers#226]
When I was playing with OpenComputers I found that floppy drives were as fast as hard drives. I have a floppy drive in my computer and it is really slow. How about slowing down disk access so it is more realistic?

**Comment by fnuecke** [comment]
The way it's implemented now, details such as "what kind of media is this file system on" are abstracted away at the level the file system component operates. So it's just not possible to have different types of item provide file systems with different speeds.

To make this work I'd need to make some pretty invasive changes in the API, I think, which I'm not convinced this warrants. Speeds are _relatively_ slow anyway, and I'll see if I can add a more data-volume-related write-speed in the future (instead of just one write per tick, as it is now).
