### ISSUE TITLE
[Feature Request] Support for Immersive Engineering's redstone network on T2 Redstone Card

### ISSUE THREAD

**Issue by Techokami** [MightyPirates/OpenComputers#2281]
Pretty much what it says in the title. Immersive Engineering provides its own "bundled redstone cable" solution, in the form of redstone wires that can be connected to connectors, which can provide input or output for one of 16 channels; you can run all 16 channels on one wire. It would be super awesome to have a means of interfacing with this network in OpenComputers, to have I/O on all 16 channels with one connection; right now you'd need a big messy setup with individual input connections and individual output connections...

**Comment by xarses** [comment]
It does? Which versions is this for?

**Comment by Techokami** [comment]
It was added in Immersive Engineering 0.10-31, the second build for 1.10.2. The current build (as of this posting) is 0.10-56, so it's been in there for a while now!

**Comment by brisingraerowing** [comment]
OT: I use IE and didn't realize that. I'm going to have to toy with it some. Thanks for the tip!

**Comment by payonel** [comment]
I added this ticket some time ago because I wanted our redstone support improved (project red works nicely now, btw)
But as it turns out, IE isn't providing a block or device that emits bundled redstone, instead, they carry the bundled signal on wires, but the redstone connector only emits a single channel back into the world. OC would need a hook, a device or mechanism to read the data from the bundled current.
One solution would be to add a device driver for the connector, then someone could place the connector on one of our adapters and the machine could then interact with the connector and possible get data from it about the bundled channels

adding new mod integration with IE would be great, but out of scope of 1.7.3
