### ISSUE TITLE
Feature Request: Coprocessors

### ISSUE THREAD

**Issue by ds84182** [MightyPirates/OpenComputers#2283]
Seems a bit more reasonable than exposing your GPU to OC. This would add [almost] symmetric multiprocessing (not full, since components can't be shared to all of them at the same time).

Coprocessors would be implemented as components for the card slot on a computer. Coprocessors share resources with each other and the main processor of the computer. However, to prevent weird oddities (like two coprocessors sharing the same GPU, etc), the main processor can lease components to a coprocessor. While the component is leased, the main processor cannot access the component and the coprocessor can.

# Bootstrapping

When the main processor (aka the processor in the CPU slot of the computer) starts up, the coprocessors are in the stopped state. The main processor simply calls `<coprocessor>.bootstrap(source: string, memory: number)` to startup a coprocessor. The source code passed in is executed on the coprocessor when it boots up. The memory is the amount of memory the coprocessor should use. For example, if the entire computer has 250K of memory and a coprocessor is started with 10K of memory, the main processor will now only have access to 240K of memory. Starting a coprocessor with too much memory (given memory > free memory) will cause the bootstrap method to fail.

# Component leasing

After the coprocessor starts, the only component it sees is the main processor (a component with the type "processor"). To allow the coprocessor to see other components they need to be leased to it by the main processor (AND ONLY THE MAIN PROCESSOR). A call to `<coprocessor>.lease(component address: string)` will temporarily disconnect a component from the main processor (so a component_removed event is generated) and connects it to the coprocessor (so a component_added event is generated). A call to `<coprocessor>.evict(component address: string)` will forcefully disconnect a component from the coprocessor and reconnect the component to the main processor. Also, a call to `<coprocessor>.leased()` gives a list of all components (with types) that the coprocessor is currently leasing from the main processor. On coprocessor shutdown ALL components that the coprocessor has ownership over will be given back to the main processor.

# Message passing and signals

Coprocessors can receive signals from the main processor. These are emitted as actual signal events from `computer.pullSignal`. The coprocessors can also send signals to the main processor. These are both implemented as `<[co]processor>.signal(type, ...)`.

# Coprocessor shutdown

Coprocessors can be forcefully terminated by calling `<coprocessor>.terminate()`.

# Coprocessor errors

Coprocessors also have time limits like normal processors. When an error occurs on a coprocessor a signal with the type `coprocessor_error` is sent with the error that occurred.

# Example program

```lua
local copro = component.coprocessor

local s, e = copro.bootstrap([=[
local main = component.proxy(component.list("processor")())
main.signal("coprocessor_ready")
... other stuff here ...
]=], 4096)

if not s then
  print("failed to start coprocessor: "..e)
  return
end

... wait for "coprocessor_ready" signal, etc. ...
```

# What this means for virtualization?!

With coprocessors, people can write virtualization solutions for OC! Why? I don't know :D!

No more hypervisors, hello coprocessors!

**Comment by MajorGeneralRelativity** [comment]
In a perfect world, both this and GPU compute would be implemented, but I can definitely get behind at least this idea.

**Comment by payonel** [comment]
interesting suggestion but this isn't the direction we're going with oc. Keep in mind we have some concurrency with openos threads now. Really the way to achieve concurrent work is to build a network with multiple distinct cpus

**Comment by MajorGeneralRelativity** [comment]
But coprocessors, like a vector FPU (found inside all modern x86 CPUs released in this decade at least), can scale up performance in specialized applications much faster than parallel CPUs

**Comment by skyem123** [comment]
There will be no performance gain for multiprocessors in OC due to the nature of Lua. While there is some threading, if everyone abuses it, everyone loses.
Performance bottlenecks of OC are actually artificial! Yielding is needed to other computers can function, due to the nature of Lua (also to not eat up all the CPU of the host), and there are enforced call limits for certain components, again to reduce load on the host systems (GPUs have limits to reduce bandwidth use between client and server).

This is an interesting concept from the "isolated systems" part, which might be worth exploring, co-processors for the sake of abstraction rather than performance. But if anything, it'll make performance worse due to the implicit yielding when one pulls signals.

**Comment by MajorGeneralRelativity** [comment]
There can definitely be a performance gain from making a SIMD unit available in Lua, even one that is slow by today's standards, as it can easily be faster than serial execution on the "Lua CPU" while still not taking up a lot of a modern CPUs FPU. The latest Intel processors can do over 1TFLOPS, so I don't think making even a 1KFLOPS FPU available would result in a noticeable CPU load increase.

**Comment by skyem123** [comment]
If the "coprocessor" didn't use Lua, then theoretically you could get better performance, yes. Though the bottleneck will be the transfer speed between the OC computer and the "coprocessor".

**Comment by MajorGeneralRelativity** [comment]
I can live with that. It would prevent it from becoming too easy to make good use of it.

**Comment by MajorGeneralRelativity** [comment]
There are ways to make good use of a Vector SIMD unit, or similar fast math coprocessor, which makes this a good addition. If it support variable precision math, it could even maybe be used for simple neural networks
Disclaimer: I'm not in that field, and only know that they work on INT8 or FP16 operations

**Comment by skyem123** [comment]
Note that a separate component could be done by another mod, and doesn't need to be in OC proper.

**Comment by MajorGeneralRelativity** [comment]
I am aware

**Comment by payonel** [comment]
@ds84182 

I got some valuable feedback that I didn't give this issue the quality of care that it deserved, and I totally agree. You have here a very well thought out feature request, and it does bring to mind some really interesting projects that would be made possible with this feature.

I wanted to give a little bit more care in my response and explanation for why I felt we could close this issue. I also wanted you to know that I did give this more thought before closing the ticket, but the comment/reason I gave for closing the ticket did not respect that consideration.

The coprocessor described here, and in the context of OpenComputers, represents a machine. Not in the typical sense of a full blown machine block in the world, no, but there must be a machine state that represents the virtual machine. 

There are a few things, in the software design of OC, that we can assume about any machine. The architecture and the memory size. Your suggestion about memory would solve the issue of how a coproc would define its own memory limit, but removing that memory amount from the parent machine is not straight forward. Our machine code relies on the architecture to manage its own memory usage. Thus our arch code would have to understand that the vm (of the parent machine) might need to allocate memory in a new way, by size in bytes. I have considered many methods to do this, but it would probably make sense to have the coproc component code request a memory allocation from the machine, and hopefully the archectures are checking the machine's memory limit during runtime, and not just once at boot time -- but it looks like something like `Machine.onHostChanged` might be the type of thing we would call when changing the free memory amount on the host machine -- so that the architecture calls `recomputeMemory`

As for the arch, It would make sense to craft the coproc card with a cpu to define its tier, perhaps only tier 1. The arch would need to be defined, which we could inherit from the cpu that was used in the craft.

A machine also checks for an eeprom component. A machine fails (gracefully) when there is no eeprom, but the coproc being a machine itself would need the ability to report that it has an eeprom. Your `bootsrap` method could be used to set a virtual eeprom's data. This is just something to consider. The `lease` suggestion has an interesting situation if the user chooses to lease the parent machine's EEPROM. You could even lease coprocs to coprocs. How far does this rabbit hole go? :)

> A call to <coprocessor>.lease(component address: string) will temporarily disconnect a component from the main processor

Our implementation of the component network has basically locked us into some limiting factors. One of the things in this feature request I would change is this minor detail here. I would not remove the component from the parent machine, but it makes sense to add it to the child machine. There also isn't a problem in our network code to share components. I would leave it up to the user code to keep track of "leased" components, and just have an add/remove api on the coproc: `coproc.add(addr)` and `coproc.remove(addr)`. The corpoc component should look a lot like the `computer` api, in fact. Instead of `terminate`, we could use the same api `shutdown` (with bool option for reboot even. Reboot would reuse the same code written to the virtual eeprom again, it wouldn't be wiped). Whether we called the push signal api on this coproc component `pushSignal` or just `signal` isn't a big deal, but to have a similar look to `computer.pullSignal`, I would suggest `coproc.pushSignal`


> Coprocessors also have time limits like normal processors. When an error occurs on a coprocessor a signal with the type coprocessor_error is sent with the error that occurred.

Because we would want to represent the coproc as a _machine_ it would be under the exact same obligation to yield every n (default 5) seconds. When the coproc machine violated the runtime limit, it would be fine to push that as a signal to the parent machine. We could also provide an api on the coproc component to read the last error. Either or both solutions would be simple.

In your example code the coproc sees a component called "processor". which is a proxy back to the parent machine. This proxy would need a pushSignal api, and I'd prefer it not act so low level. Instead, I would prefer the `computer` object in the coproc to have an `emitSignal` ... This deserves some discussion. But coprocs should generate events, not push them directly.

The one detail you added that I have left out is how to list the components that have been added to a child machine. That could either be `coproc.list()` with the same signature as `component.list()`, or `coproc.components()`, again with the same signature as `component.list()`

Now ... is this something that OC should have? To be honest, I see this as a corollary to server racks and server blades, but a type of machine case of many microcontrollers.

Some of things you could accomplish using this would be compact deployments of multiple distinct machines. A benefit to this feature over what we currently have is a programmable control over memory allocation and programmable control of component access. Interesting indeed.

So, should this ticket be closed? To be COMPLETELY honest, when I first started writing this out to explain my position my plan was to justify my reasoning for closing the ticket. But, as I explained myself carefully I found that I'm not against this feature being added, with the adjustment in my feedback. However, I personally don't have time for this but would accept contribution from the community on this request. Thus: open for adoption.

Thanks

**Comment by payonel** [comment]
removing this as won't do
