### ISSUE TITLE
[1.7.10][Open Computers 16.0.3] Extremely low FPS when looking at screen, does not occur when not looking at screen.

### ISSUE THREAD

**Issue by ethanwdp** [MightyPirates/OpenComputers#2299]
Specs:
System Model & Manufacturer: Lenovo E430
OS: Windows 7 Enterprise 32bit (6.1, build 7601) (PAE patched)
Processor: Intel(R) Core(TM) i3-3130M CPU @ 2.60GHz (4 CPUs), ~2.6GHz
Memory: 8192MB RAM (Was originally 4GB, upgraded to 8GB with a 4GB stick I salvaged from another Lenovo laptop.)
DirectX Version: DirectX 11
Integrated GPU: Intel(R) HD Graphics 4000 (note: I had to install a driver for Windows XP, since Intel "forgot" to add PAE support for Windows 7 drivers.)
Mod list: http://i.imgur.com/NOkHjQI.png
Video settings: http://i.imgur.com/MSdtPWX.png

So this is bizarre. I've booted up my modded Minecraft install for the first time in ages, created a new world, and got around to messing with Open Computers. When the PC turned on, I had an immediate frame drop. I noticed that this frame drop only occurs when looking at the screen, looking away alleviates this.

It's been a looong while since I've last played, so I cannot tell if this issue is from the GPU driver I had to install or if it's always been there. However, this makes the mod nearly unplayable, as simply typing has an excruciating delay.

**Comment by xarses** [comment]
Things to try:
* Make sure you are on a recent forge 1566 or later
* Update to 1.6.2 (latest) or at least 1.6.1.11
* Try again without TE and Project Red
* add optfine
* Do you have integrated intel / nvidia combo card? If so switch it over in the bios (also install the nvidia drivers)
* install the latest intel drivers from intel.

If none of that works then try the absolute minimal set:
* forge
* opencomputers
* optfile (optional)

If you still have a FPS issue, then there should be something in the logs to work otherwise we are un-likely to be able to reproduce an issue like this

**Comment by ethanwdp** [comment]
@xarses 
I am on 1.7.10, forge 1566 is not available.
Upgrading had no effect.
Trying again with TE and Project Red had no effect.
Adding optifine and configuring it to have minimal settings had no effect.
I have an integrated intel GPU, I've said that in the OP.
I cannot install the latest intel drivers as they are not PAE compatible. I've said that in the OP


I've also tried the minimal set, didn't work either.

**Comment by ethanwdp** [comment]
I've figured it out!


I had to use PaePatch3 and install the latest Intel driver, as PaePatch3 somehow manages to fix the lack of PAE functionality in Windows 7 Intel drivers.
