### ISSUE TITLE
Cannot install dig

### ISSUE THREAD

**Issue by MaZyGer** [MightyPirates/OpenComputers#2303]
I want to use "dig". If I use it says dig not installed. So if I try to install I get this error.
![screenshot](http://i.imgur.com/yqk7BVy.png "Screenshot")

We use 1.6.1.6 and Minecraft 1.10.2. We use FTB Infinity Lite on linux server

I tried again after restart. Now I just get **"Nothing to install labeled: dig"**

**Comment by xarses** [comment]
To confirm, you did craft the "dig" floppy and insert it into the floppy disk slot prior running the `install dig` command?

if so what happens if you just use `install`

**Comment by payonel** [comment]
I'm more concerned about the crash (in openos) the first time you ran `install dig`

The 2nd time (After reboot) when you say it reports `Nothing to install labeled: dig` is by design, that means the installer can't find the `dig` install (you need to have the dig floppy in the machine) (see xarses's comment)

@MaZyGer but back to the first issue - if you can reproduce that crash, that would be helpful

**Comment by payonel** [comment]
@xarses do you know any repro for `install` crash?

**Comment by payonel** [comment]
dig installs fine, and i've made many improvements to install to handle malformed prop files which should protect us from the crash shown in the screenshot
