### ISSUE TITLE
ArgumentsImpl is not accessible via the API

### ISSUE THREAD

**Issue by SolraBizna** [MightyPirates/OpenComputers#2307]
I want to call `apply`, `unapply`, or `call` on a `Value` from Java code. I can't see a good way to make an `Arguments` object, so it looks like I have to implement `Arguments` myself if I want to be able to do that. I think it should be simpler.

**Comment by thiakil** [comment]
That all sounds like Javascript, which is completely different...

What exactly are you trying to do?

**Comment by SolraBizna** [comment]
I am implementing an architecture. My architecture needs a way to call the `apply`, `unapply`, or `call` method of `Value`, like how Lua code can by doing `value[...]`, `value[...] = ...`, or `value(...)`.

**Comment by Hawk777** [comment]
If anyone’s going to do this, there’s a more important omission: `Machine.invoke` calls `Registry.convert` on the result of the callback, which is important because it does things like turning an `ItemStack` into a `Map`, and other things potentially registered by addons. But `Value.call`, `Value.apply`, and `Value.unapply` can’t go through `Machine.invoke` AFAICT, which means you have to call `Registry.convert` on the result yourself, and `Registry` isn’t part of the API either. Certainly the Lua `UserdataAPI` just calls `Registry.convert` itself.

So far I’ve just done the hacky option, which is using reflection to get at `Registry`. It would be nice if someone fixed this, though at this point I don’t know whether a PR is worth making since I don’t know whether OC is going to release again?
