### ISSUE TITLE
8-8-8 GPU, sega genesis emulators, etc

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#237]
I need a creative mode GPU that has no delay, supports 8-8-8 colors, and... yeah...

please?

**Comment by fnuecke** [comment]
Feel free to make an addon that does that, so people can come to you to whine about the network connection dying / terrible lag / it not working right in multiplayer.

**Comment by SoniEx2** [comment]
Then an operator-only (/give-only) GPU?

**Comment by fnuecke** [comment]
Sure, you could do that.

**Comment by SoniEx2** [comment]
Why can't _you_ do it?

**Comment by SoniEx2** [comment]
Plus you could just compress the screen at the end of the tick and send that instead...

**Comment by fnuecke** [comment]
Why won't you do it?

Sending the full screen each tick is inefficient for small changes - which are relatively typical, really: typing in commands, scroll+write new line... so the current system works well. And is much more server friendly. You do understand that you're basically asking for streaming video, right?

**Comment by SoniEx2** [comment]
That's why I said "compress it"
AKA find the parts that changed, compress the changes, send that
Then ppl can spam color changing or w/e and it just won't do anything...

**Comment by fnuecke** [comment]
Right. That's sounds cool. I'm looking forward to your pull request!

**Comment by LizzyTrickster** [comment]
@SoniEx2 The whole movement behind OpenComputers is that it is **Open** which gives people like you the ability to _almost anything_ you want with it. So, how about instead of running around telling **other people** what to do with _their_ mod you create **_your own**_ addon mod which you can do whatever you like in. Then, instead of using time/energy to tell other people what **you** want them to do you can use that time to **do it yourself**.
