### ISSUE TITLE
[1.7.10] Cannot get data of itemstack from inventory controller upgrade

### ISSUE THREAD

**Issue by DaComputerNerd717** [MightyPirates/OpenComputers#2412]
Before this gets closed automatically for being for an outdated version or something (has happened before with issues on other mods), I understand if this is a bug and you do not want to patch it back in a new 1.7.10 version, then that is your choice.

Basically, I tried to get the item stack data for an item (a Blood Magic slate, to be exact), and some of the parts of the table (name and id) were nil. I am not sure why this would happen, as it should be AWWayOfTime:blankSlate and 4437, respectively, if I am not misunderstanding the wiki. Am I missing some other upgrade that I need to be able to get this data? Is this a bug that was never patched in 1.7.10 versions? Am I simply accessing it wrong?

**Comment by payonel** [comment]
the metadata is more verbose when you enable `insertIdsInConverters=true` in the config, see the details in our docs about `getStackInSlot` here: http://ocdoc.cil.li/component:inventory_controller

I'll test your specific repro and update this ticket when I have done so

**Comment by payonel** [comment]
this may have been fixed since you tested it, or perhaps there was an isssue with the nbt data from blood magic. However, I have just tested this with our latest OC dev build, and the last 1.7.10 build from bloodmagic, and all of the slates (i think there are 8?) properly return their name value to our oc stack data, however the id is omitted unless you change your config and set `insertIdsInConverters` to `true` (the default is `false`). If you enable the id data, then that is working as well.
Hope this helps, thanks for reporting!
