### ISSUE TITLE
default HTTP blacklist has some problems

### ISSUE THREAD

**Issue by nyanlathotep** [MightyPirates/OpenComputers#244]
192.168.0.0/16 is private, but most of the rest of 192.0.0.0/8 is not. For example, adobe.com is 192.150.16.117. "^192\.\d+\.\d+\.\d+$" should be "^192\.168\.\d+\.\d+$".
There's also a third block reserved for private use, 172.16.0.0/12 (172.16.0.0-172.31.255.255).

**Comment by LordFokas** [comment]
following that logic, 10.0.0.0/8 is private too.
but should you block it just because it's a private IP block? me thinks not. If you have a server on a local network that serves content you might be wanting to use in game, you should be able to use it... unless for third-party lua scripts security, which kinda defeats my whole point.

**Comment by nyanlathotep** [comment]
The default blacklist consists of localhost (both as a hostname and 127.0.0.1) and private use blocks, the mistake with 192.0.0.0/8 aside. It has 10.0.0.0/8. And it's just the default, if you want to do that, you can allow it. I think it makes sense to blacklist these things by default because relatively few people are going to have a local server they want to allow access to, and everywhere else, it just becomes a potential security problem.

**Comment by LordFokas** [comment]
yes, of course... by the way, speaking of localhost, isn't the whole 127.0.0.0/24 a private net too?

**Comment by dashkal16** [comment]
127.0.0.0/8 is all localhost.  A trick I've taken advantage of from time to time when doing gnarly networking tricks.

**Comment by nyanlathotep** [comment]
Yep, I have no idea why the entire 16.5 million or so address block is all for localhost. IPv6 does what I'd expect and localhost is just a single address (::1). It may be a good idea to set the default blacklist to include all of 127.0.0.0/8, if it's blocking localhost. I imagine a competently set up network at, say, a game server host, would block local traffic, and as far as I'm aware, any other special-use IPv4 addresses are very unlikely to come up (e.g. 169.254.0.0/16; a computer with one of those addresses is fairly unlikely to be connected to the internet at all). As far as I'm aware, you can't TCP/HTTP multicast or broadcast, but if you could, those should be blocked to remove the potential for DoS attacks. I'm not a security person though, and obviously, any mod that enables users to do networking like this should be looked at carefully with your specific setup in mind if you're using it on a public server.

**Comment by LordFokas** [comment]
I say we block 127.0.0.0/8 and 169.254.0.0/16

There's nothing there for the common user, and it can be exploited (even if just third-party lua scripts attempting to read from your local http server if any and sending that data away. Not that it has any use, but we're better safe than sorry and that's OC's stance up to this point).

**Comment by nyanlathotep** [comment]
I don't know about that; the private-use subnets and loopback seem reasonable to me, but I'm not sure it's worth putting 169.254.0.0/16 in the default blacklist just on the off chance some lunatic is using that on a regular basis. Here's all the reserved addresses that Wikipedia lists and therefore that I am aware of:

Private Subnets:
- 10.0.0.0/8
- 172.16.0.0/12
- 192.168.0.0/16

Loopback:
- 127.0.0.0/8

Broadcast/Multicast:
- 0.0.0.0/8
- 224.0.0.0/4
- 255.255.255.255

Other Private Use:
- 100.64.0.0/10 (communications between a service provider and its subscribers when using a Carrier-grade NAT)
- 169.254.0.0/16 (autoconfiguration between two hosts on a single link)
- 198.18.0.0/15 (testing of communication between two separate subnets)

IPv4-IPv6 interfacing:
- 192.0.0.0/29 (DS-Lite)
- 192.88.99.0/24 (6to4 anycast)

Test Networks (for documentation and example source; should not be used in practice):
- 192.88.99.0/24
- 198.51.100.0/24
- 203.0.113.0/24

Reserved for future use:
- 240.0.0.0/4

Private nets and loopback seem reasonable to me to blacklist by default. Probably shouldn't bother with the test nets or the reserved block. 169.254.0.0/16 really shouldn't ever come up in practice on a server with this, but it may be worth adding. I don't really know enough about the implications of HTTP/TCP traffic to the rest to comment on them. As far as I'm aware, everything outside of these belongs to the public net. On the other hand, regex is cheap enough, it might not be a horrible idea to just put them all in.

**Comment by fnuecke** [comment]
I'll look into parsing address ranges in CIDR notation for 1.3, so these extended defaults can be specified more concisely. Keep in mind that this is intended to be a 'minimal' basis, I'd pretty much expect dedicated servers to handle blacklisting via iptables or similar anyway (and possibly just disable this). So, would a new default blacklist like this be reasonable?
- 127.0.0.0/8
- 10.0.0.0/8
- 192.168.0.0/16
- ^localhost$

That would be the more common private nets plus the loopback. Broadcasts and multicasts shouldn't work anyway, since only TCP is supported, not UDP (and TCP, at least in Java, can only unicast - correct me if I'm wrong).

All the other stuff seems too special-case-ish to be included in the default config, which is more of an example anyway.

As for IPv6, I actually don't know if Java sockets do that automatically? If so, adding ::1 would be reasonable, I suppose. Although I'll have to read up on IPv6 addresses again, since I seem to remember there can be multiple representations for a single address, and that's just a shorthand, right? Some pointers towards Java libs that handle IPv6 address parsing would be appreciated in that case, thanks.

**Comment by LordFokas** [comment]
You missed 172.16.0.0/12, apart from that, it looks just fine.

**Comment by nyanlathotep** [comment]
I have no idea how commonly used 172.16.0.0./12 is, but I'd be inclined to include it for the sake of consistency. Regex for that would be, what, `^172\\.(1[6-9]|2\\d|3[01])\\.\\d+\\.\\d+$`? Not as messy as I thought it might be.
As far as I'm aware, TCP/HTTP are unicast-only.
For IPv6, if you're just taking the strings as is, looking for ::1 won't suffice, yes. You'd probably need to do something along the lines of checking the number of zero-blocks represented by a ::, checking if that's the largest possible group of zero blocks, if not, replace it with zero blocks and switch the :: to the largest group. Absorb any adjacent zero blocks into the ::, and remove any leading zeros on other blocks. And either instruct people to write IPv6 rules like that or have it process the rules in the same way. So that's a mess, in short. You're better off with a library for that, and I'm afraid I have no recommendations, I'm not a java person.
If you can detect IP addresses (are domain names allowed to consist solely of digits? if not, it's easy), checking against CIDR blocks is super easy if you convert them to integers. So if you have the IP **input** and you want to check against **rule/prefix**. Let **highN(n)** generate a 32-bit integer with the top n bits high. Then, input matches the rule if `input & highN(prefix) == rule & highN(prefix)`. You can probably also find a library that deals with this.

**Comment by LordFokas** [comment]
Well, Minecraft is even less likely to be played inside a 10.0.0.0/8 network.
As for domains and IPv6, I'm no help, even though I'm supposed to know all of that (passed that college class with 18 out of 20)...

Anyways, for the sake of simplicity, OC should include the basics only and let admins put advanced configurations in...

**Comment by MaHuJa** [comment]
"Well, Minecraft is even less likely to be played inside a 10.0.0.0/8 network." [citationneeded]

For IPv6 loopback, [0:]+1 might do it... but...

(I wrote and forgot to submit a issue on this a while back. All of it has been covered _except one item_.)

If you're matching for ^localhost$ - on the url/host string then you won't be blocking any of
- localhost. (note the . ) 
- localhost.org  (optional trailing . again)
- yourself.mahuja.net (should I add it.)

Look at the last one again. Who says it has to be pointing to localhost? 

TL;DR: Blacklists are near impossible to get right.

**Comment by nyanlathotep** [comment]
"Well, Minecraft is even less likely to be played inside a 10.0.0.0/8 network."
I'm with MaHuJa on the citation needed there. The blacklist is mostly an issue on public servers, and a significant portion of those are gonna be on hosting services. That's a group that's more likely to use 10.0.0.0/8.

And the localhost point is a good one. Maybe what you really want is an IP blacklist that's checked _after_ name resolution? Can that be done easily?

Having localhost in the blacklist (and allowing domain names) might give a false sense of security in light of that workaround. That seems like a potentially much more serious issue than which private subnets are there by default.

**Comment by LordFokas** [comment]
Let me be more specific. The default configs we're discussing are meant for players who want to get the mod and be ready to play safely out of the box. Server admins are expected to configure their server to perform better / be safer on whatever setup they are. Plus, the people who manage the networks of hosting services already made sure (or should have) that places that shouldn't be accessed are out of reach. So, there are very few chances of instances of Minecraft inside 10.0.0.0/8 nets _really_ needing these default blacklists (by which I mean minecraft clients on poorly managed 10.0.0.0/8 nets).

I'm with @nyanlathotep on checking IPs after name resolution, but I doubt that can be done anywhere near easily, so I'm up for the next best thing.

**Comment by fnuecke** [comment]
Right, I omitted the 172 range because _I_ thought _that one_ wasn't very common - purely from personal experience. I'll keep both, then. Also, only using IPs and trying to resolve names first would be preferable indeed. Will have to see how feasible that is.

**Comment by fnuecke** [comment]
So, actually having thought about this in terms of implementation, the immediate issue that pops up is that name resolving is potentially slow. Really slow (which may actually a problem in the current implementation of the Internet Card). Meaning it'd have to run in a worker thread. Which is ugly but possibly.

It also means both `connect` and `request` would not fail immediately anymore, but return no data (empty string) on the first `read` attempts, and potentially fail after that with 'invalid host name' / 'blacklisted' / 'not whitelisted'. I think that would be acceptable, but let me know if you think there's a better way to tackle this issue.

**Comment by MaHuJa** [comment]
I'm assuming most code will want to open-act-close. Think very carefully about forcing people to make open-_wait_-act-close. Especially when that _wait_ will rely on esoteric behavior like your described usage of `read`.

The most obvious solution is to make the default functions block. They may be lua functions calling the non-blocking version.
At that point it should also be obvious that you need a solid way of checking if the connection is pending/open/failed. If the connection is open, but the remote side isn't sending data, how do you detect this? (component.internet.isopen(socket:number):boolean,[string] perhaps? )

With your described implementation, would writes work correctly if you issue the command before it's open?

**Comment by fnuecke** [comment]
Well for reading the wait is always implicitly there anyway. On a slow connection data can most certainly be read faster than it is produced / downloaded. It's already like that anyway, since the connection is created in non-blocking mode. Same goes for writes, it's like this already - it returns the number of bytes written, so if the connection isn't established when calling write it just returns zero. So there's really nothing that doesn't have to be handled already. Only the point at which the hostname resolving error is propagated would change, and I don't think that's esoteric ;-)

As for detecting if the remote end isn't sending data, that's the job of the dev using the API, it's a generic problem for sockets, nothing OC can or should take care of, IMHO.

**Comment by MaHuJa** [comment]
@fnuecke - Here's how I read your statement of may 21 (supplemented by the documentation):

To make a socket wrapper such that each operation is synchronous, blocking until it either succeeds or fails, I could not make a `connect(where):socket` but would basically need to provide `connect_readfirst(where):socket, string` and `connect_writefirst(where,string):socket`. Do I need to say much more?

I expect the underlying socket lib allows querying the state of the socket. Expose that, and I could block (sleep) until it's either open or failed.

Or is the latter part better formed as a request in a new issue?

**Comment by fnuecke** [comment]
'readfirst' and 'writefirst' are just read and write. This is OK because the write method already returns the number of written bytes anyway (which it has to either way because of the non-blocking IO), same for read, which returns no data (empty string) if there is nothing to read at the moment of the call. Since those cases have to be checked for either way, and both may error either way, I think it's fine to make the hostname lookup error propagate from read and write instead of connect. I don't think it will have any real impact on programs in most cases. That said, I'll expose the `finishConnect` call just in case people really think they need it, I just wanted to make the point that in most cases it will be unnecessary :-)
