### ISSUE TITLE
event.push

### ISSUE THREAD

**Issue by Nex4rius** [MightyPirates/OpenComputers#2467]
I just found out about the thread api (Is that new?) and I noticed an undocumented feature of the event api.
<img src="http://imgur.com/NL9JgUX.png"/>
<img src="http://imgur.com/P2lt0Il.png"/>

How exactly does event.push() work?

**Comment by payonel** [comment]
The thread api is new as of OpenOS 1.6.5 ( http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/1043/ ) and technically a few builds before that, but stable in 1.6.5 ( 2017-June-23 )

I've updated the event api to reference `push`, which has been in OpenOS since .. .probably some time shortly after 1.6

Here is a snippet of the text I added to the wiki:
    event.push(name: string[, ...])
    This is only an alias to computer.pushSignal. This does not modify the arguments in any way. It seemed logical to add the alias to the event library because there is also an event.pull for signals.

http://ocdoc.cil.li/api:event#functions

**Comment by Nex4rius** [comment]
Thanks :)
