### ISSUE TITLE
FMP support for keyboards

### ISSUE THREAD

**Issue by pingbird** [MightyPirates/OpenComputers#247]
i have a keyboard i would like to conceal
![](http://i.imgur.com/bAVJhSC.png)

**Comment by fnuecke** [comment]
I knew it was only a matter of time until this would pop up ;-)

It's something I considered, but it's more complex than it might first appear, since at that point more than one OC 'node' can be in one block space (cables and keyboards), making a bunch of new connectivity checks necessary. I'm sure I'll find the time to do it at some point, just can't say when. Simple workaround for now: just place it on the back of the screen. It's the perfect workaround because it's just as illogical as hiding it behind a wall and still being able to type! :P

**Comment by asiekierka** [comment]
@Sangar: Did you consider adding support for Immibis' Microblocks, then? (Bonus points: Actually bother raising the keyboard if a cover is on the same side as the keyboard)

**Comment by fnuecke** [comment]
Hmm, yeah, might look into that. Should be comparatively easy to do.
