### ISSUE TITLE
OpenComputers & IC2Classic adapter crash

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#2487]
When placing down the adapter block while the mod IC2Classic is installed, the game crashes.
In 1.7.10 it crashes nearly instantly, while in 1.10.2 the game crashes only when placing down multiple adapter blocks.

Crash Logs:
[1.7.10](https://github.com/MightyPirates/OpenComputers/files/1211488/1710-logs.zip)
[1.10.2](https://github.com/MightyPirates/OpenComputers/files/1211522/1102-logs.zip)

**Comment by payonel** [comment]
sadly we would have to add some java reflection in order to add support for IC2 Classic given that the modid is the same ("IC2") and some of the methods are different (such as with mass fabricator). The class paths are the same between the two mods, but the methods of many of the objects we are concerned with are different.

For now I am fixing this by reducing the support loaded if I can detect that IC2-Classic was loaded and reducing the OC drivers that are loaded.

I did find in testing that we can continue to support the nuclear reactor, luckily it appears to have kept the same method api
