### ISSUE TITLE
Chunkloader

### ISSUE THREAD

**Issue by Nex4rius** [MightyPirates/OpenComputers#2499]
Right now it only works in drones and robots.
Could you add something like a chunkloader card to use in the normal computers?

**Comment by Techokami** [comment]
Or a way to stick the existing upgrade item into an adapter and use it that way?

**Comment by purplemonday** [comment]
i like to note that chunkloading **like that** might couse other complications in multiplay

if chunkloaders can be used annywhere then some restrictions are needit like a cost.
work only if the user is online. and should use power to function.

my thoughts here.. if that chunkloaders get to populair it might just couse more problems then its worth and youll endup it being banned or disabled everywhere.  or everntually with massive lag with oipencomputers getting the blaim. hate that to happen.

having said this .. it just doing one chunk prolly not going tobe enough.. can we also have a chunkrange for stationary loaders when they get interduced?

**Comment by Nex4rius** [comment]
If your only goal is to chunkload **all the time** then you can already do it very simple by placing a robots on top of a charger for each chunk and you can do that anywhere (robot can even have a solar generator for it).

I don't think the option of chunkloading for a stationary computer will impact the server performance more than the chunkloader upgrade for the robots.

**Comment by ben-mkiv** [comment]
the servers that dont allow chunkloaders already ban the chunk loader upgrade for robots...

as fingercomp noted in the other bugthread:
"allowing to assemble a microcontroller with the chunkloader upgrade"

and i like the idea of using them in a adapter.

the size of one chunk is fine, too. because people use to load unnecessary chunks with range based chunkloaders.

for the cost... IC2 chunkloader costs 1EU/tick (~4RF) for each chunk it loads. imho it can be more expensive, like 40 RF/FE for a chunk

**Comment by payonel** [comment]
note that we won't be adding chunkloaders to adapters, just the microcontroller. that is its purpose, to run upgrades and cards in an otherwise dumb block.
