### ISSUE TITLE
Robots use power after shutting down with computer.shutdown()

### ISSUE THREAD

**Issue by Forecaster** [MightyPirates/OpenComputers#2515]
Found this out with my reactor refuelling program on the Railcraft server.

Just confirmed in a SP world just using a non-creative robot and the Lua prompt.

```
/home # lua
lua> computer.shutdown()
```

It's not a lot of power, but it is slowly going down. This makes the part of my program that turns the robot off if the reactor stops charging it for some reason pretty useless D:

Power does not seem to be lost mysteriously when you use the power button or the "shutdown" program.

**Comment by xarses** [comment]
The robot will continue to consume power if there is any text on its screen. iirc computer.shutdown() can leave text on the screen. You should reference what is done, or just dofile() the openos [shutdown](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/loot/openos/bin/shutdown.lua) script

**Comment by Vexatos** [comment]
Easier alternative to that: `os.execute("shutdown")`

**Comment by payonel** [comment]
We've discussed expected behavior for this and we feel that screen-clearing should occur when a gpu receives a stop, either by power button or by calling `computer.shutdown()` [[ which is called by /bin/shutdown ]]. We have also agreed that a screen with TEXT can continue to draw power whether or not the case it is attached to is on. That doesn't mean we don't have any bugs related to this (continue reading)

I decided to do some testing

Test results from
OpenComputers-MC1.10.2-1.6.2.114-dev.jar
OpenComputers-MC1.7.10-1.6.2.1073-dev-universal.jar

Yes: Screen is cleared, No otherwise

| Action | 1.7.10 Computer Case | 1.7.10 Robot | 1.10.2 Computer Case | 1.10.2 Robot |
| --- | --- | --- | --- | --- |
| Pickaxe/break case | **No** | - | Yes | - |
| Manually Remove Gpu | No | - | No | - |
| Calling `computer.shutdown()` | Yes | **NO** | Yes | **NO** |
| Pressing power button | Yes | Yes | Yes | Yes |

We probably aren't going to care about fixing 1.7.10 pickaxe break to clear the screen, but the robot discrepancies are definitely an issue. Calling `computer.shutdown()` on a robot SHOULD clear its screen, and that is a bug. We'll track this robot shutdown bug with this ticket

For kicks I tested removing the case when two are attached to the same screen. Nicely, the screen remained on until the 2nd case was removed.

**Comment by payonel** [comment]
well this definitely doesn't repro for me anymore

not sure when this was fixed. i dont have that exact build available anymore, but even retesting the 1.6.2 build from cursor and testing our latest builds -- robot calling coputer.shutdown() clears the screen just fine. I also stepped through the code and confirmed a computer shutdown message was sent, and that the code to fill the screen with black spaces is successfully called.

anyways -- if people continue to have problems with non-blank robot screens, we can look into it
