### ISSUE TITLE
a.onDisconnect(a) isn't called on environments managed by adapters

### ISSUE THREAD

**Issue by malte0811** [MightyPirates/OpenComputers#2525]
I came across this issue while updating the IE OC compat (which is a broken mess right now. This issue is part of a fix). The idea is that machines (mostly IE multiblocks) are controlled (turned on/off) by redstone signals unless they are connected to a computer, in which case that computer controls the machine. To detect whether they are connected to a computer (via an adapter) they have a counter that is incremented/decremented when a computer is connected/disconnected (when `node==node()` is true in `onConnect`/`onDisconnect`). According to the documentation both `a.onConnect(a)` and `a.onDisconnect(a)` should be called.
`a.onConnect(a)` is called as intended, no matter whether the machine or the adapter was placed first. `a.onDisconnect(a)` is only called if the machine is removed first. If the adapter is removed (which is the relevant case for this mechanism, a broken machine doesn't care whether it's turned on or off) it will not be called with `node()` as the parameter.
I tested this on 1.12.1, but I think it affects all versions.

[Test Mod](https://gist.github.com/malte0811/2f64c29f65c8ee1df987236aabb39050)
[Output for placing&breaking the sand](https://gist.github.com/malte0811/c18b5a193fa9d3ecdd984fbe0f2f9b0b)
[Output for placing&breaking the adapter](https://gist.github.com/malte0811/1f1c367b54850a4eb619df9849504d58)

**Comment by payonel** [comment]
there is probably a block change event that causes the adapter to consider it if there is a driver for it, and if so, connects to it. It would seem that a common code path need to also call disconnect. my first concern is that this might cause double disconnect events to occur when both blocks are oc blocks, i suppose a check that they are still connected could be made before calling disconnect.

This deserves some testing and investigation. It feels like something we should fix, but I don't know at this time the cost this might have to support. I'll leave it open for adoption in case someone else prioritizes this before I would otherwise have to fix it myself.
