### ISSUE TITLE
Modem bound to side [Stop super cables]

### ISSUE THREAD

**Issue by lifewcody** [MightyPirates/OpenComputers#2533]
Hello,

Networking in OpenComputers can be easy and hard. Making routers is hard because if you seperate into the OSI model layers, Layer 2 is extremely difficult. Example:

My computer has one network card (fe2), the left is the WAN and the right is the LAN. If someone sent a L2 frame destination for the 'router' (fe2), the router could broadcast the packet on the WAN, but then everything would get it. The cables don't act as cables at all, they act as very smart routers themselves.

To resolve this issue, there could be an implementation of network cards in the GUI that 'binds' them to a specific side. So if I had 3 network cards (f2e), (ga2), and (adf) I can assign (f2e) on the left, (ga2) on the back, and (adf) on the right. If there is a broadcast on one side, then only 1 network card would receive it, instead of all 3. Because what is the point of having 3 network cards in a computer since they all receive the same message. EX:

[https://imgur.com/a/CkX13](https://imgur.com/a/CkX13)

This would allow the computer to determine what to do with network messages instead of them getting broadcasted out without any way to stop it.

I don't know if this would break the computer acting as a cable itself though. You could program OpenOS to automatically forward network messages out the other sides to remedy the issue.

### Stopping Super Cables
Right now, the routing on the cables is _insane_. That is not how cables work. If a network card is listening on the 'port' (I like to think of them as VLANs,) then any information transmitted on that should be listened to even if it isn't intended for the network card.

#### Reworked broadcast
Instead of generating a packet for each network card the source finds on the 'super cable' set the destination ffffff-ffff-ffff-ffff-ffff-ffff or whatever and then it will get routed to all network cards. When you 'send' from the network card then the destination will get replaced with the correct destination UDID.

#### Computers OR microcontroller modem binding
Allow microcontrollers to bind network cards on a specific side, same thing with computers.

#### pulling events
Here is how the current event is pulled

| receiverAddress | senderAddress | port | distance | data |
| --- | --- | --- | --- | --- |

Instead of the receiverAddress being the actual network card for a broadcast it would be the broadcast UDID (fff-fff-ff-ff-f-f-ff) or whatever. A 'side' option could optionally be passed as well.

#### Switches
They would become relevant now. Have them have a switch table of where they saw addresses. (maybe add a floppy for storage or something, and you can upgrade them). Placing switched in (T) or (+) sections of cable would make it more secure.

**Comment by Tahakk** [comment]
`[Example](https://imgur.com/a/CkX13)` <-- GOOD vs BAD --> `[https://imgur.com/a/CkX13](Example)`
[Example](https://imgur.com/a/CkX13) <-- GOOD vs BAD --> [https://imgur.com/a/CkX13](Example)
just FYI :)

**Comment by lifewcody** [comment]
@Tahakk Oops, completely messed it up haha. Thank you, it is fixed now

**Comment by payonel** [comment]
This is an interesting suggestion but a work around would be to add two more computers to your router hub. One is the LAN connection, the other the WLAN.

**Comment by skyem123** [comment]
It's already possible to do this with server racks and microcontrollers, though it'd be nice if there was a way to do it using normal computers somehow too.

Sadly you can't forward messages transparently without spoofing and that's not built into OC. 😛 Also, not forwarding would break other protocols which are built with this in mind.

**Comment by lifewcody** [comment]
@payonel What do you mean adding two more computers? Like [Computer]-------[Router]--------[Computer]?
The issue is that, in the example above, If I broadcasted from the left, then the router would be 'transparent'. Even using relays doesn't fix it

@skyem123 It is possible to do this with server racks, but not entirely microcontrollers. From what I understand, micro controllers allow you to to set a side where network messages are received from, not making a network card only listen and respond to on a side. The cables act as a super smart system, not as cables transmitting data

**Comment by payonel** [comment]
My suggestion as a work around is to have two separate computers to form a router
The WAN facing computer would broadcast, the LAN facing computer would route and filter. The LAN computer would ignore broadcasts from the WAN that itself created.

It would be easier and cooler to have better cabling for this, but, we've decided to not change our networking code that we have. Thanks

**Comment by SaphireLattice** [comment]
Perhaps a kind of toggle on the case/network cards that would stop a computer from acting like a network cable? Like a power distributor that only distributes power, but with ability to receive network messages as well. Something similar to what is there in the server rack, but with network cards, rather than servers.

Though, such design would either break backward compatability, or will be way too complex to implement due to supporting both "new" and current styles of networking. And would need tons of complex GUI work.

**Comment by lifewcody** [comment]
@payonel What do you mean have 2 computers to form a router? Computers act as cables themselves so it wouldn't matter.

@dangranos What I think they should do is disable this feature. Add in OpenOS a background agent when a network message is received then it is broadcasted (can be turned off) so it wouldn't break backwards compatibility.

I don't know why the networking code was created like this. Honestly, to me, it is illogical and doesn't follow physics. A cable is a cable, and should be a cable.

**Comment by skyem123** [comment]
Physics has nothing to do with what protocol goes on top most of the time. In this case, it's a giant bus network, which has both component data and network message data. Relays filter out component messages, and recreate and forward the network messages (also Minecraft and Physics?! That's never been true... 😛).

It's not ideal, but it's probably not worth changing. What would be interesting is a way to lock a side of a computer to be network only for a certain network card, which could work, though it would be very painful to make the GUI for.

**Comment by magik6k** [comment]
That's what you use racks/servers for, you can bind servers and network cards to specific side of the rack.

**Comment by payonel** [comment]
@lifewcody you make a good point (i.e. computers act as cables).That would completely break my solution
You could use link cards to communicate between the WAN node and the LAN node

As I look more and more at the code, how we handle networking and connected devices in OC, I'm convinced that this request is simply out of scope for how the code is working. This would be a rather risky change to make, let alone how we expose it to the user.

**Comment by skyem123** [comment]
Possible solutions here include microcontrollers or server racks... The advantage of a server rack is that you can fit both the WAN computer and LAN computer in a single rack.

**Comment by lifewcody** [comment]
@skyem123 The issue with microcontrollers is that the network cards are not on a specific side. If I have 2 network cards (ex: 00f and 00a) and I have one cable to the micro controller, then both 00f and 00a receive the message.

**Comment by purplemonday** [comment]
just thinking here and ive run into this aswell. found that wireless solves most for now. as it returns the distance, with distance you can have somesort of detected order without having a giant list of keys.

to make a sub-network either to connect more components, spread load or whatever aplication this might be good for,.
there sertianly uses for this. 

i would like to see some optional "device" filter, say firewall
with this i could blacklist/whitelist sertian "keys", "types" and "maxium length of cable"  and achieve the above and at the same time allow to blacklist some components that might be in the subset or main network, or even the same network,

to exclude keys from showingup in component list would be extremly usefull. 

Nother use for such a filter would be selecting the right monitor etc. to detect the distance of that monitor would be importand aswell to detect the order instead of the random primary witch is the case now

**Comment by skyem123** [comment]
@lifewcody, well... then I recommend server racks, they seem to do what you want, even if they are expensive.

@purplemonday, that's an interesting idea, but I don't think there is a way to get wire distance, only wireless distance...

**Comment by lifewcody** [comment]
@skyem123 Yea, I was figuring server racks were what I was going to have to use, I originally was trying to do micro controllers but that blew up as I found out messages go through them as well and the network cards get the message.

**Comment by purplemonday** [comment]
would be perfectly fine to get a euclidean distance instead of the wire distance, 
 say component.getDistance(key) or component.getLocation(key)/computer.getLocation(null)

tho the latter would eliminate the need for gps stuffs, basing it out a local location instead of global would limit it from being abused for gps.

i like to add that getting a random primary realy bites in making more complex networks
if that could be chanced in length instead of randomly picking one. the need for those functions i sugested would not exsist. (so instead of a random primary, the primary would always be closest, the lowest slot number, lowest side number or whatever logic aplies except making it random.)

combo of those options, with the ability to blacklist keys would add somuch dynamic in making more complex networks. 

one aplication would be to allow multiple computers to use the same component (like the raid)
or computers to share a network without playing rusian rolete with the monitors.
keeping track of connected redstonecard cubes without configuring keys. 

im pritty sure it doesnt end there. overall it would allow for more automated and user friendly scripts
