### ISSUE TITLE
Unable to run oc from gradle

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#2561]
When attempting to run oc from gradlew runClient, I receive a forge error telling me that there are 2 instances of ae2, any help?
MC Log: [https://pastebin.com/D60tX652](https://pastebin.com/D60tX652)

**Comment by payonel** [comment]
we should update the AE2 zip we've bundled, it is a bit messed up.
But OC won't support running the mod from runClient, you can either link to the built jar or run it from gradle.

I'll update the Readme.md to reflect some of this info

**Comment by payonel** [comment]
http://ocdoc.cil.li/tutorial:debug_1.7.10

**Comment by ghost** [comment]
Thats... interesting behavior

**Comment by payonel** [comment]
this would be nice to have, but we've decided not to improve support for this

**Comment by Xyxen** [comment]
Could we continue discussion on this, actually? This was a pain point while I was working on another issue. The current build instructions only work for IDEA, and require no less than 200 (!) clicks to get up and running (assuming a Gradle import). On the other hand, it only took a couple of tiny changes in `build.gradle` to get `runClient` working for me, and that's IDE-agnostic.

The issue is that the `compile` configuration is extending from `provided`, which means all of the compile-time dependencies are also put on the runtime classpath. Forge loads any mods it finds on the classpath, and the set of dependencies definitely don't make up a functional modpack (especially with the broken AE2 jar). Separating `provided` and putting it strictly on the compile classpath fixes the problem. [ForgeGradle even does this, post-2.0.2.](https://github.com/MinecraftForge/ForgeGradle/blob/f49079dd11c037f74cc740285b2c5504fbf8a7f6/src/main/java/net/minecraftforge/gradle/user/UserBasePlugin.java#L502-L515)

Would a pull request be considered?

**Comment by skyem123** [comment]
Well... As long as it doesn't break anything and isn't hard to maintain, then I don't see why it wouldn't be considered. :P
