### ISSUE TITLE
[Suggestion] Low-range wireless network card.

### ISSUE THREAD

**Issue by S0ZDATEL** [MightyPirates/OpenComputers#2562]
I think it's a good idea adding a low-range wireless network card, because I don't always need a wireless network card with a range of 400 blocks. Low-range wireless network card can have a range ~40 blocks, have reduced complexity and lower power consumption. They can simultaneously support open less ports than wireless network card.

**Comment by skyem123** [comment]
That seems like an interesting concept...

**Comment by Kiritow** [comment]
You can configure the range of a wireless card in game using Lua API. And the document also says lower range will consume lower energy.

**Comment by S0ZDATEL** [comment]
You did not understand me. I need a wireless network card with a maximum range of 40 blocks. Network card configured for low range, will receive messages from a distance of 400 blocks.

**Comment by skyem123** [comment]
Hmm... maybe a way to set receive range would be a good idea?

**Comment by S0ZDATEL** [comment]
Or you can do so.

**Comment by payonel** [comment]
i suppose we could consider a tier 1 wireless card

**Comment by TheCodex6824** [comment]
So I was thinking I might try to add a tier 1 wireless card, but I want to get some feedback on some stuff before I would start:

1. 40 blocks for the max range sounds reasonable.
2. Power draw I was thinking would maybe be half the amount of the tier 2 card per block by default, which with default config settings would be .025 power per block.
3. Open ports I was thinking should get nerfed quite a bit on the tier 1 card, to make the tier 2 actually considerable in low-distance settings / make it so that everyone doesn't use the tier 1 everywhere to save a tier 2 slot. So, maybe 2 open ports max by default?

If anyone has any feedback about the above points or the existance of a tier 1 wireless card at all, I'd be glad to hear it.

**Comment by payonel** [comment]
I think the tier 1 wireless card needs to be limited enough such that it is only a good solution in very controlled circumstances. We want the tier 2 wireless card to really be valuable in comparison, without having to increase(i.e. change our default settings for) the t2 wireless card

I'm open to feedback on this:

1. 16m radius
2. same power draw [ same cost per block for same data, no freebies! ]
3. 1 open port by default. [ you want a router? upgrade your wireless card ]

**Comment by TheCodex6824** [comment]
I was afraid of being too harsh on it, but you bring up a good point. I also didn't really think about the fact that it would be competing with a spot for the normal network card, another reason why it needs all those nerfs. One interesting thing I just thought of though - I wonder if it should send wireless packets only, and lose the ability to do wired networking. It'd kind of be like those standalone PCIE wireless cards. Just something to think about.

But overall I agree with the changes you suggested.

**Comment by payonel** [comment]
> I wonder if it should send wireless packets only, and lose the ability to do wired networking

Isn't that how wireless cards work normally - they don't have a wired connection, they only broadcast wirelessly? I'm a bit confused what you mean - but - there are areas of the mod i haven't play-tested to be honest.

**Comment by TheCodex6824** [comment]
The wireless card can send both wired and wireless packets (wireless strength can be set to 0 on it to just send wired)

**Comment by payonel** [comment]
ok interesting. I think it would be okay to disable wired support (ha, I didn't even know it was there 15 minutes ago, not sure why this was a hard decision for me to make to give it up)

**Comment by TheCodex6824** [comment]
Ok to summarize:

- It will be tier 1
- Will have a max range of 16 blocks (default)
- Will have the same energy cost as the normal card
- Will only support 1 open port at a time
- ~~Will only send wireless packets, not wired~~

~~I'm probably also going to have to add a method to the modem component that's called isWired or something like that, since that will no longer be guaranteed.~~

**Comment by payonel** [comment]
Ok i've changed my mind :)
It should continue to support wired messages, no new `isWired`

**Comment by payonel** [comment]
ok let's talk about the craft, ender pearl is used for the wireless (t2) card, so what should this one be? a noteblock? :)

**Comment by TheCodex6824** [comment]
A noteblock would be pretty funny, there really isn't too much that is suitable for tier 1 stuff so that's really the best thing for it. The only other thing would be replacing the t2 chip with a t1. For hardmode recipes I would probably keep the ender pearl and just switch the chip to t1. Peaceful would work with the default recipe, but I don't use gregtech so I have no idea about that.

**Comment by payonel** [comment]
i'll leave the craft decisions up to you, I don't want to change the t2 craft nor the network card craft, and it should somehow cost more than the network card and cost less than an ender pearl -- but besides that you can come up with what you like.

**Comment by payonel** [comment]
maybe a redstone torch. noteblock might be too "sound" oriented, like a sound card
{ redstone torch, t1 chip, and card base }
but i'm happy to consider what  you come up for this, i'm just brainstorming if thathelps

**Comment by TheCodex6824** [comment]
I'll try to think about them. The redstone torch is not a bad idea, but the [tier 1 redstone card uses a redstone torch already](http://ocdoc.cil.li/item:redstone_card) in that spot. ~~Maybe it can be a redstone torch on top of an iron ingot or something like that?~~ I know, _two_ redstone torches.

**Comment by skyem123** [comment]
I actually think limiting it to just wireless networking is a good idea. You either waste two T1 slots or a T2 slot. I feel the limits are a little harsh but it's probably best to start more restrictive and open it up later if it isn't very useful, I guess.

**Comment by TheCodex6824** [comment]
Yeah my thinking with that was it would make the decision between the normal network card and the T1 wireless card more meaningful. As it is, the only thing really stopping the normal network card from being useless is the port limit. My goal with this was more to have people say "oh I have options for T1 networking now, cool" rather than "hmm, I only need 1 open port, time to replace all the network cards". Either way, I'm going to put power, range, and maximum ports for the T1 card in the config so people can tweak it if they want to.

**Comment by payonel** [comment]
ok I like that choice between the two tier 1 types -- and thus removing wired messages from the tier 1 wireless card. Can I change my mind every 5 minutes?! sure! :) So, okay, I'm back on the side no-wired-network and adding the `isWired` method

Instead of adding maxOpenPorts, add some data to the device info instead

**Comment by TheCodex6824** [comment]
Welcome back to `isWired` land! And yeah, I'll add the maxOpenPorts to deviceinfo instead. Speaking of deviceinfo, `maxPacketSize` is still in the modem component and [was supposed to be removed in version 1.7](https://github.com/MightyPirates/OpenComputers/blob/8e1faa831a12c4ebcbf752947f76385e3adbf71e/src/main/scala/li/cil/oc/server/component/NetworkCard.scala#L110-L112). Should I remove that?

**Comment by payonel** [comment]
no we remove it in 1.11, but left it in 1.7.10. I know the comment says that but .. i decided to leave it in

**Comment by TheCodex6824** [comment]
Sorry about the commit spam, had to change a bunch of stuff for a config change and I made the mistake of putting this issue number in its title... But in other news, #2657

**Comment by xarses** [comment]
I think there is an argument for the max ports to be 2 or even 3. I see an Application port, an admin port, and a re-programming port. Otherwise it would need to all be bound into one. I could see this somewhat easily for admin/programming but not as easily with the application merged in and addressing possible auth needs w/o an entire REST and probably htaccess level of coding which probably far exceeds the resources of embedding onto a EEPROM

**Comment by skyem123** [comment]
well one could multiplex everything into one port! :P

**Comment by xarses** [comment]
for a coder, heavily experienced to do such a thing, for an low or mid level coder it would be much harder, again this is based off keeping everything running over eeprom aka, uC. If we don't we need to make it really obvious that these will be a LOT harder to work with, that while they are t1, they are much more stripped down than the wireless cards of previous versions

**Comment by payonel** [comment]
I agree that it is easy to think of reasons to need more than 1 port (@xarses your list is a great list) but I don't feel that justifies making the T1 wireless card handle it. I feel wireless tech is a big gain for t1 -- i feel there needs to be a reason to NOT use the t1 wireless card. I feel there needs to be a few reasons not to. I like the idea of these 3 cards (network, t1 wireless, and t2 wireless) giving a real choice pool. If the t1 is good enough, why ever use t2? Tradeoff is good.

**Comment by skyem123** [comment]
I guess the tradeoff is that one needs to design a protocol for it, it's not hard, but it requires someone to make programs specifically for it.

**Comment by SaphireLattice** [comment]
Isn't that the whole idea of OC, to provide tools that don't really do much
by themselves, by with application of some thought, you can do anything¹?

1 - Except for going past core limitations of Minecraft. Argueably.

---

As for T1 card and 1 port, it's perfectly enough to implement short range
communication, just needs some protocol and addressing. And if you think of
it, real life networking doesn't have any ports until the higher level,
where someone implemented then.
Well, in short, it's a very good tradeoff for a cheaper card, especially to
be used in "IoT" microcontrollers. It will make them cheap enough to
quickly make, and with a bit of programming, you could create "cheap"
(cheap in materials, kinda, but not the "we need to make it more expensive"
cheap) base control solutions. And obviously provides some choice between
all-powerful (but kinda expensive unless you got a mob farm. And it's not
*too* powerful, plsnonerf. Nerfing anything that is just powerful but not
OP is a sign that developer is trying to just say "hey, I'm doing things,
okay?") card and non-wireless one.

**Comment by payonel** [comment]
we now have the T1 wireless card in our 1.7.10 branch
it'll be merged up, and available in our  1.7.2 release when that is released on curseforge
