### ISSUE TITLE
Mutex in OpenComputers...

### ISSUE THREAD

**Issue by Kiritow** [MightyPirates/OpenComputers#2575]
Hi, I am designing a program that can queue redstone changed events. The code might be like:
```
event.listen("redstone_changed",
	function(device,side,from,to)
		lockGlobalQueue()
		pushValues(device,side,from,to)
		unlockGlobalQueue()
		event.push("queue_new_value")
	end
)
```
And the main program might be like:
```
while(true) do
	event.pull("queue_new_value")
	lockGlobalQueue()
	doWork() -- Deal with values...
	unlockGlobalQueue()
end
```

So, does OpenComputer provides something like mutex ?

**Comment by skyem123** [comment]
Well... I don't think so but it should be easy to implement yourself, as only one piece of code will run at a time, so a simple counter should be enough. It's worth noting due to lua's cooperative multitasking, it should be safe to do multiple operations until a yield, which is caused by many things, but if you just increment / set a lock, then read /write data, then it's fine.

**Comment by payonel** [comment]
the Lua cpu is single threaded and thus we don't need any critical sections
Even if your `pushValues` or `doWork` yield or resumes, it would be possible to add any custom user level variable could act as a lock.
