### ISSUE TITLE
Loot disks cannot be found in chests

### ISSUE THREAD

**Issue by AbsalomAchitophel526** [MightyPirates/OpenComputers#2602]
Playing on MC 1.10.2 OC 1.7.0.124 and I cannot find loot disks at all.  At first I thought one of my other mods were interfering with the chest loot tables but after a fresh install with the only mod being OC I still cannot find any, even in creative.  I realize that I can simply craft them but that's no fun for RP purposes.

For the record, my previous foray into a earlier opencomputers version on MC 1.7 yielded the disks easily.

**Comment by payonel** [comment]
@AbsalomAchitophel526 I personally have never found an oc disk as loot. CC definitely did this.
I'm not saying OC never did, just that I haven't seen it. I know far too little about how the rest of the mod works, outside of the areas that I have worked on myself.

**Comment by skyem123** [comment]
I know that they are meant to be found as loot, but I don't think I ever played in survival with OC long enough to find a dungeon. 😛

**Comment by Techokami** [comment]
At one point, they were found in dungeon loot chests. But **I think** it got depreciated in favor of the crafting method due to how OC handles loot disk generation that was making it incompatible with things like Minetweaker.

Back in MC1.7.2 a few years ago, OC had a singular item that got re-rolled on generation to become one of the possible loot disks, to avoid flooding the loot tables with all the possible loot disks. If you have multiple possible items added to the table, each item got its own chance to be rolled. This resulted in flooding chests with several varieties of this item, as my friend found out with Garden Stuff and loot-obtained pottery stamps for making patterned flower pots. He fixed that by adding a new item - a dirty stamp - that when used with a cauldron of water, rolled for a random stamp out of all the possibilities and generated that in its place. This resulted in us no longer being flooded with pottery stamps in the dungeons we were generating. But OC's method was... different. When we tried to re-balance the mods in the server via custom loot tables, we were no longer able to get OC loot disks, because the special item *did not re-roll into a loot disk when added to a loot chest by Minetweaker.* We were getting unusable floppy disks; they were blank and write-protected. [I submitted an issue about this back in 2014!](https://github.com/MightyPirates/OpenComputers/issues/253)

**Comment by payonel** [comment]
I spoke with sangar about this. we used to have this feature but in the 1.10 time frame this was removed due to breaking changes. I do not see plans to reintroduce this feature. Right now the expected user workflow is to craft the disks, not find them in loot chests.

**Comment by skyem123** [comment]
That means the documentation should be updated to not confuse people. 😅

**Comment by payonel** [comment]
now dup of #2686
