### ISSUE TITLE
OpenComputers not properly closing TCP Sockets

### ISSUE THREAD

**Issue by MajorGeneralRelativity** [MightyPirates/OpenComputers#2620]
Like in the title, OpenComputers does not properly close TCP sockets when a computer shuts down. They remain open for an indefinite period of time, and interfere with new sockets being opened to the same address. Screenshot below of unclosed sockets:
https://imgur.com/a/QgsZk

Please let me know if I should provide any further information

**Comment by Inari-Whitebear** [comment]
Seems to close for me at least, but I'm on Windows 10.

**Comment by MajorGeneralRelativity** [comment]
The MC server is running on W10, with the socket recipient running on Linux.

**Comment by Kristopher38** [comment]
I'm having a similar issue and I think it's related - some sockets don't get closed when the computer shuts down (it should be noted that in the majority of cases - they do get closed, so it might be some sort of race condition, I don't know). That leads to a buggy behavior - when I open a new socket on the same or different internet card after the previous one happened to not close and is left in a zombie state, internet_ready signal doesn't get queued anymore, but the data that was supposed to queue the signal still arrives and can be read from the socket, it's just that I can't detect it with a signal handler. It's especially bad on servers because I can't forcibly close lingering TCP connections with some utility or restart the server (as I would do on singleplayer), as that seems to fix the issue.

Workaround for that is either waiting for sockets on the server to close themselves (which can sometimes take hours if not days) or just scheduling a timer and polling the socket instead of using internet_ready signal, but that was exactly what I tried to avoid. This isn't a game-breaking bug but certainly script-breaking.

**Comment by Kristopher38** [comment]
After my investigation it might not be related - it was caused by this bug https://github.com/MightyPirates/OpenComputers/issues/3228 to which the issue's author provided a fix.
