### ISSUE TITLE
Creative component bus?

### ISSUE THREAD

**Issue by anar4732** [MightyPirates/OpenComputers#2633]
for 1000 components

**Comment by payonel** [comment]
note that in the config you can change the cpu component count for the 3 tiers to any value you may need. But if someone else wants to put in the work to make this type of component bus I think it would be considered for merge.

**Comment by Xyxen** [comment]
I'd like to have a go at this, to get my feet wet with this codebase. I just have a few questions:
- *Should the component capacity be configurable?* The existing bus cards piggyback off of the CPU component counts, and it might be confusing to add a fourth when there are only three CPU tiers.
- *How are translations handled?* I'm only an English speaker, but the requisite translations for all but Chinese seem lexically straightforward. I could give it a shot; maybe clumsy translations are better than none, to start.
- *Are there any forseeable problems if I edit `assets.psd` with GIMP?* I don't want to PR an icon that isn't found on the master sheet, but if there's anything fancy going on in that file, I wouldn't want to clobber it.

**Comment by skyem123** [comment]
Well... I think it's a bad idea to translate what you don't fluently know. Who knows what it ends up as. :P
Component capacity should be Inf / math.huge / largest value possible.
Using GIMP should be fine, you can always test if it renders and compiles properly...

**Comment by Xyxen** [comment]
I'm always a bit leery about fiddling with what I don't know, but it's awfully tempting when the wording looks like
```
item.oc.apu0.name=Unité de Traitement Accélérée (UTA) (Niveau 1)
item.oc.apu1.name=Unité de Traitement Accélérée (UTA) (Niveau 2)
item.oc.apu2.name=Unité de Traitement Accélérée (UTA) (Créatif)
...
item.oc.componentbus0.name=Bus des composants (Niveau 1)
item.oc.componentbus1.name=Bus des composants (Niveau 2)
item.oc.componentbus2.name=Bus des composants (Niveau 3)
item.oc.componentbus3.name=Bus des composants (______)
```
Seems so easy to fill in that blank, but you may be right.

Setting component capacity to `Integer.MAX_VALUE` seems like the wrong approach. There'd definitely be overflow problems if any other component (e.g. the CPU) added capacity. I think 1024 is a pretty reasonable value. The other angles include modifying `supportedComponents` to return a union type that includes "no limit," or just changing the [summing code in `Machine.scala`](https://github.com/MightyPirates/OpenComputers/blob/63a89b368897ac42a098c682a57d005a3fc66bdb/src/main/scala/li/cil/oc/server/machine/Machine.scala#L109-L115) to cap out instead of overflowing. Starts entering overengineering territory, though.

The only problem I've noticed with stable GIMP is that the layer groups are flattened out. [Seems like they've fixed that,](https://bugzilla.gnome.org/show_bug.cgi?id=705895) so I'll try out the latest development build later.

**Comment by payonel** [comment]
1. make the component capacity configurable, don't worry about making it unlimited. 1024 is a fine number.
1. Vex says don't translate stuff you don't understand
1. I dont know about the image resources

**Comment by skyem123** [comment]
Maybe make it cap out and not overflow as well? 
Over-engineering best engineering! :3
