### ISSUE TITLE
Administrative decision on addon mods

### ISSUE THREAD

**Issue by KFAFSP** [MightyPirates/OpenComputers#267]
Hello OC-Team,
this is kind of an unusual question, but is there some kind of design-guideline for addons to this mod? As with other mods like ComputerCraft there is usually an (unwritten) rule of what you should do and what not, such as how hard crafting recipes should be, wether to include (like with MMM's PS addons) other mod items into recipes whenever possible. But also very "trivial" decisions like the art-style one should stick to.

I don't want to suggest destroying any creativity and/or originality, but I personally would really welcome some sort of rough plan, like, in which direction the whole mod should be going, so to speak.

This is just a suggestion and a personal question, as I am unsure of the authenticity of my own addons ;).

**Comment by Wuerfel21** [comment]
Cause its open you can do what you like(mostly)
Correct my if im wrong.

**Comment by Techokami** [comment]
Open source means there really aren't any limits :)

If you want to make your mod feel like it's part of OC though, I would suggest using a similar art style for the textures (Painterly Pack seems to be the style, imho?), require some effort to craft (use ICs in your recipes!), and use simple block models. Also keep in mind that the mod makes computers more _limited_ than what ComputerCraft provides, so you should consider keeping some limits on what can be accomplished. This actually makes things more fun if done well; I'd rather engineer a creative solution to get around a limitation than just have everything available from the start!

And one last thing: consider posting your mod on the forums, and joining the IRC channel! We'd love to see more peripheral mods :smile:

**Comment by fnuecke** [comment]
I wouldn't presume any authority over what people do with their addon mods, really. But if it helps, I just pushed the [PSDs I use for the block and item textures](https://github.com/MightyPirates/OpenComputers/tree/master/assets) (mostly as a backup, really), feel free to use those as a basis for your own textures.

If you want something like 'best practices' or 'code conventions' but for design choices: I try to keep things from getting too powerful, as Techokami pointed out. Prefer providing tools over solutions (give a man fire and he is warm for a night, ~~set him on fire and he is warm for the rest of his life~~... you know what I mean). Another guideline is the fourth wall, of course. Aside from the Internet Card I try not to break it. Hence the Navigation Upgrade only returning relative coordinates, for example. As for recipes... I'm not really good at designing those either (see hardmode recipes, those were the normal ones originally... yeah... that's also the reason OC's chipsets are not the oredict chipsets (UE/Mekanism/BC/...) because I'm afraid of messing up other mods' balance), so just do what you feel is fair but challenging and somewhat logical.

Feel invited to start a forum thread for discussing what's fair game and what might be too overpowered!
