### ISSUE TITLE
[bug with Ae2 integration] me_interface.store(filter,dbaddress) function does not work

### ISSUE THREAD

**Issue by PizzaAddict** [MightyPirates/OpenComputers#2674]
![image](https://user-images.githubusercontent.com/34593536/34067930-f757586c-e275-11e7-982c-37e25ed17e12.png)
: test setup. the adapter has tier 3 database inside

![image](https://user-images.githubusercontent.com/34593536/34067935-0bfd5a28-e276-11e7-98bd-44fcd564cc74.png)
:test code

for test , the network has only 1 stack of dirt.
using store() method does not write database.

but writing database manually(by hand) works.
I might used this function wrong,but I think it's a bug...
oc version: 1.7.1.43
ae2 version: rv5-stable-3
modpack: https://www.curseforge.com/minecraft/modpacks/ftb-presents-direwolf20-1-12

**Comment by Xyxen** [comment]
This happens because [a couple of ItemStack comparisons didn't get updated across 1.11.](https://github.com/MightyPirates/OpenComputers/blob/40eb91d6b8f73d4aebf64d0b6dc7177b551a0662/src/main/scala/li/cil/oc/integration/appeng/NetworkControl.scala#L88-L89) Since that version, empty item slots are initialized with a singleton `ItemStack.EMPTY`. They're never null anymore, so those checks fail every time. Fixing those two comparisons resolved the issue for me.

**Comment by pkartner** [comment]
@Xyxen Do you know when this will be released?

**Comment by payonel** [comment]
@pkartner before xmas :) but it'll be on our jenkins server, not curseforge

**Comment by payonel** [comment]
fixed in 07911b6c011830c0c89c123f3c300a24891d18ec
will be official in our 1.7.2 coming soon
