### ISSUE TITLE
\r is treated as newline

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#269]
when \r is outputted, the terminal goes to the next line
This is bad if you have \r\n, because its treated as \n\n

**Comment by fnuecke** [comment]
Hmm, yeah. Changing the pattern `([^\r\n]*)([\r\n]?)` in text.lua to `([^\r\n]*)(\r?\n?)` should do the trick from what I can tell. If no-one proves that pattern to be borked that'll be in 1.3. Unless another terrible bug in 1.2 pops up I won't do another 1.2 release, though, so you'll have to patch it in there yourself.

**Comment by evg-zhabotinsky** [comment]
`edit.lua` shows `'?'` in place of `'\r'` when it is present. However, such files cannot be easily created from within the game as I understand.
The problem is that `read()` (and maybe `write()`) don't throw `'\r'` away when not in binary mode as they normally do. The question is if they really should do it.

**Comment by gamax92** [comment]
My test I just did with normal lua5.2 shows that the \r is still there when read.
The editor should probably be filtering out the \r's
