### ISSUE TITLE
I can't start the computer! And yes i have been following the tutorital! [BUG] + Fixed it!

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#27]
I have made a video about it:
http://vimeo.com/82692390
Ps. Start the launcher in adminstrator mode to fix it!

**Comment by fnuecke** [comment]
Please check/post your log. I'll be adding more immediate feedback if something goes wrong during startup in the next patch, that should make it easier to figure out what exactly went wrong.

**Comment by ghost** [comment]
i have the same problem :O

**Comment by ghost** [comment]
Log file: https://dl.dropboxusercontent.com/u/147351443/ForgeModLoader-client-0.log    @fnuecke

**Comment by fnuecke** [comment]
Thanks for the log, seems the libraries were missing / could not be extracted or something.
@enderossel check your logs, if it's the same thing install the VC2012 runtimes (as mentioned in the posts on MCF) and try what Dacexi suggests. If it's something else, please open a new ticket.

Edit: this surprises me by the way, since I expected the temp folder to be writable by anyone. I may have to change to extracting the libraries into the Minecraft folder or something...

**Comment by ghost** [comment]
i cant install vc2012 on mac so does it even work for mac or is it winodows only

**Comment by fnuecke** [comment]
Aside from the fact that you don't _need_ the VC2012 runtime on Mac (because they're Windows only, of course), so it doesn't matter that you can't install it, they are built into the Windows libraries since 1.1.0. Just to kill that misconception as quickly as possible.

So your problem is more likely related to the fact that the MacOS you're running is older than the one that was on the Mac Mini I used to compile the Mac library. Or has the system libraries in another place. Apple does stupid things, so it could be that, too. The Mac Mini is the only Mac system I can get my hands on, though, so I'm afraid I can't help you by building the library on an older Mac. Just to make sure, you _did_ try this in the most recent version, too, not an old one that didn't even have the Mac lib?

Either way, a future version of the Mod will probably have a fallback Lua implementation, lacking the persistence but at least make the mod usable for the most part on systems where the libraries aren't available.
