### ISSUE TITLE
event.push and event.pull may cause event lost

### ISSUE THREAD

**Issue by Kiritow** [MightyPirates/OpenComputers#2722]
According to the document, I have understand events are queued in an internal event bus. And event.pull() will get the available event from it. But how long can the event stay in the bus?
For example, 
```
event.push("ExampleEvent")
local e=event.pull("ExampleEvent")
```
This program will pause at the event.pull() call as it can't get event named "ExampleEvent". 
Another example,
```
while true do
    local e=event.pull("SomeEvent")
    doHeavyWork(e)
end
```
If "SomeEvent" happens, the program will call `doHeavyWork()`, which will take a long time (but will not cause too long without yielding error). And if another "SomeEvent" is pushed into the bus during `doHeavyWork()` , event.pull() will get stuck in the next loop.

**Comment by payonel** [comment]
Signals are never lost, but you may be dropping them. If you say `doHeavyWork` does not die due to TLWY (too long without yielding) that means it is yielding, and yielding pops signals. One of those signals is one that you care about apparently.

If you call `event.pull("A")`, then you are dropping all other signals until A is found. Event registers are still notified, such as listeners. To them, no signals are lost. But to your current process, you are ignoring everything until there is an A signal. The pending signal collection is a queue - if you have signals coming in an unspecified order then your code needs to respect that.

Sounds to me like you need to keep track of all `SomeEvent` signals. Perhaps your program needs a helper function that grabs the next event for you and collects and reorders them for you. Perhaps you need a `SomeEvent` queue that you buffer separately - so that during `doHeavyWork`, any `SomeEvent` you come across is buffered, and when you return to your outer while loop, you check that queue in order to procede.

If your program doesn't need to be sequential, I recommend using `event.listen` instead


low level answer

In order to avoid TLWY (too long without yielding), your program has to yield. Yielding pops an available signal

**Comment by payonel** [comment]
anyways, `event.push` definitely has no known signal loss, and `event.pull` DOES have the potential to "drop" signals as I explained; if you pull for `A`, then all other signals are dropped (to your context, but not to anyone else) and that is by design.

If you have further questions, please join us on irc and chat with me.
https://webchat.esper.net/?channels=oc

**Comment by payonel** [comment]
I should add to this, signals technically can be lost on the back of the queue if too many are buffered. The limit is set to 256 http://git.io/vNThZ

**Comment by xarses** [comment]
It seems you are using the event system as a queue, which it is not. As @payonel noted, as the events fire they fall off as soon as no active listeners. This is either by `event.pull()` or registering with `event.listen`.

I would set up a queue variable of my own and add events to it via `event.listen` callback and then loop over it as a worker in the main thread

**Comment by Kiritow** [comment]
Thanks. I have redesigned my event library and now it uses `event.listen` and `table.insert` 😆
