### ISSUE TITLE
[Idea] Font sizes

### ISSUE THREAD

**Issue by Steve505** [MightyPirates/OpenComputers#2736]
Hi there!
I like an idea of typing and printing text with different font sizes. For example, on our server I want to display info via. OC Screens and I haven't found a solution of headers and their sizes. Something like this:

### This could be a header.
_This is underline, made by gpu.setForeground() and term.clearLine()_
This is main text, formated in smaller size.

Is there any way to make it, or is it a "brand new" suggestion?

Thanks,
Jason505

**Comment by Techokami** [comment]
AFAIK the VT100 terminal standard (on which the video output of OpenOS is now based on) doesn't handle that...

**Comment by payonel** [comment]
Our fonts are a fixed size (and only can be single or double wide)
That's rather baked in and I am not interested in changing that.
As techokami said, we are trying to follow the vt100 model of things, though we don't support, nor plan to support, some of the font styles it can do (underlined, for example)

**Comment by Techokami** [comment]
So the closest thing you could do is use double wide characters for when you want big header text. Or pixel art it with the different graphical characters available in the character set.

Otherwise, if you *really need* something like this... why not make an addon mod that implements a different visual display system?
