### ISSUE TITLE
Issue with Aliases

### ISSUE THREAD

**Issue by brisingraerowing** [MightyPirates/OpenComputers#2737]
@payonel You mentioned that you tried to set up aliases for the Wireless Network Card, but seem to have messed it up. Looking at [these lines](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/common/init/Items.scala#L45-L46), I see the problem. The item name casing is incorrect for 1.12. 1.11 likely has the same issue.

Both item names need to be lowercased.

**Comment by payonel** [comment]
@BrisingrAerowing I think you are right. Can you help me understand why?

ben_mkiv is working on a mod, and apparently his code fails when it calls
`ItemStack wlanCard = Items.get("wlancard").createItemStack(1);`

He said: "changed wlanCard to wlancard which fixed my issue"

This is his bug: https://github.com/ben-mkiv/OCGlasses/issues/3

So it seems I have a case issue
I feel like any changes I make are just going to be guesses. Maybe what I need to change is the Proxy.scala referene to "wlanCard" to be "wlancard"

Here are some references to the wlancard spelling:

https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/common/Proxy.scala#L56
https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/common/Proxy.scala#L158
https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/common/init/Items.scala#L46

https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/resources/assets/opencomputers/recipes/default.recipes#L19
https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/resources/assets/opencomputers/recipes/default.recipes#L203

**Comment by payonel** [comment]
Also, this really needs to be fixed in the lowest version applicable. Please comment/review if this should be fixed in 1.11 first

**Comment by brisingraerowing** [comment]
Yup, the issue is in 1.11 as well. I manually fixed it myself in a dev version, and it works.

**Comment by payonel** [comment]
@BrisingrAerowing do any other case changes need to be made?

**Comment by brisingraerowing** [comment]
Not sure. I just changed those lines.

**Comment by TheCodex6824** [comment]
You all are correct, this happens because all the item names for oredict stuff / aliases were in the old style (i.e. "wlanCard") and newer versions tend to prefer all lowercase. To make a long story short you just have to update the aliases [here in Items.scala](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/common/init/Items.scala#L46), but here's a long explanation of what I could find for all the alias registrations everywhere for future reference:

- [Ore Dictionary Entry](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/common/Proxy.scala#L56) - This gets registered with forge like any other ore dictionary item, meaning that the name will be usable from strings in recipes and such. It will not register the alias in OC's item API.
- [Item Renames](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/common/Proxy.scala#L158) - This is only used when updating from a previous version where an item ID that existed in a previous version of OC no longer exists. It will lookup the old ID in the map and if found will replace the old ID with the new one (this is a forge event)
- [Item Alias](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/common/init/Items.scala#L46) - This is an alias for OC's item API, where it will [register a descriptor pointing to the proper item name for every entry in the map](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/common/init/Items.scala#L334). It will not register the alias outside the API.

**Comment by ben-mkiv** [comment]
guess i could change my code to use the oredict names and everything should be fine, no matter what oc release?!

**Comment by payonel** [comment]
@ben-mkiv this is marked for 1.7.2 -- which I will eventually get out. i'm working currently on AE compat issues

**Comment by payonel** [comment]
closed with 17d5355c00077e82cd86fb7b31082fcde485b238
