### ISSUE TITLE
Weirdness with Robots as Components

### ISSUE THREAD

**Issue by ZeekDaGeek** [MightyPirates/OpenComputers#2784]
At the moment Robots will only register as a component when directly next to a Computer Case, this isn't too big a deal unless you're using Server Racks where you can only have one accessible side of components. It would be nice if Robots were accessible as components when placed next to Adapters and possibly Chargers.

Also I don't know if this is supposed to be a feature or not but Robots don't seem to have accessible hard drives when next to a charger... Not sure if that's intentional or not.

**Comment by payonel** [comment]
limiting the robot-as-component is intentional, but I will investigate the feature balance of allowing adapters and chargers to see them as components as well

we've discussed adding some type of filesystem acesss, but no, there is no current feature for that

**Comment by xarses** [comment]
robots should have accessible filesystem if placed in a charger, but alas, I think that only works for tablets atm

I had no clue robots showed as a component next to a case, and it seems odd that they do. I don't have a quam with them showing up against a adapter un-scripted but I have quams with them randomly showing up on chargers ( being that they grow the component interface and robots randomly show up to charge all the time), being able to disable it on chargers (and preferably by default) would be a plus since its already an component.
