### ISSUE TITLE
Unable to use Robot API at boot

### ISSUE THREAD

**Issue by rahul-pisharody** [MightyPirates/OpenComputers#2787]
I have a service that overrides certain robot API functions. I wanted to use it at start using `rc enable` but putting a `require("robot")` in the file seems to stop it from loading at boot

**Comment by payonel** [comment]
i'm going to need a lot more information than this
what oc version? (full version name)
what api are you overriding?
what functions are you putting in place of the api?
how are you overriding them?
your rc script has require("robot")?
what is your rc script code?

**Comment by rahul-pisharody** [comment]
OpenComputers-MC1.12.2-1.7.2.67
API being overriden is this one: http://ocdoc.cil.li/api:robot
I'm overriding the up, down, forward, back, turnLeft, turnRight and turnAround functions to save the location of the robot after each movement. It's based off Jomik's location service in OpenPrograms, but he was overriding the move functions from component.robot.
I wanted to see if I could override these instead, but then it refuses to load at boot.
Code you can find here: https://github.com/ATaciturnGamer/OpenComputers-Path-Server/blob/master/robot/etc/rc.d/location.lua

Running `rc` after boot starts the service normally. But enabling it wont.

I realized just now that overriding the move functions instead would solve everything, since robot API is just a wrapper, but I wanted to know why this was happening anyways.

**Comment by payonel** [comment]
you're still leaving me with some assumptions. let me know if this is your repro
1. copy that location.lua to /etc/rc.d
2. run `enable location`
3. reboot

then "it refuses to load at boot"
does boot crash? do you have a crash report? does your code not work? how is it not working? how do you know it isn't working?

**Comment by rahul-pisharody** [comment]
Boot works fine. No crash report. I knew it didn't work because I opened up the interpreter to check if the functions were overridden, and they weren't.
Also, That file wont work by itself without the location API, but that's not the issue. 
Here's how to reproduce the issue:
1. Create a lua script(say test.lua) at /etc/rc.d and initialize a count variable to 0 (like in example.lua). In the start function increment the value and print it.
Something like:
`local count=0`
`function start()`
`  count=count+1`
`  print(count)`
`end`
2. Enable using `rc test enable`
2. Reboot
3. After boot, type `rc`. It should display 2.
4. To the same file, add `local robot = require("robot")` to the top
5. Reboot
5. Typing in `rc` after boot only displays 1, which means it didn't run at boot.
That's how I figured it out. I commented out everything from the location.lua file except the require statements and added the count variable.
I'm pretty new to posting issues, so please pardon my ignorance.

**Comment by payonel** [comment]
the robot library you are trying to hijack is a little unlike a normal library - but almost normal (read on)

Libraries loaded via `require` are defined in /lib (or elsewhere in the package path)

But the robot library is actually stored on a read-only filesystem that is provided by the robot component itself. After the robot's readonly filesystem is mounted, it might be found at (e.g.) /mnt/3fe/lib/robot.lua

When the robot component mounts its read-only filesystem, openos runs the "autorun" for that filesystem. The robot component read-only filesystem's autorun creates a symlink to its robot.lua library IN /lib (if you run `ls -l /lib/robot.lua`, you'll see the robot.lua file there is a sym link)

Some things run directly in the boot process, and some things run in response to system signals
Filesystem autoruns run indirectly during boot, in response to system signals
RC is run directly as part of boot

Thus, RC runs BEFORE the robot filesystem has mounted

Thus, when you try to require("robot") in your rc program, it actually crashes (aborts). RC catches this failure (silently, I talk more about this in a bit), and you never knew it tried to start, but failed.

The next time you run `rc` manually, the robot filesystem has mounted and your 2nd attempt to require its library is successful

three things to consider for this ticket
1. OpenOS will continue to load rc directly, and will continue to handle filesystem mounting indirectly, and the robot readonly filesystem will continue to be the host of the robot library, sym linked during its autorun.
2. Thus (due to item 1) you will have to work around this. You can mitigate this problem by delaying your own rc daemon by using signals yourself. OpenOS emits an "init" signal at the end of its boot process, if you wait for that signal you will execute after all filesystem autoruns (Signals pop from a queue, in the order they are pushed, and the filesystem signals are pushed before the init signal is pushed)
```
local event = require("event")
function start()
  event.listen("init", function()
    local robot = require("robot")
    -- inject all the things you want in the robot api
    return false -- returning false from an event handler will unsubscribe itself (i.e. stop listening)
  end)
end
```
This code isn't perfect -- if you use this as-is you won't be able to "restart" your rc daemon because the "init" signal is not going to fire again until the next boot. If you need to be able to stop and start your daemon (or for the start function to run the injection code) you'll need to add some extra code.

3. normally when things crash in the kernel, I would like to see the crash details in /tmp/event.log -- but the rc engine does not report errors there. I will close this ticket when I have added logging for failures in rc like this. It's a minor change, but helpful

**Comment by rahul-pisharody** [comment]
Oh, thanks for clearing this up. 

For now I think I'll use component.robot, but I'll keep this in mind next time I use it for an rc daemon.

**Comment by payonel** [comment]
heh, well, the convenience methods in openos to access "primary" compoents via `component[component_name]` also might not be available by the time your rc daemon starts up (for a very similar reason). you can use `component.proxy(component.list("robot")())` to deal with that, though

**Comment by rahul-pisharody** [comment]
Hmm... seems to be working, though.

**Comment by payonel** [comment]
well I said "might" specifically because I hadn't doubled checked the "primary" load order :)
