### ISSUE TITLE
[1.12.2] OC causes server crash

### ISSUE THREAD

**Issue by Morpheus1101** [MightyPirates/OpenComputers#2790]
The pack i've updated did the following update OpenComputers 1.12.1-1.7.1.43 > 1.12.2-1.7.2.67 howeevr previously the server and client worked perfectly fine, however now it seems its cracking and crashing the server, but the crash log + server log say 2 different things.

Crash log @ https://gist.github.com/Morpheus1101/a7f2369304d5866e5da9b75710b3d697 (mentions nothing about OC)

Server Log Line106 @ https://gist.github.com/Morpheus1101/ae6ea972a85f3b1ce13e5eb8888e23ee

**Comment by payonel** [comment]
you can see from your server crash log that it continues to run the world after that OC exception is reported. Note that we do not force the server to stop on that `LuaRuntimeException`, we catch it, and we do not throw it again. We are only logging that the lua state could not load. This could happen for various reasons, but it is not the reason your server is stopping. Note also that in our 1.7.1 -> 1.7.2 version change we are using lua 5.3 by default, but this shouldn't cause lua states to fail to load, and in fact existing machines in your world should continue to use the previous lua version they were using (5.2 or 5.3). But again, this wouldn't cause the lua state to fail to load. A bad server stop could cause the lua state to have persisted incorrectly, just as an example. I do not see a bug to fix in this case.

In your server log continued at line 163, you see the SAME exception (as in the crash log) that does appear to stop the server, that being: `Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/model/IBakedModel` Immediately following that stack you see that the server is stopping because of it. That appears to be your issue. Maybe this is your issue? https://github.com/rwtema/extrautilities_old_issues/issues/1342

**Comment by Morpheus1101** [comment]
I suspected EXU2 was involved and crash report mentioned ticking entity as reason, but i'll go visit EXU2 and see what i can get from over there, thanks for the response.
