### ISSUE TITLE
Invalid glyph char code detected in font.hex

### ISSUE THREAD

**Issue by josephcsible** [MightyPirates/OpenComputers#2799]
I receive the following errors from OpenComputers in the log when starting Minecraft:
```
[22:45:14] [main/WARN]: Invalid glyph char code detected in font.hex. Expected 0<= charCode <10000, got: 1D300
[22:45:14] [main/WARN]: 87 total invalid glyph char codes detected in font.hex
```

I'm on OpenComputers 1.7.2.67, Minecraft 1.12.2, and Forge 2641. This happens without any other mods installed.

**Comment by payonel** [comment]
yeah, that's not really a bug, it's a warning :)
we're using font.hex generated from https://github.com/asiekierka/funscii which supports a much larger range of unicode. Due to limitations we have with Java, we cannot support codes >= 0x10000. I added that warning as a reminder in case one day we ever implement our own code converter and stop using java ... maybe a nice //TODO would have been better :)
