### ISSUE TITLE
Unable to install OPPM [OpenComputers-MC1.12.2-1.7.2.67]

### ISSUE THREAD

**Issue by HonestyK** [MightyPirates/OpenComputers#2813]
So I've just installed this mod today and tried to get some other programs to look at. Ended up with this error message:

![oppm cannot install](https://user-images.githubusercontent.com/13384644/38800579-06cc2784-41ab-11e8-9fe1-a43122ac2ab1.PNG)

**Comment by payonel** [comment]
i can see from your error for option (1) that your / is (ro), and oppm tries to create `etc/oppm.cfg` which probably is `/etc/oppm.cfg`, and thus fails [readonly fs]
You'll need to install oppm when / is rw

**Comment by thiakil** [comment]
@payonel they appear to be trying to install it to `/small`, not `/`

**Comment by payonel** [comment]
oppm requires / for oppm.cfg
the `<package>` you are installing is the oppm package itself, but oppm forces oppm.cfg to go to /etc/oppm.cfg -- oppm itself ignores the package path (in this case, /small) for the oppm.cfg

The reason is that oppm let's you install packages anywhere, but the core oppm.cfg forces itself to /etc/oppm.cfg, that's the one places all package info is recorded

I'll bring this up with @Vexatos to see if he feels we should respect the additional `install` meta data given to oppm's `.install` . we could make an exception for the `.install` call

**Comment by HonestyK** [comment]
Thanks for the replies! Made me pay more attention to where OPPM should be installed to.

I realised that I needed to install OpenOS properly first (it was just inserted as a disk inside the computer case and I assumed that's how OS installation worked). Installed OpenOS into /small, then chose to install OPPM into OpenOS and it finished without errors.

I only just started using OC yesterday and never programmed with Lua before, so thanks for being patient with me!

**Comment by thiakil** [comment]
@HonestyK I believe payonel is saying that given that it gives you the option to install it to a specific location, that it should at least be considered to be able to install there.

e.g.
- Install openOS to `/blah`
- Install OPM to `/blah`
- Reboot to system that has both
