### ISSUE TITLE
Problem with adapter using inventory controller upgrade

### ISSUE THREAD

**Issue by Willcenx** [MightyPirates/OpenComputers#2821]
I put inventory controller upgrade in adapter and placed chest right near it. Then i tried to call method component.inventory_controller.getStackInSlot (side, 1) but it responses to me nil "no_inventory" with any side i give it as first argument. Can somebody help me pls? Sorry for bad english if it is.

**Comment by payonel** [comment]
oc version?

**Comment by Willcenx** [comment]
1.7.1.1127

**Comment by Willcenx** [comment]
1.7.1.1127

**Comment by payonel** [comment]
we're on 1.7.2 now, retest there https://minecraft.curseforge.com/projects/opencomputers/files

**Comment by Willcenx** [comment]
that does not solve my problem

**Comment by payonel** [comment]
you retested with 1.7.2 and it still fails?

**Comment by Willcenx** [comment]
i didnt. i just can't update mod because i play on a server which is not mine. so am i right saying that it is a bug and i can't do anything in this situation?

**Comment by xarses** [comment]
Its always useful to identify
* what version of OC you are using
* what version of forge you are running
* what version of minecraft you are running
* if any other mods might be involved.

Further its helpful to identify
* specific steps to took to get to the errant state (yes even if its obvious)
* expected results
* actual results

In your case since its an inventory problem, are you using a mod that offers player claim/chunk protection? If so, its likely the problem and you need to enable fakePlayer support. see #2816, #2730, #2706 This can further be seen if you move the setup to unprotected chunks and repeat and don't have the same error.

**Comment by payonel** [comment]
I fixed inventory controller issues in 1.7.2, and i cannot repro this myself - feel free to reopen if you can retest with latest versions

Also, just saying "that does not solve my problem" in answer to us asking you update to our latest version is pretty disappointing. You should ALWAYS expect any mod to only support bugs reported against their latest version.
