### ISSUE TITLE
GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread

### ISSUE THREAD

**Issue by tiger39m9** [MightyPirates/OpenComputers#2829]
[RuntimeException.txt](https://github.com/MightyPirates/OpenComputers/files/1976791/RuntimeException.txt)
while playing the game this will pop up at any time and freez my game

**Comment by payonel** [comment]
i will need more specific repro steps in order to be of much help
1. does this repro with no other mods (unlikely, ClassTransformer is involved)? you'll have to do a binary search of including+excluding other mods to help us understand which of your mods causes the conflict
2. you say "at any time", but that is quite difficult for us to repro and ever prove it is fixed. I need to find what triggers it. Something you do in the world? Loading chunks with computers? Creating computers? Does it happen in a new world? Does it always happen within the first 5 minutes? Does it happen in single player or only multi player. These are all just examples -- make a good bug report and help us see exactly when it happens so we can focus on fixing it.

**Comment by tiger39m9** [comment]
in the text file has full error log with all mods list with the dw20 pack

**Comment by tiger39m9** [comment]
sometimes it dose when I don't do a thing when it comes just the game will show about a sec then freez

**Comment by tiger39m9** [comment]
single player

**Comment by tiger39m9** [comment]
I did add 2 extra mods that the dw20 pack don't have 1 ender io  2 extra cells 2

**Comment by tiger39m9** [comment]
I don't know how to do a binary search

**Comment by payonel** [comment]
I'm sorry but this is not a bug report. Please explain carefully, in detail, what are the MINIMAL steps necessary you do to cause this crash. Please don't make 5 separate comments on this ticket to explain the repro. Do you know what a repro is?

> sometimes it dose when I don't do a thing

This makes no sense what so ever. What thing? Also, [does]

> when it comes just the game will show about a sec then freez

When what comes?

>"the game will show"

What part of the game? The game menu? The single player world?

Also, [freeze]

There are some BASICS of reporting a bug that you are missing.
How often does this happen? Can you repro this every single time you play? Does it always happen under 10 seconds? Under 5 seconds? Under 1 hour? Give us the MINIMAL repro.

Do you have to move?
Does it repro in a new creative flat world?
Does it repro on your machine with OC only?

Test this, find the minimal set of required conditions necessary to cause this crash to happen.

Binary Search for the conflicting mods:
Remove all the mods, except for OC only. Does the crash happen?
Add in half the mods, Does the crash happen? no? Try the other half?
Each time the crash happens, remove half the mod list and try the other half if the crash doesn't happen.
Eventually, you'll only have OC and one other mod that conflicts.

you don't have to use the binary search method to find the conflicting mod, but it is a fast way of doing it. Does this crash happen when you play with only OC added? If not, what other, single one mod has to be present for the crash to happen. Don't give us a list of 100 mods you are playing with. Tell us the ONE mod that doesn't play nice with OC

**Comment by thiakil** [comment]
More importantly I'd suggest first removing OC and testing if the issue persists - the stack trace doesn't call out any mod specifically, just that someone modified a list while it was iterating.

**Comment by payonel** [comment]
no repro
