### ISSUE TITLE
[OC 1.3] Creative Tier Robots

### ISSUE THREAD

**Issue by Techokami** [MightyPirates/OpenComputers#284]
Quite simply, having a Creative-tier robot made from a Creative-tier case, with an appropriately high complexity limit. Would be very useful for testing, or just having fun!

Also, shouldn't the color scheme of the robot's body match the tier of case used? (Gold robot for Tier 2, diamond for Tier 3?)

I'm really liking the things in OC 1.3 so far, keep up the good work :)

**Comment by fnuecke** [comment]
The colors were and are based on the experience of the robot. I did think of switching to tier based, but decided to keep it as is (also because it's a good test for rendering hooks in upgrades :P)

I'll think about the creative tier support. If so it'd probably also make the assembly instant or something like that. We'll see.

**Comment by Techokami** [comment]
Awesome, thank you!
