### ISSUE TITLE
Robots burn my server

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#285]
Hello.
Some players on my server try to launch too many robots and call a lot of laggs. Can you optimize it?
![2014-06-01_20 21 03](https://cloud.githubusercontent.com/assets/5736157/3161128/96181b06-eb28-11e3-937e-e6c8f535620f.png)
![2014-06-01_20 24 23](https://cloud.githubusercontent.com/assets/5736157/3161129/96382cf2-eb28-11e3-9ace-652f70e8f2f3.png)
![2014-06-01_20 26 22](https://cloud.githubusercontent.com/assets/5736157/3161130/963b009e-eb28-11e3-9fa6-15d88273432d.png)

**Comment by Wuerfel21** [comment]
Try setting the threads in the config down

**Comment by fnuecke** [comment]
Well well, nice army of robots... the last time I did some profiling there were no obvious 'bottlenecks', so I'm guessing it's just a matter of too many chunk updates being triggered too quickly. Reducing the number of threads probably won't do that much, since those run parallel anyway. You might want to focus on tweaking the delays (`robot.delays.*`) instead, since those control how often stuff has to happen synchronized to the main server thread (i.e. actual interaction with the world happens, which is what can result in noticeable lag). In particular, try upping the place and swing delays a little.

If others have a problem with players overdoing it, I'll look into limiting the number of active robots per player.
