### ISSUE TITLE
remote terminal block

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#288]
Basically, a block doing the same as a server case

**Comment by Wuerfel21** [comment]
I mean a block which allows a normwl computer use the terminals.
Maybe as a robot upgrade too

**Comment by evg-zhabotinsky** [comment]
~~Since robots are headless now (no built-in terminal), they do **really need** remote terminal support.
Alternatively, built-in support for something like ssh or telnet can be implemented.
The second alternative will also solve problem of uploading (or downloading) files to robot (they are not going to have swappable floppies as I understand)~~

**Comment by Wuerfel21** [comment]
They in fact can have up to 3 floppys(the bottom 3 slots in the assembler) also, you can add a screen and keyboard in any t1 upgrade slot

**Comment by evg-zhabotinsky** [comment]
Thanks. I didn't notice that tier 1 screens are now tier 1 upgrades.
UPD: and disk drives are container upgrades. How obvious!
UPD2: Well, at least ssh is more realistic :)

**Comment by fnuecke** [comment]
But the servers kinda need something to make them special except for just having more slots ;-)
Also, more likely is something like #204 to be added.
