### ISSUE TITLE
Computers shutdown on chunk unload

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#2890]
When chunk are unloaded, computers are shutted down. It's not a yielding problem, just it is shutted down and monitor are frozen.

Minecraft: 1.12.2
Forge: 2732
OpenComputers: 1.7.2.67

**Comment by RedstoneParkour** [comment]
What OS are you using?

**Comment by MEXAHOTABOP** [comment]
we have same problem with minecraft 1.10.2 forge 2511 OC 1.7.2.170 (linux server java 1.8.0.172 unstable gentoo)
no errors in logs related to OC 
computers/robots not always shutdown sometimes they continue to work afther chunk offload 

in previous session almost year ago with almost same mods (except we added forestry, galacticraft and tinkers construct) and same forge versions we dont have this problem 

i checked with old OC and i have same problem so probably its because something was updated in system

**Comment by Faeranne** [comment]
Computers persist by saving their state when unloaded (close the game or unload a chunk), but don't actually run.  Unfortunately persistence requires support from the architecture itself.  The native Lua arch supports this, but doesn't always get used.
You can check if you are running the native lua arch by running `computer.getArchitecture()` and if it returns `Lua 5.3` or `Lua 5.2`, then you are running the native arch.  If it returns `LuaJ` then you are running the non-native version and wont get persistence.
If you aren't running lua then you'll have to ask on the issues board of the mod that added the architecture you're using, as they would have to add persistence support.

**Comment by payonel** [comment]
I have fixed various "frozen" computer bugs in our dev builds
and I cannot repro others (i've done TONS of testing)

You can retest with latest dev builds: https://ci.cil.li/

But I will also need a copy of the world to actually see the repro in order to fix it. You can either link the world for download here, or pm me a download link in oc on esper.net
if you don't have a convenient place to upload the world to, pm me, I can provide a cloud folder

**Comment by payonel** [comment]
closing this as old with no repro
we know some users are still experiencing this issue, but if you are reading this, and you have a repro of this issue, please open a new ticket with detailed steps that I can take to repro it. If you can't repro it yourself in a new world, nor will I be able to. Once you have a repro, make the new ticket. Please don't make a new ticket about this issue without a repro. Thanks
