### ISSUE TITLE
Unable to use fishing rod with robot

### ISSUE THREAD

**Issue by bananaabandit** [MightyPirates/OpenComputers#2897]
Hi.

Been having a problem using robot.use with a fishing rod.
The bobber does not appear for some reason.

I am playing in a singleplayer world on the Direwolf20 1.12 current release using opencomputers 1.7.2.67.
I can use other items eg bucket+throwing eggs but fishing is causing me issues.
Is this a known issue or am I doing something incorrectly?

Thanks in advance!

**Comment by Asioron** [comment]
Fisherman’s robots have long been learned to assemble using existing capabilities and components. Can read http://computercraft.ru/topic/1393-robot-rybolov/

**Comment by JujuLynx** [comment]
I've looked over that page quite a bit and I can't replicate those results whatsoever. The only thing I can think of is that since the post is from 2016, something's changed over the years.

The robot appears to "swing" the rod but a line never ejects, nor does a bobber appear.

I've just come to accept that robots can't fish.

**Comment by JujuLynx** [comment]
Okay so an update to my last comment.

I finally got around to actually doing some more testing. I even resorted to getting MC 1.8 and the version of OpenComputers from then that Russian tutorial was published.

I ultimately got it working, so I can confirm that the fishing rod DOES work in 1.12.2. It just seems the exact workings of the fishing rod are very specific. I'm not sure of those specifics as of yet, but at least robots can in fact use fishing rods.
