### ISSUE TITLE
Terminal glasses

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#293]
Next Flashing idea: completely modular Terminal glasses!
Basically a screen in your face(however, without background) which is controlled by the same means as a remoteterminal(a server or a #288 ).
it all starts with crafting one of the various glass-cases(different colors and styles(stored in NBT)).
You can now wear it for pure aesthetics or put it in an assembler and add a screen and upgrades and BOOM you got it! Now you can link it and put it in your helmet slot! (Charging it would be a good idea!(i2c energy pack compatibility would be cool(possibly in open component)))
Possible upgrades:
Orientation - get the position of the player
Helmets(yes, mod helmets in open components would be cool) - provide armor
Keyboard - enter commands prefixed with some special char, and a event will be triggered)
Capicitor - energy, duh...
Biometer(new!) - get player stats like health, hunger, saturation, armor, potion effects, experience
geolyzer - geolyze the area around the player

Huh, what a long wishlist :-)

**Comment by Wuerfel21** [comment]
A standalone biolyzer could analyze the player on top of it

**Comment by Wuerfel21** [comment]
Sorry clicked wrong

**Comment by evg-zhabotinsky** [comment]
I think it should technically be a remote terminal, possibly communicating with a laptop you carry in your inventory.
About the way this thingy might be interacted with: wear it in helmet slot to see the display overlay. When opening inventory, show that display together with inventory, crafting grid and armor slots to allow input. This does not need to be implemented if the following feature is implemented:
The feature I always wanted - a way to use keyboard (or just some keys chosen using GUI or programmatically) with this thingy _without opening GUI_ while still being able to walk or look around - like touchpad built into Google glass. I thought of remote controls and other such things before, but this idea seems to be much better because it also includes HUD. However, input might be implemented as an extra item you hold in your hands to avoid problems like being unable to open inventory to take off this gadget because it overrides 'e' key.

**Comment by Wuerfel21** [comment]
add a keyboard and type something like "++foo bla whop" in cat and an event will be fired like:
"Command", address, "foo bla whop"

**Comment by Wuerfel21** [comment]
Flashing idea: biometer should fire an event when the player dies

**Comment by fnuecke** [comment]
This actually sounds like a great addon ;-) The ideas are cool, but it's a bit too complex to fit into my schedule right now.

Combining it with a laptop or so could be a nice touch, too. In fact, one might even go so far as to make certain items in the inventory components visible to a laptop... wait, this is getting too much like MPS. Oh, here's an idea. Make this an addon for MPS :P

**Comment by Wuerfel21** [comment]
_gets hopes up for 2.0_

**Comment by TorakWolf** [comment]
You can use openperipheral terminal as components, and receive messages as events, just like with computercraft. At least with the latest versions. Ah, and you can use the sensor too, and get x,y,z and facing positions of players and mobs. I am thinking about one turtle folowing me and giving me player and mob data over their heads, muehehehehe.

**Comment by fnuecke** [comment]
In OC 1.3 + latest OpenComponents builds OpenPeripherals' glasses seem to work quite well. So until someone wants to make an addon for OC like this, you can go back to using those ;-)

**Comment by marcin212** [comment]
I and @magik6k created OpenGlasses http://oc.cil.li/index.php?/topic/351-mc-1710oc-140-openglasses/
