### ISSUE TITLE
Drone/Robot do not expose inventory

### ISSUE THREAD

**Issue by nzhook** [MightyPirates/OpenComputers#2936]
OC Version: 1.10.2-1.7.2.170 (latest on Twitch)
MC Version: 1.10.2

Drones and Robots cannot interact with the others inventory correctly.
eg. 
drone.suck() can pull an item out of a robot. but robot.suck() fails in all directions
drone.drop() will drop on top of the robot (not into the robots inventory)
An Inventory_controller upgrade returns no_inventory for every action

Would it be possible to expose the inventory of both? (possibly to everything not just other robots/drones)

**Comment by nzhook** [comment]
Also of note, drone.suck() pulls from the robot's equipment slot rather than the storage. I was going to report this as a separate issue but it should be resolved by exposing the inventory correctly as the code could then select which slot to pull from.

**Comment by payonel** [comment]
This was a tricky problem to "fix".
Let me please share my sympathy! Accessing the robot inventory from the outside does not have the same behavior from the inside. And this is intended, and not intuitive! But we have good reasons for doing this.

I have done my best to explain all of these details in our wiki (I just updated it)
I'll give a snippet of those details here in this comment. But if you would like to read more, please visit: https://ocdoc.cil.li/api:robot and read the slot alignment section as well as the text under the `drop` method.



> OC Version: 1.10.2-1.7.2.170

Note that this behavior is common for all versions of OC, 1.7.10 through 1.12



> drone.suck() can pull an item out of a robot. but robot.suck() fails in all directions

This is working fine for me. This either was fixed since you've reported this, or you might be using the robot api suck which actually calls component.robot.suck(sides.front). Our inventory methods are now sided (they take a side argument). If you are above an inventory, you'll want to suckDown (via robot api) or suck(sides.down) (via component api). Also, you cannot suck slot 1 from above, but only from the right side of a robot, because slot 1 (from an outside observer) is the first toolbelt slot. This has now all been documented.




> drone.drop() will drop on top of the robot (not into the robots inventory)

This sounds like you are using the robot api (from our openos library, /lib/robot.lua, when you `require("robot")`, which has a handy wrapper methods. Again, I've documented this on our wiki page). I made this SAME mistake, and spend time trying to debug why drop was not working. It is because our robot api drop is actually calling component.robot.drop(sides.front), and you are dropping the item in front of the robot, and not below.

With a chest, or robot, in front of you, robot_api.drop() works just fine.

> An Inventory_controller upgrade returns no_inventory for every action

I also hit this problem, but then realized I was testing with creatix, our creative robot. The robot itself is not in creative mode, and requires creative mode access. Thus it can get blocked when trying to access the inventory of another creatix (creative robot). I could not repro any problems with the inventory_controller when using normal robots.

> Would it be possible to expose the inventory of 

We are already sharing nearly all methods between drones and robots, but you may have been using the openos robot api. See https://ocdoc.cil.li/component:drone#Base%20Methods for methods that are specific to drones, and https://ocdoc.cil.li/component:robot#Base%20Methods for methods that are specific  to robots.
