### ISSUE TITLE
Robots using Chisel & Bits negative patterns causes extreme server lag

### ISSUE THREAD

**Issue by natedogith1** [MightyPirates/OpenComputers#2944]
Mods: chiselsandbits-12.18 and OpenComputers-MC1.10.2-1.7.2.170

When a robot uses a chisel & bits negative pattern, it causes serious server lag.

To reproduce:
1. Creative a negative pattern of a single bit (4095 bits empty, 1 bit set)
1. Place the pattern in a creative robot's tool slot, place a diamond chisel and a bit bag in the robot's inventory.
1. Place a block in front of the robot
1. Enter lua, and run "component.robot.use(sides.forward)"
1. The server lags for about 20 seconds, and the negative pattern and chisel swap rapidly
1. The negative pattern was properly applied
1. The chisel is undamaged and the bit bag is empty

Also, it seems most of the chisel and bits stuff isn't usable (returns true, but doesn't do anything).  This includes a single bit giving (true, "item_placed") and patterns (with a bag with enough bits) giving (nil, "-1") (which I didn't know was an option).

**Comment by payonel** [comment]
good news! This doesn't repro anymore :) we must have fixed it. thanks for reporting! We have definitely improved our use() code on the robot since build 170, we've have 25 updates to our 1.10 branch, try out our latest builds and let me know if you still have issues.
https://ci.cil.li/job/OpenComputers-MC1.10/
Our next release, 1.7.3, will officially have these fixes
