### ISSUE TITLE
An api/event to determine if a tablet screen is currently "on".

### ISSUE THREAD

**Issue by ahallrq** [MightyPirates/OpenComputers#2951]
As the name suggests, the ability to detect if the player is currently using the tablet with the display currently open. A couple possible use cases I could think of are players being able to program their scripts or programs to go into some sort of power-saving mode if they aren't currently using it or to alert them to particular events (e.g making the tablet beep if they get a message in a chat script).

**Comment by payonel** [comment]
after some further review of the code, this is not a trivial feature request. The issue is that server side, we are not creating a screen container (though yes, client side there is a screen set on the player gui). Thus, from an api perspective, we do not know if the player is current actively using the screen or not. We have a couple of options such as handling this api through a network call to the client, to check if the client has the gui open, or trying to keep track of open and close actions on the screen. I think either is a bit messy to be honest (the 2nd option has a lot of potential to provide false positive and false negatives)

I'll leave this open for adoption for now, but I'm personally not interested is adding this features given how things work currently.

**Comment by payonel** [comment]
close for low interest and high cost
