### ISSUE TITLE
AE2 Integration really TPS intensive

### ISSUE THREAD

**Issue by Keridos** [MightyPirates/OpenComputers#2964]
Using Opencomputers 1.7.2.67 and AE2 rv6-stable-2.

The performance of the following program seems to be really bad. Without the os.sleep() calls in the loop this program manages to increase the tick time by over 20ms per tick on its own. Something in either my program or maybe the integration of how AE2 stuff gets called by OC is really badly optimized.

https://gist.github.com/Keridos/cc440ae8d3fbc5862f84538565cd3d3c

**Comment by payonel** [comment]
I don't think the crafting code has changed much after that release build and our dev builds, but it would be good to retest this with our dev builds

also, please assist us by narrowing in on the call that is causing the trouble. Determine if we are allow you to call it too often (hundreds of times per tick) or if it takes a long time per call.

I would like to see a bug report that is just:
```
while true do ae2.api(args) end
```
and know that calling that once causes a large drop in tps, or that we're letting you call it a million times

**Comment by Keridos** [comment]
How would I proficiently tackle narrowing that down?

**Comment by payonel** [comment]
I appreciate your patience with the issue you've found, and I would like to fix the issue. But there are hundreds of issues, and plenty of things I spend my time tracking down. So any work you can do to minimize the bug report would be helpful.

You linked a large script of code. Find the ae2 api calls, and them them individually to see which (perhaps all) cause tps lag. Reduce your test script to repro this bug to the true minimum of code necessary. Just pasting all of the code does not provide for us a narrow perspective of what the problem is.

**Comment by payonel** [comment]
it was reported (thanks @Keridos ) that this is due to calling `getCraftables`

**Comment by payonel** [comment]
@Keridos i've tested caling getCraftables() in a tight loop and I don't see tps drops. How many craftables does your system have?

**Comment by Keridos** [comment]
Should be around 150

**Comment by thiakil** [comment]
I've had a bit of a dig,

1. each call to `getCraftables` (filtered or not!) runs private `allCraftables`
1. for each item `allCraftables` returns, it queries the network for all patterns available and grabs the relevant output stack to get its size (ae2 limitation - their system doesn't care about that until the crafting calculation, which is done off-thread)

I can see a way to push (2) into `NetworkControl.Craftable` so that it's only done if `getItemStack` is called
- requires some extra fiddling about the saving of the `IAEItemStack`; currently serialises as standard ItemStack, but could have zero size once pushed
- would mean that the `getCraftables` filter won't handle size

So for now, @Keridos consider doing the craftable filtering in your Lua, instead of using the argument.

I'll probably have a stab at this Soon&trade;, unless someone else steps up in the meantime or size filter is a blocker.

**Comment by thiakil** [comment]
Well, even worse, while using breakpoints I found it does the query in (2) *twice*

**Comment by payonel** [comment]
i very much blame scala for this. this code pattern in c# would not resolve all items of `allCraftables` each time, but only when serialized, applying the filters in each iteration - similar to a stream of operations.

**Comment by Keridos** [comment]
o/ finally fixed 👍
