### ISSUE TITLE
setBundledOutput not working with EnderIO cables

### ISSUE THREAD

**Issue by MichaelCampbell2** [MightyPirates/OpenComputers#2998]
I was under the understanding that EnderIO conduits were compatible with OpenComputers 1.7.3? I am currently running OpenComputers 1.7.3.146 (as can be seen in the picture bellow) but I am unable to use them), and Forge version 14.23.5.2768 on the Minecraft Stoneblock modpack (i added OC manually through Twitch launcher)
![image](https://user-images.githubusercontent.com/45729677/49695284-b146ed00-fbe8-11e8-9830-ebb291b4e617.png)
This is the code that I am using in an attempt to make it work (literally the smallest amount of code in an attempt to get it working):
![image](https://user-images.githubusercontent.com/45729677/49695296-d2a7d900-fbe8-11e8-81bd-194e60f33696.png)
And here is my setup:
![image](https://user-images.githubusercontent.com/45729677/49695357-c7a17880-fbe9-11e8-9759-c1974df5deb7.png)
and the actual computer its self 
![image](https://user-images.githubusercontent.com/45729677/49695383-1ea74d80-fbea-11e8-9d44-70ce4a6692c0.png)

Am I doing anything wrong? or has the bug not been fixed?

**Comment by payonel** [comment]
if you open the ender io redstone conduit (the configuration gui), you'll see that you can select a color. This is because our redstone devices don't implement the ender io interface that their cables require for bundled interop, and that's because ender io isn't providing a public interface nor capability we can use. So, we're doing all we get some bundled redstone options. This isn't going to happen in the 1.12 timeframe, btw
