### ISSUE TITLE
Monitor Swap Bug

### ISSUE THREAD

**Issue by TChapman500** [MightyPirates/OpenComputers#3008]
This bug has been tested with Tier 1 on one side and Tier 2 on the other.

This bug occurs when:  (1) Two computers are connected to each other via a disk drive between them (it does not matter if they are connected directly to the drive or via cables).  (2) The computers are connected to a common power source via a power distributor.  (3) Each computer is connected to a monitor via a cable (going behind and up so that the keyboard is on top of the case and in front of the monitor).  And (4) the disk drive, power distribution system, and monitors are all on separate networks.

To clarify, the power source and power distributor are on one network by which both computers are attached, the disk drive is on a second network by which both computers are attached, and each monitor is on a separate network connected to their corresponding computer cases (with no direct connection between monitors).

When the network is configured in this manner, the computers may swap monitors.  Giving each computer its own disk drive so that they are not connected together via the disk drive fixes the issue.

**Comment by TheCodex6824** [comment]
If I understand your setup correctly, I think this is working as intended. External components like disk drives will pretty much have the same effect as a cable in connecting networks together. If you really wanted to (and you don't go over the component limit), you can use lines of disk drives, monitors, or any other component instead of cable to connect things together. Because of this, the monitors are actually on the same network so the GPUs in the computers will randomly pick one to use.

**Comment by payonel** [comment]
yep, this is not a bug. both machines are seeing all the components, and both screens. You should consider it random which screen will load when you start a computer and they could swap on reboots.

**Comment by TChapman500** [comment]
So the computer cases are meant to act like cables too?
![2018-12-24_14 12 37](https://user-images.githubusercontent.com/4523649/50405714-d447d400-0786-11e9-969c-2ab3ddaae334.png)

**Comment by payonel** [comment]
yes
