### ISSUE TITLE
itemDamageRate Do not Work

### ISSUE THREAD

**Issue by LyingCak3** [MightyPirates/OpenComputers#3041]
Hello,

I recently installed opencomputers and wanted to make it so that item took no damage.  After reading through the configs I found "itemDamageRate", which the configs states that when set to 0, item take no damage.  After setting this value to zero, my items still take damage while be utilized by robots.

Thank you for your Time

**Comment by payonel** [comment]
our code for this hasn't changed, it still works in 1.7.10 and doesn't in 1.12 (i assume you're on 1.12)
note that you didn't give the mc version nor the oc version. which you should always do in bug reports

apparently this is no longer sufficient: https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/server/agent/Player.scala#L490

**Comment by LyingCak3** [comment]
You are correct, I am running on 1.12, and running version 1.7.3.146 of opencomputers, my apologies for not providing that information.

**Comment by Dead2** [comment]
I found this issue because I have a problem where the default itemDamageRate is not being respected, so a robot running dig does 1 damage to the tool for every block, this makes for a very expensive digger. I suspect this is also how it works for the OP.
I'd say this makes tool-wielding robots practically unusable in 1.12.2, and might possibly warrant more than a "bug-minor" label..?

I am running MC 1.12.2 and OC 1.7.4.153

**Comment by BurningCole** [comment]
This still seems to have some issues, When breaking blocks the probability for durability to be used seems to be 50% instead of the value in the config (10%) unless set to 0% or 100% which work correctly, This seems to be because the code just checks if a random double (between 0 and 1) is greater than 50% in src/main/scala/li/cil/oc/common/event/RobotCommonHandler.scala line 21. (and same with other RobotUsedToolEvent.applyDamageRate listeners)

The existing code would work correctly enough if the damge was a larger number but since mining tends to cause 1 damage it just uses the greater than 0.5.

It would possibly be fixed by changing the ">0.5" to be  ">( actualDamage %1 )" which would keep the state of repairing some damage for all larger durability losses while making it more closely follow the probability of getDamageRate
