### ISSUE TITLE
OpenOS timers starved during blocking pulls

### ISSUE THREAD

**Issue by brisingraerowing** [MightyPirates/OpenComputers#3058]
[More details here](https://oc.cil.li/index.php?/topic/918-big-reactors-grid-control/&do=findComment&comment=8538)

**Comment by payonel** [comment]
yeah..i read it. and I'm working on it
i'll quote xyfreak

BRGC uses events and timers all over the place. The entire thing is running asynchronously. Now usually you don't want to drop to the prompt when running a program so here's what it does:

function libGUI.run()
	while event.pull(math.huge, "libGUI_terminate") == nil do end
end

It just waits for a libGUI_terminate event and then cleans up stuff. Pretty easy.

 

Now with the linked commit, this event.pull continues to eat timer messages. The timers are only executed once a non-timer event is executed (such as a key press or a touch).

Here's a small PoC:

event.timer(5, function() print("canary") end, math.huge)

Prints "canary" every 5 seconds - pretty easy - nothing should go wrong here. If you now do a simple

while event.pull(math.huge, "tell_me_to_terminate") == nil do end

you will stop seeing "canary" show up - it's dead ;)

--- SNIP because I didn't want to believe the issue is complicated and looked further into it ---

And here's your bug:

In /lib/event.lua line 36 computer.uptime() is read and stored in a variable called current_time that is never updated again. Afterwards we enter a post-checked loop. Inside of this loop, on line 54, this line is executed:

local event_data = table.pack(handlers(closest - computer.uptime()))

Nothing wrong with that, until you realize, that calling handlers actually calls _pullSignal, which allows time to pass. Later, current_time is used to check if timers have expired. The issue? current_time is no longer current, because _pullSignal was called and time has passed!

So unless you return from computer.pullSignal (=> cause a non-timer event to be triggered like a key press or a touch), current_time is never updated so timers will never trigger.

The fix is really easy: update current_time after _pullSignal has been called.

Here's a patch:

--- C:\Games\MultiMC\instances\Draconic Computers 1.12\.minecraft\saves\BRGC\opencomputers\a201b7a4-e2fd-4565-8b4b-79a6993a7e62\lib\event.lua.bak
+++ C:\Games\MultiMC\instances\Draconic Computers 1.12\.minecraft\saves\BRGC\opencomputers\a201b7a4-e2fd-4565-8b4b-79a6993a7e62\lib\event.lua
@@ -54,6 +54,7 @@
     local event_data = table.pack(handlers(closest - computer.uptime()))
     local signal = event_data[1]
     local copy = {}
+    current_time = computer.uptime()
     for id,handler in pairs(handlers) do
       copy[id] = handler
     end

 

That was a b*tch to figure out... holy molly.

**Comment by payonel** [comment]
also quoting XyFreak

Even since before the commit that broke things, if a timer called something that let time pass (i know this is bad anyways but it CAN happen), it would actually fully delay the deadline of successive timers (instead of just delaying the timer once).

Here's another patch

--- C:\Games\MultiMC\instances\Draconic Computers 1.12\.minecraft\saves\BRGC\opencomputers\a201b7a4-e2fd-4565-8b4b-79a6993a7e62\lib\event.lua.bak
+++ C:\Games\MultiMC\instances\Draconic Computers 1.12\.minecraft\saves\BRGC\opencomputers\a201b7a4-e2fd-4565-8b4b-79a6993a7e62\lib\event.lua
@@ -62,7 +63,11 @@
       -- nil keys match anything
       if (handler.key == nil or handler.key == signal) or current_time >= handler.timeout then
         handler.times = handler.times - 1
-        handler.timeout = current_time + handler.interval
+        -- we need to make sure the timer doesn't drift but at the same time doesn't get rescheduled
+        -- immediately if it's execution had been delayed significantly (>= handler.interval * 2).
+        repeat
+          handler.timeout = handler.timeout + handler.interval
+        until handler.timeout > current_time + handler.timeout
         -- we have to remove handlers before making the callback in case of timers that pull
         -- and we have to check handlers[id] == handler because callbacks may have unregistered things
         if handler.times <= 0 and handlers[id] == handler then

I decided to go with a loop instead of math based, because the most likely case is this loop getting executed exactly once. Solving this with math would require math.floor which would propably be slower than this most of the time.

**Comment by squishey123** [comment]
It looks like patch 1.7.4 was released a few weeks before this was merged in, I'm assuming the fix to this is still waiting for the next patch, do we have a **loose** idea to when that would be?
