### ISSUE TITLE
Custom Font Characters

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#3076]
This would be useful to have a function to change font characters, this would be useful for interface building and having custom fonts.
The function like this:
```lua
gpu﻿.setFontChar( 0x0123, 0x0123456789ABCDEF0123456789ABCDEF ) -- In hex font f﻿ormat this would be: 0123:0123456789ABCDEF0123456789ABCDEF
```
Th﻿e first argument is the unicode character, then the second argument is the chara﻿cter data in hex font format.

**Comment by payonel** [comment]
I thought this was already asked, maybe in the forums. There are a number of reasons this isn't simple. client sync, moving glyph caching to a per gpu instead of static for the system which has tremendous performance and memory costs. It is a great idea but not quite right for how our mod is used on servers
