### ISSUE TITLE
certain robot api functions return an out of bounds error

### ISSUE THREAD

**Issue by kaletaa** [MightyPirates/OpenComputers#3111]
Some of the functions from the robot api return with an "index out of bounds" error, I have not checked other APIs since then, I'm unsure if this issue is present in other places.

![oc_error](https://user-images.githubusercontent.com/45270239/59631291-bd87a600-9147-11e9-9a37-46abfabcd530.png)

Code ran on the robot above:
```
local r = require("robot")
r.forward()
```
Functions that return with said error:
- forward()
- place()
- detect()  and derivatives 

Note: I haven't checked all of the functions, these are the ones I tried to use.

OpenComputers version: 1.7.4.153

It's easy to reproduce (at least for me):
- take any robot and run the snippet above on it.

**Comment by payonel** [comment]
ah, turns out this is because you're trying to index a nil value in the lua shell, and the lua shell is trying to be very "helpful"

1. `local` variables in a lua shell are discarded/out of scope on the very next line of input (after you press enter). don't use locals on the lua shell (unless you are doing that on purpose).
2. this has nothing to do with robot, in fact, you could hit this by just openining the lua shell can running literally `foobar.baz()`.

The lua shell is trying to load a library named `r` for you, and then trying to find a method called `foward`. The reason is because it sees `r` as `nil`, and thinks you might be trying to use a library by that name. It doesn't find one, and then you're trying to index that library (you can't index a nil), and it dies/throws an exception. So, no bug, just....slightly confusing error stack
