### ISSUE TITLE
Geolyzer arguments being ignored

### ISSUE THREAD

**Issue by big-lip-bob** [MightyPirates/OpenComputers#3143]
for some reason the geolyzer does not respect any of the optional y w d h arguments
geolyzer.scan(x,z,y,w,d,h)
What i expect is from the scan(0,0,0,1,1,7) to return a table with the 7 scans but everything is being ignored and i get a table with 64 entries of numbers
i don't know how can i use the geolyzer properly with that

**Comment by xieve** [comment]
I think [this](https://github.com/MightyPirates/OpenComputers/blob/a7f000b9d29b0b525375154af6e324a32244b275/src/main/java/li/cil/oc/api/event/GeolyzerEvent.java#L42) is relevant. I'm currently testing this, because not all arguments are being ignored.

**Comment by xieve** [comment]
Okay so actually this is **not** an error in the code itself, but just straight-up poor documentation. While I still can't find out why there's 64 values in the return table (or where they come from), the operators work. If you take the `0 .. w * d * h` slice of the return table, the data is there. Now to use that data, you'll have to reverse the `index = x + z*w + y*w*d` operation. That's completely doable due to those numbers being integers.

Edit: I'll add this to #2686.

**Comment by xieve** [comment]
Okay so I wrote a little helper function/wrapper to handle the information properly:

```Lua
function scan3d(geolyzer, x1, y1, z1, width, height, depth)
    --[[
        Scan the area which is stated by x1, y1, z1, width, height, depth.
        Returns a flattened table t which can be accessed by coordinates relative
        to the robot: `t(x, y, z)`.
        width, heigth and depth need to be > 0

        geolyzer: geolyzer component (e.g. component.geolyzer)
    ]]
    return setmetatable(
        geolyzer.scan(x1, z1, y1, width, depth, height),
        {
            __call = function(self, x2, y2, z2)
                --[[coordinates passed to this function (set 2) are relative to the robot
                    coordinate set 3 is relative to set 1]]
                local x3 = x2 - x1 + 1
                local y3 = y2 - y1
                local z3 = z2 - z1
                print(x3, y3, z3)
                if x3 > width or y3 > height or z3 > depth or x3 < 1 or y3 < 0 or z3 < 0 then
                    return
                end
                local i = x3 + z3 * width + y3 * width * depth
                print(i)
                return self[i]
            end
        }
    )
end
```

Usage example:
```Lua
local t = scan3d(component.geolyzer, 0, 0, 0, 1, 7, 1)
print(t(0, 6, 0))
```
_Note that x, y and z are now in the right order, as well as width, height and depth_

**Comment by payonel** [comment]
the result data is fixed at 64 entries, regardless of the scan volume. It probably would have made more sense to make the result set the same size as the scan size. I considered making this change, but I think if the docs explain it, it's less of an issue. The values in the result are slightly randomized due to a noise factor (see the config)

**Comment by payonel** [comment]
I've added some info in the docs

```

   * Note that the values returned is always 64 values, even if the scan volume is only part of that. If 
10 blocks are scanned, the first 10 values in the result represent those blocks scanned. The 
remaining values in the result should be ignored.

```
