### ISSUE TITLE
Debug card enabled by default

### ISSUE THREAD

**Issue by clienthax** [MightyPirates/OpenComputers#3186]
I think having the debug card enabled by default is a bad idea, I have had multiple item spawning exploits abused in addition to the debug card being used for damaging players etc.

If people don't know about the debug cards existence they might not know that it is a possible cause.

**Comment by Techokami** [comment]
The only way to get the debug card is either in Creative, with the `/give` command, or from something like JEI (which the user needs to be in Creative or have `/give` command permissions to get items from in the first place). Also, these methods are also the only way to get Command Blocks, which can be just as dangerous (if not more!) in any Minecraft server, vanilla or modded.

So I would like to know more about how the players on your server got the Debug Cards in the first place, because I have a hunch you might be having problems with a rogue admin instead of the existence of a testing item in a mod.

**Comment by clienthax** [comment]
> The only way to get the debug card is either in Creative, with the `/give` command, or from something like JEI (which the user needs to be in Creative or have `/give` command permissions to get items from in the first place). Also, these methods are also the only way to get Command Blocks, which can be just as dangerous (if not more!) in any Minecraft server, vanilla or modded.
> 
> So I would like to know more about how the players on your server got the Debug Cards in the first place, because I have a hunch you might be having problems with a rogue admin instead of the existence of a testing item in a mod.

The items are generally spawned in via packet exploits, and then used to mess with players using the debug card, I don't think something with the ability to spawn blocks etc on players programitically should be enabled by default in general

**Comment by Techokami** [comment]
Packet exploits? That's... hoo boy. 😬 You should be banning people doing these things!

The debug card can be disabled via a config, but having it off by default? Paging @payonel to the thread.

**Comment by clienthax** [comment]
> Packet exploits? That's... hoo boy. 😬 You should be banning people doing these things!
> 
> The debug card can be disabled via a config, but having it off by default? Paging @payonel to the thread.

If you ban them too early you don't get a chance to figure out what other packet exploits they may have ;), but this is more aimed at a general audience of owners that wouldn't know what on earth was going on if someone decided to use a debug card to kill everyone on the server in a loop.

**Comment by payonel** [comment]
exploits in the vanilla game allowing items to be spawned? sounds like a problem with the vanilla core netcode, and not our mod :) I think we'll leave it as is. but the way, it drives me nuts how i have to enable command blocks even when i have creative :)
