### ISSUE TITLE
Black color on hologram is transparent and darker colors are more transparent than lighter colors

### ISSUE THREAD

**Issue by NopeDK** [MightyPirates/OpenComputers#3204]
Using black or any darker color results in transparency instead of rendered color.

This shows default rendering, it should have had a black head (around the gray eye) and black stripes. Instead they are transparent and actually removes some of the render faces on the yellow blocks, most noticeable in the lowest yellow squares (missing right face).
![](https://cdn.discordapp.com/attachments/641293471965118504/661967308817694722/2020-01-01_11.20.30.png)

The following image is how I would expect it to look, except for the missing transparency. This is taken using Sildurs Shaders.
![](https://cdn.discordapp.com/attachments/641293471965118504/661967453982687235/unknown.png)

OpenComputers-MC1.12.2-1.7.4.153
Tier 2 hologram projector.

**Comment by Alchemichai** [comment]
Random guy here. Would you have the projector project darkness? On a screen the pixels aren't displaying black, they are just not displaying colour, a clear oled panel's black would be transparent. That said, it's not like it couldn't be done in game I suppose. In the mean time, maybe try brown instead of black.

**Comment by payonel** [comment]
interesting issue, but we're going to leave it the way it is working. we use black as the "off" - changing this would break existing holo programs people are building
