### ISSUE TITLE
Crash in native library

### ISSUE THREAD

**Issue by TorakWolf** [MightyPirates/OpenComputers#321]
Versions:

OpenComputers 1.6.4-1.3.0.419
OpenComponents 1.6.4-0.1.1.42

Problem: 

I know there's a lot of errors with screens and OpenGL, but I never had any of these problems.

That said, on the last versions I was playing only on my test world, so I never turned off one computer ( or turned on a new one ), and every time I had one crash, when I re logged the world, the computers where on their place because of the auto save.

But yesterday, when I was playing on my normal world and turning on my computer...Boom. I got one crash. The problem is that the crash only happens when I turn on one computer with one screen or connect one screen to one recently placed computer, but old computers ( like the ones of the test world ) and computers without screens keep working normally, but the old ones ALSO crash when I reboot them...

If that helps, the problem occur when the OpenOS library disk finish loading ( may be when the computer tries to connect components ). So, yeah...

Another weird thing is that there are 2 different MC crash logs, one with OpenComponents, other without ( just for testing, I read the log and tried without OpenComponents ), but both have ( almost ) the same error log...

The crash log / error log with OpenComponents:
http://pastebin.com/bacq09R7 / http://pastebin.com/Lt9Ra6Cx

The crash log / error log without OpenComponents:
http://pastebin.com/WVxmvQfW / http://pastebin.com/ALf5Utr0

Mods I have recently updated are Railcraft, Mekanism and Traincraft, just for state.

**Comment by TorakWolf** [comment]
Sorry for my english ( like in where, when should be were, or may be, when should be maybe ).

**Comment by TorakWolf** [comment]
Also, there's no complete crash logs, since there's nothing on the crash reports folder(?)... those crash logs are generated by the console.

**Comment by TorakWolf** [comment]
I confirmed that this only happens with 397+. There's something wrong with the library... Initially I though       that this was only with remote terminals, but now I see that no...

**Comment by fnuecke** [comment]
This is quite disturbing, since the new native build actually fixed two bugs... I'll upload a custom build with DLLs containing debugging symbols later, that will hopefully make the traceback a little more useful. In the meantime, could you please try if this also happens if you use Java 1.7 instead of 1.8?

**Comment by fnuecke** [comment]
You can download the custom build with the debug natives [here](http://cil.li/mc/OpenComputers-MC1.6.4-1.3.0-universal.jar). If it crashes again the logs will hopefully be a little more helpful.

**Comment by TorakWolf** [comment]
Sorry, no chance I can use java 7. I installed just for testing and I got fps drop when moving mouse, overall fps drop in other processes, etc, and can't even load my world. But here is the Crash Log ( now complete console log, but again no one in the crash-reports folder ) and Error Log of the crash with the debug version in java 1.8:

https://www.dropbox.com/s/5smdoz4snioi7tz/Crash%20Log%20Debug.txt / http://pastebin.com/2He9uMS5

I did the same thing: turned one computer on with one screen attached. The other computer keeps running ok even with screen, the problem only occurs when attaching one screen by the first time.

Edit: Nevermind, tested with java 1.7.0.60b 19 and same thing ( no need to post the same log... )

I want to ask something: Do that only happens with me?

**Comment by fnuecke** [comment]
Well, from what I've heard you're the only one with native crashes since the natives were patched, hence my suspicion it might have to do with Java 1.8. But the sampling size is relatively small, so who knows. I'll grab a copy of Java 1.8 myself and see if I can reproduce it.

Does this happen 100% of the time for you?

**Comment by TorakWolf** [comment]
Yes, and only when placing screens... any other component do not crash when connected, and computers that were still on from older versions work ok. I also tested java 1.7.0.60b and got the same issue. I know you updated the natives, but do you changed something in the way screens are bound automatically to computers?

**Comment by Kubuxu** [comment]
I am working on Java 8 and I can't reproduce. It must be something more complex.

**Comment by fnuecke** [comment]
Hmm, can't reproduce this in Java 1.8, either.

@Kubuxu which version of Windows are you on (if you are)? Because another thing that changed since the previous libs is that the new Windows ones were built in Win 8, whereas the old ones were built in Win 7, and @TorakWolf is on Win7.

I'll set up a Win 7 VM to recompile them in there, maybe that'll help...

**Comment by fnuecke** [comment]
In the meantime, @TorakWolf, could you try changing the following settings:

```
computer.debug.disableMemoryLimit=true
computer.debug.disablePersistence=true
computer.debug.disableUserdata=true
```

And see if that makes the crash go away? And if so, ideally figure out which one(s) of these settings does the trick? Thanks!

**Comment by Kubuxu** [comment]
I am on Windows 7 but I will check again because I might has been switched to Java 1.7. I will rebuild and respond.

**Comment by Kubuxu** [comment]
Works fine even with Scala 2.11.2.

**Comment by TorakWolf** [comment]
Disabling the Memory limit and Userdata does no difference and disabling persistence cause immediate crash on world loading due to reboot... Well, I will enable updates on Windows Update and test with only opencomputers. I already tried to delete the config, but nothing changes.

Edit: No changes with only OC, NEI, Waila, UE Core, Ender IO and Mekanism...

I will enable Windows Update...

Another Edit: BY GOD. When I updated Windows, everything started to work...WoW. Please attach one note to the mod: "In order to avoid native library crashes, keep windows up-to-date". Since you compiled the mod on up-to-date environment, this can be the "issue" origin.

Time to scream by the comments and close the issue, HUEHUEHUE.

Anyways, how can I use the sensor of openperipherals with opencomputers? When I try something like:

sensor = component.proxy(component.get("address part")
infoplayer = sensor.getPlayerData("TorakWolf")
print( infoplayer["position"]["x"] )

should print my x position but return nil and an error, but when I use that code, but with the peripheral API of course, in CC computers, all runs ok...

Ok, so I have reported such thing a couple months ago, talking about the glasses bridge, but since you make possible to use the glasses bridge, I thought I should be able to use the sensor too...

**Comment by Kubuxu** [comment]
There is probably UnsupportedContext exception.  If you want to use something like OP sensor look at EvenMoreUtilities mod.

**Comment by fnuecke** [comment]
@TorakWolf oh, that's interesting. I'll definitely recompile in an older Windows 7 environment then, hoping it'll avoid those crashes. I'll also need to take a look into the crash when persistence is disabled... because it shouldn't. Thanks for letting me know!

As for the other thing, as @Kubuxu said, that's most likely unsupported because it pushes userdata, which is not handled in OpenComponents, yet (but is possible in 1.3, will need some further testing for stability, though, and I can't promise it'll be possible to automatically wrap CC userdata).
