### ISSUE TITLE
[1.12.2] Log warn spam w/ JEI?

### ISSUE THREAD

**Issue by xJon** [MightyPirates/OpenComputers#3223]
This is the warnings from the log: https://pastebin.com/BiPKSdjq
Was also reported to JEI.
Any idea? Thanks!

**Comment by payonel** [comment]
can you give *MINIMAL* mods needed for repro, steps, versions of each mod please
thanks

**Comment by xJon** [comment]
@payonel Just install & enter a world.
![Screenshot_1](https://user-images.githubusercontent.com/8945347/73316544-e292da00-423b-11ea-890a-ffb9d99b7c70.png)

**Comment by payonel** [comment]
sorry, no repro - did you have to place anything in the world?

**Comment by payonel** [comment]
ah, when you say "spam" i thought you meant it continues to "spam" the log
but no, it only dumps these errors on the first time load of mod integration with jei - and not on subsequent world loads. evidence of issues? yes, spam? no

**Comment by xJon** [comment]
So it only happens on first world load?

**Comment by otakup0pe** [comment]
Seeing this myself as well. Some context from JEI [here](https://github.com/mezz/JustEnoughItems/issues/1878).

I'm seeing it constantly since I added opencomputers to our modpack a few days ago. Can't tell if it's causing any problems and I don't think I am seeing the memory spike that some people reported in the JEI bug. To add more context based on the questions you already asked....

* i sense minimal mods are jei + opencomputers.... i have not verified this - maybe throw laggoggles in too? i see it in my [stack trace](https://gist.github.com/otakup0pe/8f3334bc4aecfac5f5d9a21b2ea5bc95)
* happens when i start modpack and load a world - not just the first time
* errors do not seem to continue once world is loading

**Comment by mezz** [comment]
This log happens when a mod adds items to JEI extremely late. 
@asiekierka has added an optimization to JEI here to reduce memory: https://github.com/mezz/JustEnoughItems/pull/1814
But it will work less efficiently if mods are adding items after that point in time.

Most likely this is not a cause of extreme issues, but just happened to show up in the logs for some people who were having serious problems.

**Comment by payonel** [comment]
can be ignored
