### ISSUE TITLE
Unmanaged drive not reading bytes correctly

### ISSUE THREAD

**Issue by JujuLynx** [MightyPirates/OpenComputers#3243]
Seems I'm having an issue with reading bytes from an unmanaged drive. Follow these steps to replicate:

- call the method drive.writeByte(offset:number, value:number).
- for the value, use any number, such that: 127 < n < 256
- for the offset value, choose any valid number, as long as you use the same value for the read method.
- call the method drive.readByte(offset:number)
- reading back that sector, the value will instead be: value - 255 (i.e. a negative number)

Example: I want to write 147 to byte 1. If I read the byte back, it gives me -109. This happens with any tier drive, including the floppy disk.

I believe it's a bug in the readByte method. If I instead follow this procedure to extract that same byte:
- str = drive.readSector(1)
- s = string.sub(str, 1, 1)
- print(string.byte(s))

It will correctly print out value 147.

I suppose... you could write a correction factor to ensure any byte <0 has 255 added to it to compensate, but fundamentally there's an issue with the method (I believe...) and it should be addressed at the source.

**Comment by Fingercomp** [comment]
`drive.readByte` returns a byte, which, just like any other integer type in Java, is signed. This means, in particular, that its range is limited from -128 to 127 (not 0 to 255). Due to [the way integers are represented in memory](https://en.wikipedia.org/wiki/Two's_complement), values greater than 127 overflow, becoming negative in the described case.

On the other hand, `drive.readSector` returns a Lua string, and `string.sub` returns a Lua integer. It is also signed, but, unlike the Java's byte, it is an 8-byte number, so it can represent much greater values, including those between 128 and 255.

Ultimately, both methods return correct values. But it is indeed unexpected to have a signed byte in Lua.

**Comment by Rayder44** [comment]
Hmmm, I see. In that case I've found performing a bitwise AND on the byte with 255 will return an unsigned integer so I guess I'll have to correct it whenever using .readByte().

Thank you.

**Comment by JujuLynx** [comment]
Hmmm, okay I see. In that case I've found performing a bitwise AND with 255 should reliably return an unsigned integer. I guess doing the correction will be necessary.

The fact that the number was negative and thus signed didn't occur to me. Seems I learned something today. Thanks for your help.

**Comment by payonel** [comment]
SADLY i cannot fix this without changing the return value of this api, and making things worse in general
1. Right now, the readSector returns a String. Each char is 2 bytes because java
2. thus, sadly, Byte.toChar is negative
3. i can "unsigned" the byte value up into positive, but then....
4. the high ascii value gets broken into a utf8 pair
5. user code would have to re-combine the utf8 byte pair into a single integer

For example, 0xf3 is 243 decimal. This is ó
But, in utf8, this is defined as 0xC3 0xB3

We have a utf8 library available in lua to the in-game lua runtime, you could extract the 243 back out using the utf8.codes api

However, for every byte >= 0xf0 in the result string there will be multiple utf8 codes. This will utterly break existing user code, and you would have to parse the string result for utf8 sequences. A user can store what ever byte sequence they desire, it may look like utf8 but be completely not. This simply cannot work

The other solution is to return an array of ints. But again, this breaks the existing api

I could add a new method that returns Array[Int] -- but i've decided to close this as won't fix. The work around is to add 0x100 when the value is negative. Apologies
