### ISSUE TITLE
Printing With Threads Bug

### ISSUE THREAD

**Issue by Robonics** [MightyPirates/OpenComputers#3262]
Open Computers Version: 1.7.5

I'm not sure if this is an issue with my Lua code, Open Computer's shell or the Thread Library. The Program works fine, however the input stream overrides the previously outputted line when I type.

```
local component = require("component")
local note = require("note")
local sides = require("sides")
local event = require("event")
local thread = require("thread")
local modem = component.modem

print("Choose a port to talk with:")
port = io.read("*n")
modem.open(port)
print("Opened Port " .. port)
--Create Thread For Receiving Messages
thread.create(function(port)
    while(true) do --I haven't added exit conditions yet
        _, _, sender, _, _, message_1 = event.pull("modem")
        note.play(75, 0.25)
        note.play(77, 0.25)
        print("<" .. sender .. "> " .. message_1)
    end
end
--Send Messages
while(true) do
    input = io.read()
    modem.broadcast(port, input)
end
```
Image of Bug: https://imgur.com/a/gSDEK8d
I didn't know where to post this, but I figured since it used Open Computer's thread library I would try here first

**Comment by payonel** [comment]
not a bug, the tty is not thread safe. only 1 thread can use the tty. you'll need to queue messages back to the main tty thread

**Comment by Robonics** [comment]
I'm new to Lua. How would I do that exactly?

**Comment by payonel** [comment]
well your code is trying to mix input reading while also printing messages from a thread
that's not really congruent with printing on the go. even if the tty were thread safe, your input (the text you are typing for input.read()) is going to be mixed with thread messages. so there is no great solution to this (again, without making the tty at least thread safe, but this is a known limitation)

assuming you weren't also concurrently trying to read user input, you could:

append your messages to a message queue, pop them off and print them in the main thread
so instead of calling print in your thread, do something like
`table.insert(messages, string.format("<%s> %s", sender, message_1))`

then back in your main thread, pop and print
```lua
while true do
  event.pull(.5) -- or something that causes a thread yield
  while #messages > 0 do
    local msg = table.remove(messages, 1)
    print(msg)
  end
end
```
