### ISSUE TITLE
Linked Cards only receiving every other message

### ISSUE THREAD

**Issue by MoonstreamJustNotInSpace** [MightyPirates/OpenComputers#3271]
I have two computers testing a set of linked cards. 
The sender runs this:
![Screen Shot 2020-04-10 at 9 28 02 AM](https://user-images.githubusercontent.com/63458530/78994268-9ef6ff00-7b0d-11ea-8156-b21c66b419e2.png)
And the receiver runs this:
![Screen Shot 2020-04-10 at 9 27 50 AM](https://user-images.githubusercontent.com/63458530/78994291-aa4a2a80-7b0d-11ea-8845-1f1164bd51a3.png)
But the receiver only receives every other message that I send. It ignores the first, prints the second, ignores the third, prints the fourth, and so on.
Am I just making a beginner's mistake or something?

**Comment by UV-Husky** [comment]
You have 2 `event.pull("modem_message")` instructions. 
1. You receive only every other because `a=...` captures the first message (you never do anything with it). 
2. Then the system waits for another message. 
3. When a second message comes it prints it.
4. Loop repeats.

Solution: Remove the `a=event.pull("modem_message")` line.

PS: This should go to the forums, but since they are little unstable at the moment :(

**Comment by payonel** [comment]
@SpaceBeeGaming is correct. you have two pulls, effectively tossing the first message away

**Comment by MoonstreamIII** [comment]
Oops. Thanks!
