### ISSUE TITLE
Creative Cpu and stuff

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#329]
Well, title states it(again), a cpu with unlimeted components would be nice to go with the creative case, aswell as creative hdd's with unlimeted storage

**Comment by fnuecke** [comment]
Sorry, but that's a road I'll not go down (soon), it'll get out of hand work-wise too quickly. Creative servers, creative floppies, creative battery upgrades, creative card containers, creative upgrade containers, creative whatever item type I add next. Just increase the values in the config.

Edit: since those are all extra items, basically, it'd be very doable to just make a 'creative' add-on mod. Just sayin' ;-)
