### ISSUE TITLE
Advanced redstone card

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#340]
A normal redstone card cant do analog redstone and rednet/boundled cable.
Advanced redstone card is more expansive and can do what the current redstone card can.

Wrote this very fast on my smartphone

**Comment by TorakWolf** [comment]
Since redstone is one very simple thing, I do not see the point on making things harder...

**Comment by LordFokas** [comment]
it'd only make sense if you were to put regular redstone, including analog signals, on a basic card and let the advanced use bundled signals. Otherwise it wouldn't make sense...

**Comment by Vexatos** [comment]
I don't see the point in that. Redstone cards are fine as they currently are, in my opinion.

**Comment by Wuerfel21** [comment]
In vanilla everyting that has to do with analog is more expansive: comperators, daylight sensors, these gold and iron pressure plates(which i never used).  So make the current card recipe become the advanced one , and the simpler just without the chip

**Comment by phillips1012** [comment]
I think this should be a feature with the redstone IO block. What kind of computer would have a massive bundled output port sticking out of a tiny card?

**Comment by Kilobyte22** [comment]
yeah, if anything, i would do what @phillips1012 said. Aka remove ability to connect a redstone card to bundled cable/rednet cable. but as mny already stated, its fine the way it is currently.

**Comment by Wuerfel21** [comment]
Every real computer has a VGA port ehich has 15 pins...

**Comment by fnuecke** [comment]
I'm a little torn about this one. On the one hand it's a neat idea, on the other hand redstone, even if bundled, _is_ a very rudimentary functionality, and splitting it up would lead to more confusion. I'll leave it open until I make up my mind.

**Comment by Wuerfel21** [comment]
Then just add some stuff like schmitt-trigers or timers to make it a bigger deal

**Comment by TorakWolf** [comment]
But you can have some pretty nice timers with Project Red, in the case you don't like computers doing those simple things...

**Comment by Wuerfel21** [comment]
I actually have mfr, but controlling the prc with a computer is a pain.

**Comment by fnuecke** [comment]
Computers aren't meant to take the role of Rednet Controllers, i.e. high frequency pattern stuff. That's what those are for. Computers are for more complex logic, that's either impossible or an utter pain you-know-where to replicate with logic gates. Built-in redstone _behavior_ doesn't really belong into OC, IMHO. That should be modeled in software. [/idea]

What I _could_ imagine would be to give tier 2 redstone cards support for other mods' wireless redstone facilities, since that would nicely mirror the T1 -> T2 network card capabilities. So basically T1 redstone card would be "vanilla" capabilities (simple, analog redstone), T2 would additionally be other mods' stuff (bundled, wireless). I'd have to take a look at the APIs of said mods, though, to see if that's even possible.

**Comment by Wuerfel21** [comment]
WR-CBE has an api, misc peripherals had an turtle upgrade for it...

**Comment by fnuecke** [comment]
Well that sounds promising then. Will have a look when I find the time.
