### ISSUE TITLE
Minecraft 1.13 or higher support?

### ISSUE THREAD

**Issue by jarno9981** [MightyPirates/OpenComputers#3413]
When will higher version of minecraft be supported

**Comment by pivinx1** [comment]
I have heard that some people are working on it, not sure if it's true

16 mar 2021 19:14 "jarno9981" ***@***.***> napisał(a):

When will higher version of minecraft be supported

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MightyPirates/OpenComputers/issues/3413>, or unsubscribe

**Comment by SirDavidLudwig** [comment]
I've been working on a fork for 1.16. It's been a bit slow recently, but I've at least made some decent progress.

**Comment by jarno9981** [comment]
@SirDavidLudwig  Nice

**Comment by LAutomate-dev** [comment]
Most of the discussion about oc2 went down in #3375.

To save you from searching for it, the git is [here](https://github.com/fnuecke/oc2).

**Comment by payonel** [comment]
closing as "won't fix"
