### ISSUE TITLE
Redstone output not working

### ISSUE THREAD

**Issue by eliasrg** [MightyPirates/OpenComputers#3439]
After switching to the latest development build ([`OpenComputers-MC1.10.2-1.7.5.259.jar`](https://ci.cil.li/job/OpenComputers-MC1.10/lastSuccessfulBuild/artifact/build/libs/OpenComputers-MC1.10.2-1.7.5.259-api.jar)), I noticed that redstone output seems not to work anymore. On a computer, after calling `component.redstone.setOutput(sides.front, 15)`, `component.redstone.getOutput(sides.front)` returns 15, but no redstone signal is emitted. If I load the following program onto a microcontroller and turn it on, no signal is output on any side:

    local rs = component.proxy(component.list('redstone')())
    
    for side = 0, 5 do
        rs.setOutput(side, 15)
    end
    
    while true do
        computer.pullSignal(1)
    end

In the latest release, however (`OpenComputers-MC1.12.2-1.7.5.192.jar`), signals are produced in both these experiments.

**Comment by RobertCochran** [comment]
The issue probably starts in this commit: https://github.com/MightyPirates/OpenComputers/commit/a1d1834597cc8ca3dc6787da991e519efcbcd510 .
I was only able to test in the 1.10/1.12 versions (since I couldn't set up a 1.7.10 environment), but if you remove the new conditional check altogether, making
```scala
  def getOutput(side: EnumFacing) = if (_output != null && _output.length <= toLocal(side).ordinal())
    _output(toLocal(side).ordinal())
  else 0
```
in the 1.12 version into just
```scala
  def getOutput(side: EnumFacing) = _output(toLocal(side).ordinal())
```
then it starts working again, at least in 1.12. That suggests to me that the conditional check is incomplete and not accounting for some other condition it needs to be aware of, but my near complete unfamiliarity with the code means I have no idea where to go from here.

**Comment by asiekierka** [comment]
Fixed
