### ISSUE TITLE
Post-1.12 update?

### ISSUE THREAD

**Issue by rodgerCastle** [MightyPirates/OpenComputers#3450]
Exactly as the title says.  I used to play this mod a lot and I'd have some interest in starting working on a newer version of this mod (the other "computer mods" just don't quite feel like this one).  Would anyone else actually have interest in working on something like this or is interest pretty much entirely dead to this mod?

**Comment by SilverSCode** [comment]
> Exactly as the title says. I used to play this mod a lot and I'd have some interest in starting working on a newer version of this mod (the other "computer mods" just don't quite feel like this one). Would anyone else actually have interest in working on something like this or is interest pretty much entirely dead to this mod?

I'm also looking forward to OC being implemented on a higher version of minecraft, so that stronger minecraft commands can be executed in OC to change the world

Moreover, CC: tweaked is implemented on minecraft 1.16.5, but OC still stays at 1.12.2

I made this suggestion in the OC forum a long time ago, but there was no response. I doubt that no one is developing OC now

**Comment by asiekierka** [comment]
Interest, yes. But it would take a lot of effort, which might be better spent collaborating with Sangar on OC2.

**Comment by asiekierka** [comment]
https://github.com/MightyPirates/OpenComputers/pull/3572

**Comment by kristibektashi** [comment]
> #3572

Any news on this?

**Comment by medzernik** [comment]
Would be really amazing if this mod could get love to 1.20. It's leagues beyond computercraft in terms of quality and fun to use

**Comment by BlakeB415** [comment]
It seems a lot of mods are skipping 1.18/1.19 and going directly to 1.20. It would be great if we could get OpenComputers on 1.20. I absolutely love this mod.

**Comment by samuelh2005** [comment]
There is [OpenComputers II](https://github.com/fnuecke/oc2) however the newest it support is 1.18

**Comment by medzernik** [comment]
but OC2 is a bit too much like a real computer not along the same levels of play/charm? is what i got a bit from that one. Maybe im mistaken tho

**Comment by samuelh2005** [comment]
@medzernik You can make Lua programs in OC2, you can customize the components inside the computer like OC1 (Open Computers). Since it is a RISC-V machine you could program in C or Python if you wanted. The computers require energy (if you have an energy mod).

And its made by one of the OC1 (Open Computers) developers: fnuecke.

**Comment by ParadiseFallen** [comment]
well... any updates on this? for me this mod just looks better then CC:Tweaked. (MC 1.20.1)

**Comment by asiekierka** [comment]
The mod has exactly zero developers left, so...

**Comment by ParadiseFallen** [comment]
are they moved to OC2?

**Comment by samuelh2005** [comment]
@ParadiseFallen development for OC2 looks like it have solved to the bugs in Sedna.

**Comment by asiekierka** [comment]
See https://github.com/MightyPirates/OpenComputers/issues/3709
