### ISSUE TITLE
Incompatibility Problem with MalisisCore

### ISSUE THREAD

**Issue by aaronschneider7797** [MightyPirates/OpenComputers#3493]
https://gist.github.com/AaronSchneider403/0dc6d8f6061d1e86fb0524c963ebf585

The ClassTransformer with MalisisCore is incompatible with OpenComputers.

MalisisCore Version: 1.12.2-6.5.1
OpenComputers Version: 1.12.2-1.7.5.192

**Comment by ghost** [comment]
I am playing with both Mods on the same version, I have no problems with them

**Comment by brisingraerowing** [comment]
You are on Java 8 Update 51, which is over 6 years out of date. As Oracle JRE 8 is now paid, you should update to the [Adoptium JRE](https://adoptium.net/releases.html?variant=openjdk8&jvmVariant=hotspot). Make sure to set your launcher to use the new version as well.

**Comment by asiekierka** [comment]
The pastebin has expired :( Please reopen if you manage to restore it.

**Comment by brisingraerowing** [comment]
@asiekierka I found the log (the OP changed their username, breaking old links)

https://gist.github.com/AaronSchneider7797/0dc6d8f6061d1e86fb0524c963ebf585

The issue here is related to Mixin and Scala conflicting. [This mod](https://www.curseforge.com/minecraft/mc-mods/forge-mixin-fix/files/2824043) fixes the issue.

**Comment by asiekierka** [comment]
Thank you!
