### ISSUE TITLE
No warning that Robot has too many components for the installed CPU.

### ISSUE THREAD

**Issue by WazWaz** [MightyPirates/OpenComputers#352]
The other warnings (no keyboard) can conceivably be ignored, but this one is equivalent to excess "Complexity", since the Robot is useless once built (fortunately I made a save just before Assembling as I was suspicious that so many were allowed, I just assumed the component limit only applied to external connected components).

Assembler should refuse to build as it does with excess complexity or missing CPU.

**Comment by Techokami** [comment]
Use a disassembler to get back the parts and start over? :V 
Also, why do I need a keyboard if I wanted to make a "headless" robot? I could have the code I want to run on the boot disk as an autorun program, and have it just do its thing without any need of manual interaction. That way, I can save on the complexity for more useful parts!

EDIT: Oh, I misread. Hm, it should check the CPU in the slot and use that to alter the complexity limit.

**Comment by fnuecke** [comment]
The tricky part of that is that to figure out the actual component count an actual instance of each items 'logic' has to be created, which is _really_ messy, since it could introduce all sorts of side-effects. And changing the API to allow drivers to specify whether they provide a component / their component cost isn't really an option right now. It's something I may put in for the next bigger, API changing update, but for 1.3 the API mustn't change anymore. Sooo it's basically a matter of 'if you screw it up, disassemble it' for now, sorry :-/

**Comment by WazWaz** [comment]
It's of course pretty hard to resist "cheating" and editing the filesystem externally :-)

I don't really understand what the assembler/disassembler mechanic is for. Have we not invented screwdrivers? I should look back in the forums, I assume it's been discussed somewhere.
