### ISSUE TITLE
I'm testing how does oc computers work while chunk unload and reload, But it only perform SOME functions

### ISSUE THREAD

**Issue by ChengxiX** [MightyPirates/OpenComputers#3529]
```
local c = require "component"
local internet = c.internet
local s = internet.connect("0.0.0.0", 1000)
local i = 1
while true do 
  s.write("abc")
  print(i)
  i = i + 1
  os.sleep(1)
end
```
When i leave the chunk, of course it stop sending tcp. But when i return, the computer still print numbers but not sending tcp.
That's really strange. I need some help and a real solution.

**Comment by RedstoneParkour** [comment]
Unloading the chunk the computer is in temporarily pauses its execution. Since the execution is paused, the TCP socket closes due to it timing out and no numbers are printed. However, when you reload the chunk, execution resumes as if nothing happened (except for the TCP socket closing), so the computer keeps printing the numbers.
