### ISSUE TITLE
better cc peripheral support

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#353]
When ever i try to use a cc addon, it either crashes or displays a dirt screen saying cc is requierd.
Also using them without adapters would be cool.

**Comment by LordFokas** [comment]
That's because CC addons F**KING REQUIRE CC!
You CANNOT, ever, load a mod 'A' that depends on a mod 'B' without installing mod 'B' in your minecraft. It has nothing to do with OC. The best you can do is leave the mighty pirates alone and go whine at the addon devs.

Using them without adapters would also mean every single OC block would be a CC adapter internally, and that is bad.

**Comment by Wuerfel21** [comment]
You already interface with peripherals, so isn't it just trick forge into thinking its there?

**Comment by LordFokas** [comment]
Nope.

In the FML `@Mod` annotation every forge mod has, you can specify a `required-after: OTHER_MOD` so that your mod doesn't load unless another specific mod is loaded. Because CC addons were made for CC computers and they reference the API directly without packaging it, it makes sense for them to require CC. Thus, CC addons can only be used if CC is present.

**Comment by Wuerfel21** [comment]
So, lets bug addon authors!
