### ISSUE TITLE
[1.7.2][1.3] Text remains on the robot screen.

### ISSUE THREAD

**Issue by MoonlightOwl** [MightyPirates/OpenComputers#360]
If you break the running robot with pickaxe, and then place it back - the screen will retain the old text (but the robot will be off).

**Comment by Wuerfel21** [comment]
This is intended, just turn it on and off to remove the text.
The background: when a computer shuts down it clears the terminal first, to make the screen black. If you dont turn it off propertly(or break the cable ), the screen will remember its contents. Try a screen next to a computer: same things happen.

**Comment by fnuecke** [comment]
While I wouldn't quite say it's intended, I wouldn't go so far as to say it's a bug, either. And yes, it's consistent with normal screen behavior, and isn't a problem, really, sooo... actually, yeah, totally intended behavior >____>

Seriously, though, since screens behave more like chalkboards than like actual screens in general (you don't have to push a 'signal' at 60Hz, you set it and forget it) I actually think this is quite consistent with their nature.
