### ISSUE TITLE
gpu.bitblt last 2 arguments are swapped

### ISSUE THREAD

**Issue by AR2000AR** [MightyPirates/OpenComputers#3609]
The last 2 arguments of `bitblt([dst: number, col: number, row: number, width: number, height: number, src: number, fromCol: number, fromRow: number])` are swapped. Instead of `fromCol`,`fromRow`, the function interprete the args as `froRow`,`fromCol`.
This code show the issue :
```lua
local component = require "component"
local gpu = component.gpu
local os = require("os")

local b = gpu.allocateBuffer(gpu.getResolution())
gpu.setBackground(0x0000ff)
for i = 1, 80, 1 do
    gpu.set(i, 1, string.char(i + 47):rep(25), true)
    os.sleep(0.01)
end
--require('event').pull('key_down')
gpu.bitblt(b)
gpu.setBackground(0)
gpu.fill(1, 1, 80, 25, " ")
for i = 1, 80, 1 do
    gpu.bitblt(0, i, 1, 1, 25, b, 1,i) --in this state, this will not work as documented
    os.sleep(0.1)
end
gpu.freeAllBuffers()
```

**Comment by KosmosPrime** [comment]
Probably caused by [GraphicsCard.bitblt](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/component/GraphicsCard.scala#L261) (swapping row & column when calling [GpuTextBuffer.bitblt](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/common/component/GpuTextBuffer.scala#L105)).
Copying from the screen to itself uses a different logic (should be the case for buffers too) which doesn't seem to have the issue.

**Comment by asiekierka** [comment]
Since this has shipped in a release build, I think the best thing to do is fix the documentation and not the implementation.
