### ISSUE TITLE
transferItem unable to transfer from a Roost chicken breeder back into a chest

### ISSUE THREAD

**Issue by MileyHollenberg** [MightyPirates/OpenComputers#3614]
I'm playing the EggBlock pack and I've enabled a couple configs so I can use OpenComputers in order to read NBT data and easily transfer items from one place to another. 

I'm currently able to transfer seeds from a chest in the top to the chicken breeder seed slot on the left side of a transposer but when I try to transfer anything back to the chest it always fails and the method returns 0 (it was false before but after the update of this mod it became a number)

I also already updated OpenComputers to the latest 1.8.0 release on CurseForge and also updated Roost to its latest version of `1.12.2-2.0.10` but left all other mods in the pack at their latest for the pack (even though 80% has some update available)

My relevant code is this,

```
local a = transposer.transferItem(sides.top, side, 64, seedIndex, 3)  
local b = transposer.transferItem(side, sides.top, 64, 3, seedIndex)  
print("Added seeds ", a, b)
```

it prints `Added seeds, 2, 0` which is quite weird as it can transfer items into but not out of the chicken breeder (same with the chickens in the last 3 slots)

Is this a bug or does the Roost mod need an extra config to allow items to be extracted?

**Comment by KosmosPrime** [comment]
Roost doesn't allow you to remove input chickens or seeds from its blocks unfortunately (via [canExtractItem](https://github.com/timrwood/roost/blob/master/src/main/java/com/timwoodcreates/roost/tileentity/TileEntityChickenContainer.java#L306)). Removing output chickens works just fine though.
Note that the actual [item removal logic](https://github.com/timrwood/roost/blob/master/src/main/java/com/timwoodcreates/roost/tileentity/TileEntityChickenContainer.java#L256) doesn't have any limitations on this, the reason why it doesn't work is because OC respects the block's _desire_ to not have input items removed (i.e. other mods might erroneously work for this purpose).

**Comment by MileyHollenberg** [comment]
Aha, thanks for the info. Unfortunate that Roost doesn't allow this behavior because whilst it's fun for the first couple chickens to do it all manually and get them to a 10/10/10 state, doing it for all of them is quite tedious. Any way I could override this somehow? Or is it pretty much locked down?

**Comment by KosmosPrime** [comment]
It's hardcoded within the roost mod, you'd have to make the changes manually.

**Comment by MileyHollenberg** [comment]
Alright, I'll have a look :)

**Comment by MileyHollenberg** [comment]
Aha, I figured out why the canExtractItem is denying the extraction for those slots, it's to prevent hoppers from extracting the chickens or seeds and only extracting the actual output items. 

Should be able to add a check to see if the block below is a hopper and then block it otherwise allow it (though obviously this wouldn't be a perfect fix as if I had Create in the pack, if that even existed back then, then the chute would already cause issues)

**Comment by MileyHollenberg** [comment]
Yes, that's working now (with a bit of help from ChatGPT-4, never done any Minecraft modding before :P ). Thanks for the tip on where to look :)
