### ISSUE TITLE
seek and floppies

### ISSUE THREAD

**Issue by istasi** [MightyPirates/OpenComputers#367]
file: test
        -- ABC
        -- DEF
        local f = io.open ( require('shell').resolve ('test'),'r')

```
    -- Works fine
    f:seek('set',7)
    print ( f:read('*line') )
    f:seek('set',0)
    print ( f:read('*line') )
```

this file works correctly in /tmp, writing:
        -- DEF
        -- ABC

whereas on a floppy, seek is ignore and writing:
        -- ABC
        -- DEF

**Comment by istasi** [comment]
fs.open ():seek is having the same issues

**Comment by fnuecke** [comment]
Hmm, which version of OC, and are you using the default settings or `bufferChanges = false`?

**Comment by istasi** [comment]
OpenComputers-MC1.7.2-1.3.0.203-rc.1-universal

Should be default, atleast i didn't know there was a bufferChanges to edit :P

**Comment by fnuecke** [comment]
When you say floppy, do you mean loot disk or a crafted one?

**Comment by istasi** [comment]
Oh god, i've been using computercraft ones -.-'

**Comment by istasi** [comment]
actually opencomputer ones works fine -.-

**Comment by fnuecke** [comment]
Ahh, yes, I can't emulate seek for the CC ones, because I only get a plain input and output stream.

Edit: oh, on a side note, the seek call _should_ return `nil, "unsupported operation"` or something along those lines when it doesn't work, so you could check for that, if you expect to work with unpredictable media.
