### ISSUE TITLE
(Non-issue) How do you achieve lua in minecraft?

### ISSUE THREAD

**Issue by PublicVoidUpdate** [MightyPirates/OpenComputers#3693]
i am working on some games of my own, and i want to have a similar terminal setup with custom programs and mapped output. im working in c in dev and want to use lua in interface. How did you map print to the screen in game, and have game components?

**Comment by TygoKooistra** [comment]
This project makes use of the Lua library*, the API allows C to create globals, tables, (C) functions, etc. (and of course load and run lua).
There are plenty of resources online about this, the terms you're looking for are 'embed lua in c'.
As for answering the question, they pretty much just override the `print` function to something that puts text on the screen**.

You'll also find it useful to know that some functions (specifically `computer.pullSignal`) actually yield to give control back to Java, and resume the Lua thread when an event (or timeout) is ready. This uses Lua coroutines.
All the lua code this project uses is somewhere in `src/main/resources/assets/opencomputers/`.

If you're going to run untrusted lua code in your game, Lua by default can access files, so you might want to consider [sandboxing](http://lua-users.org/wiki/SandBoxes). Limiting CPU time and memory is possible, see [machine.lua](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/lua/machine.lua) on this repo ([debug hooks](https://www.lua.org/manual/5.4/manual.html#6.10) are used for this).

Lua docs: https://www.lua.org/manual/5.4/ - includes C API docs

(*) Actually they use two other libraries, [eris](https://github.com/fnuecke/eris) with [luaj](https://github.com/luaj/luaj) as fallback. Eris is used because it can save and restore entire Lua states, LuaJ is used as it is written in Java.
(**) `print` specifically is more complicated, as its actually an abstraction provided by OpenOS of the `gpu` and `screen` components

**Comment by asiekierka** [comment]
Thank you!
