### ISSUE TITLE
Bad return code in function extractItem

### ISSUE THREAD

**Issue by BakermanLP** [MightyPirates/OpenComputers#382]
Hello,
it seems to be a wrong return code in the function extractItem. I try to extract items from a me network. The computer is connected to an adapter, that's sitting on top of a me controller.

Following lua line produces the wrong return code:
=component.appeng_blocks_controller.extractItem({damage=0,id=1,qty=64},"east")

But ... the item (in this case a simple stack of stone blocks) is exported in the right chest.

Can you help me?

Thanks

**Comment by BakermanLP** [comment]
Oh, forgot the following:
Minecraft 1.6.4
forge (I think 965)
appeng rv14 finale3
OpenComponents-MC1.6.4-0.2.0.44-universal.jar
OpenComputers-MC1.6.4-1.3.0.450-beta.1-universal.jar

**Comment by fnuecke** [comment]
For future reference, this would be better to report on the OpenComponents repo ;-)

As for the error that gets thrown, that method is provided by OpenPeripheral, and since CC always calls methods in the executing thread they have to synchronize stuff manually (which they manage [via package annotations](https://github.com/OpenMods/OpenPeripheral/blob/master/src/main/java/openperipheral/integration/appeng/package-info.java) AFAIK, note the 'OnTickSafe'). And that they probably do by yielding in the actual call. Which isn't supported in OC callbacks (because the computer state would become impossible to persist then). So you'll just have to suppress the error, I'm afraid (`pcall(c.extractItem, {id=...}, "side")`). It's interesting it does anything at all.
