### ISSUE TITLE
Split multiple CPUs into I/O Processors.

### ISSUE THREAD

**Issue by asiekierka** [MightyPirates/OpenComputers#393]
The architecture of OpenComputers 1.2.x and 1.3.x ties the architecture of the computer to the machine container, not the CPU. This may pose problems when we get multiple types of computers - architectures will not be easily interchangeable. Making the CPU store the architecture, though, will cause problems with servers which hold multiple architectures.

Here is a proposal we made on IRC: Every computer or server will only have one CPU. Servers will have one CPU - which will define the architecture - and multiple I/O processors, which will serve the current role of CPU (increasing the number of connectable components).

To ease the move, I propose that OpenComputers 1.4.0 converts multiple CPUs in servers to the CPU+multiple I/O processors automatically.

**Comment by Vexatos** [comment]
I wonder what different kinds of architecture would you like to see...

**Comment by asiekierka** [comment]
Nothing in OpenComputers itself, but many people have repeatedly asked for Python integration, for one.

**Comment by fnuecke** [comment]
Or JavaScript, or some old processor architectures or whatnot.

In generally I like the concept of splitting it into the i/o controller, because it is more logical than what we have now.

To elaborate a little, ideally it'd be possible to define custom architectures via items (instead of custom computer cases, as is required now) as soon as possible. Since I don't want to break the API again anytime soon, though, these changes will probably happen via IMC for now. Here's a rough plan:
- Internally, start switching to a new system for slot types, away from the enum based one. This system will be more like the new items API, but at least for now only accessible via IMC.  
  _Note: slot type enum will still work but will be deprecated, so it can be removed in 1.4._
- Introduce the I/O controllers, have CPUs double as IO processors (thus no behavioral change and no additional slot in the computer case GUI that I wouldn't know where to fit :P), convert the additional CPU slots in servers to I/O controller slots.  
  _Note: I think CPUs will continue to double as IO processors, since this will avoid any ingame breakage. When placed in I/O controller slots their architecture will simply be ignored. I/O controllers will be a lot cheaper than CPUs. The only thing that'll change is the API, in that the slot type enum will be removed._
- Assign an architecture to CPUs. Built-in CPUs will provide the Lua architecture, for example.
- Add an IMC call that allows mods to specify mappings of cpu -> architecture. Basically this would be a static method that gets called with an ItemStack (that's known to have a CPU driver) and would return `null` for unhandled CPUs or an architecture class.

I think this will allow for the fastest progress without breaking stuff. Feedback welcome.

**Comment by asiekierka** [comment]
"When placed in I/O controller slots their architecture will simply be ignored." - this should be eventually deprecated and removed as it might cause player confusion. But that can be, like, 1.5.

**Comment by fnuecke** [comment]
Yeah, I'm now thinking that will only apply to CPUs already in there, and it won't be possible to plug them in "manually". Also I think I like the name 'Component Bus' for the new item. To recap, Component Bus items will pretty much be server-only things, CPUs would act as before, but only one slot per server would be available, the remaining ones become Component Bus slots.

Now, as for CPU-Architecture binding, I've been thinking about this some more, and what I'd like to avoid is generating a sub-item per architecture (popping up in the Creative Tab e.g.). Instead I'd propose saving the arch in the CPU's NBT tag. For switching it I consider two possibilities: allowing registering a recipe to recraft a CPU to another arch, and simple Sneak-Right-Clicking the CPU while holding it in hand to cycle through available architectures. I'm kind of liking the latter, because it's easier to use _and_ implement (and can be explained by jumpers being flipped in the CPU or something :P).

**Comment by Techokami** [comment]
I like the idea of setting jumpers on a CPU! :+1:

**Comment by fnuecke** [comment]
Done in (for now) local branch.
