### ISSUE TITLE
Feature Request: Creative Server Racks

### ISSUE THREAD

**Issue by MyNameIsKodos** [MightyPirates/OpenComputers#394]
They would essentially be the same thing as a standard server rack, but with no power requirement, should a power providing mod be present.

**Comment by fnuecke** [comment]
Why not just place a create case underneath/next to it?

**Comment by MyNameIsKodos** [comment]
While that would work, it's rather ugly having a random computer case with no purpose other than to power a server rack.  Creative Computer Cases exist, it only seems consistent to have Creative Server racks at some point, even if it isn't as high on the priority list as font rendering or motion sensors.

**Comment by fnuecke** [comment]
Hmm, thinking about this some more, I think I'd actually prefer to not have the creative case generate energy (to allow testing energy consumption with it, too), and instead add a creative capacitor (that never runs out of energy). The creative case would still be relevant, because it allows easier testing without requiring a server, but would be a little more versatile at the same time, at the cost of needing one more block.

**Comment by MyNameIsKodos** [comment]
I like servers for testing over computers because of the 4th card slot, extra memory (I'm aware memory is configurable/toggleable), as well as a higher component count.  Though if you remove the infinite energy from a creative computer case, wouldn't that essentially just make the Creative case a Tier 4 case, since you'd still have the higher tier slots for, which really would just mean servers are still superior.  At that point you may as well eliminate the creative case altogether

**Comment by Vexatos** [comment]
:+1: For a creative capacitor!
