### ISSUE TITLE
Server Racks drain unlimited IC2 energy

### ISSUE THREAD

**Issue by Yepoleb** [MightyPirates/OpenComputers#404]
I connected a BatBox directly to the Server Rack and noticed, that it constantly consumes 32 EU/t, but the stored energy didn't increase. I tested this with multiple parallel MFSUs and got the same result. A Power Converter between the BatBox and Server Rack fixed the problem.

**Comment by fnuecke** [comment]
Versions of everything.

**Comment by Yepoleb** [comment]
I tested it with Minecraft 1.6.4, Forge 9.11.1.965, OC 1.3.0.507, IC2 2.0.397 and Minecraft 1.7.10, Forge 10.13.0.1180, OC 1.3.1.28, IC2 2.2.513

**Comment by fnuecke** [comment]
So, IC2 doesn't provide a proper side when injecting energy (it injects from 'unknown'), which won't work for racks as it is, and because IC2 ignores any unconsumed energy, well... energy goes poof.

I've added a (nasty) workaround for now, get build 518/30 from Jenkins. I've also opened a ticket on the IC2 bug tracker, will see if the workaround has to stay in long term.
