### ISSUE TITLE
os.sleep is broken if doDaylightCycle is deactivated

### ISSUE THREAD

**Issue by Yepoleb** [MightyPirates/OpenComputers#419]
The os.sleep function waits forever in worlds with the doDaylightCycle gamerule disabled.

**Comment by fnuecke** [comment]
Yes. That's why computers won't even start if it's disabled and show an appropriate warning/error.

The reason is that the alternative is tracking ticks per computer, which will eventually lead to different computers having different local times (depending on how long their chunks were loaded, as opposed to actual world time that passed).

I'd be kind of OK with that and giving computers a `computer.setTime(value:number)` method, to allow people synchronizing their computers' times manually, but that may a) break existing stuff b) be pretty confusing. Also, I have a somewhat bad feeling about this because I remember there were some other problems that popped up the last time I looked into this, but I can't remember what those were, exactly.

**Comment by MyNameIsKodos** [comment]
I'm just curious, what reason(s) would a person have to need a 'timeless' world?  I sincerely can't think of a situation outside of creative mode, where I would think the time wouldn't matter.

**Comment by Yepoleb** [comment]
Some mining worlds have the daylight cycle disabled. 

I would use the system time for sleep instead of the minecraft time. I don't see a reason for making the sleep function depending on the game time, because it counts in real seconds and everyone would expect it to wait exactly that time, no matter if the game time changes or not. Some servers allow players to change the time manually, that would cause issues as well. The time and date functions can still return game seconds, but durations should use system time in my opinion, because the game time can always change and isn't reliable for that reason.

**Comment by fnuecke** [comment]
Hmm, so you suggest decoupling uptime from general time? I suppose that would work. Could work. I'll have to double-check where what is used, but that seems quite reasonable. It'll still break other people's programs that expect the _game time_ to change (e.g. for network protocols doing time-based message validity checks). But I suppose that would be... manageable. They weren't usable in timeless worlds before, anyway.

**Comment by Yepoleb** [comment]
This doesn't only affect timeless worlds anymore. Currently every time someone sleeps or uses /time programs could break, because time is skipped or rewinded. In the first case, most timeouts would be canceled and in the second case they could wait much longer and time calculations may crash because they get a negative value. I suggest changing os.time to return a unix timestamp, like it does in the original lua implementation and add the game time as a separate function (or keep the game time and add a timestamp function). That would break stuff in all worlds, not just timeless ones, but I think that's the best way to fix this issue.

**Comment by Techokami** [comment]
I'd have game time a separate thing, and make general time be a UNIX time thing based on the server's current time. So you can get the real world time (which you know will always be ticking) and the game world time (which can be used for game-related functionality, if the world has a normal flow of time).

Now that I think about it... what happens if you try to use a computer in the Nether? Or in The End?

**Comment by LizzyTrickster** [comment]
@Techokami not sure on The End but the nether works (the world still ticks)

**Comment by Techokami** [comment]
@JoshTheEnder Yeah I just tested that myself, it does indeed work.

**Comment by fnuecke** [comment]
Hrm, about `/time set`, true, it influences sleeps, but that's actually intentional, so I guess it's a matter of perspective. I'd like to keep `os.time` the way it is, reporting ingame time as a unix timestamp, because that's just more... immersive. Unlocking `computer.uptime()` from actual world time however I can agree would be sensible, since state-wise computers are already fixed-points in time (given `/time set` is effectively time travel). I'll look into this now.
