### ISSUE TITLE
Request: Computer Mice (Does the same thing as a touchscreen does but works with keyboards) 

### ISSUE THREAD

**Issue by MFernflower** [MightyPirates/OpenComputers#42]

**Comment by fnuecke** [comment]
Hmm. Care to elaborate what you're thinking of? Two arguments for why there aren't any mice right now (because it's not like I didn't think about it) are: unlike keyboards, which serve to differentiate screens with a GUI from ones without one, I don't see an additional _practical_ value in adding mice. Also, if this were to allow tier one screens to process mouse input, I personally feel this would make it too cheap - note that starting with 1.1 you could always just meddle with the recipes if you don't agree with that, but still, I'd like some kind of consistent "default", so to speak.

**Comment by MFernflower** [comment]
Ok.
