### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by feldim2425** [MightyPirates/OpenComputers#424]
Some computers in multiplayer have an Index out of bounds Exeption if you type edit.
This error come randomly.

![2014-07-21_12 01 24](https://cloud.githubusercontent.com/assets/6705744/3642217/b8982e6c-10be-11e4-8101-9711318fea14.png)

**Comment by fnuecke** [comment]
Which version? Judging from the font, it's a 1.3.2 dev build? If this is a build < 539 / 46, please update; in those that _should_ have been fixed. Remember to re-install OpenOS if you have it on a hard drive (since it was a fix in term.lua) and to reboot either way (to force re-loading the term API) after updating.
