### ISSUE TITLE
Make programmable "ROM" with NVRAM

### ISSUE THREAD

**Issue by skyem123** [MightyPirates/OpenComputers#425]
In issue #172 (Built in persistant memory), I wanted to there to be a programmable ROM with NVRAM to be used to store settings. I didn't come up with I good way to make it work, but now I have an idea on how to make it work nicely.
### The "ROM"

The "ROM" will be a string of LUA code that has a limited size, programmable with a function, that is run right before loading init.lua.
Ideas for APIs:
- computer.setROM(data) will set the "ROM" code. Returns true if successful, false if not (too big, disabled in config, etc...)
- computer.getROM() will get the "ROM" code. Returns the "ROM" string if successful, nil if not.
  As a safety measure, in the computer GUI there should be a button to ignore the rom for one startup.
### The NVRAM

The NVRAM will be a string that has a limited size (more limited than the "ROM"), also programmable with a function. In the computer GUI there should be a button to clear the NVRAM (computers have this in real life!)
Ideas for APIs:
- computer.setROM(data) will set the NVRAM string. Returns true if successful, false if not (too big, etc...)
- computer.getROM() will get the NVRAM string. Returns the string if successful, nil if not.

**Comment by fnuecke** [comment]
Hrm, so basically one step 'lower' than `init.lua`? The thing is, I'm not going to have computer cases keep any 'local' data when they're broken (because I want to keep them stackable and dead-simple) so this would have very limited use anyway. So I'm not really convinced the added complexity is worth it.

Admittedly, I like the idea of having the 'bootstrap code' that's in the kernel, looking for `init.lua`s in a mutable pseudo-BIOS. But still...

**Comment by skyem123** [comment]
Yes. You got it. The "ROM" could be useful for things like PXE. The main difference between the NVRAM and the "ROM" would be that the data in the "ROM" would be run. (I also have another idea, writing to the "ROM" should be slow, so it doesn't get used for generic sorage)

**Comment by asiekierka** [comment]
I could add the NVRAM to Computronics and have, in fact, considered it.

The ROM, though, is going to be a bit harder to add without support from Sangar...

**Comment by Techokami** [comment]
@asiekierka Maybe we can use the EEPROM Reader block in Computronics for this? :O

**Comment by asiekierka** [comment]
@Techokami Yes, we may.

**Comment by fnuecke** [comment]
I'll be adding an EEPROM item. It'll be able to store up to 4KB (not set in stone, yet) of data. Arbitrary data. I.e. it'll just store a byte array. For Lua that will be a script; by default (i.e. the craftable Lua BIOS) that'll be the part that's currently in the `kernel.lua`, looking for file systems with an `init.lua` script. The `kernel.lua` will just get the data from the EEPROM built into the computer (there can be only one) and try to load its data as a Lua script (and I'll probably rename `kernel.lua` to `machine.lua`, come to think of it).

This should allow booting off of non OC file system components (e.g. tapes) and adds some more flexibility for other architectures (it could store the plain machine code a more low-level architecture would use to initialize its memory, e.g.). Or it can just house a really small, self-contained OS.

While this adds another hurdle to getting computers to start up, I think it'll be worth it in the long run. The main concern for me is currently avoiding existing worlds breaking, and making the transition as easy as possible. ~~For one, the floppy slot in T3 computers and robots will be replaced with an EEPROM slot. In addition, T1 and T2 computers will also get that slot, servers will lose their fourth hdd slot and instead get an EEPROM slot - I think this can be justified with the addition of the Raid block. Tablets will also get an EEPROM slot.~~ Meh, everything will just get a new slot for the EEPROM... I'll squeeze it in somewhere.

For computers/robots/etc already in the world, I'll try to inject the Lua BIOS so that they can reboot and work as before. ~~The main issue here are servers with a fourth HDD and T3+ cases, if they have a floppy in them (for robots and tablets the internal inventory isn't accessible anyway, so I can just add the EEPROM). I'm honestly not sure how to best handle those, yet, or rather if those will continue working at all (there's always a way, of course, but it might be too special-case-ish for my tastes). I could of course just add another slot, but that'll mean reworking the GUI a bit, and I hate messing with the GUI, so...~~

Anyway, that's the plan. If anyone feels something is very very wrong with it, let me know.

**Comment by Vexatos** [comment]
@asiekierka Incoming EEPROM reader support

**Comment by rmellema** [comment]
I think that this is a good solution for the last "magic" step of the boot process. I only have no clue how small 4KB actually is, so I have no way to properly judge the size of this thing.

**Comment by fnuecke** [comment]
To get a feeling for the size: almost all programs in OpenOS are smaller than that (except edit and sh), most libs also are, or at least _almost_ are (except edit and term). And the ones that are bigger could most likely be squeezed down by stripping whitespaces and shortening internal variable and method names.

**Comment by Vexatos** [comment]
OPPM is 14 kB, for reference, being roughly 475 lines of code.
