### ISSUE TITLE
API changes for OC 1.4

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#432]
I'll be using this issue to track changes that should be made to the API so I don't forget them for 1.4. If you feel some functionality is missing from the APIs, please feel free to bring it up in this issue.
- [x] Method to specify sound type / callback when filesystems are accessed when they are created.
- [x] Provide `isDirect` (and `limit`?) in the `Component` interface for custom architecture implementations.
- [x] Provide architecture getter in `Processor` interface, to allow CPUs to specify the Architecture they provide.
- [x] Change architecture registration internals - registering an architecture will make it available via the built-in CPUs, creating a machine with one will _not_ automatically register it anymore.
- [x] Remove the `Slot` enum, make these string literals instead? Would allow more flexibility in the future. E.g. no API change each time a new slot type is required, addons could easily define their own slot types, ...
- [x] Add `optXYZ` methods to `Arguments` for optional arguments (avoids manual `count() > x` checks).
- [x] Add `toArray` method to `Arguments` that auto-converts byte arrays to strings, to facilitate conversion (since this is _usually_ what people will want, in particular when writing callbacks for both OC and CC).
- [x] Add `getComponentIndex(address)` to the `Owner` interface to allow querying some "location" for certain components, mostly to be used for item components (e.g. get the slot a GPU is in, see #502).
- [x] Add interface for colored blocks to API (most notably for cables).
- [x] Field annotation, see #511.
- [x] Allow providing a priority for the `NamedBlock` interface.
- [x] Pass host along to `worksWith` (same as when actually creating the environments) to allow container specific drivers (mostly to allow upgrades to deny working in some containers, e.g. inventory upgrade only makes sense in robots).
- [x] Update the `ManagedEnvironment` prefab (see internal ManagedComponent class; also make that use the prefab).
- [x] Add interface that can be added to drivers to query the environment class, e.g. to allow providing static information about components (such as, as suggested by Vexatos, show ingame documentation of the callbacks in the env in the NEI usage info of items).
- [x] Provide a way to query for tablets - for example for drivers to decide whether they want to work with them or not.

**Comment by Eunomiac** [comment]
The Hologram API could use a method that lets you fill a column from a minimum point to a maximum point, without changing anything else in the column---currently, I think your only options are to iterate over each voxel with a "set" command, or fill from the bottom to a set y-level, and clear the rest of the column.

I would be great to have an easy way to blank out ALL startup text on displays---everything from the boot sequence, to the motd, to the little red ">>" prompt that appears.  Reboot, screen fades to black, and the first thing that shows up is text I wanted displayed in my autorun.

Finally (and perhaps this already exists, and I just don't know it), a debugging API would be icing:  Something that automatically writes variable contents, time stamp and line number to a debug file on disk when called upon in code, as well as logging any errors to that same file, would make my Christmas.

Hope that was helpful, and my apologies if any of these suggestions aren't really what you meant when you contemplated missing API functionality :)

**Comment by Kilobyte22** [comment]
we should maybe make a second issue for lua side api changes

**Comment by fnuecke** [comment]
Oh, oops, I completely forgot to reply to this.

Yeah, this was more intended for Java/Scala side changes (i.e. stuff relevant for modders using the API). But suggestions for changes on the Lua side are of course also welcome, though as @Kilobyte22 suggests it might make more sense to have those in an extra issue, since they can often be implemented in a non-breaking fashion.

~~hologram.fill: hmm, yeah, not sure why I didn't allow specifying the 'min' to begin with. This can probably be made a non-breaking change, by just taking one more parameter, and make it contextual (i.e. (x, z, max, value) and (x, z, min, max, value)).~~ Done.

Boot stuff: you can already do that, just edit `init.lua` after installing OpenOS to an HDD for example.

Debug stuff: not sure what you mean by that, exactly? If you mean automatically log stuff based on what happens in Lua to the _external_ log, not going to happen. Inside Lua you can use pcall/xpcall to handle errors and log them using the provided file i/o (`local f = io.open("tmp/custom.log", "a") f:write("ermahgerd it borked\n")` for example).

**Comment by Eunomiac** [comment]
> Oh, oops, I completely forgot to reply to this.

It's 28 days later (thankfully zombie-free), and I'm in the same boat :)

> Debug stuff: not sure what you mean by that, exactly? If you mean automatically log stuff based on what happens in Lua to the external log, not going to happen. Inside Lua you can use pcall/xpcall to handle errors and log them using the provided file i/o (local f = io.open("tmp/custom.log", "a") f:write("ermahgerd it borked\n") for example).

For the debug suggestion, I misused the word "automatically".  What I meant was a function (perhaps as part of the computer API?) like `debugInfo()` that, when called, would:
- return a table-list of all variables currently in memory and their contents
- a timestamp at the moment it was called, perhaps measured in milliseconds of uptime
- the line number containing the debugInfo() call
- ... and, depending on how your power overhaul proceeds, perhaps even some information on current power consumption

Players would then be responsible for parsing all of this information themselves and writing it to file or whatever---basically, a powerful information-providing function about the current status of the machine.

Alternatively, the above bullets could each be their own separate callback, maybe in a debugging API containing `listVariables()`, `getLineNumber()` and `getPowerConsumption()` callbacks?  (... as the timestamp could be done with os.time)

**Comment by fnuecke** [comment]
Oh. That sounds like full blown Lua debugger inside Lua? That's... a little too overkill, I'm afraid :-/ In particular since it'd need the debug library and that has the potential for a gazillion security issues.

**Comment by Techokami** [comment]
Maybe it could be a part of that Debug card you recently added?

**Comment by fnuecke** [comment]
Hmm, not really, it's a component, and components don't really have access to the underlying architecture (read: the Lua VM), and even when hacking around that by casting stuff it'd be relatively nasty and only allow variable inspection, which can pretty much already be done, just by inspecting `_G`. But timings for methods? That'd need tons of debug hooks, for example.

Oh, and the power consumption: what would that measure? The computer itself? All attached components? What if there are multiple computers in the same net? I think that would be better to handle using Lua itself (sampling `computer.energy()` over time).

**Comment by Eunomiac** [comment]
> Oh. That sounds like full blown Lua debugger inside Lua? That's... a little too overkill, I'm afraid :-/

Understood---what can I say, I have big ideas, not all of them are feasible ;)  Are either of the `listVariables()` and/or `getLineNumber()` callbacks possible on their own?  Each one would have its own independent value, at least to me.
- `listVariables()` would be the most helpful, but I suspect that's where the bulk of the issues lie.  
- `getLineNumber()` is already "accessed", so to speak, whenever the code errors out; I've often found myself wishing I could manually log this (without erroring out) as a sort of "checkpoint" to see whether a certain segment of code is being accessed, or in what order, or combine this with `os.time()` to see where my code is slowing down

`getPowerConsumption()`, on the other hand, was poorly thought out---of course, it would have to be a sampling over time to have any real "meaning".  I'm ashamed to say I wasn't even aware of `computer.energy()` (as you may recall, much of my work has been with Creative-mode computers/servers for an adventure map)---but would sampling it over time work if the computer were hooked up to a power source that continuously replenished its reserves?

Sure, it would be fairly easy to temporarily disconnect the computer from its power supply, run the code you want to test, and sample `computer.energy()` over time to get an accurate read of power consumption.  But, to avoid the need to disconnect a power supply, would a callback like `computer.usedEnergy()` that worked like `computer.uptime()`, reporting the power consumed since the computer booted up, be feasible?

**Comment by Kilobyte22** [comment]
If you really want the debug api. either use a lua interpreter written in lua (they exist but are slow as fuck) or you can use my fork. its a bit outdated though (the more recent versions don't compile, gotta fix a few things as soon as i have time), but has config options to enable for example the debug api.
Download:
1.6.4 - http://ci.cil.li/view/Unofficial/job/Kilobyte-OC-MC1.6.4/lastSuccessfulBuild/
1.7.10 - http://ci.cil.li/view/Unofficial/job/Kilobyte-OC-MC1.7.10/lastSuccessfulBuild/

**Comment by Vexatos** [comment]
@fnuecke Regarding the upcoming possible NEI support: Will that be in OC itself or should it be added by an addon? It should certainly be a config option to do, but I don't know whether you want it in OC itself. That might be quite a lot easier since OC is already having a list of all the drivers and TEs with environments (which should need that interface as well, those might just return their own class, I guess) in game at some point, and I am not sure whether that list is accessible to other mods (So an addon would need to search every class in the classpath itself to find appropriate drivers / environments).

**Comment by fnuecke** [comment]
@Vexatos I'd be happy to have that in OC itself.

**Comment by Vexatos** [comment]
@fnuecke That's some great news! But please make it a config option, not everyone might like that.

**Comment by fnuecke** [comment]
Sure!

**Comment by fnuecke** [comment]
All done in (for now) local branch.
