### ISSUE TITLE
Allow keyboard to be disabled programatically

### ISSUE THREAD

**Issue by WazWaz** [MightyPirates/OpenComputers#433]
For a purely touch-based application, it would be a better UI if the app could turn off keyboard input (so that simple right-click works), re-enabling it at exit:

```
local keyboards = screen.getKeyboards()
screen.setKeyboards({})
  ... do touch-only UI ...
screen.setKeyboards(keyboards)
```

Other ways:
- screen.setTouchPreferred(true) -- makes shift-click-to-type.
- component.keyboard.setEnabled(false) -- component-level disabled/enable

**Comment by fnuecke** [comment]
I personally like the `component.keyboard.setEnabled` variant, since it'd probably be the easiest to implement ;-)

But the second one (`setTouchPreferred`) is probably be better, flexibility-wise (shift right-click logic would simply be inverted), and it avoids forcing people to re-place keyboards if the program crashes.

**Comment by Wuerfel21** [comment]
Why replacing keyboards? Just re-enable it after a programs has run

**Comment by fnuecke** [comment]
Hmm, unless you're suggesting it should be reverted whenever _any_ program exits - which is not really an option, because it could interfere with program logic way too easily - how do you intend to do that without keyboard input? Again, I'm talking about when programs exit _abnormally_ (they crash), so they won't restore the keyboard enabled state themselves.

**Comment by WazWaz** [comment]
If there is a way to say "on exit, do f()", the program could decide this for themselves. This would also be useful for doing a signal.ignore upon termination. I'm a Lua newb, but I hear __gc metatable function can do this.

**Comment by fnuecke** [comment]
Mm, well, yes, __gc might be abused for that, but I'd consider that pretty bad style ;-) AFAIK it also only gets called once per object (which could lead to confusing bugs/behavior), and I can't remember for certain if it works in the LuaJ fallback at all (not sure if @gamax92 PRed that). I'd argue the cleaner solution would be a global pcall, e.g.

``` lua
function main()
  component.keyboard.disable()
  -- program proper
end
pcall(main)
component.keyboard.enable()
```

To clarify, my goals for this would be to
- give full control over this to programs, i.e. no automatic switching to and back by the OS.
- avoid users having to 'hardware reset' keyboards if a program misbehaves, hence me liking the 'mode toggle' idea so much ;-)

**Comment by Kilobyte22** [comment]
I vote for mode toggle as well. Just seems more advanced. And thats what OC is about after all

**Comment by Techokami** [comment]
Thirding the concept of a mode toggle!

**Comment by fnuecke** [comment]
Thinking some more on where and how to actually implement this, enabling / disabling the GUI on the screen seems more logical after all - I completely forgot that right clicking the keyboard will also open the GUI, and that would simply _always_ open the GUI, regardless of that setting.

**Comment by Kilobyte22** [comment]
Hmmm right, but many people (including myself) tend to stick the keyboard on back. I would suggest making the keyboard always open gui, for screen you can swap right-click and shift-right-click behavior
