### ISSUE TITLE
Robot unable to place Seaweed on water block (Pam's Harvestcraft)

### ISSUE THREAD

**Issue by Skudder1982** [MightyPirates/OpenComputers#438]
It seems that a robot cannot place Seaweed on water blocks though players can (without angel blocks ;-) ). Tried placeDown() and useDown() from above and place() and use() from an adjacent block.

**Comment by fnuecke** [comment]
Hmm, will have a look to see if this needs special checks or if it's something that might be wrong in general with the placement logic. Thanks for letting me know.

**Comment by Techokami** [comment]
Here's something to test: can you place a vanilla lily pad on top of water with a robot?

**Comment by Skudder1982** [comment]
Tried it - same issue.

**Comment by Techokami** [comment]
Welp, looks like Sangar has a bug to fix! Regular players are able to place lily pads on water blocks but robots cannot.

Sent from my Windows Phone

**Comment by fnuecke** [comment]
All right, so two things:
- Lily pads have to be _used_, not placed, due to the way their placement code is implemented in MC. I'm assuming the same holds true for Seaweed then. That is, use `robot.use()` and variants to place it, _not_ `robot.place()`.
- I did some tweaks to the code that determines where the robots are "looking" when placing/using items. From the quick batch of tests I did this doesn't break old stuff, but improves behavior for stuff like Lilies. In particular I added a range limit, so stuff like Lilies and Buckets can't be used more than one block space away anymore.

Please try the [latest builds](http://ci.cil.li/) when they're done (building at the time I'm writing this), and let me know if `robot.use()` works for Seaweed, and if so close this.

**Comment by fnuecke** [comment]
Closing since I'm assuming this is solved.
