### ISSUE TITLE
Server Rack resetting

### ISSUE THREAD

**Issue by Dylanavo** [MightyPirates/OpenComputers#443]
As far as I can tell, my Server Rack is resetting when it gets unloaded. I will test this further to confirm, as It may only occur when the server (MC server that is) gets shutdown/restarted.

The reset sets the range back to default (16), and also has the unfortunate side effect of deleting any servers in it. This can be a bit frustrating after spending so much time setting it up.

VERSION INFORMATION:

OPENCOMPUTERS-MC1.6.4-1.3.1.516-UNIVERSAL

**Comment by fnuecke** [comment]
The next time this happens, could you please check the (previous) logs (i.e. the logs from when it was _saved_) to see if there are any stacktraces / warnings in there?

This has been reported on IRC before, but I haven't been able to reproduce it, and I can only imagine something goes wrong while writing the state (since when reading, each 'part' of the rack is individually wrapped in error catching code, so at least settings like the range should still be restored properly).

Thanks.

**Comment by Dylanavo** [comment]
Hi fnuecke,
I'll keep an eye on it. It hasn't happened again yet, and the chunks have been loaded/unloaded plenty of times.

However the (MC) server hasn't gone down again yet, I'll be sure to check the rack/logs after the next server down time.

**Comment by fnuecke** [comment]
I've actually seen a robot that seemed to have had a similar issue (losing it's actual data) in my test world, though I also found nothing useful in the logs then. I have an idea of what _might_ be related, but it's just that, an idea (that being it might be related to the amount of data written leading to MC just not saving it at all, silently; I had a similar issue with computers themselves, which is why their state is stored externally; I'll try to switch to doing the same for screen buffer states).

I'll try to implement that change over the weekend.

**Comment by fnuecke** [comment]
All right, latest [dev builds](http://ci.cil.li/) have the externalized screen buffer storage change. I'll leave this open for a month or so (or rather a month after a release with the change in it) to see if this pops up again in those versions. If it doesn't I'd hope it fixes the issue.

**Comment by fnuecke** [comment]
Hasn't happened to me since that update, and haven't heard of it happening either, so I'll close this for now.
