### ISSUE TITLE
Monitors freeze on server reboot

### ISSUE THREAD

**Issue by applejag** [MightyPirates/OpenComputers#46]
On reboot the computers that are active seem to freeze and stop responding. The monitors stops responding unless we replace the cables from the computer to the monitor and the monitor itself. To be able to use the keyboard we have to replace the keyboard too.
And with replace I just mean breaking and placing again.

**Comment by fnuecke** [comment]
Sounds like the block update that's scheduled when the cable and keyboard blocks' TE is validated fails. I had some funky issues with those, which led me to schedule them at some time in the past to force them being run as soon as possible - otherwise they occasionally ran five seconds late, leading to computers dying because capacitors were still waiting for their block update... maybe your server doesn't like that. Or it still executes the update way too late. Anything that might shed some light on this in the logs?

**Comment by applejag** [comment]
This is getting really annoying since you have to go and replace all components after a server reboot, and since a lot of mods update and we get crashes back and forth we reboot a lot, like almost twice a day.

And when I say replace all components, I mean like cables, routers, disk drives, keyboard... Basically any block except the converter and the computer itself (the computer continues from where it left off before the server reboot, don't have to replace it).

Idk if the components go into some weird state or something, but I get kicked from the server with "internal server error" if I put in a disk in a disk drive after a reboot when not replaced it. 

I'll see what I can find on the server side errors..

**Comment by fnuecke** [comment]
I added some code to manually trigger a connect for the passive blocks on world and chunk load, which hopefully resolves the issue of those blocks not reconnecting. The internal server error surprises me, but may be related. I'll push another (final?) prerelease today. Please check if the issue is gone then.

**Comment by fnuecke** [comment]
[Prerelease 3 is out](https://github.com/MightyPirates/OpenComputers/releases/download/v1.1.0pre3/OpenComputers-1.1.0pre3.zip), please give it a try to see if the issue is gone.

**Comment by applejag** [comment]
From my experience, it works now!

**Comment by fnuecke** [comment]
Great!
