### ISSUE TITLE
Components (Screens/Holograms/etc) Emit Light Only When Powered

### ISSUE THREAD

**Issue by Eunomiac** [MightyPirates/OpenComputers#474]
**[Feature Request]** 
Currently, Screen and Hologram blocks (and perhaps other components) emit some light at _all_ times, from the moment they are placed, whether they're connected, online or receiving power.  

Would it be possible to have them emit light only when they are "active"---maybe they begin emitting light when first accessed via proxy/invoke/bind, and then stop emitting light when given a shutoff command?

I ask this because I'm creating an Adventure map that begins in a technological ruin, and I want the initial room to be pitch black until computers start to flicker on---an eerie, kind of LOST-ish vibe.  Right now, I've rigged up a deployer to place the Hologram block as part of this start-up sequence, to keep that area dark until ready... but that's rather clunky, and there's no way I can do that with my multiblock screens!

**Comment by fnuecke** [comment]
The reason I currently don't change this dynamically is because MC doesn't really do well with dynamic lighting changes. I'd basically need two _actual blocks_ to have different light levels for the "same" block.

For example: the vanilla furnace actually _replaces the block_ when it changes its state, to update the lighting (burning or not), which would be a pain for multi-blocks like screens. It's a pain even if not, because the tile entity would have to manually be transferred (which the furnace actually does), but that's a massive can of worms.

Another example of how messy lighting in MC is: redstone ore. Try placing a block of redstone ore, then walk on it - it'll be barely bright enough to prevent monsters spawning right next to it (check using NEI's spawn info overlay F7 thinger, e.g.). That's the ore's _own_ light level. Now place a torch on top of the redstone ore and break the torch again, and notice that _the surrounding area remains bright_. Until the ore replaces itself again to 'turn off' (same principle as with the furnace).

So yeah, TL;DR I don't really have the patience to mess around with MC's lighting system to that degree, in particular since I'd basically have to use up block IDs (real or virtual, either way not worth it IMHO) to make it work, sorry :-/

Edit: yes, an alternative _might_ be to force block updates on all nearby blocks, but I'm very worried about the performance of that approach, and the last time I tried it (that would be when I implemented the screen blocks) it didn't work very well, either, IIRC.
