### ISSUE TITLE
Wireless Adapter Block

### ISSUE THREAD

**Issue by Eunomiac** [MightyPirates/OpenComputers#475]
**[Feature Request]**
It would be fantastic (read: _magnifique_) to have a means of connecting components wirelessly, without needing a second computer or other go-between to interpret and pass along wireless messages.  

I'm thinking of something as simple as two "Wireless Adapters" that have to be specifically paired with each other.  From there, they behave as if they were a single Adapter block---a computer (or any component) attached to one of the adapters would have access to everything the other wireless adapter is connected to.

My motive here is that same Adventure map I mentioned in a previous feature request---I'm using a lot of Creative Cases and Command Blocks, and I'd like to be able to lock these devices away in some hidden Bedrock-encased bunker so that players can't get access to them simply by breaking through the screen and following the connections back.  (Right now I'm winding Cable through a clunky S-shaped Bedrock shield, and that's only going to work until Morph comes along and gives players the ability to navigate 1x1 spaces!  :) )

**Comment by fnuecke** [comment]
Hmm, so something like the linked card, but for actual component networks. That's actually quite an interesting idea. Takes a linked card into its inventory (so I don't have to store NBT data in the block item, and allows for some interesting things like 'dialing' into different component networks, by swapping out the card), constantly consumes a bit of energy (which would be irrelevant in your case, but generally speaking). Yeah, I think I can see that work.

**Comment by Eunomiac** [comment]
Exactly what I was thinking :)

The only problem I foresee is balance---if Adapters can communicate over great distances, it could potentially eliminate the need for the current wireless networking mechanic altogether.  I think it should be more difficult to increase the maximum range between linked Adapter blocks, than it is for wireless communication between computers?

Applied Energistics could be instructive:  Its Wireless Access Point had a single inventory slot for Range Upgrade items.  One of these upgrades only increased the maximum range by a few blocks, but they were stackable---up to 16, I believe.  

Perhaps something similar might be used here:  Wireless Adapters could contain two inventory slots---one for the linked card, and a second for a stack of moderate-to-highly-costed range upgrade items.  The need to supply these items in multiples to gain range would quickly ramp up the cost for long-distance Adapter-to-Adapter communications, preserving the value of conventional networked communication between separate computers.  And, instead of having a hard limit, this method would create an interesting decision point for the player on when to abandon linked Adapters for cheaper, conventional networked communication between separate computers.

I'm definitely quite excited about this idea---it would enable some really elegant compact builds, like floating monitors and such.

Oooh! Would it be possible to implement this as an attachment, like the Keyboard?  Maybe at a higher tier?

**Comment by fnuecke** [comment]
Hmm, I don't really think that's an issue - after all, linked cards already exist, and are without range limit as per their definition (since they also work across dimensions). If this is used for networking, the only thing you save yourself from is writing one or two lines of Lua code (receive network messages, re-broadcast them). Linked cards are much more expensive than wireless network cards (and this new block would, in addition, have its own cost - somewhere around Tesseract-ish), so unless you're so rich you don't care for material costs anymore anyway (at which point any discussion about balance becomes void), wireless networking is a very appropriate solution for medium-to-large sized networks.

Looking at it topologically, whenever you use a linked card you force a tunnel between two sub-nets. With wireless networking you have one interconnected net, which, for medium sized networks, is easier to deal with (at least IMO).

Oh, one more into the cost-argument: to avoid getting component overloads, if it's used for pure networking you will usually also want to additionally use at least one switch, to separate the subnets. Oh, and running energy costs.

I suppose I should draw up a couple of example topologies to compare costs, to make all of this less feels-right-based and more numbers-are-good-based. Which I will do when I have more time :-P

As for the attachment idea, I'll keep it a simple block (i.e. won't "pop off" if its surface is gone, among other reasons because IIRC I'd need a new block in 1.7 and while I continue keeping 1.6 up-to-date I want to avoid unnecessary differences in the branches). But I'll see what I can do to make it look appropriately fancy ;-)

**Comment by fnuecke** [comment]
So the main issue I see with having this available for non-creative gameplay is that it is _incredibly_ powerful (and yes, I think tesseracts are kind of cheating for not requiring energy to work). The best way to... balance this I could come up with so far is to have it consume energy. A lot of energy. Something along the lines of 50/tick to start working.

However, there's still the possibility of excessively misusing it for wireless power transfer. I'm not sure how best to avoid this. One way might be having it drain any energy exceeding some threshold from the network, so if the energy available in the network is larger than X, drain it down to X again. Another way might be draining a certain percentage from the network, but that could become quite... unstable. Either can be problematic due to OC's lack of finely grained control over energy distribution. I'm currently leaning the threshold way.

Thoughts?

**Comment by Vexatos** [comment]
I don't like this idea at all. Seems just too overpowered for me; cables and repeater programs exist for a reason.

**Comment by fnuecke** [comment]
I don't think it is "overpowered", not when it requires enough energy to operate. If you have some suggestions to disincentivise use of it, I'd be happy to hear them, at least. I think we had a similar discussion before; it's an alternative for the "lazy", but accordingly much more expensive (in multiple ways).

Come to think of it, this would even be better for (real) server performance, since it'd be a static, non-ticking link between two subnets, versus at least one additional computer. Which should not be the main argument, but is certainly worth keeping in mind, IMHO.

**Comment by Vexatos** [comment]
It should certainly cost a lot of power, maybe 50 or more OC/tick just to keep one running.

**Comment by fnuecke** [comment]
> The best way to... balance this I could come up with so far is to have it consume energy. A lot of energy. Something along the lines of 50/tick to start working.

So I guess we agree on that? :-P

**Comment by LizzyTrickster** [comment]
Perhaps have it consume 50/t as a base and an additional 10 for every component call that goes through it? And perhaps make it so that they don transmit power and both sides have to be powered in order to work? (energy costs applying to both ends at the same time)

**Comment by fnuecke** [comment]
Them not transferring energy is what I'd want, ideally, yes, but that's not possible with the way OC's network is structured internally at the moment - the power and component grid are one and the same. I may rework this at some point, but it's a much too massive change for now. As for component calls, those can't be tracked, I'm afraid, so while that'd be a nice way of balancing it, it's also not possible from a technical standpoint :( Thanks for the ideas, though!

One way to make it so that they virtually do not allow energy to be transferred, is to have each block consume math.max(50, globalBuffer / 2), i.e. if there's more energy than really needed in the subnet, consume all of it (half by each block of a pair). The problem I expect with that is that it'll be highly unstable, say this block tries to consume its energy before an attached power distribute gets to refill the network, or power converter does its job -> connection gone. And that's not something the player has any influence over - otherwise I wouldn't have a problem with it.

**Comment by LizzyTrickster** [comment]
How does the switch not transfer power? Or does it only recreate the network messages?

**Comment by fnuecke** [comment]
The latter.

**Comment by LizzyTrickster** [comment]
Ah, that’s a bummer

**Comment by Kubuxu** [comment]
@fnuecke the problem with consuming energy depending on buffer size is that network stability would be almost impossible to achieve. Computers use varing amount of power making it really hard to limit provided power just at the border. Also we, as players, do not know buffer sizes. Attaching fe. Advanced Cripter shouldn't spike energy usage of such network to 800/t. It would be extremely counter intuitive.

OC unit is old MJ, isn't it?? So IMHO even 50/t is too much. It is RailCraft max size boiler to handle just two of such blocks. Not everyone is using BigReactors.

**Comment by fnuecke** [comment]
> stability would be almost impossible to achieve

That's my concern, too, yes.

> Also we, as players, do not know buffer sizes

Not really true; you can easily see the networks overall buffer size using the analyzer, or via `computer.energy()`.

> So IMHO even 50/t is too much

I just had a look at [AE's quantum thingy](http://ae1.ae-mod.info/ME-Quantum-Network-Bridge/) and that clocks in at 40/tick. So I think it's at least in the right ballpark.

**Comment by Kubuxu** [comment]
In near future it might be possible to connect OC's bus via AE's P2P tunnels.

Is it possible to make the Wireless Adapter Block require external power source?

**Comment by fnuecke** [comment]
AE tunnels: oooh, that's cool. Will that be via Computronics or an extra mod or what?

External power: well... it might be. I mean, it'd basically have to be a common power acceptor (like converter, cases, charger, ...) and only use energy from an internal buffer, not from the network it relays. That still doesn't solve the issue of it relaying energy, too.

I actually think I'll scrap the idea of making this available non-creative for now, and look at that again after reworking the internal networking, i.e. separating power from component networks... which won't be soon, I don't think.

**Comment by Vexatos** [comment]
@fnuecke I am not sure whether that would be possible through Computronics, as the Tile Entity needs to implement Environment; I guess it's some AE2 thing.

**Comment by fnuecke** [comment]
I mean, if it can be done via an API I'd be cool with having that in OC itself.
I haven't had a look at AE2's API wrt that.

**Comment by Eunomiac** [comment]
I just caught this discussion, and hope to emphasize a few things right off the bat:
1. Intuitively, I don't quite "get" the overpowered argument.  Wireless technology of the sort contemplated here is trivial and omnipresent in the real world (I can think of at least three "wireless component" connections my computer is using right now---four, counting my XBox controller).  The only real in-game impact is the elimination of (cheap!) cables.  Sure, I can't wirelessly control a computer on the other side of the city---and I think some guidance can be taken from this fact (see below).  
2. A big motivation for this is not going to be laziness, it's going to be aesthetics.  OC cables don't lend themselves well to aesthetic builds, since they occupy a full block space.  Simply mounting a display monitor to a ceiling requires a 3x3 load-bearing column or 3-block thick walls, plus a 3-block thick ceiling, merely to conceal the cabling.
3. OC can already do this by replacing the Wireless Adapter with a Wireless Computer.  This is likely justified for some of the more elaborate builds, but requiring a second networked computer plus wireless event handler is a bit overkill for a ceiling-mounted monitor.

So, some suggestions:
1. One Component per Wireless Adapter --- This would certainly disincentivise the more balance-breaking builds by multiplying the impact of any increased power needs, and would certainly distinguish simple "ceiling monitor"-style builds from those builds that should require a more conventional wireless network.
2. Range Is Expensive/Limited --- Short-range communication (of the sort most aesthetically-motivated needs would be looking for) would, I think, be a lot less problematic/in need of balance, than long-range control.
3. Invisible/Intangible Cables --- Steve's Factory Manager makes fantastic use of a similar feature---you still have to connect every component (doubtless with expensive cables), but it's possible to camouflage and ghost them out of existence once you've set everything up.

... I'm sure I'll have more ideas, but those were just the few I had off the top of my head!

**Comment by LizzyTrickster** [comment]
The cables support either FMP's or Immibis Microblocks' covers, panels and such. You can always use those if you want to conceal the cable. 

Also: https://github.com/AppliedEnergistics/Applied-Energistics-2-API AE2 API for those who want to have a look

**Comment by fnuecke** [comment]
Regarding "overpowered", it's just a simple way of saying "it makes other mechanics feel superfluous, taking away too much from the existing gameplay". The other mechanic in this case being programming a computer to use networking to allow remote component calls.

Much of what you wish to use OC for is not compatible with "regular" OC gameplay, and must be considered creative-mode use. A core concept of OC is and should remain that you have to write programs to make things work. It's primary goal is _not_ to be an ingame administrative scripting system; _however_, I do see the applications for that and want to support it as much as possible - as long as it does not conflict with "normal" play.

Regarding aesthetics, as Josh mentioned, there's full support for FMP and IMB, so I honestly don't feel this is a very strong argument. There's _always_ some column that can be used to run a cable.

Regarding using a computer with a wireless / linked card, _exactly_! This comes back to the first point: I really wouldn't say it's only justified for "elaborate builds"; this is precisely what one of the primary gameplay pillars of OC is! Getting things like that to work via (potentially clever) programming.

Now for your suggestions; limiting it by component count is not ideal (imagine two of these with a bunch of capacitors and a power distributor on each end -> free wireless power transmission), but limiting it by _node_ count might work (that would include capacitors, cables, ...). Definitely something to think about. Range should not really be a consideration I think. It'll use Linked Cards, so there's no in character justification for a range limit. Invisible cables? Again, covers to the rescue!

**Comment by fnuecke** [comment]
Quick update: after adding AE2 P2P tunnels supporting OC networks, this sinks a bit on my priority list, as remote connections can be realized using AE2's Quantum Tunnels - yes, you need AE2 for that, but at the least the possibility exists now. I'll probably still add this as a creative-only thing, but no promises as to when.
