### ISSUE TITLE
Lock Creative Cases/Servers in Survival Mode (SSP and SMP)

### ISSUE THREAD

**Issue by Eunomiac** [MightyPirates/OpenComputers#476]
**[Feature Request]**
It would be very useful for Adventure map creators if we could safely use Creative Cases and Servers without having to worry about players accessing their contents.  A quick check (perhaps configurable) that makes Creative components inaccessible unless you are in Creative mode would be ideal!

**Comment by fnuecke** [comment]
Hmm, I suppose having to be in creative mode to change a creative case is a reasonable limitation. I'm assuming this is specifically because you still need user input, so you can't use the `computer.addUser` stuff for that? Meaning that'd stay untouched.

While on that train of thought, automated interaction with the creative tier case should probably be made impossible, too then, to avoid hoppers sucking stuff from the case, e.g...
