### ISSUE TITLE
out-of-memory with "pastebin run"

### ISSUE THREAD

**Issue by Akuukis** [MightyPirates/OpenComputers#479]
When I try to execute in shell `pastebin run m1Tnt0wv`, it apparently doesn't download all the file (643 lines), and gives error `tmp/[insert random number]:474: 'end' expected (to close 'if' at line 469) near <eof>`
but in the same time if I do `pastebin get m1Tnt0wv prog` and execute it, it works like it should.
I run into this bug while porting my ComputerCraft code to OpenComputers, and it worked correctly until few edits before and it keeps bugging like that. I was editing things between lines 164-254 at that time. **Restarting the world magically solved this bug.**
I will keep content of pastebin link intact so you could reproduce this bug.

**Comment by fnuecke** [comment]
Hmm, I can't reproduce it, I'm afraid. Maybe a silent out-of-memory error? How much RAM did the (ingame) computer you tested this on have? Which version of OC was this with?

**Comment by Akuukis** [comment]
That's sad, and I also today cannot reproduce that. Maybe that was because yesterday I was running pastebin, testing, editing my code and running pastebin again for 4+ hours and something filled too much? 
Restarting the computer didn't work, I tried that yesterday. And it showed other errors too like missing brackets on random lines where everything was ok. 
It has 512kb of RAM. Deleting custom content on harddisk didn't help. 
ComputerCraft.cfg says I have `version="1.3.1.266"`.
FYI I am also running mods CodeChickenCore, ExtraUtilities, Forge, IronChest, NEI, OptiFine, Waila.
I will report if bug comes back.

**Comment by Vexatos** [comment]
Seems to be some downloading error indeed. Either your internet connection is weird, or the drive was really lacking memory...

**Comment by Akuukis** [comment]
Ok, bug is back :D
1-2 hours ago I copied the content of `m1Tnt0wv` to another paste and worked on that one. While writing previous comment I downloaded & executed the `m1Tnt0wv` paste once, it worked, but afterwards neither the new paste `XYih4VfA` and the `m1Tnt0wv` works anymore, both giving similar errors like missing `end` or brackets at random lines of code.

**Comment by Akuukis** [comment]
I got `not enough memory` error when running a code that I downloaded through pastebin. But, after restarting robot there's no more `not enough memory` errors, code downloads and works like it should. For me that looks like a silent out-of-memory error where pastebin script or my code somehow overflows it over time.

**Comment by Akuukis** [comment]
The bug should be reproducable now, done the following 3+ times and it run out of memory.
1. make robot with 512kb ram, `install` openos, restart, remove diskette.
2. execute `pastebin run 0fnQvD1v 2` 27 times. (the code itself errors about misplaced brackets)
3. got `unrecoverable error: out of memory` or `Unrecoverable Error: error in __gc metamethod (not enough memory)`

Restarting the robot doesn't help, behavior stays.
Restarting the world with robot turned off doesn't help, behavior stays.

I made a script that goes until 27 tries (and once it did up to 80 tries) before runs out of memory. The behavior of output of computer.freeMemory() was really weird, jumping up or down for up to 150kb but general trend was negative.

``` lua
computer = require("computer")
shell = require("shell")
for i=1,100 do
  local ok, err = pcall(shell.execute,"pastebin run 0fnQvD1v 2")
  print("\n",i,ok,err,computer.freeMemory())
end
```

I will leave also this paste intact for you to reproduce.

**Comment by fnuecke** [comment]
> The behavior of output of computer.freeMemory() was really weird, jumping up or down for up to 150kb but general trend was negative.

Well the upward jump can be explained by the GC kicking in. To get a "reliable" value you'll want too take multiple measures across a number of `os.sleep(0)`s, e.g. `local mem = 0 for i = 1, 100 do mem = math.max(mem, computer.freeMemory()) os.sleep(0) end print(mem)`.

I am seeing that downward trend in free memory, but I can't quite pinpoint it, yet. Not sure if it's a Lua thing (e.g. tables' internal data structures never get "cleaned up" over the lifetime of the table IIRC, so even if an entry is removed, the table will usually be larger than it was before that entry was added), or a bug in the memory counter (comparing its output to that of `collectgarbage("count")` doesn't make that seem likely, though), or an actual memory leak, if so probably in the glue code.

This will probably take some time to figure out, though, meaning it'll most likely not make it for 1.3.3. For now throw some more RAM at your computers :-/

What exactly do you mean by 'behavior' stays? That the steps are reproducible or that the computer won't boot anymore and OOMs right away? The latter should be technically impossible because a completely new Lua state is created when rebooting... I'd have to guess that there's an autorun script that somehow causes this then, maybe?

**Comment by Akuukis** [comment]
> What exactly do you mean by 'behavior' stays?

I mean that steps are reproducible.

I upgraded OC to version="1.3.2.34" and MC to 1.7.10 and this bug is also present here. 

Also, while working on my code and experimenting with coroutines, I managed to make robot to freeze for 1sec and then MC crashed (see crash report http://pastebin.com/NChWtkNe). The weirdest thing is that MC wasn't able to start afterwards, and after fresh reinstall it crashed again in the same way (see crash report http://pastebin.com/26LBjkmY). I wanted to preserve the code but had to go and when I came back I forgot about that and continued to work and change things. Sorry, I will do nice report next time that happens. I don't know if this is related to this issue.

**Comment by fnuecke** [comment]
OK, good, thanks for clearing that up. That means MightyPirates/OpenComponents#22 is probably related / the same thing.

As for the other isssue, looks like the player profile got corrupted. Since both of those logs seem to be from loading the game (both go through GuiSelectWorld) there's no way to tell if this was actually caused by OC, though. A log for the actual initial crash would be needed. Did you paste the wrong one by accident for the first one?

**Comment by fnuecke** [comment]
All memory leaks in OpenOS should be fixed now; make sure to re-install OpenOS and reboot your computer(s) when testing.
