### ISSUE TITLE
LanteaCraft and/or Greg's SG Craft support

### ISSUE THREAD

**Issue by Snakybo** [MightyPirates/OpenComputers#48]
It would be nice if you could control stargates from either LanteaCraft or Greg's SG Craft  with computers.

**Comment by applejag** [comment]
I think computercraft can control SG Craft gates, but that would be quite a work around

**Comment by LordFokas** [comment]
Well it will be able to control StargateTech 2 gates soon... does it count? :p

**Comment by fnuecke** [comment]
Since I don't use either of the two mods and hence have no idea what would have to be done, and it doesn't sound like the computer or adapter would have to implement an interface (unlike bundled redstone for example) it would probably make sense to implement this as an addon component/driver. So in short: I won't implement this, but someone else might.
