### ISSUE TITLE
libraries from openOS or OpenComputers?

### ISSUE THREAD

**Issue by Akuukis** [MightyPirates/OpenComputers#489]
Hello,
I am confused about libraries. If I am going to make a new loot disk, which libraries are always usable (like Lua libraries specified in kernel.lua) and which are available only when OpenOS loot disk is installed?

**Comment by fnuecke** [comment]
Have a look at [how the sandbox is constructed](https://github.com/MightyPirates/OpenComputers/blob/master/src/main/resources/assets/opencomputers/lua/kernel.lua#L69-L290), everything in there plus [component](https://github.com/MightyPirates/OpenComputers/blob/master/src/main/resources/assets/opencomputers/lua/kernel.lua#L483-L547) (minus primaries system), [computer](https://github.com/MightyPirates/OpenComputers/blob/master/src/main/resources/assets/opencomputers/lua/kernel.lua#L549-L593) and [unicode](https://github.com/MightyPirates/OpenComputers/blob/master/src/main/resources/assets/opencomputers/lua/kernel.lua#L595-L630) are available in `init.lua` scripts.

Further talk on this would better go onto the forums, though, since it's not a bug or feature discussion :-)
