### ISSUE TITLE
Ability to set state of bundled cable

### ISSUE THREAD

**Issue by makkarpov** [MightyPirates/OpenComputers#494]
In redstone card/redstone controller there is a function `setBundledOutput(side, color, value)`. Why there is no function to set state of whole cable? Setting each wire indvidually is very slow, and takes about 2 seconds. I think it's too slow because a every call is synchronous, so a functions like `setBundledState(side, bitmask)` and `getBundledState(side)` will be useful.

P.S. Sorry, I don't know how to attach label "feature request" in GitHub

**Comment by fnuecke** [comment]
Hrm. What would that state be? Channels (colors) aren't boolean after all, i.e. they can't be represented by a single bit, really. And different mods have different max values for the signal strength, so there's no sensible automatic 'on' value, either. If anything, I suppose an alternative signature could be `setBundledOutput(side:number, values:table)` with the table being a map of color to value.

The getter is a direct call, so there is no real reason to add an overload for that (since it returns immediately anyway).

**Comment by makkarpov** [comment]
Yes, the table will be a good choice. Since the cables are usually 'digital', there is an another possible signature - `(side: number, bitmask: number, value: number)`, that set a cleared bits to zero and setted bits to `value

**Comment by fnuecke** [comment]
Which cables are digital? The only ones I know aren't: Redlogic and Project Red are  0-255 and Rednet is 0-65535 IIRC.

**Comment by makkarpov** [comment]
Yes, cables are analogue, but use cases where signal strength really matters are rare. And ProjectRed logic elements operates on digital signals. The only analogue element in ProjectRed is comparator

**Comment by fnuecke** [comment]
5a27e601c4ce5762d93cd0cb7f5b63fbd8168899
