### ISSUE TITLE
at altitude 255

### ISSUE THREAD

**Issue by Akuukis** [MightyPirates/OpenComputers#507]
Hello,
1) The highest point I can place a robot (or anything else) is at 254, but robot is able to move up itself into 255. That's weird to me. Is that my modlist problem, robot bug or undocumented normal behavior?
2) At altitude 255 `robot.detect()` returns `false, "air"`, but it cannot move there. Imo it should return `true, "air"`. Should it be considered a bug or undocumented exception?
3) At altitude 255 `robot.up()` returns `nil, "impossible move"`, but this error message is not in a list of `robot.detect` like is said on wiki. Is this a bug or undocumented exception?

I would suggest to add "impossible move" to `robot.detect` for situations like this and also for other server-side restricted movement like claimed land, force fields, and anything else I couldn't think of.

Note: all numbers are taken from F3

**Comment by skyem123** [comment]
The thing with placing the robot at Y=255 is actually a vanilla thing.

**Comment by fnuecke** [comment]
1) Yeah, as skyem123 said, that seems to be a vanilla weirdness thingy. E.g. I can't place a dirt block at the highest level, but I can place a torch. I suspect it's some odd check in the placement logic.

2) Is kinda deliberate, since it's based on the 'blockExists' check, which also neatly takes care of other "out of bounds" areas e.g. end of the world (x|z < -30000000 or x|z > 30000000) and for unloaded chunks - in particular for the latter it just means "can't really say right now". Sure, an extra check would be possible, but it's easy to differentiate in Lua by just trying the move and checking if it succeeded - which you'll have to do either way, if you want reliable movement, because some block might have been placed between the detect and move calls, or an entity might have moved into the way.

3) Yeah, that's not in the wiki right now, it should go into robot.forward etc, since it's only returned by those. Will add.
