### ISSUE TITLE
Adapter components misbehaving

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#510]
When I tested my railcarft components, I kept using the same adapter and just placed different driver components adjacent, so when I tested a different component, I broke the old one and placed the new one there. I found out that the component address stays the same, which could be due to the fact that the adapter is the same, but I also found out that the component type stays the same, so I for example replaced a routing detector with a routing switch, but when I typed `c = component.routing_switch` and `=c` in the Lua interpreter, it was showing the methods of the switch and "type=routing_detector". This happened due to the fact that the routing switch and detector do have the exact same methods. When I replaced a routing detector with, for example, a routing track, `c = component.routing_track` was working, but `=c` threw a kernel error "no such method" and the lua interpreter crashed, bringing me back to the shell. Apparently it was still searching for the methods of the component "routing_detector", which aren't existing on the routing track.

**Comment by fnuecke** [comment]
This is half bug / suboptimal behavior, half user-error.

What's suboptimal is that the address can stay the same for blocks of different types; I'll see what I can do about that without breaking things horribly. The reason this data is retained at all (across 'no block' states) is to keep the state of blocks in neighboring chunks across such chunks' unload / reload in case the adapter is placed on a chunk border.

What's sorta buggy is the name/type not changing thing, but I _think_ what's happening here is that the cached proxy for that address is re-used, see next point. So that'll sort itself out when avoiding to load inapplicable data.

What's user error is trying to access your saved component proxy (`c`) after it was invalidated (the component was removed). While the error would usually be different (`no such component` instead of `no such method`) it'd still error.

**Comment by Vexatos** [comment]
Nono, I did close the Lua interpreter and re-started it after I replaced the component, to make sure all the variables are gone again.

**Comment by Vexatos** [comment]
Can confirm it's fixed now. Thank you :+1:

**Comment by fnuecke** [comment]
Great, thanks :-)
