### ISSUE TITLE
Feature request: Expose fields in environments to computers.

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#511]
Basically an Annotation like `@Callback`, just specifically for fields in the environment. If annotated, that field will be added to the table of usually functions `component.<something>` provides. Annotation should be ignored if the class of the field doesn't match. Supported classes should be the same as supported for the return value of `@Callback` methods, so the primitive types, Strings and Maps.

Probably also ignore any non-final field, as that might be a lot harder to implement, so that every field has to be declared public and final.

``` java
@ExposedFieldOrSomeBetterAnnotationName
public final String exposedField = "test";
```

final would remove a lot of tedium, probably, and component tables should be readonly anyway if they aren't already.

**Comment by Kilobyte22** [comment]
i would combine  this with ability to use setters/getters. Valid names for getters should be getVar (or isVar for boolean) and var(). for setters setVar() or var_=(). (second alternative is for our fellow scala devs). The actual implementation would be through metatables. However i do see one issue: if you were to list table contents you wouldn't see those variables, since there is no __next or __pairs. 

But why getters/setters? well, basicly sometimes you need to do more than just storing a setting, but using `component.my_something.some_setting = some_value` just seems better. Now, if this gets liked, i may go ahead and PR it, but it would likely not be in before 1.4 because it would change the API (due to addition of annotations).

**Comment by Vexatos** [comment]
@Kilobyte22 Maybe adding one annotation I suggested for `public static final` fields, so just some constants you want to expose, and one annotation @GetterCallback and @SetterCallback extending `@Callback`, which take the field they are getter/setter of as an annotation parameter.

**Comment by fnuecke** [comment]
Setter and getter annotations? This sounds overly complicated to me. Here's how I'd imagine this could look like:

``` java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface Field {
    boolean getter() default true;
    boolean setter() default true;
}
```

With the value of `setter` being overridden by present `final` modifiers / raising an error on component registration.

This would define whether __index/__newindex error or actually do something. As for the table listing, there is in fact `__ipairs` and `__pairs` in Lua 5.2, so that would be doable.

For simplicity, field access would always be direct (i.e. from the executor thread). If one needs more flexible getters or setters, there's still `@Callback`, after all.

Now, the main downside I see with this is that it requires a more complex implementation of the component proxies on the Lua side, meaning more non-user/player-controllable memory overhead. Will have to see how much of an impact this will have, and how much of the proxying can possibly moved to 'userland' (the main reason it is in the kernel is to allow shortcutting some checks for performance, IIRC).

Either way, as Kilobyte said, the earliest this will be implemented is with 1.4.

PS: wow, there's actually a Github user name "Callback", I wonder how often he gets pinged :-P

**Comment by Kilobyte22** [comment]
i think he meant something like

``` java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface GetterCallback {
    String value(); // the field this is the getter for
    boolean direct() default false;
}

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface SetterCallback {
    String value(); // the field this is the setter for
    boolean direct() default false;
}
```

Usage would then be for example:

``` scala
private var _myvar = "default string"
@GetterCallback("myvar", direct = true) def myvar = {
    println("Getting myvar")
    _myvar
}
```

Which is IMO a pretty decent idea. I would combine this with your suggestion though so developers can save a few lines of code. You might also want to pass more parameters than i did, similar to a regular method call

**Comment by fnuecke** [comment]
Hrm, I see. That seems reasonable. I guess. Though just from a... aesthetic standpoint I think I'd prefer those as static inner classes of the callback annotation (i.e.you'd have `@Callback.Getter`).

**Comment by Kilobyte22** [comment]
also, it might be wise to also give the field annotation a 'value' field containing the target name (defaults to empty string which represents the name of the feel that is being annotated). This would come handy for scala devs:

``` scala
@Field("myfield") var _myfield = "default"
```

**Comment by fnuecke** [comment]
Yeah. Though I'm not convinced the field annotation is really... worth it, with the getter/setter annotations (which, for completion, would probably extend the normal callback annotation, I'd imagine).

**Comment by Vexatos** [comment]
The getter and setter methods are mainly there for accessing normal fields properly; what I suggest the `@Field` (Or `@FinalField` if the first has a better use) annotation to be is

``` java
@FinalField("myfield")
public static final String myfield = "I really need to expose this field because it contains important information, for example some conversion ratio";
```

<sup>(Yes, it's java, deal with it.)</sup>

The main point being to have `@FinalField` require `public static final` fields, which would make mod developers able to do things like the Sides API without having to make their own filesystem, just a final field containing all the information they want to expose.

**Comment by fnuecke** [comment]
> Though I'm not convinced the field annotation is really... worth it, with the getter/setter annotations

That statement is still true. Actually, on further thought, I think I'm actually against field annotations for the reason that they'll be impractical in all cases where the OC API is optional - fields, unlike methods, can't be stripped using one of FML's `@Optional.XYZ` annotations, after all, so an annotation on it would make the OC API a hard dependency. The other downside is that it further blows up the already hard-to-navigate API, but that's something that only irks me, not something I'd decline this over.

Consider the alternative 

``` java
@Callback.Getter("myfield") public Object getMyField(Context ctx, Arguments args) { return myfield; }
```

which isn't really that bad and would be the same from the Lua side of things.

**Comment by Vexatos** [comment]
Of course that would work, the only difference being a `()` in the code. I just thought some way to properly expose fields might look much better, as you don't have to use a function to provide some constants.

**Comment by fnuecke** [comment]
Uh, no. No `()`. That'd exactly be the point of the getter/setter callback subtypes.

**Comment by Vexatos** [comment]
Ah, then getters and setters would just be wrapped into a field, and whenever that field gets read/written to, the appropriate callback method is being called?

**Comment by Kilobyte22** [comment]
Yes that would be how it works. I mean, we got metatables

**Comment by fnuecke** [comment]
Implemented in (for now) local branch.

I decided to just go with additional fields for the existing callback annotation, makes it much easier to work with and is sufficiently easy to use (`@Callback(getter = true, setter = true) ...`).
