### ISSUE TITLE
[bug] Crash when placing hologram projector.

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#512]
I'm crafting hologram, tier 1 and tier 2, and when I place the projector, the game was crashed. Only me on server. When I'm trying to get on server, client crash. My friends must destroy the projector. They can place this block with no problem, but I'm can't.

**Comment by fnuecke** [comment]
Crash log?

**Comment by ghost** [comment]
Game console after crash: http://pastebin.com/pAQbZw39
/.minecraft/crash-reports - empty
/.minecraft/hs_err_pid3900 - http://pastebin.com/tc1Z66pz
/.minecraft/logs/fml-client-lastet - http://kgielo.pl/fml-client-latest.log
/.minecraft/logs/latest - http://pastebin.com/NaLhABTt

sorry, for my bad language, I'm from Poland ;)

**Comment by fnuecke** [comment]
Hmm, try updating your graphics card drivers. What graphics card do you have?

**Comment by ghost** [comment]
Graphic card is ATI Radeon HD 3450

**Comment by Techokami** [comment]
> ATI

Well there's your problem. ATI cards are notorious for not playing nicely with this mod. :frowning:

**Comment by ghost** [comment]
Any help?

**Comment by fnuecke** [comment]
> Hmm, try updating your graphics card drivers.

Are your drivers up to date?

Aside from that, from the last time I researched that error I remember stumbling upon a few claims that this code may be caused by [DEP](http://en.wikipedia.org/wiki/Data_Execution_Prevention), maybe try disabling that. Aside from that, try running a memory check. Since this is the first time this has been reported it might be a hardware issue.

Alternatively... I wonder, this might be a well disguised "out of memory" error on the GPU. How much memory does you GPU have (and how much do your friends have)?

**Comment by fnuecke** [comment]
Glad to hear that solved it! And thanks for offering, but I think I've got things covered for the time being :-)

**Comment by fnuecke** [comment]
Sure, thanks!
