### ISSUE TITLE
Overhaul power support

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#529]
Soooo... with all the fuss about power systems in the recent days, I've been thinking a bit on how OC handles power support from other mods at the moment, and it seems a bit... lazy. So here are some ideas on how this may be alleviated in 1.4:
- Make a clear differentiation between "electric" power systems and others. From my understanding, that would be IC2, Factorization Charge, Mek/UE/Galacticraft Joules as electrical ones, and RF and MJ as non-electrical ones. Other opinions?
- Use that differentiation to make blocks like computer cases, server racks and so on only accept _electrical_ energy directly. Force everything else to go through the power converter.
- Pick up on mods' particular mechanics, e.g. only accept packets up to a certain size from IC2, if it goes slightly over, make things go haywire (computers crash, screens display random characters), when it goes way over, blow up.
- What might be better/more specialized behavior for the other systems?

Feedback from those more familiar with the intricacies of the diverse power systems would be _very_ much welcome! Feedback in general, as to whether this would be a good or bad idea is, of course, welcomed, too.

**Comment by Wuerfel21** [comment]
wierdnes yes, blowing up no

**Comment by Kubuxu** [comment]
After 2,5h of crafting I finished my first super hi-end computer. Let's place it over here... nooooooooooo.
Please without blowing up.
If first example wasn't enough imagine reverse placeed transformer in server room.

**Comment by fnuecke** [comment]
Wow, relax. That'd be a config option, if anything (defaulting to off). It was meant more as an example of what I mean by that, anyway ;-)

**Comment by Techokami** [comment]
Have you ever used IC2? Try sending high voltage directly into a macerator.

Sent from my Windows Phone

**Comment by Wuerfel21** [comment]
Not in IC2 eperimental, through.

**Comment by Wuerfel21** [comment]
Oh, and Switches should scramble messages

**Comment by kubeliv** [comment]
This might be completely off-topic, but what about power-supplies? Feed power into the case, and then any adjacent peripheral is powered, to a point. Different tiers can withstand different amounts of power coming into them, and can power more advanced things.
-- Just an idea --

**Comment by ingie** [comment]
the thing with electricity tho is that one doesn't plug a home computer into the 3 phase bus-bar running into one's house... you plug it into the consumer socket... to this extent, i think the power converters serve that role... 

consider RF/MJ and IC2/etc, as a 3 phase bus-bar... in factories, big machines _are_ plugged into 3 phase... computers [mainframes excepting] generally aren't ... analogise the "big machines" to the other tech mod's machinery. 

with that in mind, i'd say it's better [ read: more realistic ] as it is...  although the cable being both network _and_ power is a bit wrong - PoE systems not withstanding.

with the PoE in mind, then one would expect that switches and "small devices" could be powered off the current "net" cable, but computers/ screens/ major "main" peripherals should be powered via a separate [new type of] power cable from the power converters whose job it is to convert the "bus-bar 3 phase" RF/MJ etc down to the "wall socket" 240/110V suitable for the consumer devices.

just my thoughts :)

**Comment by fnuecke** [comment]
Yeah, for the multiple tiers, I've actually been thinking about having "normal" blocks accept lower... "volumes" than the converter. For most mods that'd just mean slower intake, for IC2 in particular this could mean different packet sizes (e.g. computer case only accepts ULV, convert accepts HV or something like that). That would also give the converter more of a raison d'être again.

As for extra power cables, I'd be happy to hear what others think of this, but I personally think this is outside the scope of what the mod should focus on. It might be reasonable to add some cap on the power throughput of cables / blocks in general, but that would require a major rewrite of the underlying implementation of how power is handled inside component networks (which might not be a bad idea, though...)

**Comment by Eunomiac** [comment]
A few thoughts:

**In General, Exploding Machines Is Silly:**  We have these marvellous inventions called "fuses" that prevent things like power surges from making a crater out of one's office, and yet some of the most advanced tech mods in existence operate as if fuses were never invented.  It amazes me that I can build a GregTech Fusion Reactor, but I'm incapable of installing a simple fuse into my machines to prevent them from exploding.  Of course, if a machine is inherently dangerous (e.g. a nuclear reactor, steam boiler, pressure chamber), then explosions should definitely be part of the gameplay.  In general, I think a machine should simply turn off if it receives too much electricity---or, for especially sensitive (i.e. high-tier) computers and servers, perhaps a special "fuse" upgrade might be required to avoid damage to the system... but even then, nothing should detonate, whatever the source mod's mechanics are.  Maybe internal components like CPUs break down, either frying out or lowering in tier?

**RF vs. MJ:**  I'm not sure what the future holds for MJ, which is a shame, because I agree with CovertJaguar's point that RF (and other lossless, set-it-and-forget-it power systems) have oversimplified power generation.  But even though RF and MJ convert linearly, I think RF has more in common with the electrical systems you mentioned than it does with MJ (in terms of storage, lossless transmission, etc.)---and considering how ubiquitous RF is becoming, I don't know if it's a good idea to distance OpenComputers from it by requiring the use of power converters.

**Power Cables & Power Overhaul:**  To be honest, I don't think this should be a high-priority focus.  Power in Minecraft has become so "easy" (for lack of a better word) that, by the time a player has accumulated the resources to build any given tier of computer, they should have no problem jumping through any power-related hoops.  Much like channels in AE2, I think there's a risk of tedium trumping fun if too much focus is placed on power mechanics.  In my humble and respectfully-tendered opinion, I think all you need to do is (1) limit the amount of power each tier can use, and (2) ensure the power costs for individual computer operations are high enough that players are forced to think about what they're doing with their computers---and, combined with (1), make them decide whether to invest in an upgrade or attempt to write more efficient programs.

**Comment by fnuecke** [comment]
Thanks for the input!

For the first point, my argument here is that this would only apply for a mod _that does that in the first place_, so people powering it that way might (should?) even expect that to be what happens. Of course the tooltip would have to let people know this is the case (i.e. mention the maximum allowed EU packet size/GT voltage). That wouldn't apply to RF and so on.

RF: well, lore-wise it doesn't really have anything to do with electricity, from my understanding, but I see how the omnipresence of RF would encourage direct support in most machines... so yeah, I guess that'll be the way it'll be. Might still have some mechanism in place to limit the amount of RF/t so that normal machines accept less than the converter, for example.

I haven't played much with AE2, to be honest, but from what I've seen I actually really like the channel system, but that might just be a computer science/networking person thing. I don't want to overengineer the power logics in OC, nor even put a _focus_ on it. I just think it's fair to have a look at how certain power systems are "meant to be used" and try to incorporate that.

Throttling the throughput by tier is a good idea, I think, I like that.

As for the consumption, I personally think it's in a pretty good spot, but, as always, I'm open to feedback there. So the main energy sink where throughput actually matters will probably remain robot chargers. Differences in throughput probably won't have a massive effect on gameplay (and IMHO shouldn't, again, OC's focus shouldn't be on the power handling), but it'd just make the whole thing feel a little more... polished?

**Comment by twothe** [comment]
The problem I see currently with power support is that you actually need a complete different mod just to run OC properly, with all the pro's and con's of that mod. I would love to see some mod items being added that would allow me to run OC standalone while power usage is active. Namely these would be the 'dirty' coal generator and the 'clean' solar generator (as in robots). Or maybe just make a block that accepts one of those robot upgrades?

I like how OC currently handles most power APIs by simply accepting them, I wouldn't want to add "yet another power converter" to my system, because it kind of breaks the immersion of my main power providing mod. What makes "sense" is a question of the point of view. Even with strange power concepts like force power, the entire system "makes sense" and from that point of view the illogical thing would be the converter that converts force into "some strange other kind of energy".

**Comment by Eunomiac** [comment]
> For the first point [re: exploding machines], my argument here is that this would only apply for a mod _that does that in the first place_, so people powering it that way might (should?) even expect that to be what happens.

I'm certainly not opposed to a power system that works this way, especially if it's configurable.  But I can't shake my general view that exploding machines in any mod strains immersion/suspension of disbelief (with the already-stated exceptions for things like nuclear reactors).  Regardless of the source of the power, if it makes sense that a computer would have a fuse or surge protector, I think that's reason enough to immunize it from explosion.  (And it's my opinion that, with the exception of especially delicate (i.e. high-tier) computers, it does make sense.)

> RF: well, lore-wise it doesn't really have anything to do with electricity, from my understanding ...

True.  _(Digression:  Despite my dislike of how RF oversimplifies power systems, I think it's probably the most "in-theme" power system for Minecraft, lore-wise:  Not only does it invoke the principle vanilla mechanic for high-tech energy (i.e. redstone), the concept of power transmission through "flux" is good science.  Thermal Expansion, in general, is really good at coming up with plausible sci-fi themes for its more magical components---tesseracts are another great example.)_

> I haven't played much with AE2, to be honest, but from what I've seen I actually really like the channel system, but that might just be a computer science/networking person thing.

I think you've hit the nail on the head right there:  AE2 channels are popular among people who enjoy setting up complex networks... but are unpopular among people who don't.  AE1 catered to both crowds, while AE2 forces a degree of networking complexity that can be very frustrating and opaque to people who want to have fun with AE's mechanics without having to worry about channel counts each time they add a Level Emitter to their system.  (But that's another digression: back on point!)

> Throttling the throughput by tier is a good idea, I think, I like that. ... Differences in throughput probably won't have a massive effect on gameplay (and IMHO shouldn't, again, OC's focus shouldn't be on the power handling), but it'd just make the whole thing feel a little more... polished?

Actually, I think a little focus on "making power matter" in OpenComputers could be a _very_ worthwhile endeavor (after you give me my Wireless Adapter block, of course ;) )!  To the extent that it ties into coding practices, this could be a very clever way to encourage efficient programming.  I _really_ love the idea that a sloppy coder (e.g. me) might need a Tier 2 machine (and its higher power allowance) to accomplish what a good coder could do with a Tier 1 machine.

The critical point here (and what would distinguish this from AE2's controversial channels) is that an _alternative_ exists for people who don't want to worry about power consumption and efficient coding: simply pay the cost for a higher tier of machine.  People who enjoy coding get to have fun trying to cram efficient programs into cheaper machines, while those who "just want it to work" simply need to spend more resources to avoid the issue altogether.  Even better, those same people might be encouraged to learn more efficient methods of coding (turning OpenComputers into a tool for teaching good coding practices).  

All of this could be accomplished with a power system that focused on computer operations.

For example:  What if power consumption increased as more variables were held in memory?  Suddenly, localizing variables becomes an actual gameplay mechanic; functions become more efficient; even dividing programs into do-->end blocks could reduce power consumption.  

Another example:  What if there were an initial overhead cost to load ("require") a library, _but_ executing code within libraries came at a power _discount_?  This would create an interesting balancing puzzle---at which point does a custom library become more efficient, power-wise, than main-body functions?

And again, any argument that this might be too complex/fiddly for most coders is neatly answered by the simple work-around of upgrading your computer to a higher tier.

> I like how OC currently handles most power APIs by simply accepting them

I agree with this.  Conversion rates could be handled by config, with community-standard rates establishing the defaults.  I think this would feel _extremely_ polished, because of its elegant simplicity.

But my, I've gone on long enough.  Sorry for the Wall of Text---I have to say this is my favourite mod of all 150+ in my pack, and it's easily the central component of an adventure map I've been working on for months, so I could talk OC all day long :)

**Comment by fnuecke** [comment]
Wow, to be honest, I wouldn't have expected this to be so ... controversial (in particular considering the explody stuff would - if at all - only be related to IC2/GT power, where that's a thing anyway). Now I'm really glad I made this issue, first :-P

So let's re-evaluate. Since the MJ is going away anyway, and RF would therefore be the only power type that's "non-electrical" in nature, the differentiation between converter and other blocks regarding power type won't happen. Instead a 'tiered' throughput seems more reasonable, e.g. allow T1 cases to accept X Energy / tick, T2 2_X, T3 4_X, Converter 8*X, something along those lines? Charger and assembler falling somewhere into T3 or converter level. Will have to do some testing / math to see what a "minimum" transfer rate would be for T1 so computers won't turn off just by idling.

> Conversion rates could be handled by config, with community-standard rates establishing the defaults.

Oh right, those aren't in the config, are they? Guess I forgot about that. _Adds to todo list._

Thanks for all the input so far!

PS: regarding "computer operations", I have indeed been thinking about that a bit, currently I'm considering reworking the semantics of the call limits - right now those are 'per computer per component', and I think it'd be feasible to change those to be 'per computer' by interpreting them as "relative costs" instead, where a computer has a pool of "cost per tick" (potentially even based on the CPU tier so they'd finally actually impact performance!), that is if the `limit = 10`, unlike now it wouldn't mean "each computer can call that method 10 times per tick", but it would mean "per call consume 1/10th from the calling computer's overall call limit". It's a subtle but potentially powerful difference. We'll see.

**Comment by twothe** [comment]
To my experience there are two types of Minecraft tech players: those who want everything to be ultra complex with everything requiring at least 20 steps to complete (aka Greg-tech players) and those who want to just have some fun without going too much into detail (like those who do not want to worry about power, they just want to plug in a cable).

I am judging neither, because taste is not something you can discuss. It is difficult but possible to satisfy both, like you do currently with the extensive config options, and I hope if you continue that path then both types will be happy in the end.

**Comment by Eunomiac** [comment]
For the first time in my life, I have absolutely nothing to add to either comment; I completely agree with everything both of you said, and really like that summary of where you're currently at re: power overhaul, **fnuecke** (and yeah, I definitely over-argued the exploding machines bit, given its limited application---it's a pet peeve I have with GregTech, really, that bled over into this discussion :) )

I know I'm repeating myself, but I do want to re-emphasize how cool I think it would be if power consumption became a way to teach good coding practices, by making efficient programs cost less energy.  

And **twothe**'s absolutely right about the two broad camps of players (I call them "gamers" and "builders", myself).  It's important, I think, whenever ramping up complexity, to provide an alternative for less-technical players.  Config options are one way to do this, but players don't always have access to config settings (e.g. SMP), so in-game alternatives are important---and there is one, in this case: namely, the option to simply pay the price to upgrade to a higher tier.

So yeah! Great work! :D

**Comment by fnuecke** [comment]
Done in (for now) local branch.

Different blocks now have different 'conversion speeds' (configurable, of course), which are also shown in their tooltips (which should alleviate the old "which blocks accept power and which don't" problem).

**Comment by Keridos** [comment]
Just a small info: 3 phase power can be "converted" to normal main voltage by just using any 2 of the 3 wires and connect them normally, that is where you get 240V/110V from.

**Comment by Kubuxu** [comment]
@Keridos as far as I know you would burn my computer as normal power can be acquired by using one wire and zero. Using any 2 hot wires gives you 330V.
