### ISSUE TITLE
Server rack "Turn on" option blinks on and off

### ISSUE THREAD

**Issue by SamTebbs33** [MightyPirates/OpenComputers#532]
I am unable to turn servers inside server racks on since the button flashes on and then instantly off.

Singleplayer
All mods: CodeChickenCore v1.0.2.9, Not EnoughItems v1.0.2.15, OpenComputers v1.3.3.54
MC version: 1.7.10
Forge version: 10.13.0.1186

**Comment by magik6k** [comment]
Is there disk with some OS inside server, and are there all essential components inside the server?

**Comment by fnuecke** [comment]
Yeah, sounds like you don't have a bootable medium in your server, since that's pretty much the only boot-error that isn't logged to the chat IIRC (because it's not immediate, so it can't really be associated to a player).

Post screenshots and/or take it to the forums if you still can't get it to work.
