### ISSUE TITLE
Component internet finishConnect always returns false

### ISSUE THREAD

**Issue by twothe** [MightyPirates/OpenComputers#535]
Tried (in lua console on computer):

```
lua>  h = internet.connect("78.34.84.168:3425")
lua>  = internet.finishConnect(h)
false
```

However the other side reports a successful connection the moment finishConnect is called. Read/Write works fine as well.

**Comment by fnuecke** [comment]
While the first call seems to always return `false`, further calls properly return `true`. From what I can tell this is due to the underlying Java socket's behavior, so nothing I can do about it. It's a non-blocking call anyway, so you'd have to use it as `repeat until inet.finishConnect(h)` making this kind of a non-issue?

**Comment by twothe** [comment]
That is kind of a strange design, however just ignoring the result works as well. Might want to keep this open just as a reminder?

**Comment by fnuecke** [comment]
Having pondered this some more, this is probably because the address has to be resolved before the actual connection is made... which is done in an extra thread to avoid the blocking name resolving operation to cause lag.
I guess I could see if I can trigger the connect from within that resolver thread, instead of as it is now - from the first other operation on the handle (finishConnect, read, write)... the thing is, though, this really has _no influence on how the handling Lua code needs to be written_, since it could still happen that `finishConnect` returns `false` at first (if the address resolving didn't finish yet or, well, the connection hasn't been fully established). So it'd really be a change that doesn't change anything...

**Comment by twothe** [comment]
However that would fix the strange behavior that the connection is actually established once you send/receive data. ;)

On the other hand: why not just use NIO? It would remove the need for threads when running in not-blocking mode.

**Comment by Kubuxu** [comment]
It is NIO.

**Comment by fnuecke** [comment]
It is using non-blocking IO. Which is why what you describe really isn't weird behavior, it's expected behavior ;-)

The only threading is for the address resolving, which cannot be done non-blocking. Well, at least I didn't find a lib that implemented non-blocking DNS resolving.

**Comment by Kubuxu** [comment]
@twothe by calling `finishConnect` you requests connection to be finished but method returns whether connection was already finished.

**Comment by twothe** [comment]
Now I start to get it. I thought you were using NIO but when you said thread I thought I was wrong. ;)

Still this is a strange design, especially to users who do not know NIO. The problem is that blocking and non-blocking is combined in the Lua API, so if I do finishConnect it does not block, if I do read, it does block (and documentation in the Wiki is a bit thin).

I would recommend to use the event system here with events like "internet_connect", "internet_available" (can read) and "internet_sent" (just sent previously queued data).

**Comment by fnuecke** [comment]
Ah, well. Yes and no. The read method on the _buffered stream_ you get from `internet.open` blocks. The read on the pure socket (either direct method calls on the internet component or what you get from `internet.socket`) does not. I'll add a note to the wiki that explicitly states that. It was clear to me from mentioning the one is buffered while the other isn't but I see how that's not obvious now.

**Comment by twothe** [comment]
Thanks. And btw: if you'd open that Wiki to others, then they could do that work for you. ;)
I'd be happy to improve the documentation, I just can't do it.

**Comment by fnuecke** [comment]
Aye, it was for a while, and it will be again when I have the time to set up some captcha/antibot plugin. I just didn't have the time to look into that and got way too many bot-registrations, so the hotfix was to disable registrations temporarily :-/

**Comment by twothe** [comment]
Just add some code one-liners and as the user what the result would be. Serves as a Captcha and "sanity check" ;)
