### ISSUE TITLE
1.3.4 crashes on screen rendering

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#542]
somewhat similiar to #31, but crashes in java code. im sorry, but i cant post the log currently, i wil do that soon

**Comment by Wuerfel21** [comment]
pastebin.com/pLfVR14e here is it

**Comment by fnuecke** [comment]
Hmm, since googling for this particular error [brings up](http://openeye.openmods.info/crashes/2d0df373af1051eef52d1a3935c54baf) [numerous crashes](http://openeye.openmods.info/crashes/b76f829aa9869c8dd3438c1c470d225d) [where OC isn't even present](http://pastee.co/b3oGnX) but that share the same "root" cause (ArrayIndexOutOfBoundsException: 6 in ClassReader.readShort called from findAndMergeSuperMaps), I'm considering this "not an OC issue" until proven otherwise.

Since it's in the class loader, maybe it's a "stealthy" out of permgen memory error? Try upping your permgen memory and see if that helps. Try to see if it happens if you run _only_ OC / no other mods are present.

PS: also, I don't see any similarity to issue 31 whatsoever? Not sure what made you say that?

**Comment by Wuerfel21** [comment]
I said that cause it crashes when it tries to render a screen.
Will try upping permgen

**Comment by Wuerfel21** [comment]
i said that cause it crashes on rendering a screen.
Will try upping permgen

**Comment by Wuerfel21** [comment]
Oops

**Comment by fnuecke** [comment]
Ah. Well, on that level I suppose so. The relevant parts are quite fundamentally different, though (class loading fail vs. native driver crash), so I was a little irritated by that remark :-P

**Comment by Wuerfel21** [comment]
Its not even optifine doing it

**Comment by fnuecke** [comment]
If this still happens with increased permgen and when running the latest build, let me know and I'll reopen this. Not that I'd have any clue what might be the cause then, though.
