### ISSUE TITLE
string.gsub crashes with patter "."

### ISSUE THREAD

**Issue by twothe** [MightyPirates/OpenComputers#543]
I just tried to use strings as byte buffers and came up with a fundamental error in gsub it seems:

![ocerror_gsub](https://cloud.githubusercontent.com/assets/1131621/4178072/d8514680-3675-11e4-9dcf-168625a82dbb.png)

You can as well use other functions in place of out (like print) it will just not give such a detailed error message.

**Comment by fnuecke** [comment]
Not really, you just managed to find one of the very few places where you cannot yield from - congratulations! ;-)

Since writing to the screen potentially yields (when the number of write operations / tick provided by the GPU tier are exceeded) doing so in that callback is a bad idea because it can lead to that error.

For reference, see [the table on this page](http://lua-users.org/wiki/ResumableVmPatch). In the context of OC the other few locations where it's impossible to yield are: `table.sort` callbacks, `xpcall` error handlers and `__gc` metamethods.

So whatever doesn't work when you have a different callback, it's quite certainly unrelated to the error in the screenshot, and most likely something wrong/unsupported in the callback code, not a bug in Lua (this is the official PUC Rio `string.gsub`, after all).

Feel free to post your other callback code, if it turns out I'm wrong I'll reopen this.

**Comment by twothe** [comment]
Well all I did was to boot my OC PC, start lua, type in the code above, crash.

Nothing serious but definitely unexpected. ;)
