### ISSUE TITLE
Feature request: Allow a projection offset for hologram projectors

### ISSUE THREAD

**Issue by ingie** [MightyPirates/OpenComputers#546]
Situation:  I have a wonderful [thanks to the darkest of dark things : black canvas from Extra Utilities] holographic projection suite. 

However, there's a big hole in the floor where the half-block projector sits, and i can't hide this except with a carpet or multi-part cover on the block above, which ruins the room's aesthetic, and more importantly means that the floor-space isn't clear of collisions [i.e. a robot can't walk "through" a carpet like a player can ]
more than that, unless i project at y>=8 i can't see the pixels, as they're embedded in the floor :)

see attached screenshot - diagonal coming out of the floor is from 1,1,1 > 32,32,32 [note, 1st 7 pixels missing below the floor ] - horizontal lines at 1,y,1 -> 32,y,32 [ where y = 1>8 ]  visible across the projector

if i want to not have the projector visible/ something hiding it in the block above, then my only option is to lower the projector by another block, but that means the offset above now needs to be 8+16 pixels... which leaves me only 8 pixels to actually project above the floor [sad face] 

Possible solution: allow a "projection offset" on the hologram api [in any axis perhaps, but most importantly Y] , perhaps at a relative power cost pro-rata the pixel offset up to a max limit of, say, 2 blocks from the projector [possibly less, but enough so i can at least hide the projector 1 block below the floor, and put a block on it to hide it completely from view. :)

![2014-09-07_19 59 20](https://cloud.githubusercontent.com/assets/1855688/4179334/8dc39fc2-36c1-11e4-9b06-684fe0a30ead.png)

**Comment by Kilobyte22** [comment]
Sounds like a reasonable idea, and should be doable. Do not count on me though, i am not into the rendering code that much.

**Comment by ingie** [comment]
Definitely doable... i've just changed the relevant code myself - as far as the rendering goes... 

i just changed the Y translation in HologramRenderer.scala to 1.5 as a test - naturally that's not how it needs to be done if it's a hologram component API setting from lua, but i wanted to test the principle first. i haven't even set up a dev env yet, this was just edited in vi and rebuilt :) 

result:
![2014-09-08_08 08 34](https://cloud.githubusercontent.com/assets/1855688/4182045/4bd644c8-3727-11e4-88c2-f00ac34415d7.png)

i'll submit a PR if i get far enough along to warrant that, but really i'm not trying to go that far - just doing a proof-of-concept really. [read: i've never PRed in github before so that's more a lack of confidence in my knowledge of the process - years of using VSTS in my day job makes me fear repo managers ;) ]

**Comment by ingie** [comment]
righty... i've now added the hologram lua api hooks...

actually this is more useful than the reason i wanted it... as now i can do

for i = 0,3,0.125 do hologram.setOffset(i) os.sleep(0.25) end

or something like that, and it will animate the hologram coming out of the ground :) 

i've not implemented the power cost yet [ i'm not sure it needs it ] but i can see where it's done now, so i _could_ implement that... but i'm not going to bother for the moment

if anyone wants to talk me through a PR, i'm game for that - i'll just push back to my own fork ... 

[ note to self: i still haven't used anything other than a text editor for this, i feel sullied and unusual ]

**Comment by ingie** [comment]
righty...

i've thrown caution to the wind and submitted a PR... 

ingie/OpenComputers#548

 be gentle with me, it's my first one :)

i've added to the 1.7.10 branch only, not sure if that was correct, but at least it's there if you want it :)

edit: don't know why the link isn't linking

**Comment by Eunomiac** [comment]
I'd like to expand on this idea slightly, by emphasizing at least one need for offsets in the x/z plane, as well.  

I'm currently combining a 5x5 touch-screen floor with a hologram projector located beneath the center block, like so:

![Holo-Floor](http://i.imgur.com/09giK4P.jpg)

Unfortunately, because the hologram projection area is measured in even numbers, there's no center column (in x/z coordinates) to match the center of the hexagon displayed on the screen.  As a result, all of the hologram voxels are slightly out of alignment and asymmetrical, as I had to arbitrarily choose one of the four centermost voxel columns to be my "center".  (It's exactly the same problem you encounter when building rooms with even-numbered dimensions in Minecraft---centering doors and torches and the like becomes impossible.)

Being able to offset the hologram by half a voxel in the x/z plane would immediately solve this problem!

**Comment by ingie** [comment]
Aye, I considered [and commented the code such] that as well when I made the change, I _am_ looking into it, as I have a similar issue/requirement to allow multiple overlayed holograms [ therefore increasing the colour palette in effect ] 

I'll have a look into it further... It's not particularly difficult... I just hadn't determined the most sensible way of doing it without confusing things too much :) 

@fnuecke - do you have any objection to me doing this in "the simple obvious way" - i.e. just adding two more variables into it and modifying the methods to be setOffsetX/Y/Z, or should I keep away for now and not clutter the NBT with more values?

**Comment by fnuecke** [comment]
Did that myself real quick while going over the code and adding a setting for it.
It's now `setTranslation(tx, ty, tz)` (I prefer translation over offset since it's the more common term in 3D-terminology), and the values are the relative size of the projected hologram.

Edit: my reasoning for that is that otherwise the holograms could just be floating around somewhere in space with no semi-obvious relation to the projector projecting them, which I do not like :-P The default values are relatively restrictive for now (0.25 for T1, 0.5 for T2), might crank it up to 0.75 for T2, depending on feedback.

**Comment by ingie** [comment]
Good'o - yeah, that is a better term... i prefer it too, but it's got more letters to mistype :)) 

so long as it still allows a single block to be placed on top so that it can be hidden and not lose voxels in the floor - as that was the sole purpose of doing it...  my feature request wasn't to have it "remote" as it were, the upper limit of 3 i put on it was just to make it more fun :) 

tho, by my measurements 1.5 was the minimum to make it not be still be below the floor level [and allow the covering block to remove the light/make the floor smooth]  - but i'll check it out and see :) 

but your way, of course, does fit better into the "lore" of OC, if that's a thing :)

**Comment by fnuecke** [comment]
Heh, yeah. As for the vertical offset, depends on the scale of the hologram. To get above a full block you'd need 1.5 blocks offset, yeah. Since the vertical height of the holograms is 2 blocks at scale 1 the smallest for that to work would be 0.75 if I'm not mistaken. Otherwise you can always use slabs or even covers.

**Comment by ingie** [comment]
that was my main gripe tho initially - and sole raison d être for my PR... a slab or a cover would ruin the floor/aesthetic :) 

i've still to test it yet, i may be mis-interpreting your figures or vice versa... 

i've still yet to get a build environment working for eclipse or idea, eclipse didn't like one of the java classes in the scala tree for no obvious reason [ an import which seemed perfectly correct wasn't ] - and idea refuses to run the gradle import for me per the readme, so isn't getting the dependencies... but then i'm an idea n00b, so it's actually "no-idea" for me :)) 

.. back to using vi :D

**Comment by fnuecke** [comment]
Well, as I said, depends on the scale ;) Here's my reasoning: the translation should scale, because otherwise you end up with either huge gaps between projector and hologram for small scales, or hardly noticeable offsets for large scales. To then keep the holograms on large scales from flying all over the place, the actual delta should be kept relatively low. But yeah, give it a try and see if it works for you. One tweak I might agree to, would be to make the vertical max translation double the config value, which could also be justified by the fact that negative Y translation isn't a thing.

**Comment by ingie** [comment]
i agree with the scaling, totally...

**Comment by Eunomiac** [comment]
Two quick points:
- I _absolutely_ agree that translating holograms should be scaled/limited to prevent huge gaps between holograms and projectors, but I also think that---no matter how small the hologram's scale---it should be possible to translate the hologram vertically by at least one full block height.  This would permit concealing holograms beneath floors, or beneath objects that can't be broken down into covers (like floor-based screens).
- I'd recommend the horizontal translation be sufficiently fine-tuned so that a hologram can be positioned such that a single voxel column exists at the exact center.  I _think_ what you've described makes this possible, but I just wanted to make sure!

Indeed, both of the above points could be considered "special cases" that might be deserving of their own mode or toggle---i.e.  "translate hologram exactly one block up, regardless of scale" and "translate hologram exactly half a voxel in in x- and z-directions, so that the voxel column at (x,z) = (24,24) is in the precise center of the hologram block"

**Comment by fnuecke** [comment]
For horizontal offsets, with the current 0.5 max translation for T2 that's exactly how it is, if I understand you correctly (i.e. at maximum offset the edge of the hologram is exactly over the center of the projector block, regardless of the hologram's scale).

For vertical, I'll most likely end up doubling the max offset as mentioned, in which case it'll not quite reach past one block above the projector at minimum scale, but I think that's acceptable since using a larger scale and/or using slabs/covers solves this without making the relative gap size appear too big.

**Comment by ingie** [comment]
ingie opens worm can, sticks it on the table... :)

All The Dude ever wanted was his rug baaaaaackkkkkkk

**Comment by Eunomiac** [comment]
> For horizontal offsets, with the current 0.5 max translation for T2 that's exactly how it is, if I understand you correctly (i.e. at maximum offset the edge of the hologram is exactly over the center of the projector block, regardless of the hologram's scale).

I'm not quite sure we're on the same page, I'll have to test (which I'll do this evening EST and report back).  The best description of what I mean likely came near the end:

> ... and "translate hologram exactly half a _voxel_ in in x- and z-directions, _so that the voxel column at (x,z) = (24,24) is in the precise center_ of the hologram block"

Put another way:  Without translating anything, the 48x48 horizontal size of a hologram means the centerpoint is at the corner where four "voxel columns" meet: (24,24), (24,25), (25,24) and (25,25).  I just wanted to make sure the translation method was precise enough that I could translate exactly half-a-voxel's width in the x and z directions, to instead place the center of the (24,24) voxel column at the exact center of the hologram block.  (I _suspect_ it is, though it might need a little fiddling to get the number exactly right, but I'll test it tonight and report back.)

**ingie**, this is not 'Nam. This is bowling. There are rules.  That rug really tied the room together, did it not?
