### ISSUE TITLE
Touch only works if the current resolution is hit

### ISSUE THREAD

**Issue by twothe** [MightyPirates/OpenComputers#551]
For my stopwatch program (http://pastebin.com/1HT8k0jn) I lowered the resolution to "scale" the text when watching the screen from the game world. While it works fine, touch events are only registered if you actually hit the text. At 8x1 resolution this means that most clicks will miss.

As a side-note: it would be great if left-clicks on the screen (from game world) would be registered as well, shift-right-click is not the most convenient way of using a touchscreen.

**Comment by fnuecke** [comment]
Well, yes, the area outside the used display area can't be clicked. That's by design, because otherwise you'd get negative/out of bounds coordinates for clicks.

As for the shift-clicking, you can either remove the keyboard or use `component.screen.setTouchModeInverted` to allow simple right clicks. Which I personally find more... intuitive, since left clicks usually break blocks. I might look into accepting left 'licks nonetheless, no promises though :-P

**Comment by twothe** [comment]
You could clamp the clicks to the current resolution. This would solve this issue and I can't think of anyone who needs exact click coordinates but sets the resolution to something that low.

**Comment by fnuecke** [comment]
Sorry, but I think if a click's outside the display are it's just that, out. I just don't think clamping is a good idea. If you click next to your touchpad the click isn't clamped to it, either (yes the analogy sucks, but it hopefully illustrates where I'm coming from).
