### ISSUE TITLE
Error loading opencomputers

### ISSUE THREAD

**Issue by pfigueiredo** [MightyPirates/OpenComputers#565]
Error report at: http://web01.t3k.pt/crash-2014-09-13_21.06.19-server.txt

OpenComputers-MC1.7.10-1.3.4.63-universal.jar
forge-1.7.10-10.13.0.1208-universal.jar
OS: centos

Thanks

**Comment by fnuecke** [comment]
Ugh, sometimes I hate Java. Or Java me. Anyway, please wait for build 557 to finish, [then try with that](http://ci.cil.li/).

_grumlestupidclassloadergrumble_

**Comment by pfigueiredo** [comment]
Build 557 is for 1.6.4? "OpenComputers-1.3-MC1.6.4  2 hr 11 min - #557" 
my problem  is with 1.7.10-10.13.0.1208
Maybe i'am not looking at the right build...

**Comment by fnuecke** [comment]
Ah, then you want [#65](http://ci.cil.li/job/OpenComputers-1.3-MC1.7.10/lastSuccessfulBuild/).

**Comment by pfigueiredo** [comment]
Thanks i will try this 1th tomorow morning! :)

**Comment by pfigueiredo** [comment]
build #65 still gives errors starting with forge.

**Comment by fnuecke** [comment]
Huh, the same or a different error? If a different one, can you provide the crash log please?

**Comment by wsb9** [comment]
I have exactly same problem. Let's take a look at the log: 

```
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: java/nio/file/FileVisitor
```

it's trying to load class java.nio.file.FileVisitor. After some googling, we can see that this class was introduced in Java 7. However, we (both @pfigueiredo and me) have only Java 6:

```
-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: ***
Java Version: 1.6.0_30, Sun Microsystems Inc.
```

So, we definitely need to update our Java. I tried and it helps :)

**Comment by fnuecke** [comment]
Yeah, I know it's because of the Java version, but I try to keep the mod Java 1.6 compatible, I was hoping the earlier change would be enough, but I'm guessing it still compiles the containing class as 1.7... will probably have to move the Java 1.7 code (that should only be used when Java 1.7 is actually present) to an extra class... I'll do that tomorrow. And try to find a machine where I still have Java 1.6 installed to test it myself :-P
