### ISSUE TITLE
SimpleRedstoneDelegator Crash with Harvestcraft 1.7.10b

### ISSUE THREAD

**Issue by Arouka** [MightyPirates/OpenComputers#574]
http://pastebin.com/hXsZS0Ms

Crash occurred on start-up. Using 
Forge 1208
Harvestcraft 1.7.10b
Opencomputers 1.3.4.63

**Comment by fnuecke** [comment]
This is kinda strange; PHC ships the MFR API, which is why OC's transfomer didn't strip the interface... but apparently afterwards the interface isn't found anymore. I also cannot reproduce the issue.

However, I fixed the annotation so that FML should now strip the interface if MFR isn't present... please see if the [latest dev build](http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/) fixes this for you, thanks.

**Comment by Arouka** [comment]
Seems to have fixed the issue, thank you for the quick response.

**Comment by fnuecke** [comment]
Great, thanks for letting me know!

**Comment by Devilin-Pixy** [comment]
Sorry I started a new issue, must have overlooked this one. After installing latest dev build (1.3.4.145), the problem seems to be solved.
Good work, thnx ;-)
