### ISSUE TITLE
Running Bytecode

### ISSUE THREAD

**Issue by SpiritedDusty** [MightyPirates/OpenComputers#58]
I tried running bytecode from string.dump and it seems its not working. When I try to run some bytecode I get `attempt to load binary chunk (mode is 't')`. Was this an intentional 'feature' for security?

Code:

``` lua
local function a()
  print('Hello!')
end

local dump = string.dump(a)
load(dump)
```

**Comment by ghost** [comment]
Yes, that is intentional feature, check here https://gist.github.com/corsix/6575486

DEV RESOURCE: https://code.google.com/p/lbcv - A bytecode verifier for Lua 5.2 (Written in C)

**Comment by fnuecke** [comment]
As @EcmaXp said, this is intentional. The exploit described in the first link is for Lua 5.1, which even made an attempt to verify bytecode. This is [completely gone in 5.2](http://lua-users.org/lists/lua-l/2009-03/msg00039.html). ComputerCraft gets away with this because it uses a Java implementation of Lua, so it gets some low-level validation for free (e.g. it's unlikely that you can get arbitrary, unsandboxed code running via LuaJ).

Thanks for the link to the verifier, I'll think about it. For now the easier solution is to just add an entry to the config to allow bytecode when desired.
