### ISSUE TITLE
Read NBT wioth Inventory Controller

### ISSUE THREAD

**Issue by Voidi** [MightyPirates/OpenComputers#587]
Is it possible to read the NBT Data of Items with the Inventory Controller?

**Comment by Vexatos** [comment]
I don't think so, and I don't think you should be able to, it would be far too cheaty.

**Comment by fnuecke** [comment]
While 'cheaty' is a little strong, I agree that this should not be available under normal circumstances. Even if we ignore the fact that it'd be potentially quite overpowered, it also breaks immersion pretty hard, since NBT tags can contain all kinds of internal, implementation-specific data. If anything, things like this might go into the debug card.

**Comment by Voidi** [comment]
Well, I want to use OpenComputers to manage some Inventory of Machines from other Mods (in my case with Safari Nets and Autospawner from MineFactory Reloaded)
I would read NBT data for distinction of different Safari Nets. If this would work with another component then Inventory Controller, fine. (Debug card is a upcoming future? I can't find it in the documentation)

**Comment by fnuecke** [comment]
Hrm. Well, some kind of hash for the nbt tag could be an option. This would allow comparing items' tags for equality without having to expose implementation detail. Not a huge fan of that though. Adding a converter to OpenComponents that adds specific information (in this case: the name / stats of the entity in the net) would be preferable, IMHO. Feel free to open an issue on the OpenComponents repo for that, then I or someone else can have a look at that.
