### ISSUE TITLE
Server won't start with remote terminal

### ISSUE THREAD

**Issue by feldim2425** [MightyPirates/OpenComputers#590]
When I start a OC Server with a remote terminal it says "Press any Key to continue", but nothing happens. If I try it with a screen and a keyboard is will start without any error.

OC Version:  1.3.5.155-dev

**Comment by fnuecke** [comment]
Hmm, I can't reproduce this. Is this a fresh server with a fresh OpenOS installation / booting from the OpenOS disk?

**Comment by feldim2425** [comment]
Same problem when i boot from the os disk.
I use:
*) Tier3 Server
*) Tier2 GPU
*) Tier3 HardDrive
*) 4x Tier3.5 Memory
*) Tier3 CPU
*) 3x Tier3 Component Bus

**Comment by fnuecke** [comment]
Sorry, I just cannot reproduce this, neither with the natives, nor with LuaJ. Maybe try a newer build?

If someone else can confirm this I'll reopen this, but like this I have to assume it's either some corrupt file or some kind of user error :-/

**Comment by LizzyTrickster** [comment]
I don't know if field got the same results in single player but I'll try updating my server in a bit and testing it again (that's where it happened)

## 

Josh Green

Sent from my Surface Tablet

From: fnuecke
Sent: ‎Sunday‎, ‎5‎ ‎October‎ ‎2014 ‎13‎:‎23
To: MightyPirates/OpenComputers

Closed #590.

**Comment by fnuecke** [comment]
Allright, by chance I actually did manage to reproduce it now! In all my previous tests I powered the racks via creative cases. When I used a creative energy cell from TE, it borked. Turns out the worker threads can trigger a neighbor change (which they shouldn't not directly, which is the underlying bug), which in turn triggers TE to update, which in turn triggers a connection check in the server, which fails its side check because it's not the server thread, which then promptly errors trying to access a sided method, which bubbles back up to Lua confusing the shit out of it. Will try to fix now.
