### ISSUE TITLE
Bundled Redstone Cable Support Request: EnderIO

### ISSUE THREAD

**Issue by Qanthelas** [MightyPirates/OpenComputers#613]
I would like to request support for the [EnderIO Insulated Redstone Conduit](http://wiki.enderio.com/Insulated_Redstone_Conduit).  It supports 16 colored channels, similar to items like Rednet cable already supported by OC.  The catch is that EnderIO does not seem to have an API.  The code is [available on GitHub](https://github.com/CrazyPants/EnderIO/), though, so that should at least help.

I mentioned this idea on IRC and it sounds like the feasibility of this feature will depend on how easy it is to interact with EnderIO.  Here's to hoping it is easy!

For what it's worth, I tried a test with an OC computer with Tier 2 Redstone Card outputting a strong redstone signal on the White channel of a bundled cable and connecting via Rednet cable and then via EnderIO Insulated Redstone Conduit to a Redstone Lamp - the Rednet cable works great and lights up the lamp, but the EnderIO Insulated Redstone Conduit does not light up the lamp.  This was on Minecraft 1.6.4 using a 1.3.x version of OC.

**Comment by asiekierka** [comment]
@Qanthelas - I wante dto add EnderIO Insulated Redstone support to my mod as well. Could you talk to @CrazyPants about making a proper API?

**Comment by fnuecke** [comment]
~~I've had a quick look over the sources and meddled a bit with the conduits in-game, and from what I can see I'm not sure it even makes any sense for it to work that way? Since the color of the in/output has to be configured in the conduit connecting to, say, a computer, it'd at least be somewhat unintuitive for the connected block to ignore that color setting and set arbitrarily colored signals. Please do correct me if I'm misunderstanding something here! As an alternative approach, it might make more sense to provide a driver that allows configuring the color of the signal of a conduit? It'd be more limited, of course, since only one color could be emitted/read at a time.~~

~~What I did notice while checking the redstone conduit's code was [the use of a MFR RedNet interface](https://github.com/CrazyPants/EnderIO/blob/master/src/main/java/crazypants/enderio/conduit/redstone/InsulatedRedstoneConduit.java#L301), but I'm 99% sure this is 1) unfinished 2) a... non-standard use of the interface (it is intended to be implemented in blocks, not [tile entities](https://github.com/CrazyPants/EnderIO/blob/master/src/main/java/crazypants/enderio/conduit/redstone/InsulatedRedstoneConduit.java#L287)).~~

~~TL;DR: not sure if (insulated) redstone conduits make sense to be used that way, but if so, an API to make it clear how interact with them from "the outside" would be tremendously helpful. Reading a signal could be done without, I guess, but setting one? Not as far as I can tell.~~

~~Edit: just thinking out loud here, the most... integrated solution would maybe be a new "color" setting that isn't a color at all, but explicitly leads to the conduit getting the bundled input from an external (to EIO) source that implements a specific interface (provided by EIO)?~~

Edit 2: Just had a quick chat on IRC, the preferred strategy is to have the conduits implement MFR's RedNet API. I'll probably have a look at that over the weekend.

**Comment by Qanthelas** [comment]
Sounds to me like if EnderIO uses the RedNet API then it's a win-win - great for OC since RedNet support is already operational and great for EnderIO since they have a bit more flexibility to interact with other mods without having to create a new API from scratch.  Interested to see how this plays out!

**Comment by CrazyPants** [comment]
Implementing rednet support in eio has been on the todo list for while. It
will happen at some stage

**Comment by Kilobyte22** [comment]
Heh thats good plan. Would also ensure compatibility to a further extend. I definitely agree. I think we should close this issue given that part is no longer our task then.

**Comment by fnuecke** [comment]
Had more time than expected, so I had a go at it already; looking good so far. Will do some more testing, pull request coming soon.

**Comment by Kilobyte22** [comment]
Awesome to hear :D

**Comment by fnuecke** [comment]
Let's see if I made some silly mistake somewhere ;-) Otherwise, if the PR gets merged, redstone conduits will automagically work. If MFR is present, at the moment. Will need to add a different check on OC's end for whether RedNet is supported or not, then (sadly the RedNet API doesn't have an API annotation).

**Comment by Cycomantis** [comment]
Is this something that we can expect to see working in Minecraft 1.10? This would be extremely handy to have especially with how many people use EnderIO these days.

**Comment by Vexatos** [comment]
Not until EnderIO adds a way to pass bundled signals into insulated conduits.

**Comment by Vexatos** [comment]
...which I am working on.

EDIT: SleepyTrousers/EnderIO#3839.

**Comment by Vexatos** [comment]
Closed via #2134.
