### ISSUE TITLE
AE2 getCraftables Suggestion

### ISSUE THREAD

**Issue by Keridos** [MightyPirates/OpenComputers#623]
The Names of the items in getCraftables are not a good identifier for the items anymore because they use the internal name of the metaitem/block atm. When listing craftables for my ME system I get almost a dozen "appliedenergistics2:item.ItemMultiPart" or "ThermalFoundation:material".
In OC1.3 and OpenComponents it had better names like item.thermalfoundation.signalumIngot.
Is this intended?

Edit: noticed that you can use .label better than name now, it shows the name that you see ingame, like "Enderium Ingot" or "Oak Wood Planks".

Another bug: request(number) does not start a crafting job anymore using most current source atm and AE2 rv1 stable. Does that only work with AE2 rv2?

**Comment by fnuecke** [comment]
The name change is indeed intentional. It uses the "identified" now, i.e. what you'd also use, say, in a /give command. It's also nothing AE2 specific, as this is in the ItemStack converter, which applies to anything returning item stack information (like the inventory controller upgrade). The change was made because this value is _intended_ to be used as a clear identifier, where what was used before was basically the display name before it got squeezed through localization.

And yeah, the label field is the display name (in English, though that might in fact depend on the locale of the server, I never tried it on a non-English system). That has been there for a while, though, I think?

As for stuff not being requestable in rv1, I'll look into it. Thought I had tested that, but maybe I'm confusing that with power compatibility.

**Comment by fnuecke** [comment]
Works fine for me with rv1 and rv2, both dev-env and normal Minecraft.

**Comment by fnuecke** [comment]
@Keridos Any word on the crating requests not working? Does it still not work in the latest OC build? If so, can you post a screenshot of a minimal setup that allows reproducing the issue?

**Comment by fnuecke** [comment]
Closing due to lack of feedback. If this is still an issue let me know.

**Comment by Keridos** [comment]
Found my issue: I cannot request more than the crafting recipe returns, when I request  the same number or less than the recipe returns (example wood -> 4x planks) It starts crafting them. When requesting more it does not start a job and I think the returned object has no link to any crafting status. It alwas returns "true no link" on status.isDone()

edit: It seems to not happen with all recipes. I have issues with crafting Enderium Ingots, which are no usual crafting recipe. Oak Plank work perfectly fine.

**Comment by fnuecke** [comment]
Hmm, i.e. it happens for "external" crafting processes? Does it also happen for, say, ingots when using a vanilla furnace (that'd be easier to reproduce for me, hence me asking).

**Comment by Keridos** [comment]
Hm this does not happen with a simple furnace recipe. But Enderium is a multistaged recipe, maybe that is the issue?

**Comment by Keridos** [comment]
I did not have the resources for that. Maybe the status function should return something different when the crafting was not successful.
