### ISSUE TITLE
Perform actions without permissions [Cauldron/Bukkit]

### ISSUE THREAD

**Issue by oleg599** [MightyPirates/OpenComputers#636]
Good day!

I'm founded a critical bug on bukkit/cauldron server that allows you to perform actions without permissions, for example:

Place signs from Essentials ([Gamemode],[Free],[Heal],etc.)
Place signs from CraftBook (Command sign (op, gamemode, pex, etc.))
Place signs from ChestShop (AdminShop, sell blocks to another player without his permissions)
Break blocks without permissions to region (WorldGuard)

Is it possible to fix it? (Perform actions from FakePlayer or player, who placed a computer)

Sorry for my bad English.

**Comment by fnuecke** [comment]
I'm afraid I don't know these mods/plugins so you'll have to go a little more into detail for me here; I'm assuming these are actions performed by robots? What exactly are you using to perform these actions, i.e. do you `robot.place()` blocks? Do you `robot.use()` existing blocks?

In general, however, robots generate events to check whether they're allowed to perform the action they're about to perform using Forge's `PlayerInteractEvent`; I don't know if Cauldron maps this event to a Bukkit specific one, but at least for WorldGuard it worked when I tested it. So maybe those plugins/mods just don't handle that event.

Note that (in 1.7.10) a robot's fake player gets assigned the UUID of the player that placed it (or the player that placed the robot that places it, or a random one if it is placed otherwise [some other mods' automatic placing logic]). So in the normal case - when placed by a player - it should have the same rights as the placing player. The last time I tested it - which was when I implemented that change, which was... two or three months ago or so, it worked fine...

Which OC and Cauldron versions are you using?

**Comment by oleg599** [comment]
OC - Ubuntu server 14.04 x64, Cauldron version - git-Cauldron-MCPC-Plus-1.7.10-1.1225.01.0 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

This actions perfomed by robots and components for computer, example for signs component:

1) Player, who doesn't have a permissions to place essentials signs placed a computer with signs component
2) Player wrote a script: sign = require("component").sign
print(sign.setValue("[gamemode]\nCreative"))
3) Computer created this sign, because he have a full op permissions, but player not
4) Player clicked to sign and get creative

**Comment by fnuecke** [comment]
Ah, so the problem is the robots/computers can change the _test_ of signs they shouldn't be able to?

That's a ... very interesting mechanic. I'd have to add some protection check to the setValue method then... can normal players break these blocks? If not, a simple world.canMineBlock should do the trick.

**Comment by oleg599** [comment]
Yes, and computers/robots can place/change a special plugins signs, which doesn't have permissions.

Can you use fake player for robots and computers how do it forestry (https://github.com/ForestryMC/ForestryMC)?

Then use fake player plugins adapt to this mod.

IMPORTANT: Fake player should not have op permissions

Example snippet:

private EntityPlayer fakePlayer;

if(this.fakePlayer == null) {
this.fakePlayer = FakePlayerFactory.get((WorldServer) super.worldObj, new GameProfile((UUID) null, "[OpenComputers]"));
}

Next we called forge's block break event (net.minecraftforge.common.ForgeHooks):

BlockEvent.BreakEvent event = ForgeHooks.onBlockBreakEvent(world, WorldSettings.GameType.SURVIVAL, (EntityPlayerMP) fakePlayer, x, y, z);
if (!event.isCanceled()) {
       // break/set blocks starts here
}

**Comment by fnuecke** [comment]
Yeah. OC already uses one for the robots. And one in OCC (though that was only used for AE2 until now). It just never occurred to me someone could be using signs in such a way. If the "breakability" can be used as a permission check then it should be simple enough, as mentioned above. I'll look into it.

**Comment by oleg599** [comment]
Best solution is make a special bukkit-version with bukkit events.

We have a 2 ways - bukkit events with fake player or forge events with fake player, but small problem - bukkit events is not universal and client side will be crash.

Therefore, we remain forge events.

If this mod would be written in Java - I would have tried to adapt this mod for Bukkit, but unfortunately I do not know Scala :(

Good luck with looking, wait :)

**Comment by fnuecke** [comment]
I'll probably do close to the same thing as in the robot fake player's "click" logic, so checking for spawn protection and whether right clicking the block is allowed using the appropriate Forge event.

I personally won't make a Bukkit-specific version of the mod (in particular in light of recent events), but if someone wants to, go ahead and fork.

As for the "I cannot into Scala" argument. [rant] I'm kind of getting tired of hearing that, it's _really_ not that hard - in particular if you already know Java - nor different from Java depending on how you use it. [/rant] You could probably write that logic in Java, Scala plays nice with Java after all ;-)
