### ISSUE TITLE
Robot extreme duplication glitch

### ISSUE THREAD

**Issue by oleg599** [MightyPirates/OpenComputers#641]
Video: http://www.youtube.com/watch?v=KcxS4AH1TTs

Dupe does not always work, time by time

Please fix :)

**Comment by Vexatos** [comment]
Just for information: The Vajra is an item that instantly breaks a block on left-click (so it's faster than creative-mode left click). Might be relevant.

**Comment by fnuecke** [comment]
Tried to reproduce with latest OC, Gravisuite 2.0.3 and Iron Chests 6.0.62.742. Chest broke and was picked up as expected, nothing got duplicated. Need more information with which versions of the mods this happened.

**Comment by oleg599** [comment]
OC - OpenComputers-MC1.7.10-1.4.0.6-rc.1
GraviSuite - GraviSuite-1.7.10-2.0.3
Iron Chests - ironchest-1.7.10-6.0.62.742-universal

Vajra is in silk touch mode, server - Cauldron, Forge - 1331, at this location worldguard region (Worldguard 5.9).

Dupe is works time by time, try to turn off/on robot and try again.

**Comment by fnuecke** [comment]
Replicated, seems to be an issue with Vajira vs. WorldGuard, because that also happens when I as a player right-click a protected block. ~~I'd post a video, but youtube doesn't want to process my 4-second long demonstration, so you'll just have to believe me ;-)~~

Edit: [demonstration](https://www.youtube.com/watch?v=pJHKR5sXfhk).
