### ISSUE TITLE
Too long without yielding in Lua interpreter

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#648]
This is a strange issue. I have made a component (The EnderIO Dimensional Transceiver) that provides 21 methods in total, each including some documentation, so when I call this code in the Lua interpreter

``` lua
=component.dimensional_transceiver
```

it takes a few seconds until the computer crashes with a `too long without yielding` error. This does not happen everytime, but sometimes.
I think it could be fixed with yielding after a certain amount of processed parts in the component call.

**Comment by fnuecke** [comment]
Yeah, this has been brought up on IRC, too. It's an issue with the custom pattern matching implementation being too slow (the change was made to ensure pattern matching _can_ time out, because an evil pattern passed to the native methods could lock down the executor thread for quite some time). I'm looking into it.
