### ISSUE TITLE
hologram render bug?

### ISSUE THREAD

**Issue by marcin212** [MightyPirates/OpenComputers#655]
From this side is ok:
http://i.gyazo.com/aeeb0326ccc543cdb810acab18172001.png
but from opposite: 
http://i.gyazo.com/46b232c5be3a01308a604794f62c5069.png
I try rotate holograms.
OC version: OpenComputers-MC1.7.10-1.4.0.215-dev-universal

**Comment by fnuecke** [comment]
I'm afraid this is in part due to a limitation of Minecraft's tile entity rendering. TEs are not depth-sorted before they are being rendered, so tile entity renderers using transparency will look different when overlapping, depending on the direction you look at them from.

In the holograms' particular case, they also need to change the depth buffer to render the way they do now, or all the back faces would have to be rendered, too, for it to not look completely weird, which is a look I really don't like. And since all transparent parts are rendered in one render pass, depending on the order they are rendered in, both are rendered - first the one in back, then the one in front - or only one is rendered - first the one in front, setting the depth-buffer, so the second isn't.
