### ISSUE TITLE
debug card coordinates slightly inconsistent with world.getBlock()

### ISSUE THREAD

**Issue by seebs** [MightyPirates/OpenComputers#679]
world.getBlock() truncates towards zero, rather than rounding down. What this means is that if a robot at 0,0 or further east or south than that calls world.getBlock(debug.getX(), debug.getY() - 1, debug.getZ()), it will return the block immediately under the robot. A robot at -1, -1 or further northwest will return the block one square east-and-or-south of the robot; negative x and negative z will both be effectively rounded up. I have no immediate suggestions for a fix for this, but the asymmetry is annoying.

**Comment by fnuecke** [comment]
``` lua
world.getBlock(math.floor(debug.getX()),
               math.floor(debug.getY()) - 1,
               math.floor(debug.getZ()))
```

I did consider returning the "block" coordinates from getX/Y/Z (i.e. floored integer values), but decided against it because the precision may be useful to some (it returns the exact player position when in tablets, e.g., hence the +0.5 for blocks, for consistency). And this is a pretty simple workaround ;-)

**Comment by seebs** [comment]
Ahh, hadn't thought of floor. My workaround had been to subtract one when < 0, but this is simpler.
