### ISSUE TITLE
Redstone does not connect directly to servers

### ISSUE THREAD

**Issue by Nixill** [MightyPirates/OpenComputers#680]
I have a Server Rack with a single Server in it. This Server has a Redstone Card (Tier 2). Project:Red Red Alloy Wires or Bundled Cables will not connect to the side of the Server Rack represented by that Server slot, and cannot be activated.

**Comment by fnuecke** [comment]
Oops, fixed in next build, thanks!

Btw, the side configuration of the servers does not matter wrt to redstone wires. As with computer cases, keep in mind that the side in `getBundledInput(sides.left)` means the side _relative to the server rack's orientation_. So if you're looking at its front, left is right.

Also keep in mind that at least one server has to be powered in the rack for redstone wires to visually connect to it.

**Comment by Nixill** [comment]
> Btw, the side configuration of the servers does not matter wrt to redstone wires.

So I can have it in the rack configured to the Top, with a Bundled Cable in the Back, and I can still access it via passing `sides.back` to the rs function?

**Comment by fnuecke** [comment]
Yep.
