### ISSUE TITLE
Screens occasionally become unresponsive

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#683]
There seems to be a pretty hard to reproduce bug (well, at least for me) where screens may become unresponsive. I have seen this on a server. Interestingly, this does not necessarily happen for all players on the server. One way to _sometimes_ reproduce this is to power off a computer, remove some component(s) from it (e.g. a second hard drive), then power it on again.

The only way to solve this seems to be to break all (?) blocks and place them again.

If you have run into this before, it would be _very_ helpful if you could provide all information you have on this. Does it happen in SSP and SMP? Do you have steps to reproduce or that make it more likely to happen? Does it happen only in certain versions of OC? Either way, just let me know _if_ it happens, that alone would be interesting (to see how far spread this is... I've heard about this today for the first time, but apparently this has happened back in MC 1.6 days already).

**Comment by iambob314** [comment]
This bug is affecting our SMP server, as well. It did not affect us under OC1.3 or OC1.4RC1, but after upgrading to OC1.4 release, it is now happening consistently.

It frequently occurs when using Mystcraft books to link between dimensions. Strangely, this occurs even when the computer and all its components are chunkloaded (screen included). I'm not 100% sure if it affects only players who link, or everyone.

It affects our Mystcraft portal control computers almost 100% of the time. It usually manifests as follows:
1. Someone links between dimensions.
2. Upon returning to the Overworld, some computer screens may be black. If not, skip to step 4.
3. After rebooting the attached computer, sometimes the screen comes back on, sometimes it's still black. A second reboot gets the screen on.
4. Even with the screen on, the computer doesn't receive touch events.
5. Breaking all the screen blocks, followed by rebooting the computer again, fixes it. Rarely, removing and reinserting the CPU in the computer can fix it instead of breaking the screen.

The Mystcraft portal program is written "on the bare metal" (i.e., as the boot code, not on top of OpenOS). However, OpenOS computers are also affected, albeit less frequently. My guess is this is because the main loop of the Myst program is tighter. Here's the main loop of the Myst program, in case it helps:

```
while true do
  local evtname, screen, x, y
  repeat
    evtname, screen, x, y = computer.pullSignal(SCREEN_REFRESH_INTERVAL)

    -- <1>: Calls to gpu.setBackground() and cpu.set() happen here
  until evtname == "touch"
  -- <2>: Various GPU calls happen here
end
```

When the screen is glitched, <1> still has visible effects on the screen, so the loop is indeed running. However, <2> is never triggered, so events while events are being processed, no touch events are received.

**Comment by fnuecke** [comment]
Thanks a lot for the detailed description! I think what you're seeing may be caused by an attempted fix for this problem... that actually made it worse >_>

When it's done, please do give build 241 a go, that should fix text buffer (screen) components getting disposed in all worlds when _any_ world gets unloaded (because that's prrrrobably what you're experiencing).

**Comment by iambob314** [comment]
We installed build 241, and it appears to have fixed the problem. Thanks for the quick response!

We're still experiencing a minor, possibly related bug that was present under OC1.3 and 1.4RC1, where screens will go blank under similar circumstances as here. However, any draw to the screen refreshes it. I'll file a separate bug report for this.

**Comment by fnuecke** [comment]
Pretty sure I just forgot to close this...
