### ISSUE TITLE
Feature Request: Add 1mb and 512 RAM sticks by default with or without config option

### ISSUE THREAD

**Issue by MFernflower** [MightyPirates/OpenComputers#69]
That's all folks :D

**Comment by ghost** [comment]
It's truely require for big programs. but it must quite expensive like nether star and wither head
But it must not apply to normal computer, only advanced computer (like server) can apply this. check #17

**Comment by fnuecke** [comment]
Well, give me a concept for the textures and I'll be much more open to adding this :-P
I'm not even happy with the texture for tier three memory (because it doesn't make sense). Maybe I'll just "downgrade" the lower tier memory (less "chips" visible on it).

As for the limitation to high tier computers, that's actually a pretty interesting idea. I opened a new ticket #72 expanding on that idea a little, let me know what you think.

**Comment by MFernflower** [comment]
I can work on textures

**Comment by fnuecke** [comment]
Well the main problem I'm having is making the different memory tiers look distinct (without resorting to the gray/gold/diamond coloring, which I may have to in the end). The reason I'm not happy with tier 3 memory is that the texture shows two memory modules... but they go into one slot. If you want to, don't let me stop you from making some textures. If I really like it I'll use them as-is, if not I might make adjustments to them. Is that OK with you?

**Comment by MFernflower** [comment]
It seems like we may have to use the coloring

**Comment by LordFokas** [comment]
What about these?

![ram](https://f.cloud.github.com/assets/3021352/1864815/46dd8f42-77fd-11e3-87ed-0e31b632f2ac.png)

They're 32x32 but I think it's better than falling back to colors...
ZIP here: https://www.dropbox.com/s/6ppkfbh3ep4g5ve/ram.zip

**Comment by LordFokas** [comment]
Also, I upscaled the 16px image and left most 2x2 pixel blocks intact not to break the pixelated feel of 16px textures... basically I only made them 32px to get a bit more detail in them.

**Comment by MFernflower** [comment]
I like the 32's I think the smaller ones should have DIP packages on them
and the larger ones should have ball grid array packages

**Comment by MFernflower** [comment]
Alternate 256kb RAM texture

**Comment by MFernflower** [comment]
![memory3](https://f.cloud.github.com/assets/3164942/1869740/315da00e-787e-11e3-9864-9d0304c47e49.png)

**Comment by fnuecke** [comment]
Thanks a lot for the input. I like the 32x32 ones because they're closer to what the memory modules _should_ look like. I did an ingame comparison of those against a 16x16-with-coloring draft:
![32x32 Images](http://i.imgur.com/psIf7SZ.png)
![16x16 Images](http://i.imgur.com/m0n3ure.png)
While it's kinda lame, I think the 16x16 images with colored tiers fit better with the other item icons. For an overall more detailed 32x32 texture set mine would definitely loose, though - I wonder if anyone could be bothered to do a 32x32 pack? A man can dream...

**Comment by MFernflower** [comment]
yeah the 16x16 seems to good

**Comment by MFernflower** [comment]
Enjoy :D 
Workstation Memory:
![memory3](https://f.cloud.github.com/assets/3164942/1873838/8c79eb22-78c0-11e3-9de6-56393e1c6711.png)
Server Memory:
![memory4](https://f.cloud.github.com/assets/3164942/1873837/8c79a93c-78c0-11e3-8e0e-baa3aed0f4ee.png)

**Comment by LordFokas** [comment]
Well I tried my best. I'm not a great artist.
I'm glad my input at least served to get better inspiration :p

**Comment by fnuecke** [comment]
Thanks again for all the input. I've decided to go with the textures in the 16x16 version screenshot above, instead of the recolorings, since I can hardly tell the difference - I'm pretty much red-green color blind. I've got this working in a local branch, will push it when 1.2 gets closer to completion.
