### ISSUE TITLE
Screens with content sometimes appear blank, refresh on next GPU draw

### ISSUE THREAD

**Issue by iambob314** [MightyPirates/OpenComputers#694]
Possibly related to #683, screens that have content will occasionally appear blank, even though the screen still has content (server side). On our SMP server, this usually occurs when linking to another dimension using Mystcraft, then returning.

Whenever this occurs, the next GPU draw to the screen (set, fill, etc.) will redisplay the screen's content (the former content with the new draw applied, as expected). Thus, this bug is not generally apparent when observing OpenOS's shell or lua prompt, as the flashing cursor serves this purpose. However, programs with a usually-static screen (such as an array of buttons) will experience this bug.

(Note: for now, this is easy enough to work around by putting a flashing cursor on the monitor.)

**Comment by fnuecke** [comment]
I think I found the reason for this - most likely caused by the screen rendered by the client before the text buffer init packet from the server arrived, leading to an invalid cached render state (display list).
Thanks for the clear description! I had seen this once or twice before, but hadn't realized / didn't remember a refresh fixed it.
