### ISSUE TITLE
Arduino Like Device

### ISSUE THREAD

**Issue by scj643** [MightyPirates/OpenComputers#711]
A little device that is the functions of an arduino. It can only do redstone io and some other basic stuff. Must be hooked up somehow to a main computer to program. It has outputs on each side and inputs on each side. This way it doesn't have to load a whole computer to do something small and simple. It would give use the cheapness of ComputerCraft for the basic redstone applications while still having the realistic feel to it.

**Comment by LordFokas** [comment]
I like this idea. A lot.

![Shut up and take my money](http://genophoria.files.wordpress.com/2012/11/shut-up-and-take-my-money.jpg)

**Comment by fnuecke** [comment]
So this would be like a regular computer, but with only a redstone card, built-in (read-only?) file-system/floppy and no way to interface with external components?

**Comment by LordFokas** [comment]
I think so, yes. That's what an Arduino basically is.
And it'd use little or no power. It'd be more practical if it used no power, but I'm not sure how that fits in the rest of OC.

**Comment by rmellema** [comment]
Well, arduino's also use power, but they can be run of batteries. Maybe also give the block a slot where you can insert a battery into?

@fnuecke maybe make it kinda like a unmoveable robot, in that you can insert your own components into it, but restrict the use to certain components, like a redstone card or a network modem, but don't allow for gpus for example.

**Comment by scj643** [comment]
# Arduino

## General

The device would be built just like a tablet. It would support some components that turtles do. It would start of with 2 redstone IOs to start and has an IO upgrade (redstone card maybe or something new)

## Components

It would  support  the battery upgrade tier 1 and my logic is that it would be like having watch battery
It would also have a custom component that is the IO upgrade which is a redstone card tier 2 without the ender pearl. This adds 2 more IOs with a max of 6 IOs total

## Shields

Shields are modified versions of cards and upgrades. They are a solid block and can be placed and connected. They have to be right next to it to work. There is a limit of 1 shield per device. http://arduino.cc/en/Main/ArduinoShields is what i'm basing this off.

### The shields
- Network card
- Wireless network card
  ### Computronics shields
- Camera Upgrade
- Chat Upgrade
- Radar Upgrade

### Adapter Shield

A simple adapter block modified for the arduino it is slower than a normal adapter but allows for more compact designs.

## Cost to make

The arduino should be relatively cheap to make it shouldn't cost more than a tier 1 computer.

## Mass production

The arduino should be able to be mass produced in some way.

## Hardware

It would have lower power than a tier one computer with a tier one cpu.

## Tiers

There should be two tiers which are based off the real arduinos

### Tier one

> The ATmega328 chip found on the Uno has the following amounts of memory:
> Flash  32k bytes (of which .5k is used for the bootloader)
> SRAM   2k bytes
> EEPROM 1k byte

### Tier 2

> The ATmega2560 in the Mega2560 has larger memory space :
> Flash  256k bytes (of which 8k is used for the bootloader)
> SRAM   8k bytes
> EEPROM 4k byte

**Comment by LordFokas** [comment]
That would be a lot more like a computer, except on a single block.

Personaly, I'd prefer it to be a more basic thing, like a small component that you can program and sits there using no power interacting with anything that's not a computer. And I defend using no power, because that'd be perfect for a small controller that you can have taking care of some small subsystems on your base, say, monitoring power systems.

It'd be more like an OC take on redstone latches, except you can program what output comes from the inputs, and inputs can be a bit more than just [bundled] redstone, although I don't think it should be able to work on wireless (or wired) pc networks, even though an Arduino can do it.

**Comment by Vexatos** [comment]
I think it should use little power (maybe 1 RF/t while doing things, or even less, as OC power is using double values). It should not be able to interact with any component, but should have very basic I/O funtionality.

**Comment by scj643** [comment]
My reasoning is that once you program it, it goes off the network. More like a unmovable robot.

**Comment by scj643** [comment]
Also make an upgrade that if you use a nether star it has pwer indefinitly

**Comment by fnuecke** [comment]
Based on these suggestions, here's what I think would be orthogonal enough to existing gameplay elements:
- Assembled in assembler
- Does not interact with external components
- Built-in boot medium [1]
- Can only contain a very selective set of components:
  - Redstone Card
  - Network Card
  - _No_ wireless card. Sending messages requires energy, and I'll just define that amount to be more than this device could handle ;-) Also, you can always just plop an access point next to it.
  - Solar Gen. Upgrade
- Uses energy, but very little; less energy than solar gen. produces
- One-block thinger. Mostly to make connecting it to multiple networks less awkward.

Anything more than that would make things too complex and too close to normal computers again, IMHO.

The idea for an infinite power source using a nether star is... dangerous. If the output is low enough I might be OK with that, though. Would have to produce too little for a robot to operate while running around, but enough for this to run without an external power supply.

[1] Regarding boot medium, I want to look into implementing part of #425, specifically having a chip that's hard-programmed with some code (plain byte array, so that could be Lua code if run by a Lua arch or binary if it's another arch) that has to be built into computers (new slot). It would replace the code in the kernel.lua that's looking for the init.lua, for example (i.e. instead the kernel would try to get the code from that chip and if there is none fail horribly). That chip would then be what'd be built into this device as the _sole_ piece of data. It'd only be a few KB in size, reinforcing that these devices should be used for very specialized scenarios.

**Comment by MaHuJa** [comment]
I like that idea.

So far, my solution to this problem has been a computercraft computer. For anything serious I use OC, but for what's essentially just a logic circuit, full multiblock OC computers are a bit overkill.

There are a few mods that appear to only support CC, and a few that only load their computer interfaces when CC is installed, but this would take CC mostly out of the picture for me. Disabling the CC recipes could become a thing here.

**Comment by Vexatos** [comment]
@fnuecke I love the idea. Just make sure to add a new internal interface to the API so I can HostAware the Spoofing Card properly (as it extends the Network Card).

@MaHuJa Which mods only load their peripherals if CC is installed? Could you give a list of them?

**Comment by LordFokas** [comment]
Mine is one of those mods, but that's a different case because I don't need to use CC stuff if OC is present, as OC interfaces with it directly... But anyone using plugins the same basic way I do does that, as it checks for the mod being loaded.

**Comment by MaHuJa** [comment]
When I tried logistics pipes less than a month ago, their CC integration wouldn't work with OC at all, even with CC installed. (A CC computer could at least detect the peripheral. I didn't find out if the rest of it was broken, but I did have problems with it.) Then again, LP is still in internal development. As for those that work with OC when CC is loaded but not otherwise, I don't remember any specific examples, but noted there were some.

**Comment by morlanius** [comment]
Good idea. I would like to see this added. Though the above description is good the crafting patterns would be best kept in line with the rest of the mod. i would have something like: a battery upgrade, a redstone card, cpu and a chip of varying tiers.
The device should be only writable to via physical interfacing ie: sticking it to a computer/cable.
writing the device should not be FS based, eg: you "burn" the program on to the device not place a file there. Although this would be aesthetic as essentially you would be writing 1 file to the object path of that unit under the hood.
it should have an analogue io output on the rear, left, top and right sides but not bottom or face.
The bottom should be left available for a cable to be able to be connected so that an OC can re-burn the device or call its api and retrieve information: power status, PC (program counter), and a state for each of its 3 GPIO.

**Comment by scj643** [comment]
@morlanius has literally summed up my new revised idea. This is what I was meaning to have it be but then i got carried away. Lets keep it that simple.

**Comment by scj643** [comment]
Also the wireless part would have to run of external power and would allow it to communicate with other arduinos and computers. Say you have a control panel program a couple arduinos and you got wireless redstone without the need of another mod.

**Comment by fnuecke** [comment]
1. Data storage: as mentioned, it'll only contain an EEPROM. Which isn't a file system. It's literally just a byte array.
2. Re-programming: I'm currently leaning towards making them "recraftable" to swap the EEPROM, similar to how the maps in nav upgrades can be changed. This rather manual step makes it less likely for them to be simply re-programmed by a computer connected them on the fly, which I feel would be too abusable (you can still automate it with a robot, I guess, but that'll require enough effort for me to be OK with that).
3. IO: redstone output will behave as for cases, for consistency, i.e. they can read and output redstone signals on all sides. OC cables will be connectable on all sides but the front.
4. Component: power state can be read and changed by connected computers, there's no "program counter" in Lua, so... eh? No reading of it's redstone/network state. Computers can have redstone/network cards themselves, or share a redstone i/o block.
5. Nether star thinger: making it exclusive to the microcontroller would be a tad too special-case-ish for my tastes. If it makes it in, it'll also be available for the robot. It'll just generate very little energy. If you want to put 9 of those generators in your robot to make it autonomous, be my guest then :P
6. Wireless: network card + access point next to the device. So yeah.

**Comment by Kilobyte22** [comment]
I do like the idea. Especially since a computer is kinda too expensive to use for automating smaller things. If this would be reasonably cheap it would be a very good addition.

**Comment by LordFokas** [comment]
@fnuecke damn it you're fast.

**Comment by fnuecke** [comment]
[Short example video](http://youtu.be/SV1k3DwelZM). Some testing would be appreciated!

**Comment by MyNameIsKodos** [comment]
What I've tested thus far of it, it seems to work 100%.  Can't say I'm pleased that it doesn't handle bundled redstone, since that would make it 100x more useful, but it's great so far.  The only thing other than bundled cable I'd want is simpler components like Computronics' Colorful Lamp.  I had a really sweet idea for a Galacticraft Air Alarm but realized I couldn't do it since I can't set the MCU to change the color on the lamp.

**Comment by Vexatos** [comment]
@Kodos-Atoz If you have BuildCraft, you actually can, there is a gate action for setting a lamp colour. Just make the gate respond to redstone from the MCU.

**Comment by MyNameIsKodos** [comment]
Eh, I'll check it out.  Didn't really want to have to rely on another mod though.  But it beats nothing at all I suppose

**Comment by fnuecke** [comment]
Glad to hear it's stable!

The things are supposed to be simple, so I feel adding a T2 card slot would power them up too much. Yes, it makes them less useful than a normal computer, but that is kind of the point, so I guess it's "working as intended" :-P

**Comment by Vexatos** [comment]
@fnuecke Or it makes you have to think more outside the box (see my gate example). I really like it.

**Comment by morlanius** [comment]
These are brilliant, thank you. The only improvements I could think of would be purely aesthetic, use a model rather than a block, perhaps something slimmer. I know it's still occupying 1 block, it would just look nicer if it looked a little more discrete. Apart from that you guys are doing fantastic work.

**Comment by Kubuxu** [comment]
@morlanius it is looking like that as it should be opaque on each side.
