### ISSUE TITLE
Robots and ME Annihilation Plane

### ISSUE THREAD

**Issue by therealeldaria** [MightyPirates/OpenComputers#722]
So I was going to make a robot drop some stuff onto a ME Annihilation Plane from Applied Energistics 2.
But when it moved in front of it, well it took the robot instead. However it did not end up in the network, it just disappeared. Luckily I run a regular backup, so I could get my robot back.

**Comment by fnuecke** [comment]
That's because robot dropping needs some special drop handling. In the method that returns items dropped by a block (the one called by AE2) the tile entity is - in _normal_ Minecraft - already gone. So it'd not be possible to store a robot's info in the returned stack (such as components in the robot). Therefore the stack is spawned manually.
It looks like there's a loophole here, though - AE2 calls this method while the tile entity still exists, and doesn't call the method OC uses for normally spawning the item stack... sooo... I'll give that a shot and see if it leads to dupes with some of the other ways of automatically breaking blocks I'm aware of.

**Comment by therealeldaria** [comment]
Wow fast response. ;-)

Not sure if I should add another issue, but the reason for me trying to use the Annihilation Plane was that I could grab items from a Conversion Monitor but I could not Store items (Sneak Right Click). I tried both robot.place with and without sneak, and robot.use with sneak, (Without sneak will put a stack of the item in the Robot tool slot, so this works). Well for now my workaround is to use a chest with an import bus, not as clean looking but it works.

**Comment by fnuecke** [comment]
AE Interfaces act as inventories, so you should be able dump it into them directly, no need for an additional chest.

**Comment by therealeldaria** [comment]
Ohh, that was nice, did not know that.
I removed the chest, and as soon as the robot was in front of the import bus, it started emptying the inventory. I did not even have to add any code. :-)
