### ISSUE TITLE
getComponentName() doesn't seem to be overriding.

### ISSUE THREAD

**Issue by CaitlynMainer** [MightyPirates/OpenComputers#739]
Using this in LanteaCraft because our DHD is internally named stargate_energy
        @Override
        public String getComponentName() {
            return "stargate_controller";
        }
https://github.com/PC-Logix/LanteaCraft/blob/1.7.10-legacy-patches/src/main/java/pcl/lc/module/integration/OpenComputersWrapperPool.java#L288-L291
The returned name running components on a computer is "stargate_energy" and not "stargate_controller"
It seems this should work in a SimpileComponent but doesn't work on Managed, am I overlooking something?

**Comment by Vexatos** [comment]
@MichiyoRavencroft Are you implementing NamedBlock on that environment? If you do, you should be able to set a priority, just leave every priority at 0 and set the one of this class to 1 to make its name always preferred.

**Comment by fnuecke** [comment]
What Vexatos said. You'll have to use `NamedBlock`.

To clarify, here's the different ways different ways components are named:
- For tile entities with `@SimpleComponent` you return it from `getComponentName`.
- For tile entities implementing `Environment` you name the node yourself (`newNode(...).withComponent("name")`).
- For `Environment`s returned by item drivers you also name the node yourself.
- For `Environment`s returned by block drivers you'll have to use `NamedBlock`.  
  This is superspecial because block drivers can be merged, so there's no way for OC to know which one's node's name to use, otherwise. The merging is necessary to allow drivers for certain interfaces (such as `IInventory`).

**Comment by Vexatos** [comment]
If no `NamedBlock` is being used, the driver which has been registered first will be used, I guess.

**Comment by fnuecke** [comment]
Ah, right, addendum: if none of the used block drivers implements `NamedBlock` a name will be generated - based on the tile entity name IIRC (even if it's just one, to consistently have block driver realizations be compound drivers, easier to work with internally).
