### ISSUE TITLE
Add config option for EEPROM size

### ISSUE THREAD

**Issue by glebqip** [MightyPirates/OpenComputers#742]
Can you increase EEPROM size? My "BIOS" for now have a 12kb size, and i can't place it to EEPROM.

**Comment by LizzyTrickster** [comment]
Have you tried to see if you can move some stuff you dont need to your OS?

**Comment by fnuecke** [comment]
I don't intend to, no. You can easily get more data than fits onto the EEPROM using the code that _does_ fit on it (e.g. load more via the network or from a file system, which _easily_ fits into 4KiB). I can make the size a config option, though. Wanted to, just forgot about it, actually.

**Comment by glebqip** [comment]
I think, you can make a setting to select the size of the EEPROM. It would be cool.

**Comment by magik6k** [comment]
The problem here is that when someone makes program for i.e. the micro-controller with over-standard size, there is no good way to share them as there may be players that play on someones modpack and aren't willing to change the settings. I'm not telling that config settings shouldn't be implemented, but I'd rather prefer some kind of EEPROM tiers(2k, 4k, 8k(or times two these))

**Comment by fnuecke** [comment]
Well that's what you have to live with when changing the settings :-P

I don't really want to add higher tiers of EEPROM unless someone can give me a very good reason that isn't "I want to cram everything on the EEPROM instead of using it to bootstrap other data sources" ;-)

**Comment by glebqip** [comment]
Big thanks
