### ISSUE TITLE
[Debug Card] Remote Peripheral Binding

### ISSUE THREAD

**Issue by TinkerWorX** [MightyPirates/OpenComputers#751]
Remote Peripheral API for the Debug Card. `.bindRemotePeripheral(x, y, z)`, returns an interface for the peripheral at the location. Useful for remote control of various things, to avoid having the computer at the same place as the player.

**Comment by fnuecke** [comment]
While the creating the wrapper would be pretty easy (`api.Driver.driverFor(x, y, z).createEnvironment(...)`) the main problem would be that the card will not get block update notifcations, in other words it won't know when the block it wraps gets destroyed - which can lead to a bunch of weird scenarios and unexpected behavior.

An alternative approach might be to allow "connecting" debug cards to blocks in the world. I.e. simply connect the component node of the debug card with the component node of a block implementing `Environment` (or `SidedEnvironment`). In that case the card _will_ be notified when the block is removed, because the block will remove its node when it is destroyed or unloaded. To get the desired effect you'd still have to place an adapter, but could connect to it "wirelessly". This is somewhat similar to suggestion #475, in purely "creative" form. Would that be acceptable?

**Comment by TinkerWorX** [comment]
Yeah, that would be a good solution, perhaps with an accompanying Creative Adaptor, so I can prevent people from removing it.

**Comment by Eunomiac** [comment]
This feature would also make me a very happy camper! :)
