### ISSUE TITLE
EEPROM I/O port.

### ISSUE THREAD

**Issue by PowerOfTech** [MightyPirates/OpenComputers#756]
Computers has no additional port for EEPROMs. And loading OS, ejecting card with bios, inserting new one, writing data, etc. is not very easy,so this thing will help us in this.

**Comment by LizzyTrickster** [comment]
Heow is what you described not easy? The only hard bit is writing the code for the eeprom

**Comment by fnuecke** [comment]
The two clicks more for the removed/readded EEPROM really aren't that bad now are they ;-)
Also, I'm against making multiple EEPROM components available to one computer, mostly because it will destroy the deterministic that exists on startup now (because there's at maximum only one EEPROM to boot from).

If anything I might add a way to "clone" EEPROMs if the demand exists. Probably just by crafting two EEPROMs together and copying the data from the first in the crafting inventory onto the second, because I'm lazy. Would this be helpful to anyone?

**Comment by PowerOfTech** [comment]
I said easy? Hmm, I mean "uncomfortably". And illogical, because breaking electric circuit can damage and you, and circuit.

**Comment by celskeggs** [comment]
Perhaps what's needed is an external EEPROM read/write port that the computer doesn't boot from? That way, bootup is still deterministic, but there's also easier EEPROM rewriting.

**Comment by Vexatos** [comment]
Well, I _could_ add support for this to the Computronics EEPROM reader, but I really don't think there is a need for it. I don't think it's particulatly hard or inconvenient to do it the way it currently has to be done.
@fnuecke Crafting two cards together to copy their data would be pretty cool, I think.

**Comment by fnuecke** [comment]
Since Computronics already has such a block, I think it'd be best to add such a "comfortability" feature in there, if anywhere, instead of adding a new block to OC exclusively for that.

I'll look into the craft-to-copy thing.
