### ISSUE TITLE
Can't yield string.gsub >.>

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#757]
``` lua
c = coroutine.create(function() return string.gsub("test", ".", coroutine.yield) end)
print(coroutine.resume(c))
```

I know you have a pure-Lua reimplementation of string.gsub, why not use it? >.>

**Comment by fnuecke** [comment]
Because it'd be painfully slow. Trust me. I tried. Computers kept timing out just from `more`ing files.
Feel free to try and optimize the port, though. It was kind of a hotfix that stayed (for evil patterns potentially occupying a worker thread for a looooong time) and I don't really have the motivation to dig into again any time soon :-/

**Comment by SoniEx2** [comment]
I'll just use a hacked/tweaked Lua then >.> (just not sure how to compile for OC)

**Comment by SoniEx2** [comment]
Also why can't you make it do "internal yields" internally?
