### ISSUE TITLE
Waila Causes FPS Slowdown When Looking At Robots

### ISSUE THREAD

**Issue by Aedda** [MightyPirates/OpenComputers#764]
I noticed earlier trying to interact with a Robot my FPS dropped from 65 to 13 and as low as 9. I traced this behavior to occurring when looking at the Robot within a certain distance. My console began to become flooded with:
"[Client thread/WARN] Something's taking too long! 'root' took aprox 183.421935  ms"

I found no other OC block to cause this.

I tested OC by itself and it did not occur. Checking Warmroast it indicated the lag was being caused by:
li.cli.oc.integration.waila.BlockDataProvider$.getWailaBody()
mcp.mobius.waila.api.impl.DataAccessorBlock.getNBTData()
li.cli.oc.common.tileentity.RobotProxy.writeToNBT()
and it continues on for some time before getting to...
li.cli.oc.server.fs.Buffered$$anonfun$recurse$2$1.apply()
li.cli.oc.server.fs.Buffered$class.recurse$2()

ETA: I decided based on the nature of the profile to check disk access on the local machine. Whenever I look at the Robot OC thrashes the disk ![DiskLog.png](https://i.imgur.com/ATwmKDv.png)
Note log is condensed due to size and does not include directory and file accesses leading up to final directory as displayed.

I have attached an image of the profile:
![OCProfile.png](https://i.imgur.com/70dI6Bx.jpg)

**Comment by fnuecke** [comment]
Ah, that's interesting, I missed a path where a buffered FS is flushed due to Waila calling `writeToNBT`.

However, this is a non-issue in latest OC+Waila 1.5.7, because Waila now uses a new way to get data that does not involve calling the "regular" save method. Please upgrade to that! Will most likely also lead to performance improvements with a bunch of other mods.
