### ISSUE TITLE
Drone throws away items when using Inventory Controller

### ISSUE THREAD

**Issue by Faeranne** [MightyPirates/OpenComputers#769]
When using dropIntoSlot from a drone, the item disappears completely.  
http://pastebin.com/De6DBEXJ shows the errors listed when performing this action.  

I get too many info posts from FML to be able to see what is happening during mod loading, and the log files don't seem to be recording properly ATM.  If I can get those, ill post a full log.

**Comment by fnuecke** [comment]
The linked log mentions "mod construction", i.e. it happens during startup, so I doubt very much that that's related.

There was a mistake in the slot offset computation after the refactoring for drones, but that should be fixed in the latest dev builds. Could you please get that (http://ci.cil.li/) and see if this is still happening for you? Thanks!

**Comment by Faeranne** [comment]
Looks like that fixed it.

As for the "mod construction" issue, that gets spammed to the console anytime i open an inventory, so it may be another mod causing the issue.  If it is related to OpenComputers, ill post another issue about it.
