### ISSUE TITLE
[IRC] Enable turning off screens to conserve energy

### ISSUE THREAD

**Issue by Forecaster** [MightyPirates/OpenComputers#77]
Discussed in IRC.

Allow turning screens off to conserve energy when computer/server is not in use.

**Comment by fnuecke** [comment]
Thanks.

~~Note to self: don't forget Lua getter for power state of screen, and extend GPU lib to check for screen power events to bind GPU to another screen if necessary/possible.~~ Actually, rather not, since this could lead to very weird effects when the power gets low.

**Comment by applejag** [comment]
You could have it so that if the screen is all black and the cursor blink is off then it doesn't draw power?
I guess you could also make a switch maybe to not allow power to the monitor (switch cable maybe?).
I don't know if computers can even cut power to the monitor, they can cut the connection and therefore the screen goes into sleep mode but IRL the thing I've seen is having a switch that you flip when you're not using the computer to shutoff the power flow.

**Comment by Forecaster** [comment]
What we discussed was simply having a redstone pulse clear the screen, and the screen power usage would be calculated from the amount of lit pixels.

**Comment by fnuecke** [comment]
I have this implemented in a local branch, screens are toggled on or off when they get a redstone pulse (i.e. no input anywhere -> some input anywhere, with 'anywhere' meaning on any block of multi-block screens). Additionally there's a Lua API for querying whether the screen is on, and to turn it off and on again. Will push when 1.2 gets closer.
