### ISSUE TITLE
Drones are not charging on charging station.

### ISSUE THREAD

**Issue by Kubuxu** [MightyPirates/OpenComputers#778]
Droner are not charging after moving away form charging station and then coming back to it.

**Comment by fnuecke** [comment]
I'm relatively sure this is actually caused by the fact that the charger doesn't have enough juice to do the charging - which should be indicated by the lights on the side turning off. Note that it'll only _try_ charging if it could do so at full speed. This is to avoid energy trickling out and to improve performance a bit. The easiest way to work around this is to place a capacitor next to them, which should make it easier to keep above the required energy level (which is by default their full internal buffer).

I do agree that that might be a bit unintuitive, and am open for suggestions to alleviate it; the best way I can come up with straight away is cutting down the activation energy level to, say, half, though that kinda feels like it might fail just as easily again.

PS: I'm pretty sure of this because a) that's the only way I can "reproduce" this, b) it'd be very strange for them to stop recognizing them, because there's nothing different when moving close a second time - chargers just check their surroundings periodically to refresh the list of devices to charge.

Edit: cut the activation energy in half, see if that makes it less derpy (e.g. due to power balancing only reaching full internal buffer very slowly before).

**Comment by Kubuxu** [comment]
It probably is the issue as charger was never full (visible in WAILA) even though it was connected directly by BC pipes and then energy cells as it was extremely derpy (was sucking more than 2k RF in impulses).

EDIT: Will check the patch in near future.
