### ISSUE TITLE
Unknown code can stop server. (LIE)

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#78]
Reported.

Note. Now, i wait one guy for found this bug.

**Comment by ghost** [comment]
Me also can't reproduce huge CPU load by math.sqrt (in x64, any bignum calc very fast.)

Sorry that like ile. (I thinks rollback them is good for cpu load now.)

**Comment by fnuecke** [comment]
OK. The only way I could have imagined this happened would be if your friend somehow managed to get arbitrary Lua code to run in the main server thread, since overloading an executor thread shouldn't really matter anyway (meaning if it fails to detect a timeout quickly - which should be much less likely after the commit referenced above).
Let me know when you get more info.
