### ISSUE TITLE
OpenComputers are not building with JDK1.8

### ISSUE THREAD

**Issue by Kubuxu** [MightyPirates/OpenComputers#780]
Just a convenience issue. We will be seeing Java 8 in Minecraft 1.9.

**Comment by fnuecke** [comment]
Looks like this is an issue with the Scala plugin for Gradle that has been fixed in Gradle 2.0. But upgrading to that breaks the build script for some reason I can't quite be bothered to dig into now.

If anyone's experienced with Gradle and would like to look into making the build script work for Gradle 2.0, that'd be fantastic and very much appreciated.

**Comment by Kubuxu** [comment]
Found something:

```
Error listing versions of codechicken:CodeChickenCore using class org.gradle.api.internal.artifacts.repositories.resolver.MavenVersionLister$1. Will attempt an alternate way to list versions. This behaviour has been deprecated and is scheduled to be removed in Gradle 2.0
Error listing versions of codechicken:NotEnoughItems using class org.gradle.api.internal.artifacts.repositories.resolver.MavenVersionLister$1. Will attempt an alternate way to list versions. This behaviour has been deprecated and is scheduled to be removed in Gradle 2.0
```

**Comment by fnuecke** [comment]
I said "closing", Github...

**Comment by Vexatos** [comment]
@fnuecke Has to be "close" or "closes". I'd love the github settings to have a place to add custom phrases to recognize.

**Comment by fnuecke** [comment]
Yeah, that'd be nice to have.
