### ISSUE TITLE
Implement BC IHasWork API

### ISSUE THREAD

**Issue by asiekierka** [MightyPirates/OpenComputers#782]
It lets you signify whether a machine has work to do (including when it is doing work) (so, for example, if an assembler has a robot ready to assemble, a computer is running, etc.)

https://github.com/BuildCraft/BuildCraft/blob/6.1.x/api/buildcraft/api/tiles/IHasWork.java

This one goes on the tile entity. Really, all it does is add a "has work?" gate to BC so far, but other mods might use it in the future (hopefully)

**Comment by LordFokas** [comment]
You should do this for ALL BC gate triggers.

**Comment by fnuecke** [comment]
To clarify, this would return true whenever the comparator would return a redstone signal, basically?

**Comment by asiekierka** [comment]
@fnuecke - Generally, but with a few exceptions: "has work" does not mean that the machine is working; rather, it means that it either is working or it is ready to do work. (This also means machinery which doesn't do any work shouldn't implement the interface, or the trigger will appear on them)

**Comment by Vexatos** [comment]
Computronics already has BC triggers for checking whether the computer is running, it also provides actions to turn the computer on/off. If you are going to add full BC gate support (not just the triggers automatically being added if you implement an interface), tell me and I'll remove the OC gate stuff from Computronics.

**Comment by fnuecke** [comment]
All right, so from my understanding these would make sense:
- Computers/Microcontrollers/Robots/Servers: are running ("are working")
- Charger: is charging a robot / drone (one or more are in its vicinity)
- Assembler: can start assembly || is assembling (including if it doesn't have enough power to continue)
- Diassembler: is disassembling (including if it doesn't have enough power to continue)

@Vexatos regarding further integration: I must admit I'm shamefully out of the loop when it comes to BC's gates. The last time I actually worked with them was in MC 1.4.7 or so, and I only barely remember what I used them for (a monstrous octocore netherrack-to-lava-with-energy-surplus generator-thingy). Unless it'd make more sense to keep said integration in Computronics because it, say, also applies to CC: if you'd like to contribute it I'd gladly merge that pull request!

**Comment by asiekierka** [comment]
For Charger. "Has a robot or drone needing energy in its vicinity". Other than that, perfect.

**Comment by Vexatos** [comment]
@fnuecke CC integration? The OC-BC statements aren't related to CC at all.
I would make a pull request, but keep in mind I can only code in Java, not in Scala; of those statements you mentioned only the "is running" thing is implemented by Computronics, the other things aren't even possible to check using the API.

**Comment by fnuecke** [comment]
Is `hasWork` called on the client, too? Because getting an accurate value for "do they need charging" will need extra synching (because the actual node network is only serverside), which is kinda meh. In that case I'd prefer to make it what I wrote above.

@Vexatos ah, I just assumed. Well, it's not like I have a big problem with Java code being contributed; it's just that I may port/re-write it in Scala sooner or later - when I have to work with it - because I'm more comfortable with that. In particular in the integration package there's a bunch of Java code already, since that was pulled from OpenComponents which was pure Java. Aaaanyway, to get back on topic: if it adds additional value that is not provided by IHasWork and you want to PR it into the integration package, don't let the language stop you ;-)

**Comment by Vexatos** [comment]
Once I get time (In a few days), I might port that part of the code over.

**Comment by fnuecke** [comment]
Sufficiently complete for now, and I want to release 1.4.3, so I'm closing this :P
