### ISSUE TITLE
OpenComputers does not take WorldEdit too well

### ISSUE THREAD

**Issue by asiekierka** [MightyPirates/OpenComputers#790]
http://asie.pl/occrash.txt on every server launch

Calling @marcin212, @Kubuxu, @Magik6k as they care

**Comment by fnuecke** [comment]
Is this purely due to the presence of WorldEdit (in which case that's new in a very recent build because I have a not-too-old build running with WE just fine; then again, that's with the Bukkit version on Cauldron). Or is this after performing some world editing, probably copying a server rack? That then was somehow connected to it's "original"? Because that _might_ explain it. The only way I see this happening right now is two nodes with the same address being in a common network... I was pretty sure I checked for that when adding nodes/merging networks, but maybe I don't/forgot some case.

**Comment by fnuecke** [comment]
Please give the latest dev build a try. If it was what I think it was that _should_ fix it. Or it may also crash in the new code. Let me know how it goes.

**Comment by asiekierka** [comment]
@fnuecke - No, this happens:

(a) with WorldEdit for _Forge_, which handles things like NBT "correctly",
(b) while duplicating configurations of components, which copies over the node and causes rather serious issues.

I believe this is a bug that should be fixed on both sides. Also, yes, you're exactly right: this happens when two tiles have the same node, IMHO

**Comment by fnuecke** [comment]
Right. So it is due to components with the same node address being put into a common component network; that should be fixed by 2c6f0ee (was only tested for single nodes being added before). May have other side-effects (such as computers hiccuping) but at least it shouldn't crash anymore.

**Comment by fnuecke** [comment]
If for some reason it _does_ still crash, lemme know.
