### ISSUE TITLE
'Unsupported side' error when working with inventory_controller component

### ISSUE THREAD

**Issue by GrumpyPirate** [MightyPirates/OpenComputers#803]
Hello!

Since OC1.4.3 I've been unable to use sides.back when working with the inventory controller component and accessing a robot's own inventory. It simply throws an error, stating 'unsupported side'.

I've had a look at both the wiki and the release changelogs, and nothing seems to suggest that there has been a change with how one should access robot inventories with the inv controller, so I'd like to report this as an issue.

Cheers

**Comment by fnuecke** [comment]
Oops, I wanted to see if I could make this backwards compatible, but forgot (and therefore also forgot to mention it in the changelog). Due to a lot of people not seeing that option, and me reworking some internals for the Drones which encouraged the change, too, there's now a dedicated method for that - `getStackInInternalSlot([slot:number])`. And yes, I need to update the wiki...

I'll see if I can add backwards compatibility.

(Also, assuming you're [_the_ GrumpyPirate](http://bdcraft.net/community/pbdc-patches-wip/opencomputers-t3623.html): I absolute love the texture work you've done. The robots look particularly adorable!)

**Comment by GrumpyPirate** [comment]
Fantastic, thanks for clearing that up!

And yes - I've had almost as much fun texturing the mod as I have playing it. :) Massive thanks to both yourself and the OC team!

**Comment by shogun-kub** [comment]
Hi! It seems to not working again. Maybe it's better remove mention of _back_ in wiki? Documentation is somewhat misleading now :/
I forgot to mention, I'm using version 1.7.10-1.5.22.46 of OpenComputers
