### ISSUE TITLE
StargateTech API error

### ISSUE THREAD

**Issue by mindcloud69** [MightyPirates/OpenComputers#81]
upon placing a advanced case in a new SP testworld minecraft crashed with java.lang.NoClassDefFoundError: stargatetech2/api/bus/BusEvent$AddToNetwork.

I do not have stargate tech 2 installed. 

crashlog.
http://pastebin.com/dgYb9Yzf

**Comment by fnuecke** [comment]
Oh right, I knew I'd forget to test something... thanks for reporting, will fix ASAP.

**Comment by LordFokas** [comment]
java.lang.NoClassDefFoundError: stargatetech2/api/bus/BusEvent$AddToNetwork
Are you shipping the whole bus API? if you are, the event class should exist...

**Comment by fnuecke** [comment]
I don't ship any APIs if I don't have to, mostly to avoid conflicts. That's why OC requires Forge 940, as that introduced the [`Optional`](https://github.com/MinecraftForge/FML/blob/1.6.4/common/cpw/mods/fml/common/Optional.java) annotations that make this possible in a comfortable manner. Works pretty well for the most part, but in this case something weird is going on, so I had to work around it a bit. I'm pretty sure I got it working, now, but if you still get that error in 1.1.2a or later I'll have to take another look (but I assume you quoted the above crashlog?).

**Comment by LordFokas** [comment]
yes, I quoted it.

**Comment by LordFokas** [comment]
but Optional doesn't work in this case because it is intended for interfaces, and you're directly referencing a class that doesn't exist. It wouldn't be so bad to ship it, because if SGTech2 is loaded FML won't load the one you ship, and if I change it I'll most likely ping you in advance, even though I'm 90% sure I'll never change that class.

**Comment by fnuecke** [comment]
True. I skipped some thoughts there, sorry. That it couldn't find `AddToNetwork` is another mystery, because at construction time the class loader should have no reason to try to load that class. Moving it to another class solved that, though. Which doesn't really make sense, but hey, magic! After that change, it caused the same error but with `IBusDevice`, which is what I was referring to above. I now implement it in the first derived (abstract) class instead of in the trait (interface) directly. Which for some reason works. Again, sorry for the confusion.

**Comment by LordFokas** [comment]
It doesn't affect me because I have both mods :p
