### ISSUE TITLE
Computer wont work at all

### ISSUE THREAD

**Issue by CrazzyCreeper0000** [MightyPirates/OpenComputers#82]
i build like it says but it wont work

**Comment by fnuecke** [comment]
You'll have to help me help you, because as it is this is almost the ultimate example of a bad report/support request.

First of all, post your log files. Or just read them, maybe they'll already tell you what's wrong.
Are you using the latest version of the mod? (1.1.2a)
Local game or dedicated server?
If it's a server, which one? Forge? MCPC+?
What Forge version?
Any messages in game? What does it print if you use the Analyzer on the computer?
Did you make any config changes?
What system are you playing on? PC? Mac? Linux? 32 bit or 64 bit?
Other mods?
