### ISSUE TITLE
Port to Minecraft 1.8

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#830]
Sooo, just to give some info on where I stand on this and what the progress is. I'd like to port OC to MC1.8, but I can make no promises as to when the port will be done. I currently have it running in 1.8 (i.e. the game starts, some things work), but a lot of stuff is still broken / unfinished / unpolished.

Port-related TODO
- [X] Block rendering (including multi-block screens and cables).
- [X] Computers, servers, tablets, drones, microcontrollers and general "networking" (i.e. components connected to computers).
- [X] Case, screen and cable coloring, separating cables and screens by color.
- [X] Rework robot events to be more generic so they can be used for drones.
- [x] Special item rendering
  - [x] Floppy disk colors
  - ~~Floppy disk labels~~ Doesn't seem to be possible yet.
  - [x] Drones
  - [x] Floppies in disk drives
  - [x] Robots
  - ~~Upgrades on robots~~ Maybe at some point.
- [X] Robot equipped tool rendering.
- [X] Robot movement.
  - Redesign of robot movement? (see details below)
- [x] Clean up stuff related to new TE update logic (there's some stuff that only needs to tick on the server, e.g.) which is based on implementing an interface.
- [x] Clean up API.
- [X] Some rendering glitches here and there.
- [x] Testing all the things.

Edit: extracted non-port related stuff to #869.

~~Regarding robots, the main issue here is that the tile entity switcheroo required for moving them doesn't work the same way it did before. Since this will usually run in the TE's update method the new TE isn't set immediately when the block is set anymore (to avoid CMEs from what I can tell). A quick workaround for this _may_ be to delay machine execution into a post-tick-event-handler. However, what I'd rather do is rework robots a bit. I'd like them to actually also be entities, but as opposed to drones they'd no longer be able to fly, to make drones more desirable (at least not fly very high, jump one block maybe). To still make them usable in the old ways, they'd have the ability to "deploy" themselves into a block (and undeploy back into an entity), so they'd still be able to read and emit redstone signals, be piped into and out of and so on. Think Starcraft siege tank. Buuut that'll be work. Lots of work. Not sure when / if I'll get around to that.~~

~~Oh, side note: remote terminals will be gone. Tablets all the way now.~~ Nah, they won't.

Will probably push what I have soon-ish so those interested can have a look at the code so far. I'd kind of like to finish cleaning up the API before that, though, just in case...

**Comment by Techokami** [comment]
Only problem I can see with the change to Robots is that it would make the dig program a bit, uh, useless. Unless there is going to be a higher tier of Drone that can handle digging and inventory.

**Comment by Kubuxu** [comment]
Will drones be able to right click block? It would be extremely useful for example harvesting crops.

**Comment by rmellema** [comment]
If robots as entities means that robots are not bound to specific blocks anymore then I'm all for it! But they should still have a way to go and down. Jump for a standard configuration and maybe a hover upgrade so the robot can hover something like 2 meters into the air. 

I haven't had the time to play with drones, but how do entities actually work with liquids? Otherwise that would also be handled specially for robots, since I don't think that robots would float.

**Comment by MyNameIsKodos** [comment]
What about instead of robots jumping one block, maybe make them require a surface to be present to move, ie they could go up walls, across ceilings, etc, but drones could operate midair freely.

**Comment by fnuecke** [comment]
Robots would still have their inventory, be able to break stuff, use tools, all of that. They'd just be entities, so they could _potentially_ move around more freely (would need to see how feasible this would be, seen from a scripting position, i.e. how reliable moving around could be made to work).

As for the dig program, yeah, that'd have to be adjusted to take into account the fact that the robot couldn't leave its hole the way it works now :P

Drone right clicking... I guess.

Robot vertical movement, I didn't mean the "jump" quite so literally, more as in "they can move up to neighboring blocks if the height difference doesn't exceed one or two blocks), either "automatically", or by allowing to hover up to a certain amount, yes (I prefer the latter).

**Comment by Namarius** [comment]
Removing the ability of robots to move freely around the world seems like a feature remove for me. And that feature remove can only be compensated by other features (that already there) and not by the player itself. For me this is just over complicating stuff.
I am playing on a server where every robot is a real placement and this pretty much render them useless or mostly useless for me.
Another thing i am afraid of is the loss of a guarantee of the robots position. For example what happens to the robot if all "anchor blocks" disappear? Will if fall down or just stray there? There are too many if in this change.
But it's your decision fnuecke. I don't like it but will accept it.

**Comment by fnuecke** [comment]
By "move freely" I assume you mean flying? Drones! I feel they need some kind of advantage, otherwise they're just a tad too gimmicky :P And once they're more useful / required, I expect some programs making their use easier to pop up (I might even write something myself).

As for 'free positioning', as mentioned, that'll need some evaluation. Unless there can be a way to relatively easily make movement/positioning reliable, that won't be an option.
Assuming there's no pushing them because no way to make that work in reliable fashion, one simple solution for the falling down thing I can imagine working relatively well would be to disallow them to move into invalid positions, but always allow them to move down. I.e. they'd remain where they are, but could only move down until they're at a height again where they can move horizontally.
We'll see. None of this is set in stone, yet.

**Comment by Namarius** [comment]
If you think drones are not that useful then I have an idea for you.

Just drop the idea of robots being complete computers at all and combine the functionality of drones and robots, so that only computers/servers/microcontroller as static blocks and drones as dynamic entities are left. This would result in complex designs with computers controlling drones by wifi to do complex tasks or just using tablets.

**Comment by fnuecke** [comment]
I didn't mean to say they're useless, just that there's a bit too much overlap in functionality with robots.
And I'm left a bit confused about your preferences ;-)

Bad:

> For me this is just over complicating stuff.

Good:

> This would result in complex designs [...]

But anyway, I don't want to drop either, just separate their fields of employment a little.

**Comment by Namarius** [comment]
Well I just can't imagine how to separate them without breaking their usage. I am not afraid of complex things. I pretty much like them.
It just feels like you have build a nice road across a valley and the next day somebody placed an abyss across your road and your only options is a balloon or two elevators to go down to the ground and up again, just because you are not allowed to build a bridge.

I hope this clears it up. But I think I am doing too much alarm without any reason.

**Comment by MyNameIsKodos** [comment]
I feel like computers, servers, robots, and drones (In that order) are becoming more and more like going from wood tools, to stone, to iron, and finally to diamond, in that they each have their place in the game, and none of them are useless, but there's always the right tool for the right job.

**Comment by egorchik007** [comment]
Feature requests:
1. Please add some (mechanical) way to control the items from computer, so that we can throw items out of the chest/accept them. An upgrade or special block or so. I want to make a real ATM :bank: 
2. Also, please consider upgrading BuildCraft bridge so that we can control the diamond pipe and other stuff. Right now it isn't really useful. 
3. Right now it's impossible to make a small ATM machine within OpenComputers (as I mentioned before), and dispenser isn't the right way. However, it's not only the wrong way to do such stuff, it's inconvinient too (as dispenser needs special redstone wiring, cos we can work with it only as inventory, and we can't emit redstone to it directly via adapter, please add some way to do it software-way, like controlling the note block).
4. Is it possible to use CC peripherals without CC installed? I wish I could have magcards and RFID stuff with OC, but Immibis peripherals require CC to run. Perhaps it's possible to make a fake-mod (being activated when there is no CC installed)?
5. Inventory upgrade to get block/item id? PLEASE. 

Robots as entities? Great!
Thanks.

**Comment by gjgfuj** [comment]
@egorchik007 Please create a new issue.
Otherwise, a few responses to those:
1. Inventory Controller?
2. yep, may happen.
3. There's a redstone card/redstone IO block?
4. Yeah, probably good, but we could just get replacements for OC.
5. There's a config option, it's not on by default because it breaks immersion.

**Comment by rakiru** [comment]
> there's a bit too much overlap in functionality with robots.

I'd say there has to be at least a little overlap. Without a massive buff to drones (to the point where they're basically robots without being blocks), there's a void between the two which simply can't be filled because neither machine provides the necessary tools. I quite like robots as they are, and drones being almost perfect other than the inability to click on things (breaking hand-harvestable blocks would be nice too). A task as simple as mining out an area would be impossible without something that can both fly and break blocks. Perhaps an upgrade for robots that allows them to fly? Another alternative would be a ground robot (a tracked bomb disposal style one perhaps?) that has more slots/complexity than a regular robot (the robot's could be reduced), at the cost of not being able to fly?

My current use cases and what I use:
- Mine out rooms (robots: they can mine and fly)
- Build structures (robots: they can place blocks and fly)
- Automate harvesting (robots: they can mine and fly)
- Exploring (drones: they're fast and simple)

The harvesting and building could be done with drones with your suggested buffs, but mining out rooms would be impossible with robots (or at the very least, overly complicated, by building scaffolding or something) and I'd end up just using a quarry, or TNT. With that, now all I have are things that drones can do, with no practical use for robots. I feel that your suggest buffs to drones easily gives them enough of an advantage to replace robots in a lot of situations.

Edit: Sorry if that was a bit of a ramble.

**Comment by natedogith1** [comment]
For the robots' movement, I like the suggestion of having them able to climb walls. Though the point of this comment is to suggest another idea: allow robots to move from valid positions to invalid positions. This would allow robots to do things like step over a ledge and place a block beneath themselves (for things like bridge building) and navigating over 1 wide holes.

**Comment by fnuecke** [comment]
Thanks a lot for all the feedback so far! Some very good points in there.

Little update: pulling the movement logic out into a tick handler did the trick. Movement works like it did before now. Considering I'm a generally... optimizing person (yes, that was a euphemism for lazy), making some adjustments will probably the most I'll do here. Nothing near the massive redesign I mentioned earlier.

I think a basic "maximum altitude" would work well to give drones a little more advantage wrt. maneuverability while not making robots utterly useless. Something like 8 blocks above ground, potentially with upgrades to increase it further? Movement would then allow moving if either the start _or_ the destination are valid, down always being valid? And drones will likely get a usability boost in that they will be able to perform basic world interaction.
**But**: I'm currently undecided whether this will actually just go into a 1.5 version that will also be for MC 1.7, seeing as a lot of mods seem to be hesitant about moving to MC 1.8 (which I can very much understand). So this is potentially getting off-topic in this issue. We'll see.

**Comment by gjgfuj** [comment]
I vote for that.
