### ISSUE TITLE
Native lua wont work on 32bit OpenBSD

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#840]
Well... i guess you need to build it then :laughing:

**Comment by fnuecke** [comment]
If there's more than one person running OpenBSD and hosting OC out there, I may look into this.
Otherwise I'm afraid it won't justify the effort of setting up a VM and all that for me.

**Comment by Wuerfel21** [comment]
wouldnt a general unix one work? the api is said to be consistent across posix/unix systems

**Comment by fnuecke** [comment]
I'm pretty sure I tried re-using the libs compiled in Ubuntu and they didn't work in FreeBSD. I'm not familiar with the whole *BSD family, honestly, which is one of the reasons I won't just do it real quick - because it won't be. The difference in usage is just too big (took me ~10 minutes just to figure out I had to press scroll-lock to scroll back up the buffer).

Feel invited to test this yourself. If you're running OpenBSD, which I consider somewhat exotic, I'd expect you to be able to do that ;-)

**Comment by cinder1992** [comment]
The issue (Probably) is that BSD doesn't use glibc, which is default on Ubuntu. what I'd do is look into a way of allowing an OS with an existing build system (like every version of linux/BSD) to build their own Lua libraries on first install... although I'll assume you've already considered that.

**Comment by fnuecke** [comment]
Not really, because I feel that's a tad beyond the scope of a mod ;-)

**Comment by Wuerfel21** [comment]
doesnt dynamic linking work also when the function pointers are diffrent? or is libc static?

on building the thing, i would just "make" it, or is there some extra config or dependancies?

**Comment by Wuerfel21** [comment]
Actually, i think i heard once BSD had a compat thingy,  may try that, wasnt there a way to force a binary?
