### ISSUE TITLE
Client Crash when turning on Computer

### ISSUE THREAD

**Issue by Keridos** [MightyPirates/OpenComputers#855]
https://paste.ee/p/sjuxR
Computer worked fine a week ago and has the same hardware.

**Comment by fnuecke** [comment]
Hmm, the best guess I can make here is that some mod is shipping an old (1.3) OC API.
If it worked a while ago, that kind of points to a change that lead to a shuffle in load order, so that that API version is now loaded first. If you made no changes to your modpack... magic?

Either way, please also try if this happens for you if OC is the only installed mod.

**Comment by Keridos** [comment]
I broke the computer and readded all the stuff (and recrafted the lua bios) now it works.... What a weird problem

**Comment by fnuecke** [comment]
That... makes no sense. I have no idea what was going on there.
If it happens again, please reopen, until then I'll consider this some freak corruption :-P
