### ISSUE TITLE
[Robots] Unbreakable Creatix

### ISSUE THREAD

**Issue by TinkerWorX** [MightyPirates/OpenComputers#868]
For special cases it'd be great to have unbreakable creative robots.

**Comment by fnuecke** [comment]
I think it'd be fine in the case of creative robots, since those are special already anyway. The reason robots are usually always breakable (regardless of user list) is to avoid griefing after all, and if you have access to creative mode all concerns wrt that are pretty much out of the door already.

**Comment by TinkerWorX** [comment]
That's exactly my thought as well. Anyone with the rights to make a creative robot, will already be more than capable of griefing.
