### ISSUE TITLE
OpenComputers 1.5

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#869]
Splitting this out of the MC 1.8 issue, because I'm considering doing a 1.5 for MC 1.7 after all.
## Java API changes
- [X] MachineHost.markForSaving -> markChanged
- [X] MultiTank -> api.internal, Robot extends MultiTank
- [X] Make robot events in API more general so they can be used for other robot-like things (like drones)
- [X] Change driver.item.Memory to return a "general size" instead of actual bytes; allow interpretation of size by architecture (e.g. some may need more memory than Lua, some less)
- [X] Change geolyzer analyze event to take arbitrary coordinates
## Lua API changes
- [x] Make internet card use userdata (in particular for HTTP requests) 
- [x] Deprecate/remove setBootAddress/getBootAddress, add way to write to arbitrary EEPROM location instead
## Gameplay changes
- [x] Limit robot flight height
- [X] Allow simple world interaction for drones (place, break hand-breakble stuff, use?)
- ~~Make inventory upgrades store their stuff internally, act similar to bags?~~ Meh.
## General changes
- [X] Remove memory size info from RAM items, make interpretation depend on architecture
- ~~Rework power distribution logic a bit to be more efficient~~ Brainfart.

**Comment by Vexatos** [comment]
> Make robot in API more general

I hope internal.Drone won't be gone so you can still make drone-specific/drone-excluded drivers.

**Comment by fnuecke** [comment]
Edited to be more clear. I mean the events, not the internal.\* stuff. So yeah, you'll still be able to differentiate those.

**Comment by SolraBizna** [comment]
It is good that the boot address functions are being replaced by a more general, OS-independent mechanism. My NetWare-like project currently interprets the boot address as that of a modem rather than of a boot filesystem, and would certainly benefit from being able to store other data.

However, since the EEPROM is executed as one big block, the new solution would seem to require rewriting data that must survive intermixed with real Lua code. That seems a bit fragile for my taste. Making the Lua boot process ignore all data in the EEPROM past a certain point&mdash;the first NUL character, perhaps?&mdash;would fix this. The remaining EEPROM space would then be usable for arbitrary data storage without irritating Lua.

Other architectures would be able to choose whatever approach works for them... soft ones like a hypothetical Python or Ruby architecture might take a similar approach, while [a harder one](http://oc.cil.li/index.php?/topic/430-real-cpu-for-opencomputers-interested/) would simply require the code to avoid jumping to whatever areas it uses to store data.

**Comment by fnuecke** [comment]
Yes, my thought when writing the above was to have some way to get / put strings at specific addresses, and the script part of Lua simply ignoring that part - either by nulling or by prefixing the area with a "--" (comment it out, essentially).

The more I think about it though, the more inclined I am to instead make the EEPROM have a dedicated, _very small_ memory block for this. It just feels way too unstable to me, otherwise.

**Comment by natedogith1** [comment]
Essentially adding a CMOS built in to the EEPROM? (CMOS being what real computers use to store the settings you configure in BIOS, if  I recall correctly)

**Comment by SolraBizna** [comment]
Old Macs had a 256-byte "parameter RAM" that stored boot info, sound volume, and other machine-level persistent settings. That would be more than enough room for a boot address, and whatever else I can imagine needing before the filesystem is available. (Make it 512 bytes and you could even store a 2048-bit private key in there with plenty of room left over.)

As far as my NetWareish thing, 128 bytes would be enough for three addresses (primary modem, boot server, file server) and some additional cruft (client ID / deployment category / authentication / etc.) without even needing to do any binary packing.

Attaching the PRAM to the EEPROM like you suggest ensures that the PRAM will never be separated from the code that understands it. Making it part of the computer case or attaching it to the CPU makes upgrading / migrating an existing computer more annoying than it already is, and making it _yet another_ separate component people would have to put into _every_ computer would just suck.

If you wanted to be really sadistic, you could make it like a battery-backed SRAM, in that if the computer goes too long without being powered you lose the contents. ;)

**Comment by fnuecke** [comment]
Yeah, having it in the EEPROM seems to make the most sense, usability-wise, so for once that's what I'm favoring ;-) As for what it actually is pseudo-implementation-wise, I'll leave that up to interpretation, and just call the methods `getData/setData` or something generic like that, I think...
