### ISSUE TITLE
Strange power conversion ratios

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#888]
As you can see [here](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/application.conf#L735-L744), you have quite specific power conversion ratios for your internal OC power. They, however, look pretty random to me. I don't know why they are what they are right now, but wouldn't it be better to have the base conversion ratios like almost any other power-converting mod does it? (e.g. the fact that 1 BuildCraft MJ should equal 10 RF)
For conversion, most people use the value that one piece of coal gives in the according coal-burning generator of a specific power system (i.e. the IC2 Generator or the BuildCraft Stirling Engine).
The way you currently have the values makes it almost impossible to calculate actual usage between multiple power systems, at least it makes it very complicated. It also makes it hard for addons to find good energy consumption values. I'd recommend using one of the energy systems as a base value and adapting the others relatively to that base.

**Comment by gjgfuj** [comment]
Yes, I have experienced this as well, for quite a while.

**Comment by fnuecke** [comment]
The values in there are based on energy generated from coal; e.g. a normal generator in IC2, a stirling engine in BC, a steam dynamo in TE.

In particular the RF value surprised me as well, but in my tests a dynamo generated _way_ more energy per coal than, say, a stirling engine or an IC2 generator than it should at a 1:10 ratio.

Unless this changed and was "because beta", I'd need a very strong argument to use a non-coal-based (and hence in my eyes much more "random") value.

**Comment by Vexatos** [comment]
Strong argument: RF was made with a 10:1 ratio to MJ in mind. the RF values you measured seem pretty random, so I'd rather adapt a) the RF value to the BC one or b) everything to the RF one.
For reference, the BuildCraft Stirling Engine previously produced 1600 MJ per piece of coal, now that BuildCraft uses RF it produces exactly 16000 RF.

**Comment by fnuecke** [comment]
Right, well then. Will adjust and base the RF values on BC's power generation. Because dynamos are... outliers (+25% energy for 1 coal, +100% for 1 block of coal, compared to stirling... uhh,  that water must be magical).
