### ISSUE TITLE
Total memory free is dropping suggesting a memory leak

### ISSUE THREAD

**Issue by theron61** [MightyPirates/OpenComputers#893]
I have an odd issue. I have a Tier 3 server with 4 x 3.5 RAM; 8 MB on my server.  It is monitoring a combination of Thaumcraft, AE2 and RotaryCraft machines to automate fuel and essentia processing.  The gotcha is that the computer keeps running out of Memory.  The issue I have is that when I call computer.freeMemory() - I see the following:
1. The amount of free memory does not track with how I use variables/tables.  Same code, would expect a similar leak each time for the same list of tasks.  I understand you can't force LUA garbage collection in OC.
2. The amount of free memory does not return to the server maximum if I exit the progam either normally or with Ctrl-Alt-c. It is acting like memory is still allocated even though the server is idle which seems really strange to me.
3. The time to Out-of-Memory is wildly inconsistent.  The best I can do is watch for free memory to fall under a given threshold and try to reboot. 

Any ideas?

**Comment by fnuecke** [comment]
- Do you store anything as a "global" variable (_G.x = ...)?
- Do you register event listeners that you don't remove when the program terminates?

Without knowing more about your program it's hard to say what's going on, but I'd suggest checking the forums for that, there are some useful threads on this topic IIRC.

Also keep in mind that a single call to computer.freeMemory() isn't very informative, since GC runs irregularly. If you want a reliable value, try something like this script:

``` lua
local computer=require("computer")
local max = 0
for i=1,10 do
  max = math.max(max, computer.freeMemory())
  os.sleep(0)
end
print(max)
```

Saving the above as a program and running it a few times gives me stable numbers (after the first run(s) in which Lua first compiles the script and my cache function prototypes).

**Comment by theron61** [comment]
> Do you store anything as a "global" variable (_G.x = ...)?
> Do you register event listeners that you don't remove when the program terminates?

Not that I am aware of.  I use local variables in the body of the script referenced in the internal functions for things like item counts or aspect-item-associations. 

The script you provided shows around 800 KB used consistently from run to run with the server as it is now.

**Comment by Eunomiac** [comment]
I *think* there may have been a derp in the memory tiers---it's looking like each of the X.5 Tiers is taking the value of the tier below it:  Four sticks of Tier 1.5 RAM are giving me a `computer.totalMemory()` of ~786.5 KB, or 192 KB per stick, which is the Tier 1 value.  Likewise, four sticks of Tier 3.5 RAM gives me a total of ~3 MB, or ~760 KB per stick, the Tier 3 value.

Doing a bit more testing to confirm that changing the Tier 3 value in the configs affects the Tier 3.5 RAM; I'll report back.

**Comment by fnuecke** [comment]
If I understand this correctly that sounds like it has to be something with your script. I'd recommend putting it on pastebin/gist and post on the forums for feedback. Closing this unless it turns out it is an issue in OpenOS.
