### ISSUE TITLE
Metadata for files

### ISSUE THREAD

**Issue by PowerOfTech** [MightyPirates/OpenComputers#894]
Metadata should be a string with fixed size, that can store a 128 bytes of data. This should be provided by methods
filesystem.getMetadata(path:string):string or nil,string
and
filesystem.setMetadata(path:string,data:string):boolean or nil,string
Metadata will store a file permissions, or file attributes for non-Unix systems.

**Comment by fnuecke** [comment]
I don't really think this makes sense, as things stand. Access would still have to be enforced on the machine's side anyway, otherwise there'd need to be some kind of authorization logic in the read/write methods, which isn't really feasible. It'd break too much, and over-complicate file access too much, requiring the BIOS to already handle FS permissions when booting. And even if the OS would handle this, then this would basically boil down to being a "tag" for files. Which brings up the issue of how that would be stored. This was discussed before, and there were no satisfactory answers from what I can remember.

I think this is something that is better implemented in an OS that is designed for this, i.e. that also wraps "physical" access to file system access and maintains this information itself.

**Comment by PowerOfTech** [comment]
I thought, BIOS does not required to handle FS permissions, because it is in "supervisor mode", but for multiuser OSes, that provides multiusers in software level, and operates with files by system calls(component.filesystem[...] is not avaliable for users), file permissions will be checked in software level.

In OpenOS this function does not really required, and, I think, won't be provided as part of filesystem API(only by the component.filesystem[...], if user wants to create a tag for file), but specially for another systems it will be very good.

**Comment by fnuecke** [comment]
Well, in that case, those systems can do this by wrapping filesystem access then; e.g. by creating wrapper methods for `component.proxy` and `component.invoke` that supervise file access. They could store the permissions in an actual file on the file system then, that cannot be accessed without root rights or something.
