### ISSUE TITLE
Should provide a warning for lack of / improper EEPROM BIOS

### ISSUE THREAD

**Issue by Vekseid** [MightyPirates/OpenComputers#896]
Similar to the missing CPU message.

I went into Creative to test something out quick, and apparently NEI gives you a blank EEPROM when you grab a LUA one, so I was wondering why the machine refused to boot for a short while.

**Comment by Vexatos** [comment]
Well, how is the computer supposed to print an error message when it doesn't have a BIOS to print the error message?
Also, there is an Analyzer item you can use for that.

**Comment by gjgfuj** [comment]
I believe he is talking about inside the computer GUI itself.

**Comment by fnuecke** [comment]
The way the error is generated now, showing a message in chat like it is done for CPU and RAM isn't technically feasible due to how booting works (runs asynchronously).

A potential solution would be to check for an `eeprom` component when preparing to boot, but some architectures may not even need one, so I'm not sure this is the best approach?

**Comment by Vexatos** [comment]
> Also, there is an Analyzer item you can use for that.

@fnuecke How about just using analyzer prints?

**Comment by fnuecke** [comment]
Well yes, but one of the biggest hurdles of entry - from what I've seen - is that people don't know the analyzer exists / can be used for that. So somehow adding an alternative way to notify users of something as fundamental as needing an EEPROM seems like a reasonable addition?

**Comment by Vexatos** [comment]
@fnuecke How about a huge "Get an Analyzer for debugging!" message in the case?

~~Just in case~~ Bad pun, sorry.

**Comment by Vekseid** [comment]
> A potential solution would be to check for an eeprom component when preparing to boot, but some architectures may not even need one, so I'm not sure this is the best approach?

There are architectures that can attempt to boot without RAM too, In theory, you could do something with them too.

Alternately, flag potentially critical elements in the GUI itself. Let them press the power button even if things are red/missing. If it doesn't work, explain the red elements in more detail as needed, e.g.

"Perhaps something is wrong with the EEPROM/BIOS chip?"
"We seem to be missing a CPU."
"Machine seems a bit short on RAM."

**Comment by fnuecke** [comment]
> How about a huge "Get an Analyzer for debugging!" message in the case?

That seems reasonable. Well. Not the "huge" part, because the GUI is pretty crammed already, but the general idea. But I don't really see where to fit that in...

> Alternately, flag potentially critical elements in the GUI itself. 

While I'd prefer this over more text, I think it's easy for that to be misleading; e.g. red slots could easily be interpreted as locked / unavailable. Maybe a pulsating 'normal' highlight (i.e. like when hovering it)?

**Comment by magik6k** [comment]
Maybe small LCD-like Display (16x1 or like that) inside case, accesible through some kind of component (component.lcd.set("Missing BIOS") seems reasonable, also I'd call EEPROM a bootloader)

**Comment by fnuecke** [comment]
Too late :P Pointing people towards the Analyzer should cover 90% I think.
