### ISSUE TITLE
Tablets cannot be opened when looking at a block

### ISSUE THREAD

**Issue by helpiminabox** [MightyPirates/OpenComputers#905]
Before I say anything, I'm aware that this is caused by functionality added to tablets (can't remember exactly what), but it makes somewhat inconvenient for me to use a tablet in my base/underground, since I need room that I often don't have. Not only does it not let me open the tablet, it doesn't let me shift-rightclick to bypass the behavior.

Here's what I propose to let people use tablets in tight spaces:

a) disable autoshutdown on shift-rightclicking and add a power button to the "back" of the tablet (the gui you normally get when shift-rightclicking)
b) always allow shift-rightclick to let you look at the back of the tablet, no matter what
c) add a button to the back of the tablet to flip it over to the front where you can interact with it like normal

If you couldn't guess by now, I really like tablets and how they work :)

**Comment by fnuecke** [comment]
I agree this can be kind of an issue; another issue that I noticed, however, is that the way it is now (shift-rightclicking opening the GUI) it isn't possible to use this on certain blocks (like chests or levers), which is why I'm tagging this as a minor bug.

New behavior incoming (using 'long' clicks for analyzing blocks, i.e. keeping the right mouse button pressed for a bit).
