### ISSUE TITLE
Robot gather Ender-Lily spam console 

### ISSUE THREAD

**Issue by Morok91** [MightyPirates/OpenComputers#907]
Server Cauldron 1.7.10 with WorldGuard 5.9
Robot swingDown() Ender-Lily and spam in console
http://pastebin.com/LBaq6WyQ

**Comment by fnuecke** [comment]
I don't see how this message is OC's fault, sorry. From the trace it looks like some plugin can't handle block break events caused by fake players, but that's only a guess. I'm also quite sure it's not OC logging that message, I double checked all places where OC logs messages of type `ERROR`.

Try removing plugins until it doesn't happen anymore, then you know which plugin to investigate wrt. fake player support / options to suppress the log message.
