### ISSUE TITLE
TileEntity oc:case has thrown an exception, its state cannot be restored

### ISSUE THREAD

**Issue by fogger** [MightyPirates/OpenComputers#926]
After updating from `1.4.7.31` to `1.5.0.427-dev`

http://haste.pagefortress.com/sumecizure.avrasm
And as expected, my computer is empty.

I am working with a test copy of the world, and have access to the uneffected world still running `1.4.7.31`

**Comment by fnuecke** [comment]
That's quite an odd one. It looks like the data in `world/opencomputers/state` got corrupted somehow (otherwise parsing the NBT should not fail, it should fail after that, if at all). I'll throw in a try-catch to avoid these errors completely corrupting tile entities, so at least the inventory and such should survive.
