### ISSUE TITLE
Using lava in Generator Upgrade leaves bucket inside

### ISSUE THREAD

**Issue by GoneNomad** [MightyPirates/OpenComputers#930]
This was on OpenComputers v1.49, I believe.

When I used a lava bucket to fuel the generator, I had expected the empty bucket to be returned to the same slot it came from. Instead it stayed inside the Generator. I was able to pull out the empty bucket using component.generator.remove()

If this is intentional, then no problems.

**Comment by fnuecke** [comment]
This is intentional, mostly to avoid issues with stackable fuel container items where returning an empty container to the inventory might not be possible (because no slot might be freed when inserting). Instead of adding a special case for that, I think it's better to have this always behave the same way.
