### ISSUE TITLE
Suggestion: increase power requirements for disassembleAllTheThings=true

### ISSUE THREAD

**Issue by GoneNomad** [MightyPirates/OpenComputers#931]
Problem: This is incredibly useful and more than a little cheaty feeling.

Suggestion: if disassembleAllTheThings=true then increase power usage by 10-1000 times more for non-OpenComputers items. Maybe another config option: allTheThingsPowerMultiplier=250

**Comment by fnuecke** [comment]
> more than a little cheaty feeling

That's why it's disabled by default, yeah :P It may also not work ideally for all recipes, which is the other reason (in particular for oredict recipes, since you might get stuff out you didn't use to craft the thing in the first place).

I'll think about adding such a setting though, can't hurt after all.
