### ISSUE TITLE
[Might be stupid or really good] All in one machines? (Screen + CPU + Power in a single block)

### ISSUE THREAD

**Issue by MFernflower** [MightyPirates/OpenComputers#936]
I don't know why I thought of this idea but it seems something that might be of use. A single block solution containing the case (tiered of course), a single screen and a power supply and a optional disk-drive for the cases that don't include it. (could also be used as a second disk drive for the advanced cases) Ive included a concept image: ![erwuigtuirghh](https://cloud.githubusercontent.com/assets/3164942/6354999/1984ab52-bc21-11e4-945c-aa4ca6d51681.png)

**Comment by LizzyTrickster** [comment]
similar to: https://github.com/MightyPirates/OpenComputers/issues/612 which was closed because it doesn't fit the theme of the mod

**Comment by MFernflower** [comment]
This idea kinda came about in a teamspeak channel late at night. Sorry I
didn't notice it was talked about before.

**Comment by Vexatos** [comment]
There is such a block, but not in this mod; if you want all-in-one magic blocks you might want to check out this other computer mod called ComputerCraft. It's basically _made_ for allowing more "easy" programming without having to worry about anything.

**Comment by MyNameIsKodos** [comment]
ComputerCraft? I heard that was a mod not as good as OC.

EDIT: Made my statement not make me sound like an asshole.

**Comment by GopherAtl** [comment]
how does combining a case and monitor into a single, less customizable, and probably limited-capability block make it "magic?" Granted, I think it's a bit redundant, since it doesn't really gain you much to justify adding it.

Also, the random cc sniping just makes you look like assholes.

**Comment by MFernflower** [comment]
Exactly. I use both mods for different things.

**Comment by fnuecke** [comment]
> it doesn't fit the theme of the mod

This is still what I think. OC is, for the most part, relatively multiblocky by design.

> I think it's a bit redundant, since it doesn't really gain you much to justify adding it.

Very much this. Adding an extra block just to save placing a screen plus keyboard fails the my purely gut-based cost-benefit analysis ;-)

_While we're at it, I'd very much appreciate less CC flaming; I'm obviously very happy when people are vocal in that they like OC, but that should be possible without trash-talking CC, no? Keep in mind that irony and sarcasm tend to fail on the internet. The main reason I feel like I have to say something at all is that it unnecessarily fuels the (apparent?) tension in the community. The (I hope invalid) prejudice that the CC forums are DDoSed by "fans of other mods" comes from somewhere, after all. Let's not feed into that. Not trying to patronize anyone here, but please be nice, at least on the issue tracker, thanks ;-) [/blog]_
