### ISSUE TITLE
Why Not Yield In Debug Hook?

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#94]
Currently Execute time are limited. (1 second default, while 10 second are provided by ComputerCraft)
But i want OpenComputer are support long execute time. (And If you can OpenPeripheral also.)

CODE

``` lua
co = coroutine.create((function() for i = 1, 15 do print(i) end end))
debug.sethook(co, function () print("?", 1, coroutine.yield("A")) end, "", 25);

status = true
while status do
  status, result = coroutine.resume(co, "B")
  print("!", status, result)
end
```

OUTPUT

```
1
2
3
4
5
!       true    A
?       1       B
6
7
8
9
!       true    A
?       1       B
10
11
12
13
!       true    A
?       1       B
14
15
!       true    nil
!       false   cannot resume dead coroutine
```
- http://stackoverflow.com/questions/8459459/lua-coroutine-error-tempt-to-yield-across-metamethod-c-call-boundary
- And http://coco.luajit.org (Based on 5.1 and It use .patch file for lua library, required porting to lua 5.2)
- Now we don't need `os.sleep(0)`. **(I DID TEST COCO WITH YIELD IN DEBUG HOOK FUNCTION! HAYO!!!)**
- (?) If Paused by timeout. It must have some more pause times. depend on 'Cooling'? (like more fan)
- (?) OS-thing can catch detect timeout program. (like `windows` window does not respone)
- It is possible multi-coroutine can throw many timeout yield if you don't handle or ignore.

That's all.
- (And now i talk about const 100, my friend say that happening are before 3 weeks, server high load issue are maybe a bug in old version, i think increase the number to 10000 is not make problem.)
- (Can't test with Lua 5.2, and what happen if presist and unpresist happen, like server restart environ)

**Comment by fnuecke** [comment]
You're talking about pre-emptive scheduling, and yes, this is something I considered (and promised someone to have another look into, so I'll leave this open as a reminder until I do). Some more details:
- It's not possible to yield from hooks that are Lua functions / closures in 5.2. It'll give you the C-call boundary error.
- I _think_ I read somewhere that it is possible to yield from select hooks as long as they're implemented in C (including count, which is what we'd want/need).
- JNLua, the wrapper I use to interface with the native library, doesn't support setting host-side hooks (which would boil down to C hooks).
- The persistence library does not persist hooks, so they have to re-registered (I'm currently registering them each time a coroutine gets resumed anyway because there were some weird GC issues things going on if I didn't remove the hook again).
- This means I'd have to change the native lib, which I didn't really have the motivation to do lately, since there were too many other topics to tackle.
- I'm hopeful this would also work in the LuaJ fallback, since that uses threads anyway and claims one can yield from absolutely anywhere.

**Comment by fnuecke** [comment]
I had a look into this, and the main point of failure right now is that Eris doesn't support persisting coroutines yielded from hooks. I may have another look into this in the future, but not anytime soon I'm afraid.
