### ISSUE TITLE
Cannot add Leash Upgrade to Robot

### ISSUE THREAD

**Issue by GoneNomad** [MightyPirates/OpenComputers#959]
On OpenComputers v1.51 with both a Tier 2 and 3 Robot, I could not move a Leash Upgrade into the Robot, neither during assembly nor afterwards into a Tier 2 Upgrade Slot. I noticed it was not being highlighted in NEI while hovering over the appropriate slot as well.

**Comment by gjgfuj** [comment]
As far as I know you can't actually leash with robots, that may have
changed or be something that I was unaware about, but I don't think it's a
thing.

**Comment by fnuecke** [comment]
@gjgfuj is correct, robots cannot use the upgrade for technical reasons (in short: because they are blocks), so it is disabled to avoid people building a useless robot. Similar to how a bunch of other cards/upgrades are disabled for specific devices (e.g. graphics cards for mircocontrollers).

So for once it's actually true: it's not a bug, it's a feature!

**Comment by gjgfuj** [comment]
Just FYI @GoneNomad, you can use the leash upgrade with drones rather than
robots.
