### ISSUE TITLE
File metadata

### ISSUE THREAD

**Issue by magik6k** [MightyPirates/OpenComputers#974]
This would allow costom OSes to implement file permissions, some real user mechanisms, etc. without use of ugly hacks.
To access the metadata there'd be two methods: `filesystem.getMetadata(file: String): String` and `filesystem.setMetadata(file: String, metadata: String)`. It should be limited to something as tiny as 16 bytes(the value should be adjustable via config), The data should allow any character including the `NUL`(`\0`).

The data could be easily stored using extended file attributes, as this method works on all major OSes, usually enabled by default. Also, AFAIK since Java 7 it can be used without JNI hackery.
http://docs.oracle.com/javase/tutorial/essential/io/fileAttr.html
One thing I don't know is behaviour of the attributes when copied in host system or across different operating systems(i.e. Linux <=> Windows)

**Comment by gjgfuj** [comment]
We've discussed this before actually. I think that sangar rejected it
because it wasn't really necessary. Maybe there's something else though.

**Comment by Vexatos** [comment]
@magik6k You can still make your own OS and have some `/etc/metadata` folder, then change the filesystem API to add exactly those methods that just create a metadata file in `/etc/metadata/<actualpath>`. Alternatively, you could simply create a meta.dat file or whatever in `/etc`, containing a table storing path->metadata pairs. Really easy to do without bloating OC.

**Comment by magik6k** [comment]
@Vexatos thats what I consider being 'ugly hack'

**Comment by fnuecke** [comment]
One of the reasons this was declined before - if not _the_ main reason - was that we couldn't find a good, portable way of storing the attributes. The suggested Java API would probably solve that issue; while OC is still compatible with Java 6 at the moment, I think this would be worth finally giving that up.

Will definitely need some testing wrt. how it behaves when copying files across host OSes or even just between different partitions (with different file systems, say ext2 vs. ext3), first tho. Couldn't find anything on that in a few quick searches. Will also need some relatively deep changes in the OC's file system logic (virtual and buffered fses e.g.), so that plus the required API change would roadmap this in OC 1.6 at the earliest.

**Comment by fnuecke** [comment]
I'm afraid you'll have to live with the ugly hack :/
