### ISSUE TITLE
Forge b1344 breaks OpenComputers

### ISSUE THREAD

**Issue by kreezxil** [MightyPirates/OpenComputers#975]
OpenComputers-MC1.8-1.5.4.9-universal.jar
and prior exhibit the following under the new Forge b1344

Multiple entries with same key:
Crash Report: http://pastebin.com/6iYAAmeT
FML Server Latest: http://pastebin.com/aA3EAfpD

**Comment by MyNameIsKodos** [comment]
From what I can tell you're using two copies of the OC jar...

**Comment by gamax92** [comment]
Oddly, the same jar file "OpenComputers-MC1.8-1.5.4.9-universal.jar" gets listed twice in the mod list

**Comment by MyNameIsKodos** [comment]
Ah, that's odd.

**Comment by fnuecke** [comment]
Ugh, I'm pretty sure this is due to the... fix, that now makes FML also check inner classes. Because when Scala compiles singletons it applies annotations on the `object` to both the static proxy and the actual class. So now any mod using Scala for it's main `@Mod` class will probably have that issue. I'll see how I can work around it, and probably open an issue on FML to ask if there's a chance they'll fix the fix / add a special check to avoid this.

**Comment by kreezxil** [comment]
Cool. I've also reported it there. Hopefully they will give it more concern when you open your ticket there.

Btw, b1341 behaves properly with your mod.

-----Original Message-----

**Comment by fnuecke** [comment]
[Reported my findings](https://github.com/MinecraftForge/FML/issues/621), looks like someone's on it!

**Comment by kreezxil** [comment]
I just got word from diesenb07 at Minecraft forge that it is a bug in fml and they'll push a pr to fix the issue.

-----Original Message-----

**Comment by fnuecke** [comment]
:+1:

**Comment by fnuecke** [comment]
Fix has been merged into FML, so this should resolve itself once Forge updates FML.
