### ISSUE TITLE
Hologram produces light even when no power

### ISSUE THREAD

**Issue by aschmois** [MightyPirates/OpenComputers#979]
I'm trying to make my entire base electricity powered but the hologram produces light regardless if pc is on or off (or if there's even electricity). This makes it impossible to turn the lights off in a room. Would love it if you guys could add a config to lighting on a hologram. If it was up to me, I'd always leave lighting off for the hologram (I have other lighting solutions anyways).

**Comment by fnuecke** [comment]
This is due to the limitations of the rather static lighting system in Minecraft. To properly change the hologram's light level (or any block in OC emitting light, such as screens and assemblers), I'd have to trigger an update for _all blocks_ that are in the lit radius of the block. Which is pretty much a performance nightmare, since whether these blocks should emit light / are on can change very rapidly.

What you can do is "hide" the hologram under another block that blocks its light, and adjust for that via `hologram.setTranslation()`.

**Comment by gjgfuj** [comment]
But other mods do it for their things, and yes, a player could do that, and
slow down the server, but there's a lot easier things to do to slow down a
server.

**Comment by fnuecke** [comment]
Well, there is also the fact that the last time I actually did have a go at it lighting broke left and right, because MC's lighting engine is ... not the best, to put it absolutely undeservedly diplomatic. Specifically, _solid_ blocks' lighting does not properly update. So for holograms I suppose that could work, for screens it simply won't.

To verify this is a vanilla bug, take a redstone ore block, place a torch on it, then remove the torch again. You'll see the light level around the block remains that of the torch, which is higher than that of the redstone ore block.

I'll leave it open for now, but no promises.

**Comment by aschmois** [comment]
What about an on/off config option? Just remove lighting for this block altogether?

**Comment by fnuecke** [comment]
If I add it / get it to work it'll probably something along the lines of a three-way option: `true`, `false` and `auto`.

**Comment by aschmois** [comment]
Yeah that's perfect but, knowing too much about mc's lighting, you're definitely going to have a hard time, and if it just becomes too much I feel like just having on/off option is a lot easier than automatic. So if all else fails that should be enough for some people :)

**Comment by fnuecke** [comment]
Well, in the worst-case scenario, that'd still be an option. I agree ;-)
